"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type User={id:string;email:string|null;full_name:string;phone:string|null;status:string;role:string};type Order={id:string;customer_id:string|null;total:number;status:string;created_at:string};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function Clientes(){
 const[loading,setLoading]=useState(true);const[users,setUsers]=useState<User[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[notice,setNotice]=useState("");
 async function load(){const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre na Matriz primeiro.");setLoading(false);return;}const[u,o]=await Promise.all([supabase.functions.invoke("admin-users",{body:{action:"LIST"}}),supabase.from("orders").select("id,customer_id,total,status,created_at").not("customer_id","is",null).order("created_at",{ascending:false}).limit(2000)]);if(u.error||u.data?.error)setNotice("Não foi possível carregar os usuários.");else setUsers(u.data.users??[]);setOrders((o.data??[]).map((x:any)=>({...x,total:Number(x.total)})));setLoading(false);}
 useEffect(()=>{load();},[]);const customerIds=useMemo(()=>new Set(orders.map(o=>o.customer_id).filter(Boolean)),[orders]);const customers=users.filter(u=>customerIds.has(u.id));
 async function toggleStatus(user:User){const status=user.status==="BLOCKED"?"ACTIVE":"BLOCKED";const{data,error}=await supabase.functions.invoke("admin-users",{body:{action:"SET_STATUS",userId:user.id,status}});setNotice(error||data?.error?"Não foi possível alterar o cliente.":"Status atualizado.");await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando clientes...</div></main>;
 return <main className="content standaloneAdmin"><header className="topbar"><div><p className="eyebrow">MATRIZ CLICK-FOOD</p><h1>Clientes</h1></div><a className="logout adminLink" href="/">← Voltar à Matriz</a></header>{notice&&<div className="notice">{notice}</div>}<div className="metricGrid"><article className="metric"><p>Clientes com pedidos</p><strong>{customers.length}</strong></article><article className="metric"><p>Pedidos vinculados</p><strong>{orders.length}</strong></article><article className="metric"><p>GMV clientes</p><strong>{brl(orders.reduce((s,o)=>s+o.total,0))}</strong></article><article className="metric"><p>Bloqueados</p><strong>{customers.filter(c=>c.status==="BLOCKED").length}</strong></article></div><section className="panel adminStandalonePanel"><div className="panelTitle"><h2>Base de clientes</h2><button className="primary" onClick={load}>Atualizar</button></div><div className="adminDataList">{customers.map(c=>{const clientOrders=orders.filter(o=>o.customer_id===c.id);const total=clientOrders.reduce((s,o)=>s+o.total,0);return <div className="adminDataRow" key={c.id}><div><b>{c.full_name}</b><small>{c.email??"sem e-mail"} • {c.phone??"sem telefone"} • {clientOrders.length} pedido(s)</small></div><b>{brl(total)}</b><div className="adminActions"><span className={`badge ${c.status.toLowerCase()}`}>{c.status}</span><button className={c.status==="BLOCKED"?"":"danger"} onClick={()=>toggleStatus(c)}>{c.status==="BLOCKED"?"Reativar":"Bloquear"}</button></div></div>})}{!customers.length&&<div className="emptyState">Nenhum cliente fez pedido ainda.</div>}</div></section></main>;
}
