from pathlib import Path

p=Path('apps/cliente/App.tsx')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'pattern missing: {label}')
    s=s.replace(old,new,1)

rep('import CustomerSupport from "./CustomerSupport";','import CustomerSupport from "./CustomerSupport";\nimport EfiCardPayment, { type CardTokenizationConfig, type PendingCardOrder } from "./EfiCardPayment";','import')
rep('type PaymentMethod = "CASH"|"PIX";','type PaymentMethod = "CASH"|"PIX"|"CREDIT_CARD";','payment type')
rep('const refundStatusLabel:Record<string,string>={PENDING:"Estorno solicitado",PROCESSING:"Estorno em processamento",COMPLETED:"PIX devolvido",FAILED:"Falha no estorno",CANCELLED:"Estorno cancelado"};','const refundStatusLabel:Record<string,string>={PENDING:"Estorno solicitado",PROCESSING:"Estorno em processamento",COMPLETED:"Pagamento devolvido",FAILED:"Falha no estorno",CANCELLED:"Estorno cancelado"};','refund label')
rep('  const[paymentMethod,setPaymentMethod]=useState<PaymentMethod>("CASH"); const[availablePaymentMethods,setAvailablePaymentMethods]=useState<PaymentMethod[]>(["CASH"]); const[pixCharge,setPixCharge]=useState<PixCharge|null>(null); const[pixBusy,setPixBusy]=useState(false);',
'''  const[paymentMethod,setPaymentMethod]=useState<PaymentMethod>("CASH"); const[availablePaymentMethods,setAvailablePaymentMethods]=useState<PaymentMethod[]>(["CASH"]); const[pixCharge,setPixCharge]=useState<PixCharge|null>(null); const[pixBusy,setPixBusy]=useState(false);\n  const[cardTokenization,setCardTokenization]=useState<CardTokenizationConfig|null>(null); const[pendingCardOrder,setPendingCardOrder]=useState<PendingCardOrder|null>(null);''','payment state')
old='''  async function loadPaymentMethods(){\n    const{data,error}=await supabase.functions.invoke("payment-methods",{body:{}});\n    if(error||data?.error){setAvailablePaymentMethods(["CASH"]);setPaymentMethod("CASH");return;}\n    const methods=(data?.methods??[]).filter((m:string)=>m==="CASH"||m==="PIX") as PaymentMethod[];\n    const next:PaymentMethod[]=methods.includes("CASH")?methods:(["CASH",...methods] as PaymentMethod[]);\n    setAvailablePaymentMethods(next);setPaymentMethod(current=>next.includes(current)?current:"CASH");\n  }'''
new='''  async function loadPaymentMethods(){\n    const{data,error}=await supabase.functions.invoke("payment-methods",{body:{}});\n    if(error||data?.error){setAvailablePaymentMethods(["CASH"]);setPaymentMethod("CASH");setCardTokenization(null);return;}\n    const methods=(data?.methods??[]).filter((m:string)=>m==="CASH"||m==="PIX"||m==="CREDIT_CARD") as PaymentMethod[];\n    const next:PaymentMethod[]=methods.includes("CASH")?methods:(["CASH",...methods] as PaymentMethod[]);\n    const tokenization=data?.cardTokenization;\n    setCardTokenization(tokenization?.provider==="EFI"&&tokenization?.accountId?tokenization as CardTokenizationConfig:null);\n    setAvailablePaymentMethods(next);setPaymentMethod(current=>next.includes(current)?current:"CASH");\n  }'''
rep(old,new,'payment methods')
s=s.replace('.in("order_id",orderIds).eq("method","PIX")','.in("order_id",orderIds).in("method",["PIX","CREDIT_CARD"])',1)

old='''    if(paymentMethod==="PIX"){\n      const pixResult=await supabase.functions.invoke("efi-pix-create",{body:{orderId}});\n      if(pixResult.error||pixResult.data?.error||!pixResult.data?.charge?.brcode){\n        await supabase.functions.invoke("customer-cancel-order",{body:{orderId,reason:"Cobrança PIX não pôde ser criada"}});\n        setMessage("Não foi possível gerar o PIX e o pedido foi cancelado automaticamente. Nenhum pagamento foi realizado.");\n        await loadOrders();setPlacing(false);return;\n      }\n      const charge=pixResult.data.charge;\n      setPixCharge({orderId,txid:charge.txid,brcode:charge.brcode,status:charge.status,expires_at:charge.expires_at});\n      setMessage(`PIX gerado! Total ${brl(total)}. Pague pelo QR Code ou Pix Copia e Cola.`);\n    }else{\n      setMessage(`Pedido enviado! Total ${brl(total)}${deliveryFee?` • entrega calculada ${brl(deliveryFee)}`:""}${promo>0?` • economia ${brl(promo)}`:""}.`);\n    }\n    setCart([]);setCoupon("");setSelectedStore(null);setSelectedProduct(null);setTab("orders");await loadOrders();setPlacing(false);'''
new='''    if(paymentMethod==="PIX"){\n      const pixResult=await supabase.functions.invoke("efi-pix-create",{body:{orderId}});\n      if(pixResult.error||pixResult.data?.error||!pixResult.data?.charge?.brcode){\n        await supabase.functions.invoke("customer-cancel-order",{body:{orderId,reason:"Cobrança PIX não pôde ser criada"}});\n        setMessage("Não foi possível gerar o PIX e o pedido foi cancelado automaticamente. Nenhum pagamento foi realizado.");\n        await loadOrders();setPlacing(false);return;\n      }\n      const charge=pixResult.data.charge;\n      setPixCharge({orderId,txid:charge.txid,brcode:charge.brcode,status:charge.status,expires_at:charge.expires_at});\n      setMessage(`PIX gerado! Total ${brl(total)}. Pague pelo QR Code ou Pix Copia e Cola.`);\n    }else if(paymentMethod==="CREDIT_CARD"){\n      if(!cardTokenization){\n        await supabase.functions.invoke("customer-cancel-order",{body:{orderId,reason:"Tokenização de cartão não está disponível"}});\n        setMessage("O cartão ficou indisponível antes do pagamento. O pedido foi cancelado e nenhum dado de cartão foi enviado.");\n        await loadOrders();setPlacing(false);return;\n      }\n      setPendingCardOrder({orderId,total});\n      setMessage(`Pedido criado. Finalize o pagamento seguro de ${brl(total)} com cartão.`);\n      setPlacing(false);return;\n    }else{\n      setMessage(`Pedido enviado! Total ${brl(total)}${deliveryFee?` • entrega calculada ${brl(deliveryFee)}`:""}${promo>0?` • economia ${brl(promo)}`:""}.`);\n    }\n    setCart([]);setCoupon("");setSelectedStore(null);setSelectedProduct(null);setTab("orders");await loadOrders();setPlacing(false);'''
rep(old,new,'place order payment branch')

marker='''  function cancelOrder(order:Order){'''
handlers='''  async function completeCardPayment(result:{paid:boolean;approved:boolean;status:string}){\n    setPendingCardOrder(null);\n    setMessage(result.paid?"Pagamento no cartão confirmado! Seu pedido foi enviado para a loja.":"Cartão aprovado pela Efí. O pedido seguirá para a loja assim que a confirmação final chegar.");\n    setCart([]);setCoupon("");setSelectedStore(null);setSelectedProduct(null);setTab("orders");await loadOrders();\n  }\n\n  async function cancelPendingCardPayment(){\n    const pending=pendingCardOrder;if(!pending)return;\n    const{data,error}=await supabase.functions.invoke("customer-cancel-order",{body:{orderId:pending.orderId,reason:"Pagamento com cartão cancelado pelo cliente antes da conclusão"}});\n    setPendingCardOrder(null);setCart([]);setCoupon("");setSelectedStore(null);setSelectedProduct(null);setTab("orders");\n    if(error||data?.error)setMessage("Não foi possível cancelar a cobrança imediatamente. O pedido ficará em acompanhamento até a confirmação do status.");\n    else setMessage("Pagamento com cartão cancelado. Nenhum cartão foi armazenado pelo CLICK-FOOD.");\n    await loadOrders();\n  }\n\n'''+marker
rep(marker,handlers,'card handlers')

s=s.replace('setMessage(refundStatus==="COMPLETED"?"Pedido cancelado e PIX devolvido com sucesso.":refundStatus==="FAILED"?"Pedido cancelado. A devolução do PIX precisa ser tentada novamente.":"Pedido cancelado. A devolução do PIX foi solicitada e está sendo processada.");','setMessage(refundStatus==="COMPLETED"?"Pedido cancelado e pagamento devolvido com sucesso.":refundStatus==="FAILED"?"Pedido cancelado. A devolução do pagamento precisa ser tentada novamente.":"Pedido cancelado. A devolução do pagamento foi solicitada e está sendo processada.");',1)
s=s.replace('supabase.functions.invoke("efi-pix-refund",{body:{orderId:order.id,reason:"Reconciliação de estorno solicitada pelo cliente"}})','supabase.functions.invoke("payment-refund",{body:{orderId:order.id,reason:"Reconciliação de estorno solicitada pelo cliente"}})',1)
s=s.replace('setMessage(status==="COMPLETED"?"PIX devolvido com sucesso.":status==="FAILED"?"A Efí não concluiu a devolução. Você pode tentar novamente ou abrir o suporte.":"A devolução do PIX continua em processamento.");','setMessage(status==="COMPLETED"?"Pagamento devolvido com sucesso.":status==="FAILED"?"A devolução não foi concluída. Você pode tentar novamente ou abrir o suporte.":"A devolução do pagamento continua em processamento.");',1)

old='''      <View style={styles.segment}>\n        <Pressable style={[styles.segmentButton,paymentMethod==="CASH"&&styles.segmentActive]} onPress={()=>setPaymentMethod("CASH")}><Text style={paymentMethod==="CASH"?styles.segmentActiveText:undefined}>Dinheiro</Text></Pressable>\n        {availablePaymentMethods.includes("PIX")&&<Pressable style={[styles.segmentButton,paymentMethod==="PIX"&&styles.segmentActive]} onPress={()=>setPaymentMethod("PIX")}><Text style={paymentMethod==="PIX"?styles.segmentActiveText:undefined}>PIX • Efí</Text></Pressable>}\n      </View>\n      {!availablePaymentMethods.includes("PIX")&&<Text style={styles.meta}>PIX será exibido automaticamente quando a Efí Bank estiver ativada pela Matriz.</Text>}\n      <View style={styles.totalBox}><Text>Subtotal estimado</Text><Text style={styles.total}>{brl(cartSubtotal)}</Text><Text style={styles.paymentHint}>O servidor recalcula preços, promoções, adicionais, frete, estoque e cupom antes de criar o pedido. {paymentMethod==="PIX"?"No PIX, o pedido só é enviado à loja após a confirmação da Efí.":"No dinheiro, o pedido segue diretamente para a loja."}</Text></View>'''
new='''      <View style={styles.segment}>\n        <Pressable style={[styles.segmentButton,paymentMethod==="CASH"&&styles.segmentActive]} onPress={()=>setPaymentMethod("CASH")}><Text style={paymentMethod==="CASH"?styles.segmentActiveText:undefined}>Dinheiro</Text></Pressable>\n        {availablePaymentMethods.includes("PIX")&&<Pressable style={[styles.segmentButton,paymentMethod==="PIX"&&styles.segmentActive]} onPress={()=>setPaymentMethod("PIX")}><Text style={paymentMethod==="PIX"?styles.segmentActiveText:undefined}>PIX • Efí</Text></Pressable>}\n        {availablePaymentMethods.includes("CREDIT_CARD")&&cardTokenization&&<Pressable style={[styles.segmentButton,paymentMethod==="CREDIT_CARD"&&styles.segmentActive]} onPress={()=>setPaymentMethod("CREDIT_CARD")}><Text style={paymentMethod==="CREDIT_CARD"?styles.segmentActiveText:undefined}>Cartão • Efí</Text></Pressable>}\n      </View>\n      {!availablePaymentMethods.includes("PIX")&&<Text style={styles.meta}>PIX será exibido automaticamente quando a Efí Bank estiver ativada pela Matriz.</Text>}\n      <View style={styles.totalBox}><Text>Subtotal estimado</Text><Text style={styles.total}>{brl(cartSubtotal)}</Text><Text style={styles.paymentHint}>O servidor recalcula preços, promoções, adicionais, frete, estoque e cupom antes de criar o pedido. {paymentMethod==="PIX"?"No PIX, o pedido só é enviado à loja após a confirmação da Efí.":paymentMethod==="CREDIT_CARD"?"No cartão, número e CVV são tokenizados pela Efí dentro de uma tela segura e não ficam armazenados no CLICK-FOOD.":"No dinheiro, o pedido segue diretamente para a loja."}</Text></View>'''
rep(old,new,'payment UI')

old='''      <Pressable style={[styles.checkout,(!cart.length||!selectedStore.open_now)&&styles.disabled]} disabled={!cart.length||placing||!selectedStore.open_now} onPress={placeOrder}><Text style={styles.checkoutText}>{!selectedStore.open_now?"LOJA FECHADA":placing?"ENVIANDO PEDIDO...":"FAZER PEDIDO"}</Text></Pressable>\n    </ScrollView></SafeAreaView>;'''
new='''      <Pressable style={[styles.checkout,(!cart.length||!selectedStore.open_now)&&styles.disabled]} disabled={!cart.length||placing||!selectedStore.open_now} onPress={placeOrder}><Text style={styles.checkoutText}>{!selectedStore.open_now?"LOJA FECHADA":placing?"ENVIANDO PEDIDO...":"FAZER PEDIDO"}</Text></Pressable>\n    </ScrollView>\n    {pendingCardOrder&&cardTokenization&&<EfiCardPayment visible config={cardTokenization} order={pendingCardOrder} defaults={{name:String(session.user.user_metadata?.full_name??""),email:String(session.user.email??""),phone:String(session.user.user_metadata?.phone??"")}} onCancel={cancelPendingCardPayment} onComplete={completeCardPayment}/>}\n    </SafeAreaView>;'''
rep(old,new,'card modal')

p.write_text(s,encoding='utf-8')
print('patched App.tsx')
