"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Policy={grace_days:number;suspend_after_days:number;auto_suspend:boolean};
type Store={id:string;name:string;status:string};
type Subscription={id:string;store_id:string;status:string;started_at:string;renewal_at:string|null;stores:any;plans:any};
type Invoice={id:string;store_id:string;subscription_id:string|null;amount:number;due_date:string;reference_month:string;status:string;paid_at:string|null;stores:any};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);const rel=(v:any)=>Array.isArray(v)?v[0]:v;const date=(v:string|null)=>v?new Date(`${v.length===10?v+"T12:00:00":v}`).toLocaleDateString("pt-BR"):"-";const overdueDays=(v:string)=>Math.max(0,Math.floor((Date.now()-new Date(v+"T23:59:59").getTime())/86400000));

export default function BillingAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[policy,setPolicy]=useState<Policy>({grace_days:3,suspend_after_days:7,auto_suspend:false});const[stores,setStores]=useState<Store[]>([]);const[subscriptions,setSubscriptions]=useState<Subscription[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[busy,setBusy]=useState("");
 const[form,setForm]=useState({storeId:"",amount:"",dueDate:"",referenceMonth:new Date().toISOString().slice(0,7)+"-01"});
 async function load(){const[pR,sR,subR,iR]=await Promise.all([supabase.from("billing_policy").select("grace_days,suspend_after_days,auto_suspend").eq("id",1).single(),supabase.from("stores").select("id,name,status").order("name"),supabase.from("subscriptions").select("id,store_id,status,started_at,renewal_at,stores(name,status),plans(name,monthly_fee)").order("created_at",{ascending:false}),supabase.from("invoices").select("id,store_id,subscription_id,amount,due_date,reference_month,status,paid_at,stores(name,status)").order("due_date",{ascending:false}).limit(300)]);if(pR.data)setPolicy(pR.data as Policy);if(sR.data)setStores(sR.data as Store[]);if(subR.data)setSubscriptions(subR.data as any);if(iR.data)setInvoices(iR.data.map((x:any)=>({...x,amount:Number(x.amount)})));}
 async function boot(){setLoading(true);const{data}=await supabase.auth.getSession();const role=String(data.session?.user.app_metadata?.clickfood_role??"");const ok=Boolean(data.session)&&["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(ok)await load();setLoading(false);}
 useEffect(()=>{boot();},[]);
 const summary=useMemo(()=>({open:invoices.filter(i=>i.status==="OPEN").reduce((s,i)=>s+i.amount,0),past:invoices.filter(i=>i.status==="PAST_DUE").reduce((s,i)=>s+i.amount,0),pastCount:invoices.filter(i=>i.status==="PAST_DUE").length,suspended:subscriptions.filter(s=>s.status==="SUSPENDED").length}),[invoices,subscriptions]);
 async function invoke(body:any,okMessage:string){setBusy(body.action+(body.invoiceId??body.subscriptionId??""));setMessage("");const{data,error}=await supabase.functions.invoke("admin-billing",{body});if(error||data?.error)setMessage(`Operação não concluída${data?.error?`: ${data.error}`:"."}`);else{setMessage(okMessage);await load();}setBusy("");}
 async function savePolicy(e:FormEvent){e.preventDefault();await invoke({action:"UPDATE_POLICY",graceDays:Number(policy.grace_days),suspendAfterDays:Number(policy.suspend_after_days),autoSuspend:policy.auto_suspend},"Política de cobrança atualizada.");}
 async function sync(){await invoke({action:"SYNC_OVERDUE"},"Inadimplência recalculada. Faturas e assinaturas foram sincronizadas.");}
 async function createInvoice(e:FormEvent){e.preventDefault();const amount=Number(form.amount.replace(",","."));if(!form.storeId||!Number.isFinite(amount)||amount<0||!form.dueDate){setMessage("Informe loja, valor e vencimento válidos.");return;}const sub=subscriptions.find(s=>s.store_id===form.storeId&&s.status!=="CANCELLED");await invoke({action:"CREATE_INVOICE",storeId:form.storeId,subscriptionId:sub?.id??null,amount,dueDate:form.dueDate,referenceMonth:form.referenceMonth},"Fatura criada.");setForm({...form,amount:"",dueDate:""});}
 if(loading)return <main className="authPage"><div className="authCard">Carregando cobrança...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Somente administradores podem alterar cobranças e assinaturas.</p></div></main>;
 return <main className="adminPage"><section className="adminHeader"><div><small>FINANCEIRO</small><h1>Assinaturas e inadimplência</h1><p>Controle vencimentos, carência, suspensão e regularização das lojas.</p></div><button className="primaryAction" onClick={sync} disabled={!!busy}>{busy==="SYNC_OVERDUE"?"SINCRONIZANDO...":"SINCRONIZAR INADIMPLÊNCIA"}</button></section>{message&&<div className="adminNotice">{message}</div>}
  <section className="metricGrid"><article><b>{brl(summary.open)}</b><span>Em aberto</span></article><article><b>{brl(summary.past)}</b><span>Vencido</span></article><article><b>{summary.pastCount}</b><span>Faturas inadimplentes</span></article><article><b>{summary.suspended}</b><span>Assinaturas suspensas</span></article></section>
  <section className="adminGrid2"><article className="adminPanel"><div className="panelTitle"><div><small>POLÍTICA GLOBAL</small><h2>Regras de cobrança</h2></div></div><form className="adminForm" onSubmit={savePolicy}><label>Carência após vencimento (dias)<input type="number" min={0} max={90} value={policy.grace_days} onChange={e=>setPolicy({...policy,grace_days:Number(e.target.value)})}/></label><label>Suspender após quantos dias<input type="number" min={1} max={180} value={policy.suspend_after_days} onChange={e=>setPolicy({...policy,suspend_after_days:Number(e.target.value)})}/></label><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={policy.auto_suspend} onChange={e=>setPolicy({...policy,auto_suspend:e.target.checked})}/> Suspensão automática por inadimplência</label><p className="muted">A fatura vira vencida depois da carência. Se a suspensão automática estiver ligada, a loja é suspensa somente quando ultrapassa o limite configurado. O status anterior é guardado para uma regularização segura.</p><button className="primaryAction" disabled={!!busy}>SALVAR POLÍTICA</button></form></article>
   <article className="adminPanel"><div className="panelTitle"><div><small>NOVA FATURA</small><h2>Cobrança manual</h2></div></div><form className="adminForm" onSubmit={createInvoice}><label>Loja<select value={form.storeId} onChange={e=>setForm({...form,storeId:e.target.value})}><option value="">Selecione</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Valor<input placeholder="0,00" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Competência<input type="date" value={form.referenceMonth} onChange={e=>setForm({...form,referenceMonth:e.target.value})}/></label><label>Vencimento<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><button className="primaryAction" disabled={!!busy}>CRIAR FATURA</button></form></article></section>
  <section className="adminPanel"><div className="panelTitle"><div><small>FATURAS</small><h2>Recebimentos e inadimplência</h2></div><span>{invoices.length}</span></div><div className="adminList">{invoices.map(i=>{const store=rel(i.stores);const overdue=i.status==="PAST_DUE"?overdueDays(i.due_date):0;return <div key={i.id} style={{alignItems:"flex-start"}}><div style={{flex:1}}><b>{store?.name??"Loja"} • {brl(i.amount)}</b><small>Competência {date(i.reference_month)} • vencimento {date(i.due_date)} • {i.status}{overdue?` • ${overdue} dia(s) em atraso`:""}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}>{!["PAID","WAIVED","CANCELLED"].includes(i.status)&&<button onClick={()=>invoke({action:"SET_INVOICE_STATUS",invoiceId:i.id,status:"PAID"},"Fatura marcada como paga.")}>Paga</button>}{!["PAID","WAIVED","CANCELLED"].includes(i.status)&&<button onClick={()=>invoke({action:"SET_INVOICE_STATUS",invoiceId:i.id,status:"WAIVED"},"Fatura abonada.")}>Abonar</button>}{!["PAID","WAIVED","CANCELLED"].includes(i.status)&&<button onClick={()=>invoke({action:"SET_INVOICE_STATUS",invoiceId:i.id,status:"CANCELLED"},"Fatura cancelada.")}>Cancelar</button>}{["PAID","WAIVED","CANCELLED"].includes(i.status)&&<button onClick={()=>invoke({action:"SET_INVOICE_STATUS",invoiceId:i.id,status:"OPEN"},"Fatura reaberta.")}>Reabrir</button>}</div></div>})}{!invoices.length&&<p className="muted">Nenhuma fatura cadastrada.</p>}</div></section>
  <section className="adminPanel"><div className="panelTitle"><div><small>ASSINATURAS</small><h2>Planos por loja</h2></div><span>{subscriptions.length}</span></div><div className="adminList">{subscriptions.map(s=>{const store=rel(s.stores),plan=rel(s.plans);return <div key={s.id}><div><b>{store?.name??"Loja"} • {plan?.name??"Plano"}</b><small>{s.status} • início {date(s.started_at)}{s.renewal_at?` • renovação ${date(s.renewal_at)}`:""}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{s.status!=="ACTIVE"&&<button onClick={()=>invoke({action:"SET_SUBSCRIPTION_STATUS",subscriptionId:s.id,status:"ACTIVE"},"Assinatura ativada.")}>Ativar</button>}{s.status!=="SUSPENDED"&&<button onClick={()=>invoke({action:"SET_SUBSCRIPTION_STATUS",subscriptionId:s.id,status:"SUSPENDED"},"Assinatura suspensa.")}>Suspender</button>}{s.status!=="CANCELLED"&&<button onClick={()=>invoke({action:"SET_SUBSCRIPTION_STATUS",subscriptionId:s.id,status:"CANCELLED"},"Assinatura cancelada.")}>Cancelar</button>}</div></div>})}{!subscriptions.length&&<p className="muted">Nenhuma assinatura cadastrada.</p>}</div></section>
 </main>;
}
