"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Payout={id:string;recipient_type:"STORE"|"DRIVER";store_id:string|null;driver_id:string|null;amount:number;method:string;status:string;destination_value:string|null;review_notes:string|null;provider_id:string|null;requested_at:string;processed_at:string|null};
type RecipientMap=Record<string,string>;
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const statusLabel:Record<string,string>={REQUESTED:"SOLICITADO",APPROVED:"APROVADO",PROCESSING:"PROCESSANDO",PAID:"PAGO",FAILED:"FALHOU",REJECTED:"REJEITADO",CANCELLED:"CANCELADO"};

export default function RepassesAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[payouts,setPayouts]=useState<Payout[]>([]);const[busy,setBusy]=useState("");const[recipients,setRecipients]=useState<RecipientMap>({});const[filter,setFilter]=useState<"ALL"|"STORE"|"DRIVER">("ALL");
 const shown=useMemo(()=>filter==="ALL"?payouts:payouts.filter(p=>p.recipient_type===filter),[payouts,filter]);
 const summary=useMemo(()=>payouts.reduce((a,p)=>{a.total+=p.amount;if(p.status==="REQUESTED")a.requested+=p.amount;if(p.status==="APPROVED"||p.status==="PROCESSING")a.processing+=p.amount;if(p.status==="PAID")a.paid+=p.amount;return a},{total:0,requested:0,processing:0,paid:0}),[payouts]);
 async function loadRecipients(rows:Payout[]){
  const map:RecipientMap={};const storeIds=[...new Set(rows.filter(p=>p.store_id).map(p=>String(p.store_id)))];const driverIds=[...new Set(rows.filter(p=>p.driver_id).map(p=>String(p.driver_id)))];
  if(storeIds.length){const{data}=await supabase.from("stores").select("id,name").in("id",storeIds);for(const s of data??[])map[`STORE:${s.id}`]=String(s.name);}
  if(driverIds.length){const{data:drivers}=await supabase.from("drivers").select("id,user_id").in("id",driverIds);const userIds=[...new Set((drivers??[]).map((d:any)=>String(d.user_id)))];const{data:profiles}=userIds.length?await supabase.from("profiles").select("id,full_name").in("id",userIds):{data:[] as any[]};const profileMap=new Map((profiles??[]).map((p:any)=>[String(p.id),String(p.full_name??"Entregador")]));for(const d of drivers??[])map[`DRIVER:${d.id}`]=profileMap.get(String(d.user_id))??`Entregador ${String(d.id).slice(0,8)}`;}
  setRecipients(map);
 }
 async function load(){setLoading(true);const{data:sd}=await supabase.auth.getSession();const session=sd.session;if(!session){setAuthorized(false);setLoading(false);return;}const role=String(session.user.app_metadata?.clickfood_role??"");const ok=["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(!ok){setLoading(false);return;}const{data,error}=await supabase.from("payouts").select("id,recipient_type,store_id,driver_id,amount,method,status,destination_value,review_notes,provider_id,requested_at,processed_at").order("requested_at",{ascending:false}).limit(300);if(error){setMessage("Não foi possível carregar os repasses.");setLoading(false);return;}const rows=(data??[]).map((x:any)=>({...x,amount:Number(x.amount)})) as Payout[];setPayouts(rows);await loadRecipients(rows);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function status(p:Payout,target:"APPROVED"|"PROCESSING"|"PAID"|"FAILED"|"REJECTED"){let notes:string|undefined;let providerId:string|undefined;if(target==="REJECTED"||target==="FAILED"){notes=window.prompt(target==="REJECTED"?"Motivo da rejeição:":"Motivo da falha:")?.trim()||undefined;if(!notes){setMessage("Informe o motivo.");return;}}if(target==="PAID"){providerId=window.prompt("ID/comprovante do pagamento (opcional):")?.trim()||undefined;}setBusy(p.id);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"ADMIN_STATUS",payoutId:p.id,status:target,notes,providerId}});setBusy("");setMessage(error||data?.error?"Não foi possível atualizar o repasse.":`Repasse alterado para ${statusLabel[target]}.`);await load();}
 function recipientName(p:Payout){return p.recipient_type==="STORE"?recipients[`STORE:${p.store_id}`]??"Loja":recipients[`DRIVER:${p.driver_id}`]??"Entregador";}
 if(loading)return <main className="authPage"><div className="authCard">Carregando repasses...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Entre com Super Admin ou Admin.</p><a href="/">Voltar</a></div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">FINANCEIRO CLICK-FOOD</p><h1>Repasses</h1><small>Solicitações de lojistas e entregadores, com reserva financeira transacional</small></div><button className="logout" onClick={load}>Atualizar</button></header>{message&&<div className="notice">{message}</div>}
  <div className="metricGrid"><article className="metric"><p>Solicitado</p><strong>{brl(summary.requested)}</strong></article><article className="metric"><p>Aprovado/processando</p><strong>{brl(summary.processing)}</strong></article><article className="metric"><p>Pago</p><strong>{brl(summary.paid)}</strong></article><article className="metric"><p>Histórico total</p><strong>{brl(summary.total)}</strong></article></div>
  <section className="panel" style={{marginTop:16}}><div className="panelTitle"><div><h2>Fila de repasses</h2><small>{shown.length} solicitações exibidas</small></div><div className="adminActions"><button onClick={()=>setFilter("ALL")}>Todos</button><button onClick={()=>setFilter("STORE")}>Lojas</button><button onClick={()=>setFilter("DRIVER")}>Entregadores</button></div></div><div className="adminDataList">{shown.map(p=><div className="adminDataRow" key={p.id}><div><b>{p.recipient_type==="DRIVER"?"ENTREGADOR":"LOJA"} • {recipientName(p)} • {brl(p.amount)}</b><small>{p.method} • destino {p.destination_value??"não informado"} • solicitado {dt(p.requested_at)}{p.review_notes?` • ${p.review_notes}`:""}{p.provider_id?` • comprovante ${p.provider_id}`:""}</small></div><span className={`badge ${p.status==="PAID"?"active":p.status==="REJECTED"||p.status==="FAILED"||p.status==="CANCELLED"?"blocked":"pending"}`}>{statusLabel[p.status]??p.status}</span><div className="adminActions">{p.status==="REQUESTED"&&<><button disabled={busy===p.id} onClick={()=>status(p,"APPROVED")}>Aprovar</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="APPROVED"&&<><button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Processando</button><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="PROCESSING"&&<><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"FAILED")}>Falha</button></>}{p.status==="FAILED"&&<button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Tentar novamente</button>}</div></div>)}{!shown.length&&<div className="emptyState">Nenhum repasse neste filtro.</div>}</div></section>
 </main>;
}
