"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Payout={id:string;store_id:string|null;amount:number;method:string;status:string;destination_value:string|null;review_notes:string|null;provider_id:string|null;requested_at:string;processed_at:string|null;stores?:{name:string}|{name:string}[]|null};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const rel=(v:any)=>Array.isArray(v)?v[0]:v;

export default function RepassesAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[payouts,setPayouts]=useState<Payout[]>([]);const[busy,setBusy]=useState("");
 const summary=useMemo(()=>payouts.reduce((a,p)=>{a.total+=p.amount;if(p.status==="REQUESTED")a.requested+=p.amount;if(p.status==="APPROVED"||p.status==="PROCESSING")a.processing+=p.amount;if(p.status==="PAID")a.paid+=p.amount;return a},{total:0,requested:0,processing:0,paid:0}),[payouts]);
 async function load(){setLoading(true);const{data:sd}=await supabase.auth.getSession();const session=sd.session;if(!session){setAuthorized(false);setLoading(false);return;}const role=String(session.user.app_metadata?.clickfood_role??"");const ok=["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(!ok){setLoading(false);return;}const{data,error}=await supabase.from("payouts").select("id,store_id,amount,method,status,destination_value,review_notes,provider_id,requested_at,processed_at,stores(name)").eq("recipient_type","STORE").order("requested_at",{ascending:false}).limit(200);if(error)setMessage("Não foi possível carregar os repasses.");setPayouts((data??[]).map((x:any)=>({...x,amount:Number(x.amount)})));setLoading(false);}
 useEffect(()=>{load();},[]);
 async function status(p:Payout,target:"APPROVED"|"PROCESSING"|"PAID"|"FAILED"|"REJECTED"){let notes:string|undefined;let providerId:string|undefined;if(target==="REJECTED"||target==="FAILED"){notes=window.prompt(target==="REJECTED"?"Motivo da rejeição:":"Motivo da falha:")?.trim()||undefined;if(!notes){setMessage("Informe o motivo.");return;}}if(target==="PAID"){providerId=window.prompt("ID/comprovante do pagamento (opcional):")?.trim()||undefined;}setBusy(p.id);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"ADMIN_STATUS",payoutId:p.id,status:target,notes,providerId}});setBusy("");setMessage(error||data?.error?"Não foi possível atualizar o repasse.":`Repasse alterado para ${target}.`);await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando repasses...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Entre com Super Admin ou Admin.</p><a href="/">Voltar</a></div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">FINANCEIRO CLICK-FOOD</p><h1>Repasses</h1><small>Solicitações dos lojistas e processamento financeiro</small></div><button className="logout" onClick={load}>Atualizar</button></header>{message&&<div className="notice">{message}</div>}
  <div className="metricGrid"><article className="metric"><p>Solicitado</p><strong>{brl(summary.requested)}</strong></article><article className="metric"><p>Aprovado/processando</p><strong>{brl(summary.processing)}</strong></article><article className="metric"><p>Pago</p><strong>{brl(summary.paid)}</strong></article><article className="metric"><p>Histórico total</p><strong>{brl(summary.total)}</strong></article></div>
  <section className="panel" style={{marginTop:16}}><div className="panelTitle"><h2>Fila de repasses</h2><span>{payouts.length}</span></div><div className="adminDataList">{payouts.map(p=>{const s=rel(p.stores);return <div className="adminDataRow" key={p.id}><div><b>{s?.name??"Loja"} • {brl(p.amount)}</b><small>{p.method} • {p.destination_value??"destino não informado"} • solicitado {dt(p.requested_at)}{p.review_notes?` • ${p.review_notes}`:""}{p.provider_id?` • comprovante ${p.provider_id}`:""}</small></div><span className={`badge ${p.status==="PAID"?"active":p.status==="REJECTED"||p.status==="FAILED"||p.status==="CANCELLED"?"blocked":"pending"}`}>{p.status}</span><div className="adminActions">{p.status==="REQUESTED"&&<><button disabled={busy===p.id} onClick={()=>status(p,"APPROVED")}>Aprovar</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="APPROVED"&&<><button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Processando</button><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="PROCESSING"&&<><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"FAILED")}>Falha</button></>}{p.status==="FAILED"&&<button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Tentar novamente</button>}</div></div>})}{!payouts.length&&<div className="emptyState">Nenhum repasse solicitado.</div>}</div></section>
 </main>;
}
