"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Payout={id:string;recipient_type:"STORE"|"DRIVER";store_id:string|null;driver_id:string|null;amount:number;method:string;status:string;destination_value:string|null;review_notes:string|null;provider_id:string|null;provider_name:string|null;provider_status:string|null;provider_end_to_end_id:string|null;provider_last_error:string|null;requested_at:string;processed_at:string|null};
type ProviderConfig={provider:string;display_name:string;environment:"SANDBOX"|"PRODUCTION";enabled:boolean;credentials_configured:boolean;automatic_processing:boolean;validated_at:string|null;updated_at:string};
type RecipientMap=Record<string,string>;
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const statusLabel:Record<string,string>={REQUESTED:"SOLICITADO",APPROVED:"APROVADO",PROCESSING:"PROCESSANDO",PAID:"PAGO",FAILED:"FALHOU",REJECTED:"REJEITADO",CANCELLED:"CANCELADO"};
function maskDestination(value:string|null){if(!value)return"não informado";const x=value.trim();if(x.includes("@")){const[a,...rest]=x.split("@");return`${a.slice(0,2)}***@${rest.join("@")}`;}if(x.length<=6)return"***";return`${x.slice(0,3)}***${x.slice(-3)}`;}
function shortId(value:string|null){if(!value)return"-";return value.length>14?`${value.slice(0,6)}…${value.slice(-6)}`:value;}

export default function RepassesAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[payouts,setPayouts]=useState<Payout[]>([]);const[busy,setBusy]=useState("");const[providerBusy,setProviderBusy]=useState(false);const[provider,setProvider]=useState<ProviderConfig|null>(null);const[recipients,setRecipients]=useState<RecipientMap>({});const[filter,setFilter]=useState<"ALL"|"STORE"|"DRIVER">("ALL");
 const shown=useMemo(()=>filter==="ALL"?payouts:payouts.filter(p=>p.recipient_type===filter),[payouts,filter]);
 const summary=useMemo(()=>payouts.reduce((a,p)=>{a.total+=p.amount;if(p.status==="REQUESTED")a.requested+=p.amount;if(p.status==="APPROVED"||p.status==="PROCESSING")a.processing+=p.amount;if(p.status==="PAID")a.paid+=p.amount;return a},{total:0,requested:0,processing:0,paid:0}),[payouts]);
 const efiReady=!!provider?.enabled&&!!provider?.credentials_configured;
 async function loadRecipients(rows:Payout[]){
  const map:RecipientMap={};const storeIds=[...new Set(rows.filter(p=>p.store_id).map(p=>String(p.store_id)))];const driverIds=[...new Set(rows.filter(p=>p.driver_id).map(p=>String(p.driver_id)))];
  if(storeIds.length){const{data}=await supabase.from("stores").select("id,name").in("id",storeIds);for(const s of data??[])map[`STORE:${s.id}`]=String(s.name);}
  if(driverIds.length){const{data:drivers}=await supabase.from("drivers").select("id,user_id").in("id",driverIds);const userIds=[...new Set((drivers??[]).map((d:any)=>String(d.user_id)))];const{data:profiles}=userIds.length?await supabase.from("profiles").select("id,full_name").in("id",userIds):{data:[] as any[]};const profileMap=new Map((profiles??[]).map((p:any)=>[String(p.id),String(p.full_name??"Entregador")]));for(const d of drivers??[])map[`DRIVER:${d.id}`]=profileMap.get(String(d.user_id))??`Entregador ${String(d.id).slice(0,8)}`;}
  setRecipients(map);
 }
 async function loadProvider(){const{data,error}=await supabase.functions.invoke("efi-payout-setup",{body:{action:"STATUS"}});if(!error&&!data?.error)setProvider(data?.config??null);}
 async function load(){setLoading(true);const{data:sd}=await supabase.auth.getSession();const session=sd.session;if(!session){setAuthorized(false);setLoading(false);return;}const role=String(session.user.app_metadata?.clickfood_role??"");const ok=["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(!ok){setLoading(false);return;}const{data,error}=await supabase.from("payouts").select("id,recipient_type,store_id,driver_id,amount,method,status,destination_value,review_notes,provider_id,provider_name,provider_status,provider_end_to_end_id,provider_last_error,requested_at,processed_at").order("requested_at",{ascending:false}).limit(300);if(error){setMessage("Não foi possível carregar os repasses.");setLoading(false);return;}const rows=(data??[]).map((x:any)=>({...x,amount:Number(x.amount)})) as Payout[];setPayouts(rows);await Promise.all([loadRecipients(rows),loadProvider()]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function providerAction(action:"VALIDATE"|"DISABLE"){setProviderBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("efi-payout-setup",{body:{action}});setProviderBusy(false);if(error||data?.error){const code=String(data?.error??"");if(code==="EFI_PAYOUT_SCOPES_MISSING")setMessage(`A aplicação Efí ainda não tem todos os escopos de envio Pix: ${(data?.missingScopes??[]).join(", ")}.`);else if(code==="EFI_PAYOUT_WEBHOOK_NOT_READY")setMessage("O webhook Pix da Efí precisa estar ativo antes de liberar repasses.");else setMessage("Não foi possível validar o envio Pix de repasses.");await loadProvider();return;}setProvider(data?.config??null);setMessage(action==="VALIDATE"?"Envio Pix de repasses validado em modo seguro. Os repasses continuam exigindo aprovação e clique de envio.":"Envio Pix de repasses desativado. O fluxo manual continua disponível.");}
 async function status(p:Payout,target:"APPROVED"|"PROCESSING"|"PAID"|"FAILED"|"REJECTED"){let notes:string|undefined;let providerId:string|undefined;if(target==="REJECTED"||target==="FAILED"){notes=window.prompt(target==="REJECTED"?"Motivo da rejeição:":"Motivo da falha:")?.trim()||undefined;if(!notes){setMessage("Informe o motivo.");return;}}if(target==="PAID"){providerId=window.prompt("ID/comprovante do pagamento manual (opcional):")?.trim()||undefined;}setBusy(p.id);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"ADMIN_STATUS",payoutId:p.id,status:target,notes,providerId}});setBusy("");setMessage(error||data?.error?"Não foi possível atualizar o repasse.":`Repasse alterado para ${statusLabel[target]}.`);await load();}
 async function efiPayout(p:Payout,action:"SEND"|"STATUS"){setBusy(p.id);setMessage("");const{data,error}=await supabase.functions.invoke("efi-payout-action",{body:{action,payoutId:p.id}});setBusy("");const code=String(data?.error??"");if(error||code){if(code==="EFI_PAYOUT_ANOTHER_TRANSFER_PROCESSING")setMessage("Já existe outro envio Pix Efí em processamento. Aguarde a conclusão antes de iniciar o próximo.");else if(code==="EFI_PAYOUT_CONFIRMATION_PENDING")setMessage("A Efí ainda não confirmou o resultado. O repasse permanece PROCESSANDO e deve ser consultado novamente; nenhum segundo Pix será criado.");else if(code==="EFI_PAYOUT_REJECTED")setMessage("A Efí rejeitou o envio Pix. O saldo reservado foi liberado e o repasse ficou como FALHOU para nova tentativa.");else if(code==="INSUFFICIENT_AVAILABLE_BALANCE")setMessage("O saldo disponível mudou e já não cobre este repasse.");else setMessage(action==="SEND"?"Não foi possível iniciar o envio Pix pela Efí.":"Não foi possível consultar o envio Pix na Efí.");await load();return;}const ps=String(data?.providerStatus??"").toUpperCase();setMessage(ps==="REALIZADO"?"Pix enviado e confirmado pela Efí. O repasse foi marcado como PAGO.":"Envio registrado na Efí. O repasse ficará PROCESSANDO até a confirmação do webhook.");await load();}
 function recipientName(p:Payout){return p.recipient_type==="STORE"?recipients[`STORE:${p.store_id}`]??"Loja":recipients[`DRIVER:${p.driver_id}`]??"Entregador";}
 if(loading)return <main className="authPage"><div className="authCard">Carregando repasses...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Entre com Super Admin ou Admin.</p><a href="/">Voltar</a></div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">FINANCEIRO CLICK-FOOD</p><h1>Repasses</h1><small>Solicitações de lojistas e entregadores, com reserva financeira transacional</small></div><button className="logout" onClick={load}>Atualizar</button></header>{message&&<div className="notice">{message}</div>}
  <section className="panel" style={{marginBottom:16}}><div className="panelTitle"><div><h2>Efí • Envio Pix</h2><small>{provider?`${provider.environment} • ${efiReady?"VALIDADO":"DESATIVADO"}`:"Carregando configuração"}</small></div><span className={`badge ${efiReady?"active":"pending"}`}>{efiReady?"PRONTO PARA ENVIO":"AGUARDANDO VALIDAÇÃO"}</span></div><p style={{margin:"8px 0",color:"#666",fontSize:13}}>Usa as credenciais Efí já protegidas no backend. Nada é enviado automaticamente: a Matriz aprova o repasse e depois confirma o envio individual.</p><div className="adminActions">{!efiReady?<button disabled={providerBusy} onClick={()=>providerAction("VALIDATE")}>{providerBusy?"VALIDANDO...":"VALIDAR ENVIO PIX"}</button>:<button className="danger" disabled={providerBusy} onClick={()=>providerAction("DISABLE")}>DESATIVAR ENVIO PIX</button>}</div></section>
  <div className="metricGrid"><article className="metric"><p>Solicitado</p><strong>{brl(summary.requested)}</strong></article><article className="metric"><p>Aprovado/processando</p><strong>{brl(summary.processing)}</strong></article><article className="metric"><p>Pago</p><strong>{brl(summary.paid)}</strong></article><article className="metric"><p>Histórico total</p><strong>{brl(summary.total)}</strong></article></div>
  <section className="panel" style={{marginTop:16}}><div className="panelTitle"><div><h2>Fila de repasses</h2><small>{shown.length} solicitações exibidas</small></div><div className="adminActions"><button onClick={()=>setFilter("ALL")}>Todos</button><button onClick={()=>setFilter("STORE")}>Lojas</button><button onClick={()=>setFilter("DRIVER")}>Entregadores</button></div></div><div className="adminDataList">{shown.map(p=>{const efiTransfer=p.provider_name==="EFI";return <div className="adminDataRow" key={p.id}><div><b>{p.recipient_type==="DRIVER"?"ENTREGADOR":"LOJA"} • {recipientName(p)} • {brl(p.amount)}</b><small>{p.method} • destino {maskDestination(p.destination_value)} • solicitado {dt(p.requested_at)}{p.review_notes?` • ${p.review_notes}`:""}</small>{efiTransfer&&<small>Efí {p.provider_status??"AGUARDANDO"} • idEnvio {shortId(p.provider_id)}{p.provider_end_to_end_id?` • E2E ${shortId(p.provider_end_to_end_id)}`:""}{p.provider_last_error?` • ${p.provider_last_error}`:""}</small>}</div><span className={`badge ${p.status==="PAID"?"active":p.status==="REJECTED"||p.status==="FAILED"||p.status==="CANCELLED"?"blocked":"pending"}`}>{statusLabel[p.status]??p.status}</span><div className="adminActions">{p.status==="REQUESTED"&&<><button disabled={busy===p.id} onClick={()=>status(p,"APPROVED")}>Aprovar</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="APPROVED"&&p.method==="PIX"&&efiReady&&<><button disabled={busy===p.id} onClick={()=>efiPayout(p,"SEND")}>{busy===p.id?"ENVIANDO...":"ENVIAR PIX PELA EFÍ"}</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="APPROVED"&&!(p.method==="PIX"&&efiReady)&&<><button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Processando manual</button><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"REJECTED")}>Rejeitar</button></>}{p.status==="PROCESSING"&&efiTransfer&&<button disabled={busy===p.id} onClick={()=>efiPayout(p,"STATUS")}>{busy===p.id?"CONSULTANDO...":"CONSULTAR EFÍ"}</button>}{p.status==="PROCESSING"&&!efiTransfer&&<><button disabled={busy===p.id} onClick={()=>status(p,"PAID")}>Marcar pago</button><button className="danger" disabled={busy===p.id} onClick={()=>status(p,"FAILED")}>Falha</button></>}{p.status==="FAILED"&&p.method==="PIX"&&efiReady?<button disabled={busy===p.id} onClick={()=>efiPayout(p,"SEND")}>{busy===p.id?"TENTANDO...":"TENTAR PIX NOVAMENTE"}</button>:p.status==="FAILED"&&<button disabled={busy===p.id} onClick={()=>status(p,"PROCESSING")}>Tentar manualmente</button>}</div></div>})}{!shown.length&&<div className="emptyState">Nenhum repasse neste filtro.</div>}</div></section>
 </main>;
}
