"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Doc={id:string;driver_id:string;document_type:string;file_path:string;status:string;expires_at:string|null;rejection_reason:string|null;reviewed_at:string|null;created_at:string};
type Driver={id:string;user_id:string;status:string};
type Profile={id:string;full_name:string|null;phone:string|null};

const labels:Record<string,string>={PROFILE_PHOTO:"Foto do perfil",IDENTITY:"Documento de identidade",CNH:"CNH",VEHICLE_DOCUMENT:"Documento do veículo",OTHER:"Outro"};

export default function DocumentosEntregadores(){
 const[loading,setLoading]=useState(true);const[docs,setDocs]=useState<Doc[]>([]);const[drivers,setDrivers]=useState<Driver[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[notice,setNotice]=useState("");const[filter,setFilter]=useState("PENDING");
 async function load(){setLoading(true);setNotice("");const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre na Matriz primeiro.");setLoading(false);return;}const[d,dr]=await Promise.all([supabase.from("driver_documents").select("id,driver_id,document_type,file_path,status,expires_at,rejection_reason,reviewed_at,created_at").order("created_at",{ascending:false}).limit(500),supabase.from("drivers").select("id,user_id,status").limit(1000)]);if(d.error||dr.error){setNotice("Não foi possível carregar os documentos.");setLoading(false);return;}const driverRows=(dr.data??[]) as Driver[];setDocs((d.data??[]) as Doc[]);setDrivers(driverRows);const ids=[...new Set(driverRows.map(x=>x.user_id))];if(ids.length){const{data:p}=await supabase.from("profiles").select("id,full_name,phone").in("id",ids);setProfiles((p??[]) as Profile[]);}setLoading(false);}
 useEffect(()=>{load();},[]);
 const driverMap=useMemo(()=>new Map(drivers.map(d=>[d.id,d])),[drivers]);const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const visible=filter==="ALL"?docs:docs.filter(d=>d.status===filter);
 async function openDocument(doc:Doc){const{data,error}=await supabase.storage.from("driver-documents").createSignedUrl(doc.file_path,300);if(error||!data?.signedUrl){setNotice("Não foi possível abrir o arquivo.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 async function review(doc:Doc,action:"APPROVE"|"REJECT"){let reason="";if(action==="REJECT"){reason=window.prompt("Informe o motivo da recusa:")?.trim()??"";if(!reason)return;}const{data,error}=await supabase.functions.invoke("driver-document-review",{body:{documentId:doc.id,action,reason:reason||undefined}});if(error||data?.error){setNotice(data?.error==="DOCUMENT_ALREADY_REVIEWED"?"Este documento já foi analisado.":"Não foi possível registrar a análise.");return;}setNotice(action==="APPROVE"?"Documento aprovado.":"Documento recusado e o entregador foi avisado.");await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando documentos...</div></main>;
 return <main className="content standaloneAdmin"><header className="topbar"><div><p className="eyebrow">MATRIZ CLICK-FOOD</p><h1>Documentos dos entregadores</h1><p>Arquivos privados. Acesso somente ao entregador e à Matriz.</p></div><a className="logout adminLink" href="/">← Voltar à Matriz</a></header>{notice&&<div className="notice">{notice}</div>}
 <div className="metricGrid"><article className="metric"><p>Pendentes</p><strong>{docs.filter(d=>d.status==="PENDING").length}</strong></article><article className="metric"><p>Aprovados</p><strong>{docs.filter(d=>d.status==="APPROVED").length}</strong></article><article className="metric"><p>Recusados</p><strong>{docs.filter(d=>d.status==="REJECTED").length}</strong></article><article className="metric"><p>Entregadores</p><strong>{new Set(docs.map(d=>d.driver_id)).size}</strong></article></div>
 <section className="panel adminStandalonePanel"><div className="panelTitle"><h2>Fila de análise</h2><div className="adminActions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="PENDING">Pendentes</option><option value="APPROVED">Aprovados</option><option value="REJECTED">Recusados</option><option value="ALL">Todos</option></select><button className="primary" onClick={load}>Atualizar</button></div></div><div className="adminDataList">{visible.map(doc=>{const driver=driverMap.get(doc.driver_id);const profile=driver?profileMap.get(driver.user_id):undefined;return <div className="adminDataRow" key={doc.id}><div><b>{profile?.full_name||"Entregador"}</b><small>{labels[doc.document_type]??doc.document_type} • enviado {new Date(doc.created_at).toLocaleString("pt-BR")}{profile?.phone?` • ${profile.phone}`:""}</small>{doc.rejection_reason&&<small>Motivo: {doc.rejection_reason}</small>}</div><span className={`badge ${doc.status.toLowerCase()}`}>{doc.status}</span><div className="adminActions"><button onClick={()=>openDocument(doc)}>Abrir arquivo</button>{doc.status==="PENDING"&&<><button className="primary" onClick={()=>review(doc,"APPROVE")}>Aprovar</button><button className="danger" onClick={()=>review(doc,"REJECT")}>Recusar</button></>}</div></div>})}{!visible.length&&<div className="emptyState">Nenhum documento nesta situação.</div>}</div></section>
 </main>;
}
