"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Member={id:string;user_id:string;role:string;active:boolean;full_name:string;email:string|null;phone:string|null};
type Store={id:string;name:string;role:string};
const roles=["MANAGER","CASHIER","KITCHEN","EXPEDITION"];
export default function Usuarios(){
 const[loading,setLoading]=useState(true);const[store,setStore]=useState<Store|null>(null);const[members,setMembers]=useState<Member[]>([]);const[message,setMessage]=useState("");const[email,setEmail]=useState("");const[role,setRole]=useState("CASHIER");
 async function boot(){setLoading(true);const{data:s}=await supabase.auth.getSession();if(!s.session){setMessage("Entre no Painel do Lojista primeiro.");setLoading(false);return;}const{data:m}=await supabase.from("store_memberships").select("store_id,role,stores!inner(name)").eq("user_id",s.session.user.id).eq("active",true).limit(1);if(!m?.length){setMessage("Sua conta não está vinculada a uma loja.");setLoading(false);return;}const row:any=m[0];const relation=Array.isArray(row.stores)?row.stores[0]:row.stores;const current={id:row.store_id,name:relation?.name??"Minha loja",role:row.role};setStore(current);await loadMembers(current.id);setLoading(false);}
 async function loadMembers(storeId:string){const{data,error}=await supabase.functions.invoke("store-users",{body:{action:"LIST",storeId}});if(error||data?.error){setMessage("Não foi possível carregar a equipe.");return;}setMembers(data.members??[]);}
 useEffect(()=>{boot();},[]);
 async function addUser(e:FormEvent){e.preventDefault();if(!store)return;setMessage("");const{data,error}=await supabase.functions.invoke("store-users",{body:{action:"ADD",storeId:store.id,email,role}});if(error||data?.error){setMessage(data?.error==="INVITE_FAILED"?"Não foi possível convidar esse e-mail.":"Não foi possível adicionar o usuário.");return;}setEmail("");setMessage(data.invited?"Convite enviado por e-mail e usuário vinculado à loja.":"Usuário existente vinculado à loja.");await loadMembers(store.id);}
 async function changeRole(member:Member,newRole:string){if(!store)return;const{data,error}=await supabase.functions.invoke("store-users",{body:{action:"SET_ROLE",storeId:store.id,membershipId:member.id,role:newRole}});setMessage(error||data?.error?(data?.error==="LAST_OWNER"?"A loja precisa manter pelo menos um proprietário.":"Não foi possível alterar a função."):"Função atualizada.");await loadMembers(store.id);}
 async function toggle(member:Member){if(!store)return;const{data,error}=await supabase.functions.invoke("store-users",{body:{action:"SET_ACTIVE",storeId:store.id,membershipId:member.id,active:!member.active}});setMessage(error||data?.error?(data?.error==="LAST_OWNER"?"Não é possível desativar o último proprietário.":"Não foi possível alterar o acesso."):"Acesso atualizado.");await loadMembers(store.id);}
 if(loading)return <main className="configPage"><div className="configShell"><p>Carregando equipe...</p></div></main>;
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>{store?.name??"Painel do Lojista"}</small><h1>Usuários e permissões</h1></div><a className="backLink" href="/">← Voltar ao painel</a></header>{message&&<div className="setupMessage">{message}</div>}{store&&["OWNER","MANAGER"].includes(store.role)?<div className="managementGrid two"><form className="mgCard" onSubmit={addUser}><h2>Adicionar funcionário</h2><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Função<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option value={r} key={r}>{r}</option>)}</select></label><p className="muted">Se a conta ainda não existir, o CLICK-FOOD envia um convite por e-mail.</p><button className="setupPrimary">ADICIONAR / CONVIDAR</button></form><section className="mgCard"><h2>Equipe</h2><div className="dataList">{members.map(member=><div className="dataRow" key={member.id}><div><b>{member.full_name}</b><small>{member.email??"sem e-mail"} • {member.active?"ATIVO":"BLOQUEADO"}</small></div><div className="rowActions"><select value={member.role} onChange={e=>changeRole(member,e.target.value)}><option value="OWNER">OWNER</option><option value="MANAGER">MANAGER</option><option value="CASHIER">CASHIER</option><option value="KITCHEN">KITCHEN</option><option value="EXPEDITION">EXPEDITION</option></select><button onClick={()=>toggle(member)}>{member.active?"Bloquear":"Ativar"}</button></div></div>)}</div></section></div>:<div className="mgCard"><h2>Acesso limitado</h2><p>Somente proprietário ou gerente pode administrar usuários.</p></div>}</div></main>;
}
