"use client";
import { useEffect,useState } from "react";
import { supabase } from "../../lib/supabase";
const today=()=>new Date().toISOString().slice(0,10);const daysAgo=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)};const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function EntregadoresMatriz(){const[from,setFrom]=useState(daysAgo(30));const[to,setTo]=useState(today());const[status,setStatus]=useState("");const[cityId,setCityId]=useState("");const[data,setData]=useState<any>({drivers:[],cities:[]});const[loading,setLoading]=useState(false);const[msg,setMsg]=useState("");
 async function load(){setLoading(true);const end=new Date(`${to}T00:00:00`);end.setDate(end.getDate()+1);const{data:r,error}=await supabase.functions.invoke("admin-report-read",{body:{from:`${from}T00:00:00`,to:end.toISOString(),limit:250,driverStatus:status||undefined,cityId:cityId||undefined}});setLoading(false);if(error||r?.error){setMsg("Falha ao carregar os entregadores.");return;}setData(r);}
 useEffect(()=>{void load()},[]);
 async function setDriverStatus(driverId:string,next:"ACTIVE"|"BLOCKED"|"PENDING"){const{data:r,error}=await supabase.functions.invoke("admin-operations",{body:{action:"DRIVER_STATUS",driverId,status:next}});setMsg(error||r?.error?"Não foi possível alterar o entregador.":next==="BLOCKED"?"Entregador bloqueado pela Matriz.":"Status do entregador atualizado.");await load();}
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>MATRIZ • CONTROLE GLOBAL</small><h1>Entregadores CLICK-FOOD</h1><p>Cadastro, documentos, veículo, status e bloqueio são exclusivos da Matriz.</p></div><a className="backLink" href="/">← Painel Matriz</a></header><section className="mgCard"><div style={{display:"flex",gap:9,flexWrap:"wrap",alignItems:"end"}}><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="ACTIVE">Ativos</option><option value="PENDING">Pendentes</option><option value="BLOCKED">Bloqueados</option></select></label><label>Cidade<select value={cityId} onChange={e=>setCityId(e.target.value)}><option value="">Todas</option>{(data.cities??[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></label><button className="setupPrimary" onClick={()=>void load()}>{loading?"CARREGANDO...":"FILTRAR"}</button></div></section>{msg&&<div className="setupMessage">{msg}</div>}<section className="mgCard"><h2>{(data.drivers??[]).length} entregador(es)</h2><p>O período afeta entregas e ganhos; os dados cadastrais permanecem disponíveis para a Matriz.</p><div className="dataList">{(data.drivers??[]).map((d:any)=><div key={d.id} style={{border:"1px solid #e4e4e4",borderRadius:14,padding:14,marginBottom:10,background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h3 style={{margin:0}}>{d.name}</h3><small>{d.email||"sem e-mail"} • {d.phone||"sem telefone"}</small><p style={{margin:"5px 0",fontSize:12}}>{d.city||"Cidade não definida"} • {d.online?"🟢 ONLINE":"🔴 OFFLINE"} • ★ {Number(d.rating||0).toFixed(1)} • aceitação {Math.round(Number(d.acceptanceRate||0))}%</p>{d.vehicle&&<p style={{fontSize:12,margin:"4px 0"}}>Veículo: {d.vehicle.vehicle_type} • {[d.vehicle.brand,d.vehicle.model].filter(Boolean).join(" ")} • {d.vehicle.plate||"sem placa"} • {d.vehicle.year||""}</p>}<p style={{fontSize:12,margin:"4px 0"}}>Documentos: {(d.documents??[]).map((x:any)=>`${x.document_type}: ${x.status}`).join(" • ")||"nenhum documento"}</p></div><div style={{textAlign:"right"}}><b>{d.period?.deliveries||0} entrega(s)</b><div>{brl(Number(d.period?.earnings||0))} no período</div><div style={{marginTop:8,display:"flex",gap:6,justifyContent:"flex-end"}}>{d.status!=="ACTIVE"&&<button className="setupPrimary" onClick={()=>void setDriverStatus(d.id,"ACTIVE")}>ATIVAR</button>}{d.status!=="BLOCKED"&&<button className="setupSecondary" onClick={()=>void setDriverStatus(d.id,"BLOCKED")}>BLOQUEAR</button>}</div></div></div></div>)}</div></section></div></main>}
