"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import DeliveryIncidentActions from "../DeliveryIncidentActions";

type Ticket={id:string;opened_by:string;store_id:string|null;order_id:string|null;delivery_id:string|null;category:string;priority:string;status:string;subject:string;created_at:string;updated_at:string;stores?:{name:string}|{name:string}[]|null};type Msg={id:string;sender_id:string;body:string;created_at:string};
export default function Suporte(){
 const[loading,setLoading]=useState(true);const[tickets,setTickets]=useState<Ticket[]>([]);const[selected,setSelected]=useState<Ticket|null>(null);const[messages,setMessages]=useState<Msg[]>([]);const[reply,setReply]=useState("");const[notice,setNotice]=useState("");
 async function load(){const{data,error}=await supabase.from("support_tickets").select("id,opened_by,store_id,order_id,delivery_id,category,priority,status,subject,created_at,updated_at,stores(name)").order("updated_at",{ascending:false}).limit(200);if(error)setNotice("Não foi possível carregar os chamados.");else setTickets(data as unknown as Ticket[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function open(ticket:Ticket){setSelected(ticket);const{data}=await supabase.from("support_messages").select("id,sender_id,body,created_at").eq("ticket_id",ticket.id).order("created_at");setMessages((data??[]) as Msg[]);}
 async function send(e:FormEvent){e.preventDefault();if(!selected||!reply.trim())return;const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"REPLY",ticketId:selected.id,message:reply}});if(error||data?.error){setNotice("Não foi possível enviar a resposta.");return;}setReply("");setNotice("Resposta enviada.");await open(selected);await load();}
 async function status(value:string){if(!selected)return;const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"SET_STATUS",ticketId:selected.id,status:value}});if(error||data?.error){setNotice("Não foi possível alterar o chamado.");return;}const updated={...selected,status:value};setSelected(updated);setNotice("Status atualizado.");await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando suporte...</div></main>;
 return <main className="content standaloneAdmin"><header className="topbar"><div><p className="eyebrow">MATRIZ CLICK-FOOD</p><h1>Central de suporte</h1></div><a className="logout adminLink" href="/">← Voltar à Matriz</a></header>{notice&&<div className="notice">{notice}</div>}<div className="twoColumns"><section className="panel"><div className="panelTitle"><h2>Chamados</h2><button className="primary" onClick={load}>Atualizar</button></div><div className="adminDataList">{tickets.map(ticket=>{const store=Array.isArray(ticket.stores)?ticket.stores[0]:ticket.stores;return <button className="adminTicket" key={ticket.id} onClick={()=>open(ticket)}><div><b>{ticket.subject}</b><small>{store?.name??"Usuário"} • {ticket.category} • {ticket.priority}</small></div><span className={`badge ${ticket.status.toLowerCase()}`}>{ticket.status}</span></button>})}{!tickets.length&&<div className="emptyState">Nenhum chamado.</div>}</div></section><section className="panel">{selected?<><div className="panelTitle"><div><h2>{selected.subject}</h2><small>{selected.category} • {selected.priority}</small></div><select value={selected.status} onChange={e=>status(e.target.value)}><option value="OPEN">Aberto</option><option value="IN_PROGRESS">Em atendimento</option><option value="WAITING_USER">Aguardando usuário</option><option value="RESOLVED">Resolvido</option><option value="CLOSED">Fechado</option></select></div>{selected.category==="DELIVERY_INCIDENT"&&selected.delivery_id&&<DeliveryIncidentActions deliveryId={selected.delivery_id} onChanged={async()=>{await open(selected);await load();}}/>}<div className="adminSupportMessages">{messages.map(msg=><div key={msg.id}><p>{msg.body}</p><small>{new Date(msg.created_at).toLocaleString("pt-BR")}</small></div>)}</div><form className="adminSupportReply" onSubmit={send}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Responder chamado..."/><button className="primary">ENVIAR RESPOSTA</button></form></>:<div className="emptyState">Selecione um chamado.</div>}</section></div></main>;
}
