"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type StoreAccess={id:string;name:string;role:string};
type Product={id:string;name:string;active:boolean;available_delivery:boolean};
type Category={id:string;name:string;active:boolean;sort_order:number};
type Promotion={id:string;name:string;description:string|null;promotion_type:string;discount_value:number;product_id:string|null;starts_at:string|null;ends_at:string|null;active:boolean;created_at:string};
type CouponRule={id:string;coupon_id:string;rule_type:string;rule_value:Record<string,string>};
type Coupon={id:string;code:string;discount_type:string;discount_value:number;minimum_order:number;max_uses:number|null;max_uses_per_customer:number|null;starts_at:string|null;ends_at:string|null;active:boolean;created_at:string;rules:CouponRule[];uses:number;total_discount:number};
type PromotionForm={id:string;name:string;description:string;promotionType:"PERCENTAGE"|"FIXED"|"PRODUCT_PRICE"|"FREE_DELIVERY";discountValue:string;productId:string;startsAt:string;endsAt:string};
type CouponForm={id:string;code:string;discountType:"PERCENTAGE"|"FIXED"|"FREE_DELIVERY";discountValue:string;minimumOrder:string;maxUses:string;maxUsesPerCustomer:string;startsAt:string;endsAt:string;ruleType:"NONE"|"FIRST_ORDER"|"PRODUCT"|"CATEGORY";ruleTargetId:string};

const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const blankPromotion:PromotionForm={id:"",name:"",description:"",promotionType:"PERCENTAGE",discountValue:"",productId:"",startsAt:"",endsAt:""};
const blankCoupon:CouponForm={id:"",code:"",discountType:"PERCENTAGE",discountValue:"",minimumOrder:"0",maxUses:"",maxUsesPerCustomer:"1",startsAt:"",endsAt:"",ruleType:"NONE",ruleTargetId:""};
const promotionLabel:Record<string,string>={PERCENTAGE:"Desconto percentual",FIXED:"Desconto em reais",PRODUCT_PRICE:"Preço especial",FREE_DELIVERY:"Entrega grátis"};
const couponLabel:Record<string,string>={PERCENTAGE:"Percentual",FIXED:"Valor fixo",FREE_DELIVERY:"Entrega grátis"};
const ruleLabel:Record<string,string>={FIRST_ORDER:"Somente primeira compra",PRODUCT:"Exige produto",CATEGORY:"Exige categoria"};

function toLocalInput(iso:string|null){if(!iso)return"";const d=new Date(iso);if(Number.isNaN(d.getTime()))return"";const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
function toIso(local:string){if(!local)return null;const d=new Date(local);return Number.isNaN(d.getTime())?null:d.toISOString();}
function parseMoney(value:string){return Number(String(value||"0").replace(",","."));}
function errorText(code:string){const map:Record<string,string>={COUPON_CODE_EXISTS:"Já existe um cupom com esse código nesta loja.",INVALID_PROMOTION:"Preencha os dados da promoção.",INVALID_PROMOTION_VALUE:"Informe um valor válido para a promoção.",PROMOTION_PRODUCT_REQUIRED:"Escolha o produto que receberá a promoção.",INVALID_PROMOTION_DATES:"A data final precisa ser posterior à data inicial.",INVALID_COUPON:"Revise código, pedido mínimo e limites de uso.",INVALID_COUPON_VALUE:"Informe um valor válido para o cupom.",INVALID_COUPON_DATES:"A data final do cupom precisa ser posterior à inicial.",COUPON_RULE_PRODUCT_REQUIRED:"Escolha o produto exigido pelo cupom.",COUPON_RULE_CATEGORY_REQUIRED:"Escolha a categoria exigida pelo cupom.",STORE_WRITE_DENIED:"Seu perfil pode consultar, mas não pode alterar promoções.",STORE_ACCESS_DENIED:"Sua conta não tem acesso a esta loja."};return map[code]??"Não foi possível concluir a operação agora.";}

export default function PromocoesPage(){
 const[loading,setLoading]=useState(true);const[store,setStore]=useState<StoreAccess|null>(null);const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[promotions,setPromotions]=useState<Promotion[]>([]);const[coupons,setCoupons]=useState<Coupon[]>([]);const[notice,setNotice]=useState("");const[saving,setSaving]=useState(false);const[promotionForm,setPromotionForm]=useState<PromotionForm>(blankPromotion);const[couponForm,setCouponForm]=useState<CouponForm>(blankCoupon);
 const canManage=store?.role==="OWNER"||store?.role==="MANAGER";
 const activePromotions=promotions.filter(p=>p.active).length;const activeCoupons=coupons.filter(c=>c.active).length;const totalUses=coupons.reduce((s,c)=>s+Number(c.uses||0),0);const totalDiscount=coupons.reduce((s,c)=>s+Number(c.total_discount||0),0);
 const productNames=useMemo(()=>new Map(products.map(p=>[p.id,p.name])),[products]);const categoryNames=useMemo(()=>new Map(categories.map(c=>[c.id,c.name])),[categories]);

 async function load(){
  setLoading(true);
  const{data:sessionData}=await supabase.auth.getSession();
  const session=sessionData.session;if(!session){setStore(null);setNotice("Entre no Painel Lojista primeiro.");setLoading(false);return;}
  const{data:memberships,error:membershipError}=await supabase.from("store_memberships").select("store_id,role,stores!inner(name)").eq("user_id",session.user.id).eq("active",true).limit(1);
  if(membershipError||!memberships?.length){setStore(null);setNotice("Sua conta ainda não está vinculada a uma loja.");setLoading(false);return;}
  const row:any=memberships[0],rel=Array.isArray(row.stores)?row.stores[0]:row.stores;const access={id:String(row.store_id),name:String(rel?.name??"Minha loja"),role:String(row.role)};setStore(access);
  const{data,error}=await supabase.functions.invoke("store-promotions",{body:{storeId:access.id,action:"GET"}});
  if(error||data?.error){setNotice("Não foi possível carregar promoções e cupons.");setLoading(false);return;}
  setPromotions((data.promotions??[]).map((p:any)=>({...p,discount_value:Number(p.discount_value)})));setCoupons((data.coupons??[]).map((c:any)=>({...c,discount_value:Number(c.discount_value),minimum_order:Number(c.minimum_order),total_discount:Number(c.total_discount||0),uses:Number(c.uses||0)})));setProducts((data.products??[]) as Product[]);setCategories((data.categories??[]) as Category[]);setLoading(false);
 }
 useEffect(()=>{void load();},[]);

 async function savePromotion(e:FormEvent){
  e.preventDefault();if(!store||!canManage)return;const value=parseMoney(promotionForm.discountValue);if(!promotionForm.name.trim()){setNotice("Informe o nome da promoção.");return;}if(promotionForm.promotionType!=="FREE_DELIVERY"&&!promotionForm.productId){setNotice("Escolha o produto da promoção.");return;}
  setSaving(true);setNotice("");const{data,error}=await supabase.functions.invoke("store-promotions",{body:{storeId:store.id,action:"SAVE_PROMOTION",promotion:{id:promotionForm.id||undefined,name:promotionForm.name.trim(),description:promotionForm.description.trim(),promotionType:promotionForm.promotionType,discountValue:promotionForm.promotionType==="FREE_DELIVERY"?0:value,productId:promotionForm.promotionType==="FREE_DELIVERY"?null:promotionForm.productId,startsAt:toIso(promotionForm.startsAt),endsAt:toIso(promotionForm.endsAt)}}});setSaving(false);
  if(error||data?.error){setNotice(errorText(String(data?.error??"")));return;}setNotice(promotionForm.id?"Promoção atualizada.":"Promoção criada e ativada.");setPromotionForm(blankPromotion);await load();
 }
 function editPromotion(p:Promotion){setPromotionForm({id:p.id,name:p.name,description:p.description??"",promotionType:p.promotion_type as PromotionForm["promotionType"],discountValue:p.promotion_type==="FREE_DELIVERY"?"":String(p.discount_value).replace(".",","),productId:p.product_id??"",startsAt:toLocalInput(p.starts_at),endsAt:toLocalInput(p.ends_at)});setNotice("");window.scrollTo({top:0,behavior:"smooth"});}
 async function togglePromotion(p:Promotion){if(!store||!canManage)return;const{data,error}=await supabase.functions.invoke("store-promotions",{body:{storeId:store.id,action:"TOGGLE_PROMOTION",id:p.id,active:!p.active}});if(error||data?.error){setNotice("Não foi possível alterar a promoção.");return;}setNotice(p.active?"Promoção pausada.":"Promoção ativada.");await load();}

 function rulesForForm(){if(couponForm.ruleType==="NONE")return[];if(couponForm.ruleType==="FIRST_ORDER")return[{type:"FIRST_ORDER"}];if(couponForm.ruleType==="PRODUCT")return[{type:"PRODUCT",productId:couponForm.ruleTargetId}];return[{type:"CATEGORY",categoryId:couponForm.ruleTargetId}];}
 async function saveCoupon(e:FormEvent){
  e.preventDefault();if(!store||!canManage)return;if(couponForm.ruleType!=="NONE"&&couponForm.ruleType!=="FIRST_ORDER"&&!couponForm.ruleTargetId){setNotice("Escolha o produto ou categoria da regra do cupom.");return;}
  setSaving(true);setNotice("");const{data,error}=await supabase.functions.invoke("store-promotions",{body:{storeId:store.id,action:"SAVE_COUPON",coupon:{id:couponForm.id||undefined,code:couponForm.code.trim().toUpperCase(),discountType:couponForm.discountType,discountValue:couponForm.discountType==="FREE_DELIVERY"?0:parseMoney(couponForm.discountValue),minimumOrder:parseMoney(couponForm.minimumOrder),maxUses:couponForm.maxUses.trim()?Number(couponForm.maxUses):null,maxUsesPerCustomer:couponForm.maxUsesPerCustomer.trim()?Number(couponForm.maxUsesPerCustomer):null,startsAt:toIso(couponForm.startsAt),endsAt:toIso(couponForm.endsAt),rules:rulesForForm()}}});setSaving(false);
  if(error||data?.error){setNotice(errorText(String(data?.error??"")));return;}setNotice(couponForm.id?"Cupom atualizado.":"Cupom criado e ativado.");setCouponForm(blankCoupon);await load();
 }
 function editCoupon(c:Coupon){const r=c.rules?.[0];let ruleType:CouponForm["ruleType"]="NONE",ruleTargetId="";if(r?.rule_type==="FIRST_ORDER")ruleType="FIRST_ORDER";if(r?.rule_type==="PRODUCT"){ruleType="PRODUCT";ruleTargetId=String(r.rule_value?.product_id??"");}if(r?.rule_type==="CATEGORY"){ruleType="CATEGORY";ruleTargetId=String(r.rule_value?.category_id??"");}setCouponForm({id:c.id,code:c.code,discountType:c.discount_type as CouponForm["discountType"],discountValue:c.discount_type==="FREE_DELIVERY"?"":String(c.discount_value).replace(".",","),minimumOrder:String(c.minimum_order).replace(".",","),maxUses:c.max_uses==null?"":String(c.max_uses),maxUsesPerCustomer:c.max_uses_per_customer==null?"":String(c.max_uses_per_customer),startsAt:toLocalInput(c.starts_at),endsAt:toLocalInput(c.ends_at),ruleType,ruleTargetId});setNotice("");window.scrollTo({top:0,behavior:"smooth"});}
 async function toggleCoupon(c:Coupon){if(!store||!canManage)return;const{data,error}=await supabase.functions.invoke("store-promotions",{body:{storeId:store.id,action:"TOGGLE_COUPON",id:c.id,active:!c.active}});if(error||data?.error){setNotice("Não foi possível alterar o cupom.");return;}setNotice(c.active?"Cupom pausado.":"Cupom ativado.");await load();}

 function promotionValue(p:Promotion){if(p.promotion_type==="FREE_DELIVERY")return"Entrega grátis";if(p.promotion_type==="PERCENTAGE")return`${p.discount_value}%`;return brl(p.discount_value);}
 function couponValue(c:Coupon){if(c.discount_type==="FREE_DELIVERY")return"Entrega grátis";if(c.discount_type==="PERCENTAGE")return`${c.discount_value}%`;return brl(c.discount_value);}
 function couponRule(c:Coupon){const r=c.rules?.[0];if(!r)return"Sem restrição adicional";if(r.rule_type==="PRODUCT")return`Exige ${productNames.get(String(r.rule_value?.product_id))??"produto selecionado"}`;if(r.rule_type==="CATEGORY")return`Exige categoria ${categoryNames.get(String(r.rule_value?.category_id))??"selecionada"}`;return ruleLabel[r.rule_type]??r.rule_type;}

 if(loading)return <main className="promoPage"><div className="promoShell">Carregando promoções...</div></main>;
 if(!store)return <main className="promoPage"><div className="promoShell"><h1>Promoções e cupons</h1><p>{notice}</p><a href="/">Voltar ao painel</a></div></main>;
 return <main className="promoPage"><div className="promoShell">
  <header className="promoHero"><div><span>MARKETING DA LOJA</span><h1>Promoções e cupons</h1><p>{store.name} • campanhas integradas ao checkout do CLICK-FOOD, sem cálculo manual.</p></div><div className="promoHeroActions"><a href="/">← Painel</a><a href="/produtos">Produtos</a><button onClick={()=>void load()}>Atualizar</button></div></header>
  {!!notice&&<div className="promoNotice">{notice}</div>}
  <section className="promoStats"><article><span>Promoções ativas</span><strong>{activePromotions}</strong><small>de {promotions.length}</small></article><article><span>Cupons ativos</span><strong>{activeCoupons}</strong><small>de {coupons.length}</small></article><article><span>Cupons utilizados</span><strong>{totalUses}</strong><small>resgates confirmados</small></article><article><span>Desconto por cupons</span><strong>{brl(totalDiscount)}</strong><small>histórico registrado</small></article></section>

  <section className="promoForms">
   <form className="promoPanel" onSubmit={savePromotion}><div className="promoPanelTitle"><div><span>{promotionForm.id?"EDITAR":"NOVA"} PROMOÇÃO</span><h2>Campanha automática</h2></div>{promotionForm.id&&<button type="button" onClick={()=>setPromotionForm(blankPromotion)}>Cancelar</button>}</div>
    <label>Nome<input value={promotionForm.name} onChange={e=>setPromotionForm({...promotionForm,name:e.target.value})} placeholder="Ex.: Hambúrguer da terça" required/></label>
    <label>Descrição<textarea value={promotionForm.description} onChange={e=>setPromotionForm({...promotionForm,description:e.target.value})} placeholder="Mensagem interna para organizar a campanha."/></label>
    <div className="promoTwo"><label>Tipo<select value={promotionForm.promotionType} onChange={e=>setPromotionForm({...promotionForm,promotionType:e.target.value as PromotionForm["promotionType"],productId:e.target.value==="FREE_DELIVERY"?"":promotionForm.productId})}><option value="PERCENTAGE">Desconto percentual</option><option value="FIXED">Desconto em reais</option><option value="PRODUCT_PRICE">Preço especial</option><option value="FREE_DELIVERY">Entrega grátis</option></select></label><label>Valor<input disabled={promotionForm.promotionType==="FREE_DELIVERY"} value={promotionForm.discountValue} onChange={e=>setPromotionForm({...promotionForm,discountValue:e.target.value})} inputMode="decimal" placeholder={promotionForm.promotionType==="PERCENTAGE"?"10":"9,90"}/></label></div>
    {promotionForm.promotionType!=="FREE_DELIVERY"&&<label>Produto<select value={promotionForm.productId} onChange={e=>setPromotionForm({...promotionForm,productId:e.target.value})} required><option value="">Selecione</option>{products.filter(p=>p.active&&p.available_delivery).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
    <div className="promoTwo"><label>Início <small>(opcional)</small><input type="datetime-local" value={promotionForm.startsAt} onChange={e=>setPromotionForm({...promotionForm,startsAt:e.target.value})}/></label><label>Fim <small>(opcional)</small><input type="datetime-local" value={promotionForm.endsAt} onChange={e=>setPromotionForm({...promotionForm,endsAt:e.target.value})}/></label></div>
    <p className="promoHelp">O desconto é recalculado no servidor ao criar o pedido. O cliente nunca define o preço final.</p><button className="promoPrimary" disabled={saving||!canManage}>{saving?"SALVANDO...":promotionForm.id?"SALVAR PROMOÇÃO":"CRIAR PROMOÇÃO"}</button>
   </form>

   <form className="promoPanel" onSubmit={saveCoupon}><div className="promoPanelTitle"><div><span>{couponForm.id?"EDITAR":"NOVO"} CUPOM</span><h2>Código promocional</h2></div>{couponForm.id&&<button type="button" onClick={()=>setCouponForm(blankCoupon)}>Cancelar</button>}</div>
    <div className="promoTwo"><label>Código<input value={couponForm.code} onChange={e=>setCouponForm({...couponForm,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,"")})} placeholder="BEMVINDO10" maxLength={32} required/></label><label>Tipo<select value={couponForm.discountType} onChange={e=>setCouponForm({...couponForm,discountType:e.target.value as CouponForm["discountType"]})}><option value="PERCENTAGE">Percentual</option><option value="FIXED">Valor fixo</option><option value="FREE_DELIVERY">Entrega grátis</option></select></label></div>
    <div className="promoTwo"><label>Valor<input disabled={couponForm.discountType==="FREE_DELIVERY"} value={couponForm.discountValue} onChange={e=>setCouponForm({...couponForm,discountValue:e.target.value})} inputMode="decimal" placeholder={couponForm.discountType==="PERCENTAGE"?"10":"10,00"}/></label><label>Pedido mínimo<input value={couponForm.minimumOrder} onChange={e=>setCouponForm({...couponForm,minimumOrder:e.target.value})} inputMode="decimal" placeholder="0,00"/></label></div>
    <div className="promoTwo"><label>Limite total <small>(vazio = ilimitado)</small><input value={couponForm.maxUses} onChange={e=>setCouponForm({...couponForm,maxUses:e.target.value.replace(/\D/g,"")})} inputMode="numeric"/></label><label>Por cliente <small>(vazio = ilimitado)</small><input value={couponForm.maxUsesPerCustomer} onChange={e=>setCouponForm({...couponForm,maxUsesPerCustomer:e.target.value.replace(/\D/g,"")})} inputMode="numeric"/></label></div>
    <label>Regra adicional<select value={couponForm.ruleType} onChange={e=>setCouponForm({...couponForm,ruleType:e.target.value as CouponForm["ruleType"],ruleTargetId:""})}><option value="NONE">Nenhuma</option><option value="FIRST_ORDER">Somente primeira compra na loja</option><option value="PRODUCT">Exigir produto no carrinho</option><option value="CATEGORY">Exigir categoria no carrinho</option></select></label>
    {couponForm.ruleType==="PRODUCT"&&<label>Produto exigido<select value={couponForm.ruleTargetId} onChange={e=>setCouponForm({...couponForm,ruleTargetId:e.target.value})}><option value="">Selecione</option>{products.filter(p=>p.active&&p.available_delivery).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
    {couponForm.ruleType==="CATEGORY"&&<label>Categoria exigida<select value={couponForm.ruleTargetId} onChange={e=>setCouponForm({...couponForm,ruleTargetId:e.target.value})}><option value="">Selecione</option>{categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
    <div className="promoTwo"><label>Início <small>(opcional)</small><input type="datetime-local" value={couponForm.startsAt} onChange={e=>setCouponForm({...couponForm,startsAt:e.target.value})}/></label><label>Fim <small>(opcional)</small><input type="datetime-local" value={couponForm.endsAt} onChange={e=>setCouponForm({...couponForm,endsAt:e.target.value})}/></label></div>
    <p className="promoHelp">O código é validado no backend quanto a loja, validade, limite, pedido mínimo e regra escolhida.</p><button className="promoPrimary" disabled={saving||!canManage}>{saving?"SALVANDO...":couponForm.id?"SALVAR CUPOM":"CRIAR CUPOM"}</button>
   </form>
  </section>

  <section className="promoListGrid"><div className="promoPanel"><div className="promoPanelTitle"><div><span>CAMPANHAS</span><h2>Promoções cadastradas</h2></div></div><div className="promoList">{promotions.length?promotions.map(p=><article className={`promoRow ${p.active?"":"paused"}`} key={p.id}><div className="promoRowTop"><div><strong>{p.name}</strong><span className={p.active?"promoBadge active":"promoBadge"}>{p.active?"ATIVA":"PAUSADA"}</span></div><b>{promotionValue(p)}</b></div><p>{promotionLabel[p.promotion_type]??p.promotion_type}{p.product_id?` • ${productNames.get(p.product_id)??"Produto"}`:""}</p><small>{p.starts_at?`Início ${new Date(p.starts_at).toLocaleString("pt-BR")}`:"Sem data inicial"} • {p.ends_at?`fim ${new Date(p.ends_at).toLocaleString("pt-BR")}`:"sem data final"}</small><div className="promoRowActions"><button onClick={()=>editPromotion(p)} disabled={!canManage}>Editar</button><button onClick={()=>void togglePromotion(p)} disabled={!canManage}>{p.active?"Pausar":"Ativar"}</button></div></article>):<div className="promoEmpty">Nenhuma promoção cadastrada.</div>}</div></div>
   <div className="promoPanel"><div className="promoPanelTitle"><div><span>CÓDIGOS</span><h2>Cupons cadastrados</h2></div></div><div className="promoList">{coupons.length?coupons.map(c=><article className={`promoRow ${c.active?"":"paused"}`} key={c.id}><div className="promoRowTop"><div><strong className="couponCode">{c.code}</strong><span className={c.active?"promoBadge active":"promoBadge"}>{c.active?"ATIVO":"PAUSADO"}</span></div><b>{couponValue(c)}</b></div><p>{couponRule(c)} • pedido mínimo {brl(c.minimum_order)}</p><small>{c.uses} uso(s) • {brl(c.total_discount)} concedidos{c.max_uses!=null?` • limite ${c.max_uses}`:""}</small><div className="promoRowActions"><button onClick={()=>editCoupon(c)} disabled={!canManage}>Editar</button><button onClick={()=>void toggleCoupon(c)} disabled={!canManage}>{c.active?"Pausar":"Ativar"}</button></div></article>):<div className="promoEmpty">Nenhum cupom cadastrado.</div>}</div></div></section>
  {!canManage&&<div className="promoReadOnly">Seu perfil está em modo consulta. Apenas proprietário ou gerente pode alterar campanhas.</div>}
 </div></main>;
}
