"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Product={id:string;name:string;price:number;promotional_price:number|null;active:boolean};
type Variant={id:string;product_id:string;name:string;price:number;active:boolean;sort_order:number};
type Group={id:string;store_id:string;name:string;required:boolean;minimum_choices:number;maximum_choices:number;active:boolean};
type Option={id:string;option_group_id:string;name:string;additional_price:number;active:boolean;sort_order:number};
type Link={product_id:string;option_group_id:string};
type Promotion={id:string;name:string;description:string|null;promotion_type:string;discount_value:number;product_id:string|null;starts_at:string|null;ends_at:string|null;active:boolean};

const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const fmt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"sem data";

export default function CatalogoAvancado(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[role,setRole]=useState("");const[message,setMessage]=useState("");
 const[products,setProducts]=useState<Product[]>([]);const[variants,setVariants]=useState<Variant[]>([]);const[groups,setGroups]=useState<Group[]>([]);const[options,setOptions]=useState<Option[]>([]);const[links,setLinks]=useState<Link[]>([]);const[promotions,setPromotions]=useState<Promotion[]>([]);
 const[variantForm,setVariantForm]=useState({productId:"",name:"",price:""});const[groupForm,setGroupForm]=useState({name:"",required:false,min:"0",max:"1"});const[optionForm,setOptionForm]=useState({groupId:"",name:"",price:"0"});const[linkForm,setLinkForm]=useState({productId:"",groupId:""});const[promoForm,setPromoForm]=useState({name:"",description:"",type:"PERCENTAGE",value:"10",productId:"",startsAt:"",endsAt:""});
 const canManage=["OWNER","MANAGER"].includes(role);
 const productsById=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);const groupsById=useMemo(()=>new Map(groups.map(g=>[g.id,g])),[groups]);

 async function resolveStore(){setLoading(true);const{data:sd}=await supabase.auth.getSession();if(!sd.session){setMessage("Entre no Painel Lojista antes de acessar o catálogo avançado.");setLoading(false);return;}const{data,error}=await supabase.from("store_memberships").select("store_id,role,stores(name)").eq("user_id",sd.session.user.id).eq("active",true).limit(1);if(error||!data?.length){setMessage("Sua conta não está vinculada a uma loja.");setLoading(false);return;}const m:any=data[0];const s=Array.isArray(m.stores)?m.stores[0]:m.stores;setStoreId(m.store_id);setStoreName(s?.name??"Minha loja");setRole(m.role);await loadData(m.store_id);setLoading(false);}
 async function loadData(id=storeId){if(!id)return;const[pR,gR,prR]=await Promise.all([supabase.from("products").select("id,name,price,promotional_price,active").eq("store_id",id).order("name"),supabase.from("option_groups").select("id,store_id,name,required,minimum_choices,maximum_choices,active").eq("store_id",id).order("name"),supabase.from("promotions").select("id,name,description,promotion_type,discount_value,product_id,starts_at,ends_at,active").eq("store_id",id).order("created_at",{ascending:false})]);const ps=(pR.data??[]).map((x:any)=>({...x,price:Number(x.price),promotional_price:x.promotional_price==null?null:Number(x.promotional_price)}));const gs=(gR.data??[]) as Group[];setProducts(ps);setGroups(gs);setPromotions((prR.data??[]).map((x:any)=>({...x,discount_value:Number(x.discount_value)})));const pids=ps.map((x:any)=>x.id),gids=gs.map(x=>x.id);const[vR,oR,lR]=await Promise.all([pids.length?supabase.from("product_variants").select("id,product_id,name,price,active,sort_order").in("product_id",pids).order("sort_order").order("name"):Promise.resolve({data:[] as any[],error:null}),gids.length?supabase.from("product_options").select("id,option_group_id,name,additional_price,active,sort_order").in("option_group_id",gids).order("sort_order").order("name"):Promise.resolve({data:[] as any[],error:null}),pids.length?supabase.from("product_option_groups").select("product_id,option_group_id").in("product_id",pids):Promise.resolve({data:[] as any[],error:null})]);setVariants((vR.data??[]).map((x:any)=>({...x,price:Number(x.price)})));setOptions((oR.data??[]).map((x:any)=>({...x,additional_price:Number(x.additional_price)})));setLinks((lR.data??[]) as Link[]);}
 useEffect(()=>{resolveStore();},[]);

 async function createVariant(e:FormEvent){e.preventDefault();if(!canManage)return;const price=Number(variantForm.price.replace(",","."));if(!variantForm.productId||!variantForm.name.trim()||!Number.isFinite(price)||price<0){setMessage("Informe produto, nome da variação e preço válido.");return;}const{error}=await supabase.from("product_variants").insert({product_id:variantForm.productId,name:variantForm.name.trim(),price,active:true});setMessage(error?"Não foi possível criar a variação.":"Variação criada.");if(!error)setVariantForm({...variantForm,name:"",price:""});await loadData();}
 async function createGroup(e:FormEvent){e.preventDefault();if(!canManage)return;const min=Number(groupForm.min),max=Number(groupForm.max);if(!groupForm.name.trim()||!Number.isInteger(min)||!Number.isInteger(max)||min<0||max<1||min>max){setMessage("Revise o nome e os limites do grupo.");return;}const{error}=await supabase.from("option_groups").insert({store_id:storeId,name:groupForm.name.trim(),required:groupForm.required,minimum_choices:groupForm.required?Math.max(1,min):min,maximum_choices:max,active:true});setMessage(error?"Não foi possível criar o grupo.":"Grupo de complementos criado.");if(!error)setGroupForm({name:"",required:false,min:"0",max:"1"});await loadData();}
 async function createOption(e:FormEvent){e.preventDefault();if(!canManage)return;const price=Number(optionForm.price.replace(",","."));if(!optionForm.groupId||!optionForm.name.trim()||!Number.isFinite(price)||price<0){setMessage("Informe grupo, nome e valor adicional válido.");return;}const{error}=await supabase.from("product_options").insert({option_group_id:optionForm.groupId,name:optionForm.name.trim(),additional_price:price,active:true});setMessage(error?"Não foi possível criar o complemento.":"Complemento criado.");if(!error)setOptionForm({...optionForm,name:"",price:"0"});await loadData();}
 async function linkGroup(e:FormEvent){e.preventDefault();if(!canManage||!linkForm.productId||!linkForm.groupId)return;const exists=links.some(x=>x.product_id===linkForm.productId&&x.option_group_id===linkForm.groupId);if(exists){setMessage("Esse grupo já está ligado ao produto.");return;}const{error}=await supabase.from("product_option_groups").insert({product_id:linkForm.productId,option_group_id:linkForm.groupId});setMessage(error?"Não foi possível vincular o grupo.":"Grupo vinculado ao produto.");await loadData();}
 async function unlinkGroup(productId:string,groupId:string){if(!canManage)return;const{error}=await supabase.from("product_option_groups").delete().eq("product_id",productId).eq("option_group_id",groupId);setMessage(error?"Não foi possível remover o vínculo.":"Vínculo removido.");await loadData();}
 async function createPromotion(e:FormEvent){e.preventDefault();if(!canManage)return;const value=Number(promoForm.value.replace(",","."));if(!promoForm.name.trim()||!Number.isFinite(value)||value<0){setMessage("Informe nome e valor válidos.");return;}if(promoForm.type==="PERCENTAGE"&&value>100){setMessage("O percentual não pode passar de 100%.");return;}if(["PRODUCT_PRICE","FIXED","PERCENTAGE"].includes(promoForm.type)&&!promoForm.productId){setMessage("Selecione o produto da promoção.");return;}const starts=promoForm.startsAt?new Date(promoForm.startsAt).toISOString():null,ends=promoForm.endsAt?new Date(promoForm.endsAt).toISOString():null;if(starts&&ends&&new Date(ends)<=new Date(starts)){setMessage("A data final precisa ser posterior à inicial.");return;}const{error}=await supabase.from("promotions").insert({store_id:storeId,name:promoForm.name.trim(),description:promoForm.description.trim()||null,promotion_type:promoForm.type,discount_value:value,product_id:promoForm.productId||null,starts_at:starts,ends_at:ends,active:true});setMessage(error?"Não foi possível criar a promoção.":"Promoção criada.");if(!error)setPromoForm({...promoForm,name:"",description:""});await loadData();}
 async function toggle(table:"product_variants"|"option_groups"|"product_options"|"promotions",id:string,active:boolean){if(!canManage)return;const{error}=await supabase.from(table).update({active:!active,updated_at:new Date().toISOString()}).eq("id",id);setMessage(error?"Não foi possível alterar o status.":"Status atualizado.");await loadData();}

 if(loading)return <main className="configPage"><div className="configShell">Carregando catálogo avançado...</div></main>;
 return <main className="configPage"><div className="configShell"><div className="setupTitle"><div><small>CLICK-FOOD • {storeName}</small><h1>Catálogo avançado</h1></div><span>{role}</span></div>{message&&<div className="setupMessage">{message}</div>}{!canManage&&<div className="notice">Somente Proprietário ou Gerente pode alterar variações, complementos e promoções. Seu acesso permanece somente para consulta.</div>}
 <section className="setupGrid">
  <article className="setupCard"><div className="setupTitle"><div><small>PRODUTOS</small><h2>Variações e tamanhos</h2></div><span>{variants.length}</span></div><form onSubmit={createVariant}><select value={variantForm.productId} onChange={e=>setVariantForm({...variantForm,productId:e.target.value})}><option value="">Selecione o produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input placeholder="Ex.: Grande / 500 ml" value={variantForm.name} onChange={e=>setVariantForm({...variantForm,name:e.target.value})}/><input placeholder="Preço da variação" value={variantForm.price} onChange={e=>setVariantForm({...variantForm,price:e.target.value})}/><button className="setupPrimary" disabled={!canManage}>CRIAR VARIAÇÃO</button></form><div className="setupList">{variants.map(v=><div key={v.id}><div><b>{productsById.get(v.product_id)?.name} • {v.name}</b><small>{brl(v.price)} • {v.active?"Ativa":"Pausada"}</small></div><button disabled={!canManage} onClick={()=>toggle("product_variants",v.id,v.active)}>{v.active?"Pausar":"Ativar"}</button></div>)}{!variants.length&&<p className="setupHint">Use variações para tamanho, volume, unidade ou versão do mesmo produto.</p>}</div></article>

  <article className="setupCard"><div className="setupTitle"><div><small>COMPLEMENTOS</small><h2>Grupos de escolha</h2></div><span>{groups.length}</span></div><form onSubmit={createGroup}><input placeholder="Ex.: Escolha a borda" value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})}/><div className="setupRow"><input placeholder="Mínimo" value={groupForm.min} onChange={e=>setGroupForm({...groupForm,min:e.target.value})}/><input placeholder="Máximo" value={groupForm.max} onChange={e=>setGroupForm({...groupForm,max:e.target.value})}/></div><label className="checkLine"><input type="checkbox" checked={groupForm.required} onChange={e=>setGroupForm({...groupForm,required:e.target.checked,min:e.target.checked&&Number(groupForm.min)<1?"1":groupForm.min})}/> Escolha obrigatória</label><button className="setupPrimary" disabled={!canManage}>CRIAR GRUPO</button></form><div className="setupList">{groups.map(g=><div key={g.id}><div><b>{g.name}</b><small>{g.required?"Obrigatório":"Opcional"} • {g.minimum_choices}–{g.maximum_choices} escolha(s)</small></div><button disabled={!canManage} onClick={()=>toggle("option_groups",g.id,g.active)}>{g.active?"Pausar":"Ativar"}</button></div>)}</div></article>

  <article className="setupCard"><div className="setupTitle"><div><small>COMPLEMENTOS</small><h2>Opções e adicionais</h2></div><span>{options.length}</span></div><form onSubmit={createOption}><select value={optionForm.groupId} onChange={e=>setOptionForm({...optionForm,groupId:e.target.value})}><option value="">Selecione o grupo</option>{groups.filter(g=>g.active).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input placeholder="Ex.: Cheddar extra" value={optionForm.name} onChange={e=>setOptionForm({...optionForm,name:e.target.value})}/><input placeholder="Valor adicional" value={optionForm.price} onChange={e=>setOptionForm({...optionForm,price:e.target.value})}/><button className="setupPrimary" disabled={!canManage}>CRIAR COMPLEMENTO</button></form><div className="setupList">{options.map(o=><div key={o.id}><div><b>{o.name}</b><small>{groupsById.get(o.option_group_id)?.name} • + {brl(o.additional_price)}</small></div><button disabled={!canManage} onClick={()=>toggle("product_options",o.id,o.active)}>{o.active?"Pausar":"Ativar"}</button></div>)}</div></article>

  <article className="setupCard"><div className="setupTitle"><div><small>VÍNCULO</small><h2>Complementos por produto</h2></div></div><form onSubmit={linkGroup}><select value={linkForm.productId} onChange={e=>setLinkForm({...linkForm,productId:e.target.value})}><option value="">Produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={linkForm.groupId} onChange={e=>setLinkForm({...linkForm,groupId:e.target.value})}><option value="">Grupo de complemento</option>{groups.filter(g=>g.active).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="setupPrimary" disabled={!canManage}>VINCULAR</button></form><div className="setupList">{products.map(p=>{const productLinks=links.filter(l=>l.product_id===p.id);return productLinks.length?<div key={p.id} style={{display:"block"}}><b>{p.name}</b><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8}}>{productLinks.map(l=><button key={l.option_group_id} disabled={!canManage} onClick={()=>unlinkGroup(p.id,l.option_group_id)} title="Clique para remover">{groupsById.get(l.option_group_id)?.name??"Grupo"} ×</button>)}</div></div>:null})}</div></article>

  <article className="setupCard hoursCard"><div className="setupTitle"><div><small>MARKETING</small><h2>Promoções</h2></div><span>{promotions.length}</span></div><form onSubmit={createPromotion} style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9}}><input style={{gridColumn:"1/-1"}} placeholder="Nome da promoção" value={promoForm.name} onChange={e=>setPromoForm({...promoForm,name:e.target.value})}/><input style={{gridColumn:"1/-1"}} placeholder="Descrição opcional" value={promoForm.description} onChange={e=>setPromoForm({...promoForm,description:e.target.value})}/><select value={promoForm.type} onChange={e=>setPromoForm({...promoForm,type:e.target.value})}><option value="PERCENTAGE">Desconto %</option><option value="FIXED">Desconto em R$</option><option value="PRODUCT_PRICE">Preço promocional</option><option value="FREE_DELIVERY">Entrega grátis</option></select><input placeholder={promoForm.type==="PERCENTAGE"?"Percentual":"Valor"} value={promoForm.value} onChange={e=>setPromoForm({...promoForm,value:e.target.value})}/>{promoForm.type!=="FREE_DELIVERY"&&<select value={promoForm.productId} onChange={e=>setPromoForm({...promoForm,productId:e.target.value})}><option value="">Produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<label>Início<input type="datetime-local" value={promoForm.startsAt} onChange={e=>setPromoForm({...promoForm,startsAt:e.target.value})}/></label><label>Fim<input type="datetime-local" value={promoForm.endsAt} onChange={e=>setPromoForm({...promoForm,endsAt:e.target.value})}/></label><button style={{gridColumn:"1/-1"}} className="setupPrimary" disabled={!canManage}>CRIAR PROMOÇÃO</button></form><div className="setupList">{promotions.map(p=><div key={p.id}><div><b>{p.name}</b><small>{p.product_id?productsById.get(p.product_id)?.name+" • ":""}{p.promotion_type} • {p.discount_value} • {fmt(p.starts_at)} → {fmt(p.ends_at)}</small></div><button disabled={!canManage} onClick={()=>toggle("promotions",p.id,p.active)}>{p.active?"Pausar":"Ativar"}</button></div>)}{!promotions.length&&<p className="setupHint">As promoções ativas serão validadas no servidor no momento do pedido.</p>}</div></article>
 </section></div></main>;
}
