"use client";

import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Props={deliveryId:string;onChanged?:()=>void|Promise<void>};
type State={delivery:any;order:any;incident:any;capabilities:{canResume:boolean;canReassign:boolean;canRequireReturn:boolean;canCompleteReturn:boolean}};

export default function DeliveryIncidentActions({deliveryId,onChanged}:Props){
 const[state,setState]=useState<State|null>(null);const[busy,setBusy]=useState("");const[note,setNote]=useState("");const[message,setMessage]=useState("");
 useEffect(()=>{void load();},[deliveryId]);
 async function load(){const{data,error}=await supabase.functions.invoke("delivery-incident-action",{body:{deliveryId,action:"STATUS"}});if(error||data?.error){setMessage("Não foi possível carregar o incidente.");return;}setState(data as State);}
 async function run(action:"RESUME"|"REASSIGN"|"REQUIRE_RETURN"|"COMPLETE_RETURN"){if(busy)return;const destructive=action==="REQUIRE_RETURN"||action==="COMPLETE_RETURN";if(destructive&&!window.confirm(action==="REQUIRE_RETURN"?"Confirmar que o pedido deve retornar à loja?":"Confirma que sua loja recebeu o pedido retornado? Esta ação pode iniciar o estorno."))return;setBusy(action);setMessage("");const{data,error}=await supabase.functions.invoke("delivery-incident-action",{body:{deliveryId,action,note}});setBusy("");if(error||data?.error){setMessage("Não foi possível executar esta ação. Atualize o incidente e tente novamente.");return;}setNote("");setState(data as State);const labels:any={RESUME:"Entrega retomada.",REASSIGN:data?.dispatch?.ok?"Novo chamado enviado aos entregadores.":"Entregador liberado. A nova busca continuará automaticamente.",REQUIRE_RETURN:"Retorno à loja solicitado.",COMPLETE_RETURN:data?.refund?.refundStatus?`Retorno confirmado. Estorno: ${data.refund.refundStatus}.`:"Retorno confirmado e operação encerrada."};setMessage(labels[action]);await onChanged?.();}
 if(!state)return <div style={{padding:12,border:"1px solid #eee",borderRadius:12,margin:"12px 0"}}>{message||"Carregando incidente..."}</div>;
 const c=state.capabilities??{};const active=c.canResume||c.canReassign||c.canRequireReturn||c.canCompleteReturn;
 return <div style={{padding:14,border:"2px solid #f4c400",borderRadius:14,margin:"14px 0",background:"#fffbea"}}><b>Ocorrência da entrega</b><p style={{fontSize:12,margin:"6px 0"}}>Entrega: <strong>{state.delivery?.status??"—"}</strong>{state.incident?.previous_status?` • etapa anterior: ${state.incident.previous_status}`:""}</p>{state.incident?.resolution&&<p style={{fontSize:12}}>Resolução: {state.incident.resolution}</p>}{active&&<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Observação operacional (opcional)" style={{width:"100%",minHeight:68,padding:10,borderRadius:10,border:"1px solid #ddd",margin:"8px 0"}}/>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{c.canResume&&<button className="setupPrimary" disabled={!!busy} onClick={()=>run("RESUME")}>RETOMAR ENTREGA</button>}{c.canReassign&&<button className="setupPrimary" disabled={!!busy} onClick={()=>run("REASSIGN")}>BUSCAR OUTRO ENTREGADOR</button>}{c.canRequireReturn&&<button className="setupPrimary" disabled={!!busy} onClick={()=>run("REQUIRE_RETURN")}>SOLICITAR RETORNO</button>}{c.canCompleteReturn&&<button className="setupPrimary" disabled={!!busy} onClick={()=>run("COMPLETE_RETURN")}>CONFIRMAR RETORNO RECEBIDO</button>}{!active&&<span style={{fontSize:12,fontWeight:800}}>Incidente encerrado.</span>}</div>{message&&<p style={{fontSize:12,fontWeight:800,marginTop:10}}>{message}</p>}</div>;
}
