"use client";

import { useState } from "react";
import { supabase } from "../lib/supabase";

type Paper="80"|"58";
const esc=(value:unknown)=>String(value??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]??ch));
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const pay:Record<string,string>={CASH:"Dinheiro",PIX:"PIX",CREDIT_CARD:"Cartão de crédito",DEBIT_CARD:"Cartão de débito",WALLET:"Carteira",OTHER:"Outro"};

export default function OrderThermalPrintButton({orderId}:{orderId:string}){
 const[paper,setPaper]=useState<Paper>("80");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function print(){
  setBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("store-order-receipt",{body:{orderId}});setBusy(false);
  if(error||data?.error){setMessage("Não foi possível preparar a impressão.");return;}
  const r:any=data;const width=paper==="80"?76:54;const font=paper==="80"?12:10;const address=r.address?`${esc(r.address.street)}, ${esc(r.address.number||"s/n")}${r.address.complement?` - ${esc(r.address.complement)}`:""}<br>${esc(r.address.district||"")}${r.address.postal_code?` - CEP ${esc(r.address.postal_code)}`:""}${r.address.reference?`<br>Ref.: ${esc(r.address.reference)}`:""}`:"Retirada / balcão";
  const items=(r.items??[]).map((item:any)=>`<div class="item"><div class="line"><b>${esc(item.quantity)}x ${esc(item.name)}</b><b>${esc(brl(item.totalPrice))}</b></div>${(item.options??[]).map((o:any)=>`<div class="sub">+ ${esc(o.quantity)}x ${esc(o.name)}${Number(o.price)>0?` (${esc(brl(o.price))})`:""}</div>`).join("")}${item.notes?`<div class="obs">Obs.: ${esc(item.notes)}</div>`:""}</div>`).join("");
  const payments=(r.payments??[]).map((p:any)=>`<div>${esc(pay[p.method]??p.method)} - ${esc(brl(p.amount))}${p.provider==="DELIVERY_POS"?" - NA ENTREGA":p.provider?` - ${esc(p.provider)}`:""}</div>`).join("");
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Pedido #${esc(r.order.order_number)}</title><style>@page{size:${paper}mm auto;margin:2mm}*{box-sizing:border-box}body{width:${width}mm;margin:0 auto;padding:0;font-family:Arial,Helvetica,sans-serif;font-size:${font}px;color:#000}.center{text-align:center}.title{font-size:${font+5}px;font-weight:900}.dash{border-top:1px dashed #000;margin:7px 0}.line{display:flex;justify-content:space-between;gap:5px}.item{margin:7px 0}.sub,.obs{font-size:${font-1}px;margin-top:2px}.obs{font-weight:700}.big{font-size:${font+3}px;font-weight:900}.muted{font-size:${font-1}px}.section{font-weight:900;margin-bottom:3px}body:after{content:"";display:block;height:8mm}</style></head><body><div class="center"><div class="title">CLICK-FOOD</div><b>${esc(r.store?.name??"Loja")}</b>${r.store?.document?`<div class="muted">${esc(r.store.document)}</div>`:""}${r.store?.phone?`<div class="muted">${esc(r.store.phone)}</div>`:""}</div><div class="dash"></div><div class="center big">PEDIDO #${esc(r.order.order_number)}</div><div class="center muted">${esc(new Date(r.order.created_at).toLocaleString("pt-BR"))}</div><div class="dash"></div><div class="section">CLIENTE</div><b>${esc(r.customer?.name??"Cliente CLICK-FOOD")}</b>${r.customer?.phone?`<div>Tel.: ${esc(r.customer.phone)}</div>`:""}<div style="margin-top:4px">${address}</div>${r.order.customer_notes?`<div class="obs">OBS. CLIENTE: ${esc(r.order.customer_notes)}</div>`:""}<div class="dash"></div><div class="section">ITENS</div>${items}<div class="dash"></div><div class="line"><span>Subtotal</span><b>${esc(brl(r.order.subtotal))}</b></div>${Number(r.order.delivery_fee)>0?`<div class="line"><span>Entrega</span><b>${esc(brl(r.order.delivery_fee))}</b></div>`:""}${Number(r.order.discount)>0?`<div class="line"><span>Desconto</span><b>- ${esc(brl(r.order.discount))}</b></div>`:""}<div class="line big"><span>TOTAL</span><span>${esc(brl(r.order.total))}</span></div><div class="dash"></div><div class="section">PAGAMENTO</div>${payments||esc(r.order.payment_status)}${r.delivery?`<div class="dash"></div><div><b>ENTREGA:</b> ${esc(r.delivery.status)}</div>${r.delivery.driver?.name?`<div>Entregador: ${esc(r.delivery.driver.name)}</div>`:""}`:""}<div class="dash"></div><div class="center muted">Impresso pelo CLICK-FOOD • ${paper}mm</div><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),500)}<\/script></body></html>`;
  const w=window.open("","_blank",`width=${paper==="80"?420:330},height=720`);if(!w){setMessage("O navegador bloqueou a janela de impressão. Libere pop-ups para este painel.");return;}w.document.open();w.document.write(html);w.document.close();
 }
 return <div style={{marginTop:10,padding:10,border:"1px dashed #b9b9b9",borderRadius:10,background:"#fff"}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><label style={{fontSize:12,fontWeight:800}}>Impressora térmica <select value={paper} onChange={e=>setPaper(e.target.value as Paper)} style={{marginLeft:6,padding:7,borderRadius:7}}><option value="80">80 mm (padrão)</option><option value="58">58 mm</option></select></label><button type="button" onClick={print} disabled={busy} style={{padding:"9px 12px",border:0,borderRadius:8,background:"#111",color:"#f4c400",fontWeight:900,cursor:"pointer"}}>{busy?"PREPARANDO...":"🖨 IMPRIMIR PEDIDO"}</button></div>{message&&<div style={{fontSize:11,color:"#9a2828",fontWeight:800,marginTop:7}}>{message}</div>}</div>;
}
