"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import StoreSetup from "./StoreSetup";
import { supabase } from "../lib/supabase";

type Tab="Dashboard"|"Pedidos"|"PDV"|"Produtos"|"Estoque"|"Entregas"|"Clientes"|"Cupons"|"Financeiro"|"Bônus"|"Configurações";
type Store={id:string;name:string;status:string;role:string};
type Product={id:string;name:string;price:number;promotional_price:number|null;active?:boolean};
type Order={id:string;order_number:number;customer_id:string|null;total:number;status:string;payment_status:string;delivery_type:string;source:string;created_at:string};
type Metrics={sales_today:number;orders_today:number;average_ticket_today:number;delivery_orders_today:number;pos_orders_today:number;cancelled_today:number;open_orders:number;products:number;low_stock:number};
type CartItem=Product&{quantity:number};type CashSession={id:string;opening_balance:number;opened_at:string;status:string};type PaymentMethod="CASH"|"PIX"|"CREDIT_CARD"|"DEBIT_CARD";
type Inventory={id:string;product_id:string;quantity:number;minimum_quantity:number;products?:{name:string}|{name:string}[]|null};
type Coupon={id:string;code:string;discount_type:string;discount_value:number;minimum_order:number;max_uses:number|null;ends_at:string|null;active:boolean};
type Finance={id:string;transaction_type:string;direction:string;amount:number;status:string;created_at:string};
type Delivery={id:string;status:string;delivery_fee:number;driver_earning:number;created_at:string;orders?:{order_number:number;total:number}|{order_number:number;total:number}[]|null};
type BonusTx={id:string;transaction_type:string;points:number;description:string|null;created_at:string};
type Reward={id:string;name:string;points_cost:number;reward_type:string;reward_value:number|null;active:boolean};
const emptyMetrics:Metrics={sales_today:0,orders_today:0,average_ticket_today:0,delivery_orders_today:0,pos_orders_today:0,cancelled_today:0,open_orders:0,products:0,low_stock:0};
const menu:Tab[]=["Dashboard","Pedidos","PDV","Produtos","Estoque","Entregas","Clientes","Cupons","Financeiro","Bônus","Configurações"];
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string)=>new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});

export default function Home(){
 const[loading,setLoading]=useState(true);const[signedIn,setSignedIn]=useState(false);const[userEmail,setUserEmail]=useState("");const[authMode,setAuthMode]=useState<"login"|"signup">("login");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[claimCode,setClaimCode]=useState("");const[message,setMessage]=useState("");const[store,setStore]=useState<Store|null>(null);const[tab,setTab]=useState<Tab>("Dashboard");
 const[metrics,setMetrics]=useState<Metrics>(emptyMetrics);const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[cart,setCart]=useState<CartItem[]>([]);const[cashSession,setCashSession]=useState<CashSession|null>(null);const[openingBalance,setOpeningBalance]=useState("0");const[countedCash,setCountedCash]=useState("");const[paymentMethod,setPaymentMethod]=useState<PaymentMethod>("CASH");const[processingSale,setProcessingSale]=useState(false);const[processingOrder,setProcessingOrder]=useState<string|null>(null);
 const[inventory,setInventory]=useState<Inventory[]>([]);const[coupons,setCoupons]=useState<Coupon[]>([]);const[finance,setFinance]=useState<Finance[]>([]);const[deliveries,setDeliveries]=useState<Delivery[]>([]);const[bonusBalance,setBonusBalance]=useState(0);const[bonusTx,setBonusTx]=useState<BonusTx[]>([]);const[loyalty,setLoyalty]=useState({id:"",pointsPerCurrency:1,active:true});const[rewards,setRewards]=useState<Reward[]>([]);
 const[inventoryDraft,setInventoryDraft]=useState<Record<string,string>>({});const[couponForm,setCouponForm]=useState({code:"",discountType:"PERCENTAGE",discountValue:"10",minimumOrder:"0",maxUses:""});const[loyaltyPoints,setLoyaltyPoints]=useState("1");const[rewardForm,setRewardForm]=useState({name:"",pointsCost:"500",rewardType:"DISCOUNT_FIXED",rewardValue:"20"});const[cashMove,setCashMove]=useState({type:"SUPPLY",amount:"",reason:""});
 const cartTotal=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.promotional_price??item.price)*item.quantity,0),[cart]);
 const marketplaceOrders=orders.filter(o=>o.source!=="POS");const uniqueCustomers=useMemo(()=>Array.from(new Set(orders.map(o=>o.customer_id).filter(Boolean))) as string[],[orders]);
 const financeSummary=useMemo(()=>finance.reduce((a,t)=>{const v=Number(t.amount);if(t.direction==="CREDIT")a.credit+=v;else a.debit+=v;return a},{credit:0,debit:0}),[finance]);

 async function hydrate(){setLoading(true);const{data:sd}=await supabase.auth.getSession();const session=sd.session;if(!session){setSignedIn(false);setUserEmail("");setStore(null);setLoading(false);return;}setSignedIn(true);setUserEmail(session.user.email??"");const{data,error}=await supabase.from("store_memberships").select("store_id,role,stores!inner(id,name,status)").eq("user_id",session.user.id).eq("active",true).limit(1);if(error||!data?.length){setStore(null);setLoading(false);return;}const m=data[0] as any;const s=Array.isArray(m.stores)?m.stores[0]:m.stores;const current:Store={id:m.store_id,name:s?.name??"Minha loja",status:s?.status??"PENDING",role:m.role};setStore(current);await loadStoreData(current);setLoading(false);}
 async function loadStoreData(current=store){if(!current)return;setMessage("");const[metricR,productR,orderR,cashR,inventoryR,couponR,financeR,deliveryR,bonusR,bonusTxR,loyaltyR]=await Promise.all([
  supabase.rpc("store_dashboard_metrics",{p_store_id:current.id}),
  supabase.from("products").select("id,name,price,promotional_price,active").eq("store_id",current.id).order("name"),
  supabase.from("orders").select("id,order_number,customer_id,total,status,payment_status,delivery_type,source,created_at").eq("store_id",current.id).order("created_at",{ascending:false}).limit(100),
  supabase.functions.invoke("cash-session-action",{body:{action:"STATUS",storeId:current.id}}),
  supabase.from("inventory_items").select("id,product_id,quantity,minimum_quantity,products(name)").eq("store_id",current.id).order("updated_at",{ascending:false}),
  supabase.from("coupons").select("id,code,discount_type,discount_value,minimum_order,max_uses,ends_at,active").eq("store_id",current.id).order("created_at",{ascending:false}),
  supabase.from("financial_transactions").select("id,transaction_type,direction,amount,status,created_at").eq("store_id",current.id).order("created_at",{ascending:false}).limit(100),
  supabase.from("deliveries").select("id,status,delivery_fee,driver_earning,created_at,orders!inner(order_number,total,store_id)").eq("orders.store_id",current.id).order("created_at",{ascending:false}).limit(50),
  supabase.from("store_bonus_wallets").select("id,balance").eq("store_id",current.id).maybeSingle(),
  supabase.from("store_bonus_transactions").select("id,transaction_type,points,description,created_at,store_bonus_wallets!inner(store_id)").eq("store_bonus_wallets.store_id",current.id).order("created_at",{ascending:false}).limit(50),
  supabase.from("loyalty_programs").select("id,points_per_currency,active").eq("store_id",current.id).maybeSingle()
 ]);
 if(metricR.data)setMetrics({...emptyMetrics,...metricR.data as Metrics});if(productR.data)setProducts(productR.data.map((p:any)=>({...p,price:Number(p.price),promotional_price:p.promotional_price==null?null:Number(p.promotional_price)})));if(orderR.data)setOrders(orderR.data.map((o:any)=>({...o,total:Number(o.total)})));setCashSession(cashR.data?.session?{...cashR.data.session,opening_balance:Number(cashR.data.session.opening_balance)}:null);if(inventoryR.data)setInventory(inventoryR.data.map((x:any)=>({...x,quantity:Number(x.quantity),minimum_quantity:Number(x.minimum_quantity)})));if(couponR.data)setCoupons(couponR.data.map((x:any)=>({...x,discount_value:Number(x.discount_value),minimum_order:Number(x.minimum_order)})));if(financeR.data)setFinance(financeR.data.map((x:any)=>({...x,amount:Number(x.amount)})));if(deliveryR.data)setDeliveries(deliveryR.data.map((x:any)=>({...x,delivery_fee:Number(x.delivery_fee),driver_earning:Number(x.driver_earning)})));setBonusBalance(Number(bonusR.data?.balance??0));if(bonusTxR.data)setBonusTx(bonusTxR.data as any);if(loyaltyR.data){setLoyalty({id:loyaltyR.data.id,pointsPerCurrency:Number(loyaltyR.data.points_per_currency),active:loyaltyR.data.active});setLoyaltyPoints(String(Number(loyaltyR.data.points_per_currency)));const rr=await supabase.from("loyalty_rewards").select("id,name,points_cost,reward_type,reward_value,active").eq("program_id",loyaltyR.data.id).order("points_cost");setRewards((rr.data??[]).map((x:any)=>({...x,reward_value:x.reward_value==null?null:Number(x.reward_value)})));}
 }
 useEffect(()=>{hydrate();const{data}=supabase.auth.onAuthStateChange(()=>hydrate());return()=>data.subscription.unsubscribe();},[]);useEffect(()=>{if(!store)return;const timer=setInterval(()=>loadStoreData(store),20000);return()=>clearInterval(timer);},[store?.id]);
 async function submitAuth(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");if(authMode==="signup"){const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:"Lojista CLICK-FOOD"}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Conta criada. Confirme seu e-mail e depois faça login.");else await hydrate();}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage("E-mail ou senha inválidos.");}setLoading(false);}
 async function claimStore(){setLoading(true);const{data,error}=await supabase.functions.invoke("claim-store",{body:{code:claimCode}});if(error||data?.error){setMessage(data?.error==="CODE_EXPIRED"?"Código expirado. Peça outro à Matriz.":"Código de ativação inválido ou já usado.");setLoading(false);return;}await hydrate();}
 async function logout(){await supabase.auth.signOut();setStore(null);setSignedIn(false);setCart([]);}
 function addProduct(p:Product){setCart(c=>{const f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}]});}function changeQuantity(id:string,d:number){setCart(c=>c.map(x=>x.id===id?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0));}
 async function openCash(){if(!store)return;const value=Number(openingBalance.replace(",","."));const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:"OPEN",storeId:store.id,openingBalance:value}});if(error||data?.error){setMessage(data?.error==="CASH_ALREADY_OPEN"?"O caixa já está aberto.":"Não foi possível abrir o caixa.");return;}setCashSession({...data.session,opening_balance:Number(data.session.opening_balance)});setMessage("Caixa aberto.");}
 async function closeCash(){if(!store||!cashSession)return;const value=Number(countedCash.replace(",","."));if(!Number.isFinite(value)||value<0){setMessage("Informe o dinheiro contado.");return;}const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:"CLOSE",storeId:store.id,countedCash:value}});if(error||data?.error){setMessage("Não foi possível fechar o caixa.");return;}setCashSession(null);setCountedCash("");setMessage(`Caixa fechado. Diferença: ${brl(Number(data.session.difference??0))}.`);await loadStoreData(store);}
 async function cashMovement(){if(!store||!cashSession)return;const amount=Number(cashMove.amount.replace(",","."));if(!Number.isFinite(amount)||amount<=0||!cashMove.reason.trim()){setMessage("Informe valor e motivo da movimentação.");return;}const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:cashMove.type,storeId:store.id,amount,reason:cashMove.reason}});setMessage(error||data?.error?"Não foi possível movimentar o caixa.":"Movimentação registrada.");if(!error&&!data?.error)setCashMove({...cashMove,amount:"",reason:""});}
 async function finalizeSale(){if(!store||!cashSession||!cart.length)return;setProcessingSale(true);const{data,error}=await supabase.functions.invoke("create-pos-sale",{body:{storeId:store.id,cashSessionId:cashSession.id,items:cart.map(i=>({productId:i.id,quantity:i.quantity})),payments:[{method:paymentMethod,amount:cartTotal}],discount:0}});setProcessingSale(false);if(error||data?.error){setMessage(data?.error==="INSUFFICIENT_STOCK"?"Estoque insuficiente.":"Não foi possível concluir a venda.");return;}setCart([]);setMessage("Venda concluída com sucesso.");await loadStoreData(store);}
 async function actOnOrder(order:Order,action:"ACCEPT"|"REJECT"|"START_PREPARING"|"MARK_READY"){if(!store)return;let reason:string|undefined;if(action==="REJECT"){reason=window.prompt("Motivo da recusa:")?.trim()||undefined;if(!reason){setMessage("A recusa exige motivo.");return;}}setProcessingOrder(order.id);const{data,error}=await supabase.functions.invoke("store-order-action",{body:{orderId:order.id,action,reason}});if(!error&&!data?.error&&data.dispatchRequired){const d=await supabase.functions.invoke("dispatch-delivery",{body:{orderId:order.id}});setMessage(d.error||d.data?.error?"Pedido pronto, mas nenhum entregador disponível agora.":"Pedido pronto e chamado enviado.");}else setMessage(error||data?.error?"Não foi possível atualizar o pedido.":"Pedido atualizado.");setProcessingOrder(null);await loadStoreData(store);}
 async function retryDispatch(order:Order){setProcessingOrder(order.id);const{data,error}=await supabase.functions.invoke("dispatch-delivery",{body:{orderId:order.id}});setProcessingOrder(null);setMessage(error||data?.error?"Nenhum entregador disponível agora.":"Novo chamado enviado.");}
 async function adjustStock(productId:string){if(!store)return;const q=Number((inventoryDraft[productId]??"").replace(",","."));if(!Number.isFinite(q)||q<0){setMessage("Informe um estoque válido.");return;}const{data,error}=await supabase.functions.invoke("store-management",{body:{action:"INVENTORY_ADJUST",storeId:store.id,productId,quantity:q,movementType:"ADJUSTMENT",reason:"Ajuste manual pelo Painel Lojista"}});setMessage(error||data?.error?"Não foi possível ajustar o estoque.":"Estoque atualizado.");await loadStoreData(store);}
 async function createCoupon(e:FormEvent){e.preventDefault();if(!store)return;const{data,error}=await supabase.functions.invoke("store-management",{body:{action:"CREATE_COUPON",storeId:store.id,code:couponForm.code,discountType:couponForm.discountType,discountValue:Number(couponForm.discountValue.replace(",",".")),minimumOrder:Number(couponForm.minimumOrder.replace(",",".")),maxUses:couponForm.maxUses?Number(couponForm.maxUses):null}});setMessage(error||data?.error?(data?.error==="COUPON_EXISTS"?"Esse cupom já existe.":"Não foi possível criar o cupom."):"Cupom criado.");if(!error&&!data?.error)setCouponForm({...couponForm,code:""});await loadStoreData(store);}
 async function toggleCoupon(c:Coupon){if(!store)return;await supabase.functions.invoke("store-management",{body:{action:"TOGGLE_COUPON",storeId:store.id,couponId:c.id,active:!c.active}});await loadStoreData(store);}
 async function saveLoyalty(){if(!store)return;const{data,error}=await supabase.functions.invoke("store-management",{body:{action:"UPDATE_LOYALTY",storeId:store.id,pointsPerCurrency:Number(loyaltyPoints.replace(",",".")),active:true}});setMessage(error||data?.error?"Não foi possível salvar a fidelidade.":"Fidelidade atualizada.");await loadStoreData(store);}
 async function createReward(e:FormEvent){e.preventDefault();if(!store)return;const{data,error}=await supabase.functions.invoke("store-management",{body:{action:"CREATE_LOYALTY_REWARD",storeId:store.id,name:rewardForm.name,pointsCost:Number(rewardForm.pointsCost),rewardType:rewardForm.rewardType,rewardValue:rewardForm.rewardValue?Number(rewardForm.rewardValue.replace(",",".")):null}});setMessage(error||data?.error?"Não foi possível criar a recompensa.":"Recompensa criada.");if(!error&&!data?.error)setRewardForm({...rewardForm,name:""});await loadStoreData(store);}

 if(loading)return <main className="authPage"><div className="authCard"><div className="logo"><span>CLICK</span>-FOOD</div><p>Carregando sua operação...</p></div></main>;
 if(!signedIn)return <main className="authPage"><form className="authCard" onSubmit={submitAuth}><div className="logo"><span>CLICK</span>-FOOD</div><p className="authRole">PAINEL DO LOJISTA + PDV</p><h1>{authMode==="login"?"Entrar na loja":"Criar conta de lojista"}</h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton">{authMode==="login"?"ENTRAR":"CRIAR CONTA"}</button><button type="button" className="textButton" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Ainda não tenho conta":"Já tenho conta"}</button></form></main>;
 if(!store)return <main className="authPage"><div className="authCard"><div className="logo"><span>CLICK</span>-FOOD</div><p className="authRole">ATIVAÇÃO DA LOJA</p><h1>Vincular minha loja</h1><p className="muted">Conta: {userEmail}</p><label>Código da loja<input value={claimCode} onChange={e=>setClaimCode(e.target.value.toUpperCase())} placeholder="CF-LOJA-XXXXXXXXXXXX"/></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton" onClick={claimStore}>ATIVAR MINHA LOJA</button><button className="textButton" onClick={logout}>Sair</button></div></main>;

 const renderOrders=()=> <section className="orderQueue"><div className="queueHeader"><div><small>DELIVERY / RETIRADA</small><h2>Fila operacional</h2></div><span>{metrics.open_orders} em aberto</span></div>{marketplaceOrders.length?<div className="queueGrid">{marketplaceOrders.map(order=><article className={`queueCard status-${order.status.toLowerCase()}`} key={order.id}><div className="queueTop"><b>#{order.order_number}</b><span>{order.delivery_type}</span></div><strong>{brl(order.total)}</strong><p>{order.status} • {order.payment_status}</p><div className="queueActions">{order.status==="WAITING_STORE"&&<><button onClick={()=>actOnOrder(order,"ACCEPT")} disabled={processingOrder===order.id}>Aceitar</button><button className="dangerAction" onClick={()=>actOnOrder(order,"REJECT")} disabled={processingOrder===order.id}>Recusar</button></>}{order.status==="ACCEPTED"&&<button onClick={()=>actOnOrder(order,"START_PREPARING")}>Iniciar preparo</button>}{order.status==="PREPARING"&&<button onClick={()=>actOnOrder(order,"MARK_READY")}>Marcar pronto</button>}{order.status==="READY"&&order.delivery_type==="DELIVERY"&&<button onClick={()=>retryDispatch(order)}>Chamar entregador</button>}{["WAITING_DRIVER","DRIVER_ASSIGNED","PICKED_UP","ON_THE_WAY"].includes(order.status)&&<span className="inProgress">Entrega em andamento</span>}</div></article>)}</div>:<div className="emptyQueue">Nenhum pedido aguardando ação.</div>}</section>;
 const renderCash=()=> <section className="cashPanel"><div><small>CAIXA</small><h2>{cashSession?"Caixa 01 aberto":"Caixa fechado"}</h2>{cashSession&&<p>Saldo inicial: {brl(cashSession.opening_balance)}</p>}</div>{!cashSession?<div className="cashActions"><input value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)} inputMode="decimal"/><button className="primaryCash" onClick={openCash}>ABRIR CAIXA</button></div>:<div className="cashActions"><input value={countedCash} onChange={e=>setCountedCash(e.target.value)} inputMode="decimal" placeholder="Dinheiro contado"/><button className="secondaryCash" onClick={closeCash}>FECHAR CAIXA</button></div>}</section>;

 return <main className="app"><aside className="side"><div className="logo"><span>CLICK</span>-FOOD</div><p>{store.name}</p><nav>{menu.map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</nav></aside><section className="workspace"><header><div><small>{store.status==="ACTIVE"?"LOJA ATIVA":`LOJA ${store.status}`} • {store.role}</small><h1>{tab}</h1></div><div className="headerActions"><button className="refresh" onClick={()=>loadStoreData(store)}>Atualizar</button><button className="refresh" onClick={logout}>Sair</button></div></header>{message&&<div className="notice">{message}</div>}
 {tab==="Dashboard"&&<><div className="kpis"><article><span>Vendas hoje</span><b>{brl(metrics.sales_today)}</b></article><article><span>Pedidos hoje</span><b>{metrics.orders_today}</b></article><article><span>Ticket médio</span><b>{brl(metrics.average_ticket_today)}</b></article><article><span>Pedidos em aberto</span><b>{metrics.open_orders}</b></article></div><div className="managementGrid"><article className="mgCard"><h2>Operação</h2><p>Delivery hoje: <b>{metrics.delivery_orders_today}</b></p><p>PDV hoje: <b>{metrics.pos_orders_today}</b></p><p>Cancelados: <b>{metrics.cancelled_today}</b></p></article><article className="mgCard"><h2>Financeiro</h2><p>Créditos: <b>{brl(financeSummary.credit)}</b></p><p>Débitos: <b>{brl(financeSummary.debit)}</b></p><p>Saldo contábil: <b>{brl(financeSummary.credit-financeSummary.debit)}</b></p></article><article className="mgCard"><h2>CLICK Pontos</h2><strong className="bigValue">{bonusBalance}</strong><p>Pontos disponíveis</p></article></div>{renderOrders()}</>}
 {tab==="Pedidos"&&renderOrders()}
 {tab==="PDV"&&<>{renderCash()}<div className="pos"><section className="catalog"><div className="search">Toque em um produto para adicionar</div><div className="productGrid">{products.filter(p=>p.active!==false).map(p=><button className="product" onClick={()=>addProduct(p)} key={p.id}><span>{p.name}</span><strong>{brl(Number(p.promotional_price??p.price))}</strong></button>)}</div></section><aside className="cart"><div className="cartHead"><div><small>PEDIDO ATUAL</small><h2>Balcão</h2></div><button onClick={()=>setCart([])}>Limpar</button></div><div className="cartItems">{cart.map(i=><div className="item" key={i.id}><div><b>{i.quantity}× {i.name}</b><div className="quantity"><button onClick={()=>changeQuantity(i.id,-1)}>−</button><button onClick={()=>changeQuantity(i.id,1)}>+</button></div></div><strong>{brl(Number(i.promotional_price??i.price)*i.quantity)}</strong></div>)}{!cart.length&&<div className="emptyCart">Carrinho vazio.</div>}</div><div className="paymentMethods">{[["CASH","Dinheiro"],["PIX","PIX"],["DEBIT_CARD","Débito"],["CREDIT_CARD","Crédito"]].map(([v,l])=><button key={v} className={paymentMethod===v?"payActive":""} onClick={()=>setPaymentMethod(v as PaymentMethod)}>{l}</button>)}</div><div className="totals"><div className="grand"><span>Total</span><strong>{brl(cartTotal)}</strong></div></div><button className="checkout" disabled={!cart.length||!cashSession||processingSale} onClick={finalizeSale}>{cashSession?"FINALIZAR VENDA":"ABRA O CAIXA"}</button></aside></div>}
 {tab==="Produtos"&&<StoreSetup storeId={store.id} onChanged={()=>loadStoreData(store)}/>} 
 {tab==="Estoque"&&<section className="mgCard"><h2>Controle de estoque</h2><p className="muted">Defina a quantidade atual. Cada ajuste gera histórico.</p><div className="dataList">{products.map(p=>{const inv=inventory.find(i=>i.product_id===p.id);return <div className="dataRow" key={p.id}><div><b>{p.name}</b><small>Atual: {inv?inv.quantity:"não controlado"}</small></div><div className="rowActions"><input value={inventoryDraft[p.id]??String(inv?.quantity??0)} onChange={e=>setInventoryDraft({...inventoryDraft,[p.id]:e.target.value})}/><button onClick={()=>adjustStock(p.id)}>Ajustar</button></div></div>})}</div></section>}
 {tab==="Entregas"&&<section className="mgCard"><h2>Entregas</h2><div className="dataList">{deliveries.map(d=>{const o=Array.isArray(d.orders)?d.orders[0]:d.orders;return <div className="dataRow" key={d.id}><div><b>Pedido #{o?.order_number??"-"}</b><small>{d.status} • {dt(d.created_at)}</small></div><div><b>{brl(d.delivery_fee)}</b><small>ganho entregador {brl(d.driver_earning)}</small></div></div>})}{!deliveries.length&&<div className="emptyRow">Nenhuma entrega registrada.</div>}</div></section>}
 {tab==="Clientes"&&<section className="mgCard"><h2>Clientes da loja</h2><div className="summaryStrip"><div><b>{uniqueCustomers.length}</b><span>clientes únicos</span></div><div><b>{orders.length}</b><span>pedidos registrados</span></div></div><div className="dataList">{uniqueCustomers.map((id,index)=>{const count=orders.filter(o=>o.customer_id===id).length;const total=orders.filter(o=>o.customer_id===id).reduce((s,o)=>s+o.total,0);return <div className="dataRow" key={id}><div><b>Cliente {index+1}</b><small>ID protegido • {count} pedido(s)</small></div><b>{brl(total)}</b></div>})}</div></section>}
 {tab==="Cupons"&&<div className="managementGrid two"><form className="mgCard" onSubmit={createCoupon}><h2>Novo cupom</h2><label>Código<input value={couponForm.code} onChange={e=>setCouponForm({...couponForm,code:e.target.value.toUpperCase()})} required/></label><label>Tipo<select value={couponForm.discountType} onChange={e=>setCouponForm({...couponForm,discountType:e.target.value})}><option value="PERCENTAGE">Percentual</option><option value="FIXED">Valor fixo</option><option value="FREE_DELIVERY">Entrega grátis</option></select></label><label>Valor<input value={couponForm.discountValue} onChange={e=>setCouponForm({...couponForm,discountValue:e.target.value})}/></label><label>Pedido mínimo<input value={couponForm.minimumOrder} onChange={e=>setCouponForm({...couponForm,minimumOrder:e.target.value})}/></label><label>Limite de usos<input value={couponForm.maxUses} onChange={e=>setCouponForm({...couponForm,maxUses:e.target.value})}/></label><button className="setupPrimary">CRIAR CUPOM</button></form><section className="mgCard"><h2>Cupons cadastrados</h2><div className="dataList">{coupons.map(c=><div className="dataRow" key={c.id}><div><b>{c.code}</b><small>{c.discount_type} • mínimo {brl(c.minimum_order)}</small></div><button onClick={()=>toggleCoupon(c)}>{c.active?"Pausar":"Ativar"}</button></div>)}{!coupons.length&&<div className="emptyRow">Nenhum cupom.</div>}</div></section></div>}
 {tab==="Financeiro"&&<><div className="kpis"><article><span>Créditos</span><b>{brl(financeSummary.credit)}</b></article><article><span>Débitos</span><b>{brl(financeSummary.debit)}</b></article><article><span>Saldo contábil</span><b>{brl(financeSummary.credit-financeSummary.debit)}</b></article><article><span>Caixa</span><b>{cashSession?"ABERTO":"FECHADO"}</b></article></div>{renderCash()}{cashSession&&<div className="mgCard compactForm"><h2>Movimentar caixa</h2><select value={cashMove.type} onChange={e=>setCashMove({...cashMove,type:e.target.value})}><option value="SUPPLY">Suprimento</option><option value="WITHDRAWAL">Sangria</option><option value="EXPENSE">Despesa</option></select><input placeholder="Valor" value={cashMove.amount} onChange={e=>setCashMove({...cashMove,amount:e.target.value})}/><input placeholder="Motivo" value={cashMove.reason} onChange={e=>setCashMove({...cashMove,reason:e.target.value})}/><button onClick={cashMovement}>REGISTRAR</button></div>}<section className="mgCard"><h2>Extrato</h2><div className="dataList">{finance.map(t=><div className="dataRow" key={t.id}><div><b>{t.transaction_type}</b><small>{dt(t.created_at)} • {t.status}</small></div><b>{t.direction==="DEBIT"?"−":"+"} {brl(t.amount)}</b></div>)}{!finance.length&&<div className="emptyRow">Sem lançamentos financeiros ainda.</div>}</div></section></>}
 {tab==="Bônus"&&<div className="managementGrid two"><section className="mgCard"><h2>CLICK Pontos</h2><strong className="bigValue">{bonusBalance}</strong><div className="dataList">{bonusTx.map(t=><div className="dataRow" key={t.id}><div><b>{t.transaction_type}</b><small>{t.description||dt(t.created_at)}</small></div><b>{t.points>0?"+":""}{t.points}</b></div>)}</div></section><section className="mgCard"><h2>Fidelidade do cliente</h2><label>Pontos por R$ 1<input value={loyaltyPoints} onChange={e=>setLoyaltyPoints(e.target.value)}/></label><button className="setupPrimary" onClick={saveLoyalty}>SALVAR REGRA</button><form onSubmit={createReward} className="rewardForm"><h3>Nova recompensa</h3><input placeholder="Nome" value={rewardForm.name} onChange={e=>setRewardForm({...rewardForm,name:e.target.value})} required/><input placeholder="Custo em pontos" value={rewardForm.pointsCost} onChange={e=>setRewardForm({...rewardForm,pointsCost:e.target.value})}/><select value={rewardForm.rewardType} onChange={e=>setRewardForm({...rewardForm,rewardType:e.target.value})}><option value="DISCOUNT_FIXED">Desconto fixo</option><option value="DISCOUNT_PERCENTAGE">Desconto %</option><option value="FREE_DELIVERY">Entrega grátis</option></select><input placeholder="Valor" value={rewardForm.rewardValue} onChange={e=>setRewardForm({...rewardForm,rewardValue:e.target.value})}/><button className="setupPrimary">CRIAR RECOMPENSA</button></form><div className="dataList">{rewards.map(r=><div className="dataRow" key={r.id}><div><b>{r.name}</b><small>{r.points_cost} pontos</small></div><span>{r.active?"ATIVA":"PAUSADA"}</span></div>)}</div></section></div>}
 {tab==="Configurações"&&<StoreSetup storeId={store.id} onChanged={()=>loadStoreData(store)}/>} 
 </section></main>;
}
