"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Store={id:string;name:string;status:string;role:string};
type Product={id:string;name:string;price:number;promotional_price:number|null};
type Order={id:string;order_number:number;total:number;status:string;payment_status:string;delivery_type:string;source:string;created_at:string};
type Metrics={sales_today:number;orders_today:number;average_ticket_today:number;delivery_orders_today:number;pos_orders_today:number;cancelled_today:number;open_orders:number;products:number;low_stock:number};
type CartItem=Product&{quantity:number};type CashSession={id:string;opening_balance:number;opened_at:string;status:string};type PaymentMethod="CASH"|"PIX"|"CREDIT_CARD"|"DEBIT_CARD";
const emptyMetrics:Metrics={sales_today:0,orders_today:0,average_ticket_today:0,delivery_orders_today:0,pos_orders_today:0,cancelled_today:0,open_orders:0,products:0,low_stock:0};
const menu=["Dashboard","Pedidos","PDV","Produtos","Estoque","Entregas","Clientes","Cupons","Financeiro","Bônus","Configurações"];
const brl=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);

export default function Home(){
  const[loading,setLoading]=useState(true);const[signedIn,setSignedIn]=useState(false);const[userEmail,setUserEmail]=useState("");const[authMode,setAuthMode]=useState<"login"|"signup">("login");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[claimCode,setClaimCode]=useState("");const[message,setMessage]=useState("");const[store,setStore]=useState<Store|null>(null);
  const[metrics,setMetrics]=useState<Metrics>(emptyMetrics);const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[cart,setCart]=useState<CartItem[]>([]);const[cashSession,setCashSession]=useState<CashSession|null>(null);const[openingBalance,setOpeningBalance]=useState("0");const[countedCash,setCountedCash]=useState("");const[paymentMethod,setPaymentMethod]=useState<PaymentMethod>("CASH");const[processingSale,setProcessingSale]=useState(false);const[processingOrder,setProcessingOrder]=useState<string|null>(null);
  const cartTotal=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.promotional_price??item.price)*item.quantity,0),[cart]);

  async function hydrate(){setLoading(true);const{data:sessionData}=await supabase.auth.getSession();const session=sessionData.session;if(!session){setSignedIn(false);setUserEmail("");setStore(null);setLoading(false);return;}setSignedIn(true);setUserEmail(session.user.email??"");const{data:memberships,error:membershipError}=await supabase.from("store_memberships").select("store_id,role,stores!inner(id,name,status)").eq("user_id",session.user.id).eq("active",true).limit(1);if(membershipError||!memberships?.length){setStore(null);setLoading(false);return;}const membership=memberships[0] as any;const linkedStore=Array.isArray(membership.stores)?membership.stores[0]:membership.stores;const currentStore:Store={id:membership.store_id,name:linkedStore?.name??"Minha loja",status:linkedStore?.status??"PENDING",role:membership.role};setStore(currentStore);await loadStoreData(currentStore);setLoading(false);}
  async function loadStoreData(currentStore=store){if(!currentStore)return;const[metricsResult,productsResult,ordersResult,cashResult]=await Promise.all([supabase.rpc("store_dashboard_metrics",{p_store_id:currentStore.id}),supabase.from("products").select("id,name,price,promotional_price").eq("store_id",currentStore.id).eq("active",true).eq("available_pos",true).order("name").limit(100),supabase.from("orders").select("id,order_number,total,status,payment_status,delivery_type,source,created_at").eq("store_id",currentStore.id).order("created_at",{ascending:false}).limit(30),supabase.functions.invoke("cash-session-action",{body:{action:"STATUS",storeId:currentStore.id}})]);if(metricsResult.data)setMetrics({...emptyMetrics,...(metricsResult.data as Metrics)});if(productsResult.data)setProducts(productsResult.data.map((p:any)=>({...p,price:Number(p.price),promotional_price:p.promotional_price==null?null:Number(p.promotional_price)})));if(ordersResult.data)setOrders(ordersResult.data.map((o:any)=>({...o,total:Number(o.total)})));setCashSession(cashResult.data?.session?{...cashResult.data.session,opening_balance:Number(cashResult.data.session.opening_balance)}:null);if(metricsResult.error||productsResult.error||ordersResult.error||cashResult.error)setMessage("Alguns dados da loja não puderam ser carregados.");}
  useEffect(()=>{hydrate();const{data}=supabase.auth.onAuthStateChange(()=>hydrate());return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{if(!store)return;const timer=setInterval(()=>loadStoreData(store),15000);return()=>clearInterval(timer);},[store?.id]);

  async function submitAuth(event:FormEvent){event.preventDefault();setLoading(true);setMessage("");if(authMode==="signup"){const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:"Lojista CLICK-FOOD"}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Conta criada. Confirme o e-mail recebido e depois faça login.");else await hydrate();}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage("E-mail ou senha inválidos.");}setLoading(false);}
  async function claimStore(){setLoading(true);setMessage("");const{data,error}=await supabase.functions.invoke("claim-store",{body:{code:claimCode}});if(error||data?.error){const code=data?.error;setMessage(code==="CODE_EXPIRED"?"Este código expirou. Peça um novo à Matriz.":code==="CODE_ALREADY_USED"?"Este código já foi utilizado.":"Código de ativação inválido.");setLoading(false);return;}setMessage("Loja ativada para sua conta.");setClaimCode("");await hydrate();}
  async function logout(){await supabase.auth.signOut();setStore(null);setCart([]);setSignedIn(false);}
  function addProduct(product:Product){setCart(current=>{const found=current.find(item=>item.id===product.id);return found?current.map(item=>item.id===product.id?{...item,quantity:item.quantity+1}:item):[...current,{...product,quantity:1}];});}
  function changeQuantity(id:string,delta:number){setCart(current=>current.map(item=>item.id===id?{...item,quantity:item.quantity+delta}:item).filter(item=>item.quantity>0));}

  async function openCash(){if(!store)return;setMessage("");const value=Number(String(openingBalance).replace(",","."));const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:"OPEN",storeId:store.id,openingBalance:value}});if(error||data?.error){setMessage("Não foi possível abrir o caixa.");return;}setCashSession({...data.session,opening_balance:Number(data.session.opening_balance)});setMessage("Caixa aberto com sucesso.");}
  async function closeCash(){if(!store||!cashSession)return;const value=Number(String(countedCash).replace(",","."));if(!Number.isFinite(value)||value<0){setMessage("Informe o dinheiro contado no caixa.");return;}const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:"CLOSE",storeId:store.id,countedCash:value}});if(error||data?.error){setMessage("Não foi possível fechar o caixa.");return;}setCashSession(null);setCountedCash("");setMessage(`Caixa fechado. Diferença: ${brl(Number(data.session.difference??0))}.`);await loadStoreData(store);}
  async function finalizeSale(){if(!store||!cashSession||!cart.length)return;setProcessingSale(true);setMessage("");const{data,error}=await supabase.functions.invoke("create-pos-sale",{body:{storeId:store.id,cashSessionId:cashSession.id,items:cart.map(item=>({productId:item.id,quantity:item.quantity})),payments:[{method:paymentMethod,amount:cartTotal}],discount:0}});if(error||data?.error){const code=data?.error;setMessage(code==="INSUFFICIENT_STOCK"?"Estoque insuficiente para concluir a venda.":code==="CASH_NOT_OPEN"?"Abra o caixa antes de vender.":"Não foi possível concluir a venda.");setProcessingSale(false);return;}setCart([]);setMessage(`Venda concluída. Pedido ${String(data.orderId).slice(0,8)}.`);setProcessingSale(false);await loadStoreData(store);}

  async function actOnOrder(order:Order,action:"ACCEPT"|"REJECT"|"START_PREPARING"|"MARK_READY"){
    if(!store)return;let reason:string|undefined;if(action==="REJECT"){reason=window.prompt("Informe o motivo da recusa:")?.trim()||undefined;if(!reason){setMessage("A recusa exige um motivo.");return;}}
    setProcessingOrder(order.id);setMessage("");const{data,error}=await supabase.functions.invoke("store-order-action",{body:{orderId:order.id,action,reason}});if(error||data?.error){setMessage(data?.error==="ORDER_STATUS_CHANGED"?"O status deste pedido mudou. Atualize a fila.":"Não foi possível executar esta ação no pedido.");setProcessingOrder(null);await loadStoreData(store);return;}
    if(data.dispatchRequired){const dispatch=await supabase.functions.invoke("dispatch-delivery",{body:{orderId:order.id}});if(dispatch.error||dispatch.data?.error){const code=dispatch.data?.error;setMessage(code==="NO_DRIVERS_ONLINE"||code==="NO_ELIGIBLE_DRIVERS"?"Pedido pronto. Nenhum entregador online agora; tente despachar novamente em instantes.":"Pedido pronto, mas o despacho precisa ser repetido.");}else setMessage("Pedido pronto e chamado enviado aos entregadores próximos.");}else setMessage(action==="ACCEPT"?"Pedido aceito.":action==="START_PREPARING"?"Pedido em preparação.":action==="REJECT"?"Pedido recusado.":"Pedido atualizado.");setProcessingOrder(null);await loadStoreData(store);
  }
  async function retryDispatch(order:Order){setProcessingOrder(order.id);const{data,error}=await supabase.functions.invoke("dispatch-delivery",{body:{orderId:order.id}});setProcessingOrder(null);setMessage(error||data?.error?"Ainda não há entregador disponível para este pedido.":"Novo chamado enviado aos entregadores.");await loadStoreData(store);}

  if(loading)return <main className="authPage"><div className="authCard"><div className="logo"><span>CLICK</span>-FOOD</div><p>Carregando sua operação...</p></div></main>;
  if(!signedIn)return <main className="authPage"><form className="authCard" onSubmit={submitAuth}><div className="logo"><span>CLICK</span>-FOOD</div><p className="authRole">PAINEL DO LOJISTA + PDV</p><h1>{authMode==="login"?"Entrar na loja":"Criar conta de lojista"}</h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton">{authMode==="login"?"ENTRAR":"CRIAR CONTA"}</button><button type="button" className="textButton" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Ainda não tenho conta":"Já tenho conta"}</button></form></main>;
  if(!store)return <main className="authPage"><div className="authCard"><div className="logo"><span>CLICK</span>-FOOD</div><p className="authRole">ATIVAÇÃO DA LOJA</p><h1>Vincular minha loja</h1><p className="muted">Conta: {userEmail}</p><p>Digite o código enviado pela Matriz CLICK-FOOD.</p><label>Código da loja<input value={claimCode} onChange={e=>setClaimCode(e.target.value.toUpperCase())} placeholder="CF-LOJA-XXXXXXXXXXXX"/></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton" onClick={claimStore}>ATIVAR MINHA LOJA</button><button className="textButton" onClick={logout}>Sair desta conta</button></div></main>;

  const marketplaceOrders=orders.filter(order=>order.source!=="POS").slice(0,12);
  return <main className="app"><aside className="side"><div className="logo"><span>CLICK</span>-FOOD</div><p>{store.name}</p><nav>{menu.map((x,i)=><button key={x} className={i===2?"active":""}>{x}</button>)}</nav></aside><section className="workspace">
    <header><div><small>{store.status==="ACTIVE"?"LOJA ATIVA":`LOJA ${store.status}`} • {store.role}</small><h1>PDV e Pedidos</h1></div><div className="headerActions"><a className="refresh linkButton" href="/configuracao">Configurar loja</a><button className="refresh" onClick={()=>loadStoreData(store)}>Atualizar</button><button className="refresh" onClick={logout}>Sair</button></div></header>{message&&<div className="notice">{message}</div>}
    <section className="orderQueue"><div className="queueHeader"><div><small>DELIVERY / RETIRADA</small><h2>Fila operacional</h2></div><span>{metrics.open_orders} em aberto</span></div>{marketplaceOrders.length?<div className="queueGrid">{marketplaceOrders.map(order=><article className={`queueCard status-${order.status.toLowerCase()}`} key={order.id}><div className="queueTop"><b>#{order.order_number}</b><span>{order.delivery_type}</span></div><strong>{brl(order.total)}</strong><p>{order.status} • {order.payment_status}</p><div className="queueActions">{order.status==="WAITING_STORE"&&<><button onClick={()=>actOnOrder(order,"ACCEPT")} disabled={processingOrder===order.id}>Aceitar</button><button className="dangerAction" onClick={()=>actOnOrder(order,"REJECT")} disabled={processingOrder===order.id}>Recusar</button></>}{order.status==="ACCEPTED"&&<button onClick={()=>actOnOrder(order,"START_PREPARING")} disabled={processingOrder===order.id}>Iniciar preparo</button>}{order.status==="PREPARING"&&<button onClick={()=>actOnOrder(order,"MARK_READY")} disabled={processingOrder===order.id}>Marcar pronto</button>}{order.status==="READY"&&order.delivery_type==="DELIVERY"&&<button onClick={()=>retryDispatch(order)} disabled={processingOrder===order.id}>Chamar entregador</button>}{["WAITING_DRIVER","DRIVER_ASSIGNED","DRIVER_TO_STORE","PICKUP_CONFIRMED","DRIVER_TO_CUSTOMER","DRIVER_AT_CUSTOMER"].includes(order.status)&&<span className="inProgress">Entrega em andamento</span>}</div></article>)}</div>:<div className="emptyQueue">Nenhum pedido do aplicativo aguardando ação.</div>}</section>
    <section className="cashPanel"><div><small>CAIXA</small><h2>{cashSession?"Caixa 01 aberto":"Caixa fechado"}</h2>{cashSession&&<p>Saldo inicial: {brl(cashSession.opening_balance)}</p>}</div>{!cashSession?<div className="cashActions"><input value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)} inputMode="decimal" placeholder="Saldo inicial"/><button className="primaryCash" onClick={openCash}>ABRIR CAIXA</button></div>:<div className="cashActions"><input value={countedCash} onChange={e=>setCountedCash(e.target.value)} inputMode="decimal" placeholder="Dinheiro contado"/><button className="secondaryCash" onClick={closeCash}>FECHAR CAIXA</button></div>}</section>
    <div className="kpis"><article><span>Vendas hoje</span><b>{brl(metrics.sales_today)}</b></article><article><span>Pedidos hoje</span><b>{metrics.orders_today}</b></article><article><span>Ticket médio</span><b>{brl(metrics.average_ticket_today)}</b></article><article><span>Estoque baixo</span><b>{metrics.low_stock}</b></article></div>
    <div className="pos"><section className="catalog"><div className="search">Produtos reais cadastrados no CLICK-FOOD</div><div className="productGrid">{products.length?products.map(product=><button className="product" onClick={()=>addProduct(product)} key={product.id}><span>{product.name}</span><strong>{brl(Number(product.promotional_price??product.price))}</strong></button>):<div className="emptyCatalog">Nenhum produto cadastrado ainda. Use “Configurar loja”.</div>}</div><article className="incoming"><div><small>HISTÓRICO RECENTE</small><h2>Pedidos</h2></div><div className="orderRows">{orders.length?orders.slice(0,10).map(order=><div key={order.id}><b>#{order.order_number}</b><span>{order.status}</span><span>{order.source}</span><strong>{brl(order.total)}</strong></div>):<div className="emptyRow">Nenhum pedido ainda.</div>}</div></article></section>
      <aside className="cart"><div className="cartHead"><div><small>PEDIDO ATUAL</small><h2>Balcão</h2></div><button onClick={()=>setCart([])}>Limpar</button></div><div className="cartItems">{cart.length?cart.map(item=><div className="item" key={item.id}><div><b>{item.quantity}× {item.name}</b><div className="quantity"><button onClick={()=>changeQuantity(item.id,-1)}>−</button><button onClick={()=>changeQuantity(item.id,1)}>+</button></div></div><strong>{brl(Number(item.promotional_price??item.price)*item.quantity)}</strong></div>):<div className="emptyCart">Toque em um produto para iniciar a venda.</div>}</div><div className="paymentMethods">{[["CASH","Dinheiro"],["PIX","PIX"],["DEBIT_CARD","Débito"],["CREDIT_CARD","Crédito"]].map(([value,label])=><button key={value} className={paymentMethod===value?"payActive":""} onClick={()=>setPaymentMethod(value as PaymentMethod)}>{label}</button>)}</div><div className="totals"><div className="grand"><span>Total</span><strong>{brl(cartTotal)}</strong></div></div><button className="checkout" disabled={!cart.length||!cashSession||processingSale} onClick={finalizeSale}>{processingSale?"PROCESSANDO...":cashSession?"FINALIZAR VENDA":"ABRA O CAIXA"}</button></aside>
    </div></section></main>;
}
