"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Props={storeId:string;onChanged:()=>void};type Product={id:string;name:string;price:number;active:boolean;category_id:string|null};type Category={id:string;name:string;active:boolean};type DeliverySettings={pricing_model:string;fixed_fee:number;base_fee:number;per_km_fee:number;minimum_fee:number;max_radius_km:number|null;pickup_enabled:boolean;clickfood_delivery_enabled:boolean;own_delivery_enabled:boolean};type StoreProfile={description:string;phone:string;minimumOrder:string;preparationTime:string;latitude:string;longitude:string};type Hours={weekday:number;opens_at:string;closes_at:string;closed:boolean};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);const dayNames=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
export default function StoreSetup({storeId,onChanged}:Props){
 const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[message,setMessage]=useState("");const[locating,setLocating]=useState(false);const[product,setProduct]=useState({name:"",description:"",price:"",categoryId:""});const[categoryName,setCategoryName]=useState("");const[profile,setProfile]=useState<StoreProfile>({description:"",phone:"",minimumOrder:"0",preparationTime:"30",latitude:"",longitude:""});const[delivery,setDelivery]=useState<DeliverySettings>({pricing_model:"FIXED",fixed_fee:5,base_fee:4,per_km_fee:1.5,minimum_fee:5,max_radius_km:10,pickup_enabled:true,clickfood_delivery_enabled:true,own_delivery_enabled:false});const[hours,setHours]=useState<Hours[]>(dayNames.map((_,weekday)=>({weekday,opens_at:"08:00",closes_at:"22:00",closed:false})));
 async function load(){const[pR,cR,dR,sR,hR]=await Promise.all([supabase.from("products").select("id,name,price,active,category_id").eq("store_id",storeId).order("name"),supabase.from("categories").select("id,name,active").eq("store_id",storeId).order("sort_order").order("name"),supabase.from("store_delivery_settings").select("pricing_model,fixed_fee,base_fee,per_km_fee,minimum_fee,max_radius_km,pickup_enabled,clickfood_delivery_enabled,own_delivery_enabled").eq("store_id",storeId).maybeSingle(),supabase.from("stores").select("description,phone,minimum_order,average_preparation_time,latitude,longitude").eq("id",storeId).maybeSingle(),supabase.from("store_business_hours").select("weekday,opens_at,closes_at,closed").eq("store_id",storeId).order("weekday")]);
  if(pR.data)setProducts(pR.data.map((x:any)=>({...x,price:Number(x.price)})));if(cR.data)setCategories(cR.data as Category[]);if(dR.data)setDelivery({...dR.data,fixed_fee:Number(dR.data.fixed_fee),base_fee:Number(dR.data.base_fee),per_km_fee:Number(dR.data.per_km_fee),minimum_fee:Number(dR.data.minimum_fee),max_radius_km:dR.data.max_radius_km==null?null:Number(dR.data.max_radius_km)} as DeliverySettings);if(sR.data)setProfile({description:sR.data.description??"",phone:sR.data.phone??"",minimumOrder:String(Number(sR.data.minimum_order??0)),preparationTime:String(Number(sR.data.average_preparation_time??30)),latitude:sR.data.latitude==null?"":String(Number(sR.data.latitude)),longitude:sR.data.longitude==null?"":String(Number(sR.data.longitude))});if(hR.data?.length){const map=new Map(hR.data.map((x:any)=>[Number(x.weekday),x]));setHours(dayNames.map((_,weekday)=>{const x:any=map.get(weekday);return x?{weekday,opens_at:String(x.opens_at??"08:00").slice(0,5),closes_at:String(x.closes_at??"22:00").slice(0,5),closed:Boolean(x.closed)}:{weekday,opens_at:"08:00",closes_at:"22:00",closed:false}}));}}
 useEffect(()=>{load();},[storeId]);
 async function saveProfile(coords?:{latitude:number;longitude:number}){const minimumOrder=Number(profile.minimumOrder.replace(",",".")),prep=Number(profile.preparationTime);const latitude=coords?.latitude??(profile.latitude===""?undefined:Number(profile.latitude.replace(",","."))),longitude=coords?.longitude??(profile.longitude===""?undefined:Number(profile.longitude.replace(",",".")));if(!Number.isFinite(minimumOrder)||minimumOrder<0||!Number.isInteger(prep)||prep<1){setMessage("Revise pedido mínimo e tempo de preparo.");return;}if((latitude===undefined)!==(longitude===undefined)){setMessage("Preencha latitude e longitude juntas.");return;}const{data,error}=await supabase.functions.invoke("store-settings",{body:{storeId,description:profile.description,phone:profile.phone,minimumOrder,averagePreparationTime:prep,...(latitude!==undefined&&longitude!==undefined?{latitude,longitude}:{})}});if(error||data?.error){setMessage("Não foi possível salvar os dados da loja.");return;}const s=data.store;setProfile({description:s.description??"",phone:s.phone??"",minimumOrder:String(Number(s.minimum_order)),preparationTime:String(Number(s.average_preparation_time)),latitude:s.latitude==null?"":String(Number(s.latitude)),longitude:s.longitude==null?"":String(Number(s.longitude))});setMessage("Dados da loja salvos.");onChanged();}
 function captureLocation(){if(!navigator.geolocation){setMessage("Este navegador não oferece geolocalização.");return;}setLocating(true);navigator.geolocation.getCurrentPosition(async pos=>{await saveProfile({latitude:pos.coords.latitude,longitude:pos.coords.longitude});setLocating(false)},()=>{setMessage("Permita a localização do navegador ou informe latitude/longitude manualmente.");setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:30000});}
 async function createCategory(e:FormEvent){e.preventDefault();if(!categoryName.trim())return;const{error}=await supabase.from("categories").insert({store_id:storeId,name:categoryName.trim(),active:true});if(error){setMessage("Não foi possível criar a categoria.");return;}setCategoryName("");setMessage("Categoria criada.");await load();onChanged();}
 async function toggleCategory(c:Category){await supabase.from("categories").update({active:!c.active}).eq("id",c.id).eq("store_id",storeId);await load();}
 async function createProduct(e:FormEvent){e.preventDefault();const price=Number(product.price.replace(",","."));if(!product.name.trim()||!Number.isFinite(price)||price<=0){setMessage("Informe nome e preço válido.");return;}const{error}=await supabase.from("products").insert({store_id:storeId,category_id:product.categoryId||null,name:product.name.trim(),description:product.description.trim()||null,price,active:true,available_delivery:true,available_pos:true,control_inventory:false});if(error){setMessage("Não foi possível cadastrar o produto.");return;}setProduct({name:"",description:"",price:"",categoryId:""});setMessage("Produto cadastrado.");await load();onChanged();}
 async function toggleProduct(p:Product){await supabase.from("products").update({active:!p.active,updated_at:new Date().toISOString()}).eq("id",p.id).eq("store_id",storeId);await load();onChanged();}
 async function saveDelivery(){const{error}=await supabase.from("store_delivery_settings").update({pricing_model:delivery.pricing_model,fixed_fee:Number(delivery.fixed_fee),base_fee:Number(delivery.base_fee),per_km_fee:Number(delivery.per_km_fee),minimum_fee:Number(delivery.minimum_fee),max_radius_km:delivery.max_radius_km==null?null:Number(delivery.max_radius_km),pickup_enabled:delivery.pickup_enabled,clickfood_delivery_enabled:delivery.clickfood_delivery_enabled,own_delivery_enabled:delivery.own_delivery_enabled,updated_at:new Date().toISOString()}).eq("store_id",storeId);setMessage(error?"Não foi possível salvar as regras de entrega.":"Configuração de entrega salva.");}
 async function saveHours(){const del=await supabase.from("store_business_hours").delete().eq("store_id",storeId);if(del.error){setMessage("Não foi possível atualizar os horários.");return;}const rows=hours.map(h=>({store_id:storeId,weekday:h.weekday,opens_at:h.closed?null:h.opens_at,closes_at:h.closed?null:h.closes_at,closed:h.closed}));const{error}=await supabase.from("store_business_hours").insert(rows);setMessage(error?"Não foi possível salvar os horários.":"Horários salvos.");}
 return <section className="setupGrid">
  <article className="setupCard"><div className="setupTitle"><div><small>LOJA</small><h2>Dados e localização</h2></div><span>{profile.latitude&&profile.longitude?"GPS configurado":"GPS PENDENTE"}</span></div><label>Descrição<input value={profile.description} onChange={e=>setProfile({...profile,description:e.target.value})}/></label><label>Telefone<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><div className="setupRow"><label>Pedido mínimo<input value={profile.minimumOrder} onChange={e=>setProfile({...profile,minimumOrder:e.target.value})}/></label><label>Preparo médio (min)<input value={profile.preparationTime} onChange={e=>setProfile({...profile,preparationTime:e.target.value})}/></label></div><div className="setupRow"><label>Latitude<input placeholder="-14.52" value={profile.latitude} onChange={e=>setProfile({...profile,latitude:e.target.value})}/></label><label>Longitude<input placeholder="-49.14" value={profile.longitude} onChange={e=>setProfile({...profile,longitude:e.target.value})}/></label></div><button className="setupPrimary" onClick={()=>saveProfile()}>SALVAR DADOS</button><button className="setupSecondary" onClick={captureLocation} disabled={locating}>{locating?"CAPTURANDO GPS...":"USAR LOCALIZAÇÃO DESTA LOJA"}</button><p className="setupHint">Frete e busca de entregador só funcionam com coordenadas da loja.</p></article>
  <article className="setupCard"><div className="setupTitle"><div><small>CATÁLOGO</small><h2>Categorias</h2></div><span>{categories.length}</span></div><form onSubmit={createCategory}><input placeholder="Ex.: Hambúrgueres" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button className="setupPrimary">CRIAR CATEGORIA</button></form><div className="setupList">{categories.map(c=><div key={c.id}><div><b>{c.name}</b><small>{c.active?"Ativa":"Pausada"}</small></div><button onClick={()=>toggleCategory(c)}>{c.active?"Pausar":"Ativar"}</button></div>)}</div></article>
  <article className="setupCard"><div className="setupTitle"><div><small>CATÁLOGO</small><h2>Produtos</h2></div><span>{products.length}</span></div><form onSubmit={createProduct}><input placeholder="Nome do produto" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/><input placeholder="Descrição" value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/><select value={product.categoryId} onChange={e=>setProduct({...product,categoryId:e.target.value})}><option value="">Sem categoria</option>{categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Preço" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/><button className="setupPrimary">CADASTRAR PRODUTO</button></form><div className="setupList">{products.map(p=><div key={p.id}><div><b>{p.name}</b><small>{brl(p.price)} • {p.active?"Ativo":"Pausado"}</small></div><button onClick={()=>toggleProduct(p)}>{p.active?"Pausar":"Ativar"}</button></div>)}</div></article>
  <article className="setupCard"><div className="setupTitle"><div><small>ENTREGA</small><h2>Frete e atendimento</h2></div></div><label>Modelo<select value={delivery.pricing_model} onChange={e=>setDelivery({...delivery,pricing_model:e.target.value})}><option value="FREE">Grátis</option><option value="FIXED">Taxa fixa</option><option value="DISTANCE">Por distância</option></select></label>{delivery.pricing_model==="FIXED"&&<label>Taxa fixa<input value={String(delivery.fixed_fee)} onChange={e=>setDelivery({...delivery,fixed_fee:Number(e.target.value.replace(",","."))||0})}/></label>}{delivery.pricing_model==="DISTANCE"&&<div className="setupRow"><label>Base<input value={String(delivery.base_fee)} onChange={e=>setDelivery({...delivery,base_fee:Number(e.target.value.replace(",","."))||0})}/></label><label>Por km<input value={String(delivery.per_km_fee)} onChange={e=>setDelivery({...delivery,per_km_fee:Number(e.target.value.replace(",","."))||0})}/></label></div>}<label>Raio máximo km<input value={String(delivery.max_radius_km??"")} onChange={e=>setDelivery({...delivery,max_radius_km:e.target.value?Number(e.target.value.replace(",",".")):null})}/></label><div className="checkRows"><label><input type="checkbox" checked={delivery.clickfood_delivery_enabled} onChange={e=>setDelivery({...delivery,clickfood_delivery_enabled:e.target.checked})}/> Entregadores CLICK-FOOD</label><label><input type="checkbox" checked={delivery.own_delivery_enabled} onChange={e=>setDelivery({...delivery,own_delivery_enabled:e.target.checked})}/> Entrega própria</label><label><input type="checkbox" checked={delivery.pickup_enabled} onChange={e=>setDelivery({...delivery,pickup_enabled:e.target.checked})}/> Retirada na loja</label></div><button className="setupPrimary" onClick={saveDelivery}>SALVAR ENTREGA</button></article>
  <article className="setupCard hoursCard"><div className="setupTitle"><div><small>FUNCIONAMENTO</small><h2>Horários da loja</h2></div></div>{hours.map((h,index)=><div className="hoursRow" key={h.weekday}><b>{dayNames[h.weekday]}</b><label><input type="checkbox" checked={!h.closed} onChange={e=>setHours(hours.map((x,i)=>i===index?{...x,closed:!e.target.checked}:x))}/> Aberta</label><input type="time" disabled={h.closed} value={h.opens_at} onChange={e=>setHours(hours.map((x,i)=>i===index?{...x,opens_at:e.target.value}:x))}/><input type="time" disabled={h.closed} value={h.closes_at} onChange={e=>setHours(hours.map((x,i)=>i===index?{...x,closes_at:e.target.value}:x))}/></div>)}<button className="setupPrimary" onClick={saveHours}>SALVAR HORÁRIOS</button></article>
  {message&&<div className="setupMessage">{message}</div>}
 </section>;
}
