"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type ScopeType="GLOBAL"|"PLAN"|"STORE"|"SUBSCRIPTION";
type Tab="CARD"|"SPLIT"|"ANTICIPATION";
type RuleSummary={id:string;name:string;scope_type:ScopeType;store_id:string|null;plan_id:string|null;subscription_id:string|null;status:string;version:number;effective_from:string|null;effective_to:string|null;activated_at:string|null;updated_at:string};
type Opt={id:string;name:string;status?:string;active?:boolean};
type SubOpt={id:string;store_id:string;plan_id:string;status:string;started_at:string};
type Split={role:"STORE"|"DRIVER"|"PLATFORM";calculationType:string;calculationBasis:string;percentage:number;fixedCents:number;absorbsCardFee:boolean;allowsAnticipation:boolean};
type Config={rule:{id?:string;name:string;description:string;scopeType:ScopeType;storeId:string|null;planId:string|null;subscriptionId:string|null;status?:string;version?:number;feeTiming:string;effectiveFrom:string|null;effectiveTo:string|null};cardFees:{debitPercentage:number;creditCashPercentage:number;fixedTransactionCents:number};installmentFees:Array<{id?:string;from:number;to:number;percentage:number}>;anticipation:{storeAllowed:boolean;driverAllowed:boolean;monthlyPercentage:number;defaultMode:string;feeDestination:string};splits:Split[];audit?:any[]};
type Simulation={gross:number;productsAmount:number;deliveryFee:number;paymentMethod:string;installments:number;cardFeeRate:number;cardFee:number;cardFeeResponsible:string|null;anticipationFee:number;storeAmount:number;driverAmount:number;platformAmount:number;checkTotal:number;effectivePlatformPercentage:number};

const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const pct=(v:number)=>`${Number(v||0).toFixed(2).replace(".",",")}%`;
const defaultConfig=():Config=>({
 rule:{name:"Regra Padrão Marketplace - Matriz",description:"Regra global de taxas, split, repasses e antecipação CLICK-FOOD.",scopeType:"GLOBAL",storeId:null,planId:null,subscriptionId:null,feeTiming:"BEFORE_SPLIT",effectiveFrom:null,effectiveTo:null},
 cardFees:{debitPercentage:1.99,creditCashPercentage:3.49,fixedTransactionCents:50},
 installmentFees:[{from:2,to:6,percentage:4.99},{from:7,to:12,percentage:6.99}],
 anticipation:{storeAllowed:true,driverAllowed:true,monthlyPercentage:2.5,defaultMode:"AUTOMATIC",feeDestination:"MATRIX"},
 splits:[
  {role:"STORE",calculationType:"RESIDUAL",calculationBasis:"GROSS",percentage:0,fixedCents:0,absorbsCardFee:true,allowsAnticipation:true},
  {role:"DRIVER",calculationType:"DELIVERY_EARNING",calculationBasis:"DRIVER_EARNING",percentage:0,fixedCents:0,absorbsCardFee:false,allowsAnticipation:true},
  {role:"PLATFORM",calculationType:"PERCENTAGE_AND_FIXED",calculationBasis:"PRODUCTS",percentage:10,fixedCents:150,absorbsCardFee:false,allowsAnticipation:false},
 ]
});
const errors:Record<string,string>={
 MATRIX_REQUIRED:"Apenas a Matriz pode acessar este módulo.",RULE_NAME_REQUIRED:"Informe o nome da regra.",THREE_SPLIT_ROLES_REQUIRED:"Configure Lojista, Entregador e Plataforma.",STORE_RESIDUAL_OR_PERCENTAGE_REQUIRED:"O Lojista deve usar cálculo Residual ou Percentual.",EXACTLY_ONE_CARD_FEE_RESPONSIBLE_REQUIRED:"Defina exatamente um responsável pelas taxas de cartão.",INSTALLMENT_BANDS_MUST_COVER_2_TO_12_ONCE:"As faixas parceladas devem cobrir de 2x a 12x, sem lacunas nem sobreposição.",INSTALLMENT_BANDS_REQUIRED:"Configure as taxas parceladas de 2x a 12x.",NEGATIVE_RECIPIENT_STORE:"A simulação deixaria o Lojista com valor negativo.",NEGATIVE_RECIPIENT_DRIVER:"A simulação deixaria o Entregador com valor negativo.",NEGATIVE_RECIPIENT_PLATFORM:"A simulação deixaria a Plataforma com valor negativo.",ANTICIPATION_NOT_ALLOWED:"A antecipação não está permitida para este participante.",INSTALLMENT_RATE_NOT_CONFIGURED:"Não existe taxa configurada para esta quantidade de parcelas."};

export default function DivisionRulesPage(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[rules,setRules]=useState<RuleSummary[]>([]);const[stores,setStores]=useState<Opt[]>([]);const[plans,setPlans]=useState<Opt[]>([]);const[subs,setSubs]=useState<SubOpt[]>([]);const[config,setConfig]=useState<Config>(defaultConfig());const[tab,setTab]=useState<Tab>("CARD");const[busy,setBusy]=useState(false);const[simulation,setSimulation]=useState<Simulation|null>(null);const[sim,setSim]=useState({productsAmount:100,deliveryFee:10,driverEarning:10,paymentMethod:"CREDIT_CARD",installments:1,anticipationRole:"NONE",anticipationDays:30});
 const storeMap=useMemo(()=>new Map(stores.map(x=>[x.id,x.name])),[stores]);const planMap=useMemo(()=>new Map(plans.map(x=>[x.id,x.name])),[plans]);
 const activeRules=rules.filter(r=>r.status==="ACTIVE").length;const draftRules=rules.filter(r=>r.status==="DRAFT").length;
 const currentSplit=(role:Split["role"])=>config.splits.find(x=>x.role===role)!;
 function setSplit(role:Split["role"],patch:Partial<Split>){setConfig(c=>({...c,splits:c.splits.map(s=>s.role===role?{...s,...patch}:s)}));setSimulation(null)}
 function scopeLabel(r:RuleSummary){if(r.scope_type==="GLOBAL")return"Global";if(r.scope_type==="STORE")return `Loja • ${storeMap.get(String(r.store_id))??"—"}`;if(r.scope_type==="PLAN")return `Plano • ${planMap.get(String(r.plan_id))??"—"}`;const sub=subs.find(s=>s.id===r.subscription_id);return `Contrato • ${sub?`${storeMap.get(sub.store_id)??"Loja"} / ${planMap.get(sub.plan_id)??"Plano"}`:"—"}`;}
 async function invoke(body:any){const{data,error}=await supabase.functions.invoke("admin-division-rules",{body});if(error||data?.error)throw new Error(String(data?.error??"DIVISION_RULE_OPERATION_FAILED"));return data;}
 async function boot(){setLoading(true);setMessage("");const{data:sd}=await supabase.auth.getSession();const role=String(sd.session?.user.app_metadata?.clickfood_role??"");if(!sd.session||!["SUPER_ADMIN","ADMIN"].includes(role)){setAuthorized(false);setLoading(false);return;}setAuthorized(true);try{const[list,options]=await Promise.all([invoke({action:"LIST"}),invoke({action:"OPTIONS"})]);setRules(list.rules??[]);setStores(options.stores??[]);setPlans(options.plans??[]);setSubs(options.subscriptions??[]);}catch(e:any){setMessage(errors[e.message]??"Não foi possível carregar as Regras de Divisão.");}setLoading(false);}
 useEffect(()=>{boot();},[]);
 async function openRule(id:string){setBusy(true);setMessage("");try{const data=await invoke({action:"GET",ruleId:id});setConfig(data.config);setSimulation(null);setTab("CARD");}catch(e:any){setMessage(errors[e.message]??"Não foi possível abrir esta regra.");}setBusy(false);}
 function newRule(){setConfig(defaultConfig());setSimulation(null);setTab("CARD");setMessage("Nova regra iniciada como rascunho. Nada será aplicado até a Matriz ativar.");}
 function setScope(scopeType:ScopeType){setConfig(c=>({...c,rule:{...c.rule,scopeType,storeId:null,planId:null,subscriptionId:null}}));setSimulation(null)}
 async function saveDraft(){setBusy(true);setMessage("");try{const data=await invoke({action:"SAVE_DRAFT",config});setConfig(data.config);setMessage(data.config.rule.version>1?`Nova versão v${data.config.rule.version} criada como RASCUNHO. A versão ativa anterior continua valendo até a ativação.`:"Rascunho salvo com sucesso.");await refreshList();}catch(e:any){setMessage(errors[e.message]??"Não foi possível salvar a regra.");}setBusy(false);}
 async function activate(){if(!config.rule.id){setMessage("Salve o rascunho antes de ativar.");return;}if(!window.confirm(`Ativar “${config.rule.name}”? A regra ativa anterior do mesmo escopo será arquivada.`))return;setBusy(true);setMessage("");try{const data=await invoke({action:"ACTIVATE",ruleId:config.rule.id});setConfig(data.config);setMessage(`Regra v${data.config.rule.version} ATIVADA para ${data.config.rule.scopeType}.`);await refreshList();}catch(e:any){setMessage(errors[e.message]??"Não foi possível ativar. Revise taxas, faixas e responsáveis.");}setBusy(false);}
 async function archive(){if(!config.rule.id||config.rule.status==="ARCHIVED")return;if(!window.confirm("Arquivar esta regra?"))return;setBusy(true);try{await invoke({action:"ARCHIVE",ruleId:config.rule.id});setMessage("Regra arquivada.");await refreshList();setConfig(defaultConfig());}catch{setMessage("Não foi possível arquivar.");}setBusy(false);}
 async function refreshList(){const data=await invoke({action:"LIST"});setRules(data.rules??[]);}
 async function simulate(){setBusy(true);setMessage("");try{const data=await invoke({action:"SIMULATE",config,input:sim});setSimulation(data.simulation);setMessage("Simulação validada: a divisão fecha exatamente com o valor bruto informado.");}catch(e:any){setSimulation(null);setMessage(errors[e.message]??(String(e.message).startsWith("NEGATIVE_RECIPIENT_")?"A configuração gera valor negativo para um recebedor.":"Não foi possível simular esta regra."));}setBusy(false);}
 function numberValue(v:string){return Number(String(v).replace(",","."))||0}
 if(loading)return <main className="authPage"><div className="authCard">Carregando Regras de Divisão...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Somente Super Admin ou Admin da Matriz pode configurar taxas, split e antecipação.</p><a href="/">Voltar</a></div></main>;
 const splitCards:[Split["role"],string,string][]=[["STORE","Lojista","Recebe o residual da venda ou um percentual definido pela Matriz."],["DRIVER","Entregador","Recebe valor fixo, percentual ou o ganho calculado da entrega."],["PLATFORM","Plataforma / Matriz","Recebe comissão, parcela fixa, taxas de cartão e antecipação."]];
 return <main className="content">
  <header className="topbar"><div><p className="eyebrow">CONFIGURAÇÕES FINANCEIRAS • MATRIZ</p><h1>Regras de Divisão</h1><small>Taxas de cartão, split, repasses e antecipação centralizados pela CLICK-FOOD.</small></div><div className="topActions"><span className="status">{activeRules} ativa(s)</span><button className="logout" onClick={boot}>Atualizar</button></div></header>
  {message&&<div className="notice">{message}</div>}
  <div className="metricGrid"><article className="metric"><p>Regras ativas</p><strong>{activeRules}</strong></article><article className="metric"><p>Rascunhos</p><strong>{draftRules}</strong></article><article className="metric"><p>Escopo atual</p><strong style={{fontSize:18}}>{config.rule.scopeType}</strong></article><article className="metric"><p>Versão</p><strong>v{config.rule.version??1}</strong></article></div>
  <div style={{display:"grid",gridTemplateColumns:"minmax(270px,340px) minmax(0,1fr)",gap:16,marginTop:16,alignItems:"start"}}>
   <section className="panel" style={{position:"sticky",top:20}}><div className="panelTitle"><div><h2>Regras e versões</h2><span>{rules.length} cadastradas</span></div><button className="primary" onClick={newRule}>+ Nova</button></div><div className="tableList" style={{maxHeight:"68vh",overflow:"auto"}}>{rules.map(r=><button key={r.id} onClick={()=>openRule(r.id)} style={{textAlign:"left",border:r.id===config.rule.id?"2px solid #d7b500":"1px solid #e8e8e2",background:r.id===config.rule.id?"#fff9d8":"#fafaf8",padding:12,borderRadius:12,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b>{r.name}</b><span className={`badge ${r.status==="ACTIVE"?"active":r.status==="ARCHIVED"?"blocked":"pending"}`}>{r.status}</span></div><small style={{display:"block",color:"#777",marginTop:5}}>{scopeLabel(r)} • v{r.version}</small></button>)}</div></section>
   <div style={{display:"grid",gap:16}}>
    <section className="panel formPanel"><div className="panelTitle"><div><h2>{config.rule.name||"Nova regra"}</h2><span>{config.rule.status??"DRAFT"} • v{config.rule.version??1}</span></div><div className="itemActions"><button onClick={saveDraft} disabled={busy}>{busy?"AGUARDE...":"SALVAR RASCUNHO"}</button><button onClick={activate} disabled={busy||config.rule.status==="ACTIVE"} style={{background:"#ffd400",borderColor:"#d7b500"}}>ATIVAR REGRA</button>{config.rule.id&&config.rule.status!=="ARCHIVED"&&<button className="danger" onClick={archive} disabled={busy}>ARQUIVAR</button>}</div></div>
     {config.rule.status==="ACTIVE"&&<div className="notice">Esta versão está ATIVA. Ao salvar alterações, o sistema cria automaticamente uma nova versão em rascunho; a versão atual continua valendo até a nova ser ativada.</div>}
     <div className="formRow"><label>Nome da regra<input value={config.rule.name} onChange={e=>setConfig(c=>({...c,rule:{...c.rule,name:e.target.value}}))}/></label><label>Escopo<select value={config.rule.scopeType} onChange={e=>setScope(e.target.value as ScopeType)}><option value="GLOBAL">Global • toda a plataforma</option><option value="PLAN">Por plano</option><option value="STORE">Por loja/unidade</option><option value="SUBSCRIPTION">Por contrato/assinatura</option></select></label></div>
     {config.rule.scopeType==="PLAN"&&<label>Plano<select value={config.rule.planId??""} onChange={e=>setConfig(c=>({...c,rule:{...c.rule,planId:e.target.value||null}}))}><option value="">Selecione...</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
     {config.rule.scopeType==="STORE"&&<label>Loja / Unidade<select value={config.rule.storeId??""} onChange={e=>setConfig(c=>({...c,rule:{...c.rule,storeId:e.target.value||null}}))}><option value="">Selecione...</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name} • {s.status}</option>)}</select></label>}
     {config.rule.scopeType==="SUBSCRIPTION"&&<label>Contrato / Assinatura<select value={config.rule.subscriptionId??""} onChange={e=>setConfig(c=>({...c,rule:{...c.rule,subscriptionId:e.target.value||null}}))}><option value="">Selecione...</option>{subs.map(s=><option key={s.id} value={s.id}>{storeMap.get(s.store_id)??"Loja"} • {planMap.get(s.plan_id)??"Plano"} • {s.status}</option>)}</select></label>}
     <label>Descrição<textarea value={config.rule.description??""} onChange={e=>setConfig(c=>({...c,rule:{...c.rule,description:e.target.value}}))}/></label>
     <div style={{display:"flex",gap:8,flexWrap:"wrap",borderBottom:"1px solid #eee",paddingBottom:12,marginTop:16}}><button className={tab==="CARD"?"primary":"logout"} onClick={()=>setTab("CARD")}>1. Taxas de Cartão & Operação</button><button className={tab==="SPLIT"?"primary":"logout"} onClick={()=>setTab("SPLIT")}>2. Split / Repasses</button><button className={tab==="ANTICIPATION"?"primary":"logout"} onClick={()=>setTab("ANTICIPATION")}>3. Antecipação</button></div>

     {tab==="CARD"&&<div style={{marginTop:12}}><div className="formRow"><label>Taxa Débito (%)<input type="number" step="0.01" min="0" value={config.cardFees.debitPercentage} onChange={e=>setConfig(c=>({...c,cardFees:{...c.cardFees,debitPercentage:numberValue(e.target.value)}}))}/></label><label>Crédito à vista 1x (%)<input type="number" step="0.01" min="0" value={config.cardFees.creditCashPercentage} onChange={e=>setConfig(c=>({...c,cardFees:{...c.cardFees,creditCashPercentage:numberValue(e.target.value)}}))}/></label></div><label>Tarifa fixa por transação (R$)<input type="number" step="0.01" min="0" value={(config.cardFees.fixedTransactionCents/100).toFixed(2)} onChange={e=>setConfig(c=>({...c,cardFees:{...c.cardFees,fixedTransactionCents:Math.round(numberValue(e.target.value)*100)}}))}/></label><div className="panelTitle" style={{marginTop:18}}><div><h2>Crédito parcelado</h2><span>As faixas devem cobrir 2x até 12x sem sobreposição.</span></div><button className="logout" onClick={()=>setConfig(c=>({...c,installmentFees:[...c.installmentFees,{from:2,to:12,percentage:0}]}))}>+ Faixa</button></div><div className="tableList">{config.installmentFees.map((b,i)=><div className="tableItem" key={i} style={{gridTemplateColumns:"1fr 1fr 1fr auto"}}><label>De<input type="number" min="2" max="12" value={b.from} onChange={e=>setConfig(c=>({...c,installmentFees:c.installmentFees.map((x,j)=>j===i?{...x,from:Number(e.target.value)}:x)}))}/></label><label>Até<input type="number" min="2" max="12" value={b.to} onChange={e=>setConfig(c=>({...c,installmentFees:c.installmentFees.map((x,j)=>j===i?{...x,to:Number(e.target.value)}:x)}))}/></label><label>Taxa (%)<input type="number" step="0.01" value={b.percentage} onChange={e=>setConfig(c=>({...c,installmentFees:c.installmentFees.map((x,j)=>j===i?{...x,percentage:numberValue(e.target.value)}:x)}))}/></label><button className="logout" onClick={()=>setConfig(c=>({...c,installmentFees:c.installmentFees.filter((_,j)=>j!==i)}))}>Remover</button></div>)}</div></div>}

     {tab==="SPLIT"&&<div style={{display:"grid",gap:12,marginTop:14}}>{splitCards.map(([role,title,help])=>{const s=currentSplit(role);return <article key={role} style={{border:"1px solid #e5e5df",borderRadius:14,padding:15,background:role==="PLATFORM"?"#111":role==="DRIVER"?"#f6faf7":"#fffdf1",color:role==="PLATFORM"?"#fff":"#111"}}><div className="panelTitle"><div><h2>{title}</h2><span style={{color:role==="PLATFORM"?"#aaa":"#777"}}>{help}</span></div><b>{role}</b></div><div className="formRow"><label>Tipo de cálculo<select value={s.calculationType} onChange={e=>setSplit(role,{calculationType:e.target.value})}><option value="RESIDUAL" disabled={role!=="STORE"}>Residual</option><option value="FIXED">Fixo (R$)</option><option value="PERCENTAGE">Percentual (%)</option><option value="PERCENTAGE_AND_FIXED">Percentual + Fixo</option><option value="DELIVERY_EARNING" disabled={role!=="DRIVER"}>Ganho calculado da entrega</option></select></label><label>Base do cálculo<select value={s.calculationBasis} onChange={e=>setSplit(role,{calculationBasis:e.target.value})}><option value="PRODUCTS">Produtos / serviços</option><option value="DELIVERY_FEE">Taxa de entrega</option><option value="GROSS">Valor bruto</option><option value="DRIVER_EARNING">Ganho do entregador</option></select></label></div><div className="formRow"><label>Percentual (%)<input type="number" step="0.01" min="0" value={s.percentage} disabled={["RESIDUAL","FIXED","DELIVERY_EARNING"].includes(s.calculationType)} onChange={e=>setSplit(role,{percentage:numberValue(e.target.value)})}/></label><label>Valor fixo (R$)<input type="number" step="0.01" min="0" value={(s.fixedCents/100).toFixed(2)} disabled={["RESIDUAL","PERCENTAGE","DELIVERY_EARNING"].includes(s.calculationType)} onChange={e=>setSplit(role,{fixedCents:Math.round(numberValue(e.target.value)*100)})}/></label></div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:8}}><label style={{display:"flex",alignItems:"center",gap:7,margin:0}}><input type="checkbox" checked={s.absorbsCardFee} onChange={e=>{const checked=e.target.checked;setConfig(c=>({...c,splits:c.splits.map(x=>({...x,absorbsCardFee:checked?x.role===role:false}))}))}}/> Responsável pelas taxas de cartão</label><label style={{display:"flex",alignItems:"center",gap:7,margin:0}}><input type="checkbox" checked={s.allowsAnticipation} disabled={role==="PLATFORM"} onChange={e=>setSplit(role,{allowsAnticipation:e.target.checked})}/> Permite antecipação</label></div></article>})}</div>}

     {tab==="ANTICIPATION"&&<div style={{marginTop:14}}><div className="notice"><b>Controle exclusivo da MATRIZ.</b> Lojistas e entregadores apenas podem solicitar/receber conforme esta política; não conseguem alterar a taxa.</div><div className="formRow"><label>Modalidade padrão<select value={config.anticipation.defaultMode} onChange={e=>setConfig(c=>({...c,anticipation:{...c.anticipation,defaultMode:e.target.value}}))}><option value="AUTOMATIC">Automática</option><option value="ON_DEMAND">Sob demanda</option><option value="DISABLED">Desativada</option></select></label><label>Taxa de antecipação (% a.m.)<input type="number" step="0.01" min="0" value={config.anticipation.monthlyPercentage} onChange={e=>setConfig(c=>({...c,anticipation:{...c.anticipation,monthlyPercentage:numberValue(e.target.value)}}))}/></label></div><div style={{display:"grid",gap:10,marginTop:10}}><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={config.anticipation.storeAllowed} onChange={e=>setConfig(c=>({...c,anticipation:{...c.anticipation,storeAllowed:e.target.checked}}))}/> Permitir antecipação para Lojista</label><label style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" checked={config.anticipation.driverAllowed} onChange={e=>setConfig(c=>({...c,anticipation:{...c.anticipation,driverAllowed:e.target.checked}}))}/> Permitir antecipação para Entregador</label></div><article style={{marginTop:18,background:"#111",color:"white",borderRadius:14,padding:16}}><small style={{color:"#ffd400",fontWeight:900}}>DESTINO DA RECEITA</small><h2 style={{margin:"5px 0"}}>100% Plataforma / Matriz</h2><p style={{color:"#aaa",margin:0,fontSize:13}}>Toda taxa de antecipação descontada do participante é contabilizada como receita da Matriz.</p></article></div>}
    </section>

    <section className="panel formPanel"><div className="panelTitle"><div><h2>Simulador da divisão</h2><span>Valide a regra antes de ativar.</span></div><button className="primary" onClick={simulate} disabled={busy}>SIMULAR</button></div><div className="formRow"><label>Produtos / serviços (R$)<input type="number" step="0.01" value={sim.productsAmount} onChange={e=>setSim(s=>({...s,productsAmount:numberValue(e.target.value)}))}/></label><label>Taxa de entrega (R$)<input type="number" step="0.01" value={sim.deliveryFee} onChange={e=>setSim(s=>({...s,deliveryFee:numberValue(e.target.value)}))}/></label></div><div className="formRow"><label>Ganho do entregador (R$)<input type="number" step="0.01" value={sim.driverEarning} onChange={e=>setSim(s=>({...s,driverEarning:numberValue(e.target.value)}))}/></label><label>Pagamento<select value={sim.paymentMethod} onChange={e=>setSim(s=>({...s,paymentMethod:e.target.value}))}><option value="PIX">PIX</option><option value="DEBIT_CARD">Cartão Débito</option><option value="CREDIT_CARD">Cartão Crédito</option><option value="CASH">Dinheiro</option></select></label></div>{sim.paymentMethod==="CREDIT_CARD"&&<label>Parcelas<input type="number" min="1" max="12" value={sim.installments} onChange={e=>setSim(s=>({...s,installments:Number(e.target.value)}))}/></label>}<div className="formRow"><label>Simular antecipação<select value={sim.anticipationRole} onChange={e=>setSim(s=>({...s,anticipationRole:e.target.value}))}><option value="NONE">Sem antecipação</option><option value="STORE">Lojista</option><option value="DRIVER">Entregador</option></select></label><label>Dias antecipados<input type="number" min="1" max="365" value={sim.anticipationDays} onChange={e=>setSim(s=>({...s,anticipationDays:Number(e.target.value)}))}/></label></div>
     {simulation&&<><div className="summaryGrid" style={{marginTop:16}}><div><span>Valor bruto</span><b>{brl(simulation.gross)}</b></div><div><span>Taxa cartão • {pct(simulation.cardFeeRate)}</span><b>{brl(simulation.cardFee)}</b></div><div><span>Antecipação</span><b>{brl(simulation.anticipationFee)}</b></div></div><div className="metricGrid" style={{marginTop:12}}><article className="metric"><p>Lojista</p><strong>{brl(simulation.storeAmount)}</strong></article><article className="metric"><p>Entregador</p><strong>{brl(simulation.driverAmount)}</strong></article><article className="metric"><p>Plataforma / Matriz</p><strong>{brl(simulation.platformAmount)}</strong><small style={{display:"block",color:"#777",marginTop:4}}>efetivo {pct(simulation.effectivePlatformPercentage)}</small></article><article className="metric"><p>Conferência</p><strong>{brl(simulation.checkTotal)}</strong><small style={{display:"block",color:"#16723b",marginTop:4}}>fecha com o bruto</small></article></div></>}
    </section>
    <section className="panel"><div className="panelTitle"><div><h2>Precedência do motor</h2><span>A regra mais específica vence automaticamente.</span></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><span className="badge active">1. CONTRATO</span><b>›</b><span className="badge active">2. LOJA</span><b>›</b><span className="badge pending">3. PLANO</span><b>›</b><span className="badge">4. GLOBAL</span></div><p style={{color:"#666",fontSize:13,marginBottom:0}}>Uma alteração de regra nunca recalcula pedidos antigos. A versão aplicada ao pedido será registrada em snapshot financeiro.</p></section>
   </div>
  </div>
 </main>;
}
