"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Store={id:string;name:string;status:string;latitude:number|null;longitude:number|null};
type Driver={id:string;user_id:string;online:boolean;status:string;rating:number;profileName:string;latitude:number|null;longitude:number|null;recorded_at:string|null};
type Delivery={id:string;driver_id:string|null;status:string;order_id:string;orders:any};
const activeDeliveryStatuses=new Set(["SEARCHING_DRIVER","OFFER_SENT","DRIVER_ASSIGNED","DRIVER_TO_STORE","DRIVER_AT_STORE","PICKUP_CONFIRMED","DRIVER_TO_CUSTOMER","DRIVER_AT_CUSTOMER"]);
const rel=(v:any)=>Array.isArray(v)?v[0]:v;
const ago=(value:string|null)=>{if(!value)return"sem GPS";const s=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}min`:`${Math.floor(s/3600)}h`;};
const merc=(lat:number)=>Math.log(Math.tan(Math.PI/4+(Math.max(-85,Math.min(85,lat))*Math.PI/180)/2));

export default function OperationalMap(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[stores,setStores]=useState<Store[]>([]);const[drivers,setDrivers]=useState<Driver[]>([]);const[deliveries,setDeliveries]=useState<Delivery[]>([]);const[onlyOnline,setOnlyOnline]=useState(true);const[lastRefresh,setLastRefresh]=useState<Date|null>(null);
 async function load(){const[sR,dR,lR,dlR]=await Promise.all([supabase.from("stores").select("id,name,status,latitude,longitude").in("status",["ACTIVE","SUSPENDED"]).limit(500),supabase.from("drivers").select("id,user_id,online,status,rating").in("status",["ACTIVE","PENDING"]).limit(1000),supabase.from("driver_locations").select("driver_id,latitude,longitude,recorded_at").limit(1000),supabase.from("deliveries").select("id,driver_id,status,order_id,orders(order_number,status,store_id,stores(name,latitude,longitude))").limit(500)]);
  if(sR.error||dR.error||lR.error||dlR.error){setMessage("Não foi possível carregar toda a operação agora.");return;}
  const rawDrivers=(dR.data??[]) as any[],ids=rawDrivers.map(x=>x.user_id);const pR=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[] as any[]};const names=new Map((pR.data??[]).map((p:any)=>[p.id,p.full_name]));const locs=new Map((lR.data??[]).map((x:any)=>[x.driver_id,x]));setStores((sR.data??[]).map((s:any)=>({...s,latitude:s.latitude==null?null:Number(s.latitude),longitude:s.longitude==null?null:Number(s.longitude)})));setDrivers(rawDrivers.map(d=>{const l:any=locs.get(d.id);return{...d,rating:Number(d.rating),profileName:names.get(d.user_id)||"Entregador",latitude:l?.latitude==null?null:Number(l.latitude),longitude:l?.longitude==null?null:Number(l.longitude),recorded_at:l?.recorded_at??null}}));setDeliveries(((dlR.data??[]) as any[]).filter(x=>activeDeliveryStatuses.has(x.status)));setLastRefresh(new Date());setMessage("");
 }
 async function boot(){setLoading(true);const{data}=await supabase.auth.getSession();const role=String(data.session?.user.app_metadata?.clickfood_role??"");const ok=Boolean(data.session)&&["SUPER_ADMIN","ADMIN","SUPPORT"].includes(role);setAuthorized(ok);if(ok)await load();setLoading(false);}
 useEffect(()=>{boot();},[]);
 useEffect(()=>{if(!authorized)return;let timer:any;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>load(),300)};const channel=supabase.channel("matrix-operational-map").on("postgres_changes",{event:"*",schema:"public",table:"driver_locations"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"drivers"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"deliveries"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"orders"},refresh).subscribe();const fallback=setInterval(load,10000);return()=>{clearTimeout(timer);clearInterval(fallback);supabase.removeChannel(channel)};},[authorized]);
 const visibleDrivers=useMemo(()=>drivers.filter(d=>(!onlyOnline||d.online)&&d.latitude!=null&&d.longitude!=null),[drivers,onlyOnline]);
 const bounds=useMemo(()=>{const pts=[...stores.filter(s=>s.latitude!=null&&s.longitude!=null).map(s=>[s.latitude!,s.longitude!] as const),...visibleDrivers.map(d=>[d.latitude!,d.longitude!] as const)];if(!pts.length)return{minLat:-16.15,maxLat:-15.35,minLng:-48.25,maxLng:-47.45};let minLat=Math.min(...pts.map(p=>p[0])),maxLat=Math.max(...pts.map(p=>p[0])),minLng=Math.min(...pts.map(p=>p[1])),maxLng=Math.max(...pts.map(p=>p[1]));const latPad=Math.max(.01,(maxLat-minLat)*.18),lngPad=Math.max(.01,(maxLng-minLng)*.18);return{minLat:minLat-latPad,maxLat:maxLat+latPad,minLng:minLng-lngPad,maxLng:maxLng+lngPad}},[stores,visibleDrivers]);
 const pinStyle=(lat:number,lng:number)=>{const x=(lng-bounds.minLng)/(bounds.maxLng-bounds.minLng);const top=(merc(bounds.maxLat)-merc(lat))/(merc(bounds.maxLat)-merc(bounds.minLat));return{left:`${Math.max(0,Math.min(1,x))*100}%`,top:`${Math.max(0,Math.min(1,top))*100}%`}};
 const osm=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(`${bounds.minLng},${bounds.minLat},${bounds.maxLng},${bounds.maxLat}`)}&layer=mapnik`;
 if(loading)return <main className="authPage"><div className="authCard">Carregando mapa operacional...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Entre na Matriz com perfil administrativo ou suporte.</p></div></main>;
 return <main className="adminPage"><section className="adminHeader"><div><small>OPERAÇÃO EM TEMPO REAL</small><h1>Mapa operacional</h1><p>Entregadores, lojas e entregas ativas com atualização automática.</p></div><div><button className="primaryAction" onClick={load}>ATUALIZAR AGORA</button><small style={{display:"block",marginTop:8}}>Última atualização: {lastRefresh?.toLocaleTimeString("pt-BR")??"-"}</small></div></section>
  {message&&<div className="adminNotice">{message}</div>}
  <section className="metricGrid"><article><b>{drivers.filter(d=>d.online).length}</b><span>Entregadores online</span></article><article><b>{visibleDrivers.length}</b><span>Com GPS no mapa</span></article><article><b>{deliveries.length}</b><span>Entregas ativas</span></article><article><b>{stores.filter(s=>s.status==="ACTIVE").length}</b><span>Lojas ativas</span></article></section>
  <section className="adminPanel"><div className="panelTitle"><div><small>VISÃO DA CIDADE</small><h2>Operação ao vivo</h2></div><label><input type="checkbox" checked={onlyOnline} onChange={e=>setOnlyOnline(e.target.checked)}/> Mostrar somente online</label></div>
   <div style={{position:"relative",height:560,borderRadius:18,overflow:"hidden",border:"1px solid #ddd",background:"#e9ecef"}}><iframe title="Mapa OpenStreetMap" src={osm} style={{position:"absolute",inset:0,width:"100%",height:"100%",border:0,pointerEvents:"none"}}/>{stores.filter(s=>s.latitude!=null&&s.longitude!=null).map(s=><div key={s.id} title={`${s.name} • ${s.status}`} style={{position:"absolute",transform:"translate(-50%,-50%)",...pinStyle(s.latitude!,s.longitude!),zIndex:3}}><div style={{background:"#111",color:"#fff",borderRadius:18,padding:"7px 9px",fontSize:15,border:"2px solid #fff"}}>🏪</div></div>)}{visibleDrivers.map(d=><div key={d.id} title={`${d.profileName} • ${d.online?"online":"offline"} • GPS ${ago(d.recorded_at)}`} style={{position:"absolute",transform:"translate(-50%,-50%)",...pinStyle(d.latitude!,d.longitude!),zIndex:4}}><div style={{background:d.online?"#f4c400":"#ddd",borderRadius:20,padding:"7px 9px",fontSize:18,border:"2px solid #111",boxShadow:"0 2px 8px #0005"}}>🛵</div></div>)}</div><p className="muted">Mapa-base: OpenStreetMap. Os marcadores são posicionados com as coordenadas reais registradas pelo CLICK-FOOD.</p>
  </section>
  <section className="adminGrid2"><article className="adminPanel"><div className="panelTitle"><div><small>ENTREGADORES</small><h2>Status e GPS</h2></div></div><div className="adminList">{drivers.filter(d=>!onlyOnline||d.online).slice(0,100).map(d=><div key={d.id}><div><b>{d.profileName}</b><small>{d.online?"ONLINE":"OFFLINE"} • nota {d.rating.toFixed(1)} • GPS {ago(d.recorded_at)}</small></div><span>{d.latitude!=null?"📍":"—"}</span></div>)}{!drivers.length&&<p className="muted">Nenhum entregador cadastrado.</p>}</div></article>
   <article className="adminPanel"><div className="panelTitle"><div><small>ENTREGAS</small><h2>Em andamento</h2></div></div><div className="adminList">{deliveries.map(d=>{const o=rel(d.orders),s=rel(o?.stores);const driver=drivers.find(x=>x.id===d.driver_id);return <div key={d.id}><div><b>#{o?.order_number??"-"} • {s?.name??"Loja"}</b><small>{d.status} • {driver?.profileName??"Buscando entregador"}</small></div><span>{driver?.online?"🟢":"🟡"}</span></div>})}{!deliveries.length&&<p className="muted">Nenhuma entrega ativa agora.</p>}</div></article></section>
 </main>;
}
