import React,{ReactNode,useEffect,useState}from"react";
import{Alert,Modal,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View}from"react-native";
import*as Linking from"expo-linking";
import{supabase}from"./supabase";

const RECOVERY_URL="https://rmlbmacoqnynqdqmxecz.supabase.co/functions/v1/password-recovery";

function readParam(url:string,name:string){
 const source=[url.split("?")[1]?.split("#")[0]??"",url.split("#")[1]??""].join("&");
 return new URLSearchParams(source).get(name);
}

export default function AccountLifecycleHost({children,scheme}:{children:ReactNode;scheme:string}){
 const[recoveryOpen,setRecoveryOpen]=useState(false);const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{
  async function handle(url:string|null){if(!url||!url.startsWith(`${scheme}://reset-password`))return;setMessage("");const code=readParam(url,"code");const access=readParam(url,"access_token");const refresh=readParam(url,"refresh_token");const type=readParam(url,"type");let ok=false;if(code){const{error}=await supabase.auth.exchangeCodeForSession(code);ok=!error;}else if(access&&refresh){const{error}=await supabase.auth.setSession({access_token:access,refresh_token:refresh});ok=!error;}if(ok||type==="recovery")setRecoveryOpen(true);else setMessage("O link de recuperação é inválido ou expirou.");}
  Linking.getInitialURL().then(handle);const sub=Linking.addEventListener("url",event=>{handle(event.url);});return()=>sub.remove();
 },[scheme]);
 async function save(){if(password.length<8){setMessage("A nova senha deve ter pelo menos 8 caracteres.");return;}if(password!==confirm){setMessage("As senhas não conferem.");return;}setBusy(true);setMessage("");const{error}=await supabase.auth.updateUser({password});if(error){setMessage("Não foi possível atualizar a senha. Solicite um novo link.");setBusy(false);return;}setBusy(false);setPassword("");setConfirm("");setRecoveryOpen(false);Alert.alert("Senha alterada","Sua nova senha foi salva com sucesso.");}
 return <View style={{flex:1}}>{children}<Modal visible={recoveryOpen} animationType="slide" onRequestClose={()=>setRecoveryOpen(false)}><SafeAreaView style={styles.safe}><View style={styles.modal}><Text style={styles.brand}><Text style={styles.yellow}>CLICK</Text>-FOOD</Text><Text style={styles.title}>Criar nova senha</Text><Text style={styles.info}>Digite uma nova senha para sua conta.</Text><TextInput style={styles.input} placeholder="Nova senha" secureTextEntry value={password} onChangeText={setPassword}/><TextInput style={styles.input} placeholder="Confirmar nova senha" secureTextEntry value={confirm} onChangeText={setConfirm}/>{!!message&&<Text style={styles.notice}>{message}</Text>}<Pressable style={[styles.primary,busy&&styles.disabled]} disabled={busy} onPress={save}><Text style={styles.primaryText}>{busy?"SALVANDO...":"SALVAR NOVA SENHA"}</Text></Pressable><Pressable onPress={()=>setRecoveryOpen(false)}><Text style={styles.link}>Cancelar</Text></Pressable></View></SafeAreaView></Modal></View>;
}

export function PasswordResetLink({scheme}:{scheme:string}){
 const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function openRecovery(){setBusy(true);setMessage("");try{const url=`${RECOVERY_URL}?source=${encodeURIComponent(scheme)}`;const supported=await Linking.canOpenURL(url);if(!supported){setMessage("Não foi possível abrir a recuperação de senha neste aparelho.");return;}await Linking.openURL(url);}catch{setMessage("Não foi possível abrir a recuperação de senha. Verifique sua conexão.");}finally{setBusy(false);}}
 return <View><Pressable disabled={busy} onPress={openRecovery}><Text style={styles.link}>{busy?"ABRINDO RECUPERAÇÃO...":"Esqueci minha senha"}</Text></Pressable>{!!message&&<Text style={styles.notice}>{message}</Text>}</View>;
}

const deleteErrors:Record<string,string>={BUSINESS_ACCOUNT_TRANSFER_REQUIRED:"Esta conta está vinculada a uma loja. O acesso empresarial precisa ser transferido/removido antes da exclusão.",ACTIVE_ORDER_EXISTS:"Finalize ou cancele seu pedido em andamento antes de excluir a conta.",ACTIVE_DELIVERY_EXISTS:"Finalize a entrega em andamento antes de excluir a conta.",ACTIVE_PAYOUT_EXISTS:"Existe um repasse em processamento. Aguarde a conclusão antes de excluir a conta.",ADMIN_ACCOUNT_DELETE_REQUIRES_SUPPORT:"Contas administrativas não podem ser excluídas por este aplicativo."};
export function DeleteAccountButton(){
 const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function start(){setBusy(true);setMessage("");const pre=await supabase.functions.invoke("self-account-action",{body:{action:"PRECHECK"}});setBusy(false);const code=pre.data?.error;if(pre.error||code){setMessage(deleteErrors[code]??"Não foi possível validar a exclusão da conta agora.");return;}Alert.alert("Excluir conta definitivamente","Seus dados pessoais operacionais serão removidos ou anonimizados. Histórico financeiro necessário será preservado sem os dados pessoais que não forem necessários. Esta ação não pode ser desfeita.",[{text:"Cancelar",style:"cancel"},{text:"EXCLUIR",style:"destructive",onPress:remove}]);}
 async function remove(){setBusy(true);setMessage("");const result=await supabase.functions.invoke("self-account-action",{body:{action:"DELETE",confirmation:"EXCLUIR"}});const code=result.data?.error;if((result.error&&!result.data?.ok)||!result.data?.ok){setBusy(false);setMessage(deleteErrors[code]??"Não foi possível concluir a exclusão. Tente novamente ou fale com o suporte.");return;}await supabase.auth.signOut({scope:"local"});setBusy(false);Alert.alert("Conta excluída","Sua conta foi desativada e os dados pessoais foram removidos/anonimizados conforme aplicável.");}
 return <View style={styles.deleteBox}><Text style={styles.deleteTitle}>Excluir minha conta</Text><Text style={styles.deleteInfo}>Remove seu acesso e dados pessoais operacionais. Entregas e registros financeiros obrigatórios permanecem anonimizados.</Text>{!!message&&<Text style={styles.notice}>{message}</Text>}<Pressable style={[styles.deleteButton,busy&&styles.disabled]} disabled={busy} onPress={start}><Text style={styles.deleteText}>{busy?"AGUARDE...":"EXCLUIR CONTA"}</Text></Pressable></View>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f7f7"},modal:{flex:1,justifyContent:"center",padding:24},brand:{fontSize:24,fontWeight:"900"},yellow:{color:"#f4c400"},title:{fontSize:28,fontWeight:"900",marginTop:20,marginBottom:6},info:{color:"#666",lineHeight:18,marginBottom:12},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:13,marginBottom:9},primary:{backgroundColor:"#111",padding:14,borderRadius:12,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"900"},link:{textAlign:"center",color:"#8b7000",fontWeight:"800",padding:13},notice:{backgroundColor:"#fff4c6",color:"#665100",padding:10,borderRadius:10,marginBottom:9},disabled:{opacity:.5},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.45)",justifyContent:"center",padding:22},card:{backgroundColor:"#f7f7f7",borderRadius:18,padding:18},cardTitle:{fontSize:21,fontWeight:"900",marginBottom:7},deleteBox:{backgroundColor:"#fff",borderWidth:1,borderColor:"#f0caca",borderRadius:14,padding:14,marginTop:18},deleteTitle:{fontWeight:"900",color:"#9b1c1c",fontSize:15},deleteInfo:{fontSize:11,color:"#777",lineHeight:16,marginVertical:7},deleteButton:{borderWidth:1,borderColor:"#b42318",padding:12,borderRadius:11,alignItems:"center"},deleteText:{color:"#b42318",fontWeight:"900"}});
