import React, { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "./supabase";

type Ticket={id:string;category:string;priority:string;status:string;subject:string;created_at:string;updated_at:string};
type Message={id:string;sender_id:string;body:string;created_at:string};
const statusLabel:Record<string,string>={OPEN:"Aberto",IN_PROGRESS:"Em atendimento",WAITING_USER:"Aguardando você",RESOLVED:"Resolvido",CLOSED:"Fechado"};
const categories:Record<string,string>={DELIVERY_DRIVER:"Problema em entrega",DRIVER_PAYMENT:"Ganhos / repasse",DRIVER_ACCOUNT:"Cadastro / documentos",INCIDENT:"Incidente",OTHER:"Outro assunto"};

export default function DriverSupport(){
 const[tickets,setTickets]=useState<Ticket[]>([]);const[selected,setSelected]=useState<Ticket|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[category,setCategory]=useState("DELIVERY_DRIVER");const[subject,setSubject]=useState("");const[text,setText]=useState("");const[reply,setReply]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 useEffect(()=>{load();},[]);
 async function load(){const{data}=await supabase.from("support_tickets").select("id,category,priority,status,subject,created_at,updated_at").order("updated_at",{ascending:false}).limit(50);setTickets((data??[]) as Ticket[]);}
 async function openTicket(ticket:Ticket){setSelected(ticket);setNotice("");const{data}=await supabase.from("support_messages").select("id,sender_id,body,created_at").eq("ticket_id",ticket.id).order("created_at");setMessages((data??[]) as Message[]);}
 async function createTicket(){if(!subject.trim()||!text.trim()){setNotice("Informe assunto e descrição.");return;}setBusy(true);setNotice("");const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"CREATE",category,priority:category==="INCIDENT"?"CRITICAL":"NORMAL",subject:subject.trim(),message:text.trim()}});if(error||data?.error){setNotice("Não foi possível abrir o chamado.");setBusy(false);return;}setSubject("");setText("");setNotice("Chamado aberto para a equipe CLICK-FOOD.");await load();if(data?.ticket)await openTicket(data.ticket as Ticket);setBusy(false);}
 async function sendReply(){if(!selected||!reply.trim())return;setBusy(true);const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"REPLY",ticketId:selected.id,message:reply.trim()}});if(error||data?.error)setNotice("Não foi possível enviar a mensagem.");else{setReply("");await openTicket(selected);await load();}setBusy(false);}
 if(selected)return <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>{setSelected(null);setMessages([]);}}><Text style={styles.back}>‹ Voltar</Text></Pressable><Text style={styles.title}>{selected.subject}</Text><Text style={styles.meta}>{categories[selected.category]??selected.category} • {statusLabel[selected.status]??selected.status}</Text><View style={styles.chat}>{messages.map(m=><View key={m.id} style={styles.message}><Text style={styles.messageText}>{m.body}</Text><Text style={styles.time}>{new Date(m.created_at).toLocaleString("pt-BR")}</Text></View>)}</View>{!['RESOLVED','CLOSED'].includes(selected.status)&&<><TextInput style={[styles.input,styles.multiline]} multiline placeholder="Responder ao suporte" value={reply} onChangeText={setReply}/><Pressable style={[styles.primary,busy&&styles.disabled]} disabled={busy} onPress={sendReply}><Text style={styles.primaryText}>{busy?"ENVIANDO...":"ENVIAR"}</Text></Pressable></>}{!!notice&&<Text style={styles.notice}>{notice}</Text>}</ScrollView>;
 return <ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Suporte</Text><Text style={styles.subtitle}>Fale com a equipe sobre entregas, ganhos, cadastro ou incidentes.</Text>{!!notice&&<Text style={styles.notice}>{notice}</Text>}<View style={styles.card}><Text style={styles.cardTitle}>Novo chamado</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{Object.entries(categories).map(([value,label])=><Pressable key={value} style={[styles.chip,category===value&&styles.chipActive]} onPress={()=>setCategory(value)}><Text style={category===value?styles.chipTextActive:styles.chipText}>{label}</Text></Pressable>)}</ScrollView><TextInput style={styles.input} placeholder="Assunto" value={subject} onChangeText={setSubject}/><TextInput style={[styles.input,styles.multiline]} multiline placeholder="Descreva o que aconteceu. Se for uma entrega, informe o número do pedido." value={text} onChangeText={setText}/><Pressable style={[styles.primary,busy&&styles.disabled]} disabled={busy} onPress={createTicket}><Text style={styles.primaryText}>{busy?"ABRINDO...":"ABRIR CHAMADO"}</Text></Pressable></View><Text style={styles.section}>Meus chamados</Text>{tickets.map(t=><Pressable key={t.id} style={styles.ticket} onPress={()=>openTicket(t)}><View style={{flex:1}}><Text style={styles.ticketTitle}>{t.subject}</Text><Text style={styles.meta}>{categories[t.category]??t.category}</Text></View><Text style={styles.status}>{statusLabel[t.status]??t.status} ›</Text></Pressable>)}{!tickets.length&&<Text style={styles.empty}>Nenhum chamado.</Text>}</ScrollView>;
}

const styles=StyleSheet.create({wrap:{padding:18,paddingBottom:36},title:{fontSize:28,fontWeight:"900",color:"#111"},subtitle:{fontSize:12,color:"#666",marginTop:5,marginBottom:16},notice:{backgroundColor:"#fff4c6",color:"#6d5900",padding:12,borderRadius:12,marginVertical:10},card:{backgroundColor:"#fff",borderRadius:16,padding:14,borderWidth:1,borderColor:"#e6e6e6"},cardTitle:{fontSize:17,fontWeight:"900",marginBottom:10},chip:{borderWidth:1,borderColor:"#ddd",backgroundColor:"#fff",paddingVertical:9,paddingHorizontal:11,borderRadius:18,marginRight:7},chipActive:{backgroundColor:"#111",borderColor:"#111"},chipText:{fontSize:10,fontWeight:"800"},chipTextActive:{fontSize:10,fontWeight:"900",color:"#fff"},input:{backgroundColor:"#fafafa",borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:12,marginTop:10},multiline:{minHeight:92,textAlignVertical:"top"},primary:{backgroundColor:"#f4c400",padding:14,borderRadius:13,alignItems:"center",marginTop:10},primaryText:{fontWeight:"900"},disabled:{opacity:.5},section:{fontSize:19,fontWeight:"900",marginTop:22,marginBottom:10},ticket:{backgroundColor:"#fff",borderRadius:13,padding:13,borderWidth:1,borderColor:"#e6e6e6",marginBottom:8,flexDirection:"row",alignItems:"center",gap:8},ticketTitle:{fontSize:14,fontWeight:"900"},meta:{fontSize:10,color:"#777",marginTop:4},status:{fontSize:10,fontWeight:"900",color:"#806700"},empty:{textAlign:"center",color:"#777",padding:20},back:{fontWeight:"900",color:"#806700",marginBottom:18},chat:{marginTop:16},message:{backgroundColor:"#fff",borderRadius:12,padding:12,borderWidth:1,borderColor:"#e6e6e6",marginBottom:8},messageText:{fontSize:13,lineHeight:19},time:{fontSize:9,color:"#999",marginTop:6}});
