import React,{ReactNode,useEffect,useMemo,useState}from"react";
import{Modal,Platform,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import*as DocumentPicker from"expo-document-picker";
import type{Session}from"@supabase/supabase-js";
import{supabase}from"./supabase";

type Doc={id:string;document_type:string;file_path:string;status:string;rejection_reason:string|null;expires_at:string|null;created_at:string};
type Driver={id:string;status:string};
const labels:Record<string,string>={PROFILE_PHOTO:"Foto do perfil",IDENTITY:"Documento de identidade",CNH:"CNH",VEHICLE_DOCUMENT:"Documento do veículo"};
const statusText:Record<string,string>={PENDING:"Em análise",APPROVED:"Aprovado",REJECTED:"Recusado",EXPIRED:"Expirado"};
const topInset=Platform.OS==="android"?(StatusBar.currentHeight??24):0;
let externalOpen:(()=>void)|null=null;
export function openDriverDocuments(){externalOpen?.();}

export default function DriverDocumentsHost({children}:{children:ReactNode}){
 const[session,setSession]=useState<Session|null>(null);const[driver,setDriver]=useState<Driver|null>(null);const[vehicleType,setVehicleType]=useState<string|null>(null);const[docs,setDocs]=useState<Doc[]>([]);const[open,setOpen]=useState(false);const[uploading,setUploading]=useState("");const[notice,setNotice]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(session)void load();else{setDriver(null);setDocs([]);}},[session?.user.id]);
 useEffect(()=>{if(!session||driver)return;const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer);},[session?.user.id,driver?.id]);
 useEffect(()=>{externalOpen=()=>{setOpen(true);void load();};return()=>{externalOpen=null;};},[session?.user.id,driver?.id]);
 async function load(){if(!session)return;const{data:d}=await supabase.from("drivers").select("id,status").eq("user_id",session.user.id).maybeSingle();if(!d){setDriver(null);return;}setDriver(d as Driver);const[docsResult,vehicleResult]=await Promise.all([supabase.from("driver_documents").select("id,document_type,file_path,status,rejection_reason,expires_at,created_at").eq("driver_id",d.id).order("created_at",{ascending:false}),supabase.from("driver_vehicles").select("vehicle_type").eq("driver_id",d.id).eq("active",true).limit(1).maybeSingle()]);setDocs((docsResult.data??[]) as Doc[]);setVehicleType(vehicleResult.data?.vehicle_type??null);}
 const required=useMemo(()=>vehicleType==="BICYCLE"?["PROFILE_PHOTO","IDENTITY"]:["PROFILE_PHOTO","IDENTITY","CNH","VEHICLE_DOCUMENT"],[vehicleType]);
 const latest=useMemo(()=>{const map=new Map<string,Doc>();for(const doc of docs)if(!map.has(doc.document_type))map.set(doc.document_type,doc);return map;},[docs]);
 async function pick(type:string){if(!session||!driver)return;const existing=latest.get(type);if(existing?.status==="PENDING"){setNotice("Este documento já está em análise.");return;}setNotice("");setUploading(type);try{const result=await DocumentPicker.getDocumentAsync({type:type==="PROFILE_PHOTO"?["image/jpeg","image/png","image/webp"]:["image/jpeg","image/png","image/webp","application/pdf"],copyToCacheDirectory:true,multiple:false});if(result.canceled){setUploading("");return;}const asset=result.assets[0];if((asset.size??0)>10*1024*1024){setNotice("O arquivo deve ter no máximo 10 MB.");setUploading("");return;}const rawName=(asset.name||`${type}.jpg`).replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${session.user.id}/${type.toLowerCase()}/${Date.now()}-${rawName}`;const buffer=await fetch(asset.uri).then(r=>r.arrayBuffer());const{error:uploadError}=await supabase.storage.from("driver-documents").upload(path,buffer,{contentType:asset.mimeType||"application/octet-stream",upsert:false});if(uploadError){setNotice("Não foi possível enviar o arquivo.");setUploading("");return;}const{error:insertError}=await supabase.from("driver_documents").insert({driver_id:driver.id,document_type:type,file_path:path,status:"PENDING"});if(insertError){await supabase.storage.from("driver-documents").remove([path]);setNotice(insertError.message.includes("uq_driver_pending_doc_type")?"Já existe um documento deste tipo em análise.":"Não foi possível registrar o documento.");setUploading("");return;}setNotice(`${labels[type]??type} enviado para análise.`);await load();}catch{setNotice("Falha ao processar o arquivo.");}setUploading("");}
 async function openFile(doc:Doc){const{data,error}=await supabase.storage.from("driver-documents").createSignedUrl(doc.file_path,180);if(error||!data?.signedUrl){setNotice("Não foi possível abrir o arquivo.");return;}const Linking=await import("expo-linking");await Linking.openURL(data.signedUrl);}
 return <View style={{flex:1}}>{children}<Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={[styles.safe,{paddingTop:topInset}]}><StatusBar barStyle="dark-content" backgroundColor="#f7f7f7"/><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.brand}><Text style={styles.yellow}>CLICK</Text>-FOOD</Text><Text style={styles.subtitle}>DOCUMENTOS DO ENTREGADOR</Text></View><Pressable onPress={()=>setOpen(false)}><Text style={styles.close}>Fechar</Text></Pressable></View>{!driver?<View style={styles.rules}><Text style={styles.rulesTitle}>Cadastro ainda não localizado</Text><Text style={styles.meta}>Conclua o cadastro inicial do entregador para enviar os documentos obrigatórios.</Text></View>:<><Text style={styles.title}>Validação cadastral</Text><Text style={styles.info}>Seus arquivos são privados e só podem ser acessados por você e pela equipe autorizada da Matriz.</Text>{!!notice&&<Text style={styles.notice}>{notice}</Text>}{required.map(type=>{const doc=latest.get(type);const approved=doc?.status==="APPROVED";const rejected=doc?.status==="REJECTED";return <View style={styles.card} key={type}><View style={{flex:1}}><Text style={styles.cardTitle}>{labels[type]}</Text><Text style={[styles.status,approved&&styles.ok,rejected&&styles.bad]}>{doc?statusText[doc.status]??doc.status:"Não enviado"}</Text>{doc?.rejection_reason&&<Text style={styles.reason}>Motivo: {doc.rejection_reason}</Text>}{doc?.expires_at&&<Text style={styles.meta}>Validade: {new Date(`${doc.expires_at}T12:00:00`).toLocaleDateString("pt-BR")}</Text>}</View><View style={styles.actions}>{doc&&<Pressable style={styles.secondary} onPress={()=>void openFile(doc)}><Text style={styles.secondaryText}>VER</Text></Pressable>}{!approved&&doc?.status!=="PENDING"&&<Pressable style={styles.primary} disabled={!!uploading} onPress={()=>void pick(type)}><Text style={styles.primaryText}>{uploading===type?"ENVIANDO...":doc?"REENVIAR":"ENVIAR"}</Text></Pressable>}</View></View>})}<View style={styles.rules}><Text style={styles.rulesTitle}>Arquivos aceitos</Text><Text style={styles.meta}>Foto do perfil: JPG, PNG ou WEBP. Demais documentos: JPG, PNG, WEBP ou PDF • máximo de 10 MB por arquivo.</Text><Text style={styles.meta}>{vehicleType==="BICYCLE"?"Para bicicleta: foto e identidade.":"Para moto/carro: foto, identidade, CNH e documento do veículo."}</Text></View></>}</ScrollView></SafeAreaView></Modal></View>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f7f7"},content:{padding:18,paddingBottom:56},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},brand:{fontSize:24,fontWeight:"900"},yellow:{color:"#f4c400"},subtitle:{fontSize:10,fontWeight:"900",color:"#8b7000",marginTop:4},close:{fontWeight:"900",color:"#8b7000",padding:8},title:{fontSize:28,fontWeight:"900",marginTop:26},info:{color:"#666",lineHeight:19,marginTop:6,marginBottom:14},notice:{backgroundColor:"#fff3c2",padding:12,borderRadius:12,marginBottom:12,color:"#5d4b00",fontWeight:"700"},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e5e5e5",borderRadius:16,padding:14,marginBottom:10,flexDirection:"row",gap:10,alignItems:"center"},cardTitle:{fontWeight:"900",fontSize:15},status:{fontWeight:"800",color:"#936f00",marginTop:5},ok:{color:"#147a39"},bad:{color:"#b42318"},reason:{color:"#b42318",fontSize:11,marginTop:5},meta:{color:"#777",fontSize:11,marginTop:5},actions:{gap:6},primary:{backgroundColor:"#111",paddingHorizontal:12,paddingVertical:10,borderRadius:10},primaryText:{color:"#fff",fontSize:11,fontWeight:"900"},secondary:{backgroundColor:"#f4c400",paddingHorizontal:12,paddingVertical:10,borderRadius:10},secondaryText:{fontSize:11,fontWeight:"900"},rules:{backgroundColor:"#fff",borderRadius:14,padding:14,marginTop:18},rulesTitle:{fontWeight:"900"}});
