import React,{useEffect,useMemo,useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{supabase}from"./supabase";
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const day=(d:Date)=>d.toISOString().slice(0,10);const ago=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n+1);return day(d)};
type Props={onBack:()=>void};
export default function DriverReports({onBack}:Props){const[from,setFrom]=useState(ago(7));const[to,setTo]=useState(day(new Date()));const[data,setData]=useState<any>({metrics:{},deliveries:[]});const[loading,setLoading]=useState(false);const[msg,setMsg]=useState("");
 async function load(){setLoading(true);setMsg("");const end=new Date(`${to}T00:00:00`);end.setDate(end.getDate()+1);const{data:r,error}=await supabase.functions.invoke("driver-report-read",{body:{from:`${from}T00:00:00`,to:end.toISOString(),limit:150}});setLoading(false);if(error||r?.error){setMsg("Não foi possível carregar o relatório.");return;}setData(r??{});}useEffect(()=>{void load()},[]);const m=data.metrics??{};const title=useMemo(()=>`${from.split("-").reverse().join("/")} a ${to.split("-").reverse().join("/")}`,[from,to]);
 return <ScrollView contentContainerStyle={s.page}><View style={s.header}><View style={{flex:1}}><Text style={s.title}>Relatórios</Text><Text style={s.sub}>Ganhos e entregas por período • {title}</Text></View><Pressable style={s.back} onPress={onBack}><Text style={s.backText}>VOLTAR</Text></Pressable></View><View style={s.filters}><TextInput style={s.input} value={from} onChangeText={setFrom} placeholder="AAAA-MM-DD"/><TextInput style={s.input} value={to} onChangeText={setTo} placeholder="AAAA-MM-DD"/><Pressable style={s.filterButton} onPress={()=>void load()}><Text style={s.filterText}>{loading?"...":"FILTRAR"}</Text></Pressable></View><View style={s.quick}><Pressable style={s.quickBtn} onPress={()=>{setFrom(ago(7));setTo(day(new Date()))}}><Text style={s.quickText}>7 DIAS</Text></Pressable><Pressable style={s.quickBtn} onPress={()=>{setFrom(ago(30));setTo(day(new Date()))}}><Text style={s.quickText}>30 DIAS</Text></Pressable></View>{!!msg&&<Text style={s.notice}>{msg}</Text>}<View style={s.metrics}><Metric label="ENTREGAS" value={String(m.deliveries??0)}/><Metric label="GANHOS" value={brl(Number(m.earnings??0))}/><Metric label="MÉDIA / ENTREGA" value={brl(Number(m.averageEarning??0))}/><Metric label="TEMPO MÉDIO" value={Number(m.averageDurationMinutes)>0?`${Math.round(Number(m.averageDurationMinutes))} min`:"—"}/></View><Text style={s.section}>Entregas do período</Text>{(data.deliveries??[]).map((x:any)=><View style={s.row} key={x.id}><View style={{flex:1}}><Text style={s.rowTitle}>{x.orderNumber?`Pedido #${x.orderNumber} • `:""}{x.storeName}</Text><Text style={s.meta}>{x.deliveredAt?new Date(x.deliveredAt).toLocaleString("pt-BR"):"Concluída"}</Text></View><Text style={s.earning}>{brl(Number(x.driverEarning??0))}</Text></View>)}{!(data.deliveries??[]).length&&!loading&&<Text style={s.empty}>Nenhuma entrega neste período.</Text>}</ScrollView>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({page:{padding:16,paddingBottom:40,backgroundColor:"#f7f7f7",flexGrow:1},header:{flexDirection:"row",gap:10,alignItems:"flex-start",marginBottom:15},title:{fontSize:25,fontWeight:"900"},sub:{fontSize:11,color:"#777",marginTop:4},back:{borderWidth:1,borderColor:"#ddd",backgroundColor:"#fff",borderRadius:10,padding:9},backText:{fontSize:9,fontWeight:"900"},filters:{flexDirection:"row",gap:7},input:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:10,fontSize:11},filterButton:{backgroundColor:"#111",borderRadius:10,paddingHorizontal:13,justifyContent:"center"},filterText:{color:"#f4c400",fontSize:9,fontWeight:"900"},quick:{flexDirection:"row",gap:7,marginTop:7},quickBtn:{backgroundColor:"#fff",borderWidth:1,borderColor:"#ddd",borderRadius:9,paddingHorizontal:11,paddingVertical:7},quickText:{fontSize:9,fontWeight:"900"},notice:{backgroundColor:"#fff4bf",padding:10,borderRadius:10,marginTop:10,color:"#6b5600"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:14},metric:{width:"48%",backgroundColor:"#fff",borderRadius:14,padding:13,borderWidth:1,borderColor:"#e5e5e5"},metricLabel:{fontSize:8,fontWeight:"900",color:"#777"},metricValue:{fontSize:18,fontWeight:"900",marginTop:4},section:{fontSize:18,fontWeight:"900",marginTop:18,marginBottom:9},row:{backgroundColor:"#fff",borderRadius:13,padding:13,marginBottom:7,flexDirection:"row",gap:10,alignItems:"center"},rowTitle:{fontSize:13,fontWeight:"900"},meta:{fontSize:10,color:"#777",marginTop:3},earning:{color:"#17733a",fontWeight:"900"},empty:{textAlign:"center",padding:25,color:"#777"}});
