import React, { type ReactNode, useEffect, useState } from "react";
import { Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "./supabase";

type Payout={id:string;amount:number;method:string;status:string;destination_value:string|null;requested_at:string;processed_at:string|null;review_notes:string|null;provider_id:string|null};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const labels:Record<string,string>={REQUESTED:"Solicitado",APPROVED:"Aprovado",PROCESSING:"Processando",PAID:"Pago",FAILED:"Falhou",REJECTED:"Rejeitado",CANCELLED:"Cancelado"};

export default function DriverPayoutHost({children}:{children:ReactNode}){
 const[visible,setVisible]=useState(false);const[signedIn,setSignedIn]=useState(false);const[balance,setBalance]=useState(0);const[payouts,setPayouts]=useState<Payout[]>([]);const[amount,setAmount]=useState("");const[pixKey,setPixKey]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSignedIn(!!data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(!!s));return()=>data.subscription.unsubscribe();},[]);
 async function load(){setNotice("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"DRIVER_SUMMARY"}});if(error||data?.error){setNotice("Não foi possível carregar seu saldo agora.");return;}setBalance(Number(data.availableBalance??0));setPayouts((data.payouts??[]) as Payout[]);}
 async function open(){setVisible(true);await load();}
 async function request(){const value=Number(amount.replace(",","."));if(!Number.isFinite(value)||value<=0){setNotice("Informe um valor válido.");return;}if(!pixKey.trim()){setNotice("Informe a chave PIX que receberá o repasse.");return;}setBusy(true);setNotice("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"DRIVER_REQUEST",amount:value,method:"PIX",destinationValue:pixKey.trim()}});if(error||data?.error){setNotice(data?.error==="INSUFFICIENT_AVAILABLE_BALANCE"?"O valor solicitado é maior que seu saldo disponível.":"Não foi possível solicitar o repasse.");setBusy(false);return;}setAmount("");setNotice("Repasse solicitado. O valor já ficou reservado e aparecerá na fila financeira da Matriz.");await load();setBusy(false);}
 async function cancel(p:Payout){setBusy(true);setNotice("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"DRIVER_CANCEL",payoutId:p.id}});setNotice(error||data?.error?"Não foi possível cancelar este repasse.":"Repasse cancelado e saldo liberado novamente.");await load();setBusy(false);}
 return <View style={styles.root}>{children}{signedIn&&<Pressable accessibilityRole="button" accessibilityLabel="Abrir carteira de repasses" style={styles.fab} onPress={open}><Text style={styles.fabText}>R$</Text></Pressable>}<Modal visible={visible} animationType="slide" onRequestClose={()=>setVisible(false)}><SafeAreaView style={styles.safe}><View style={styles.top}><Text style={styles.brand}><Text style={styles.yellow}>CLICK</Text>-FOOD • CARTEIRA</Text><Pressable style={styles.close} onPress={()=>setVisible(false)}><Text style={styles.closeText}>FECHAR</Text></Pressable></View><ScrollView contentContainerStyle={styles.wrap} keyboardShouldPersistTaps="handled"><View style={styles.balance}><Text style={styles.balanceLabel}>SALDO DISPONÍVEL PARA REPASSE</Text><Text style={styles.balanceValue}>{brl(balance)}</Text><Text style={styles.balanceHint}>Solicitações pendentes já são descontadas deste saldo para evitar repasse em duplicidade.</Text></View>{!!notice&&<Text style={styles.notice}>{notice}</Text>}<View style={styles.card}><Text style={styles.title}>Solicitar repasse PIX</Text><TextInput style={styles.input} placeholder="Valor, ex.: 150,00" keyboardType="decimal-pad" value={amount} onChangeText={setAmount}/><TextInput style={styles.input} placeholder="Chave PIX (CPF, e-mail, telefone ou aleatória)" autoCapitalize="none" value={pixKey} onChangeText={setPixKey}/><Pressable style={[styles.primary,busy&&styles.disabled]} disabled={busy||balance<=0} onPress={request}><Text style={styles.primaryText}>{busy?"PROCESSANDO...":"SOLICITAR REPASSE"}</Text></Pressable><Text style={styles.hint}>O pedido entra na fila financeira da Matriz. Marcar como pago exige confirmação administrativa/comprovante até que o envio bancário automático seja habilitado.</Text></View><Text style={styles.section}>Histórico de repasses</Text>{payouts.map(p=><View key={p.id} style={styles.row}><View style={{flex:1}}><Text style={styles.rowValue}>{brl(p.amount)}</Text><Text style={styles.meta}>PIX • {new Date(p.requested_at).toLocaleString("pt-BR")}{p.review_notes?` • ${p.review_notes}`:""}</Text></View><View style={{alignItems:"flex-end"}}><Text style={[styles.status,p.status==="PAID"&&styles.paid,p.status==="FAILED"&&styles.failed]}>{labels[p.status]??p.status}</Text>{["REQUESTED","FAILED"].includes(p.status)&&<Pressable disabled={busy} onPress={()=>cancel(p)}><Text style={styles.cancel}>Cancelar</Text></Pressable>}</View></View>)}{!payouts.length&&<Text style={styles.empty}>Nenhum repasse solicitado ainda.</Text>}</ScrollView></SafeAreaView></Modal></View>;
}

const styles=StyleSheet.create({root:{flex:1},fab:{position:"absolute",left:14,bottom:82,minWidth:50,height:48,borderRadius:24,backgroundColor:"#111",alignItems:"center",justifyContent:"center",paddingHorizontal:10,elevation:8},fabText:{color:"#f4c400",fontWeight:"900",fontSize:13},safe:{flex:1,backgroundColor:"#f6f6f6"},top:{height:58,backgroundColor:"#fff",borderBottomWidth:1,borderBottomColor:"#e5e5e5",paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},brand:{fontSize:15,fontWeight:"900"},yellow:{color:"#d4a900"},close:{backgroundColor:"#111",paddingVertical:8,paddingHorizontal:11,borderRadius:9},closeText:{color:"#fff",fontSize:10,fontWeight:"900"},wrap:{padding:18,paddingBottom:40},balance:{backgroundColor:"#111",borderRadius:20,padding:20},balanceLabel:{color:"#aaa",fontSize:10,fontWeight:"900",letterSpacing:1},balanceValue:{color:"#fff",fontSize:34,fontWeight:"900",marginTop:6},balanceHint:{color:"#aaa",fontSize:10,lineHeight:15,marginTop:8},notice:{backgroundColor:"#fff4c6",color:"#6d5900",padding:12,borderRadius:12,marginTop:12},card:{backgroundColor:"#fff",borderRadius:16,padding:14,borderWidth:1,borderColor:"#e6e6e6",marginTop:14},title:{fontSize:18,fontWeight:"900",marginBottom:3},input:{backgroundColor:"#fafafa",borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:12,marginTop:10},primary:{backgroundColor:"#f4c400",padding:14,borderRadius:13,alignItems:"center",marginTop:10},primaryText:{fontWeight:"900"},disabled:{opacity:.5},hint:{fontSize:9,color:"#777",lineHeight:14,marginTop:10},section:{fontSize:19,fontWeight:"900",marginTop:22,marginBottom:10},row:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e7e7e7",borderRadius:13,padding:13,marginBottom:8,flexDirection:"row",alignItems:"center",gap:8},rowValue:{fontSize:16,fontWeight:"900"},meta:{fontSize:9,color:"#777",marginTop:4},status:{fontSize:10,fontWeight:"900",color:"#856c00"},paid:{color:"#1f7a45"},failed:{color:"#a52d2d"},cancel:{fontSize:10,fontWeight:"900",color:"#9b2c2c",marginTop:7},empty:{textAlign:"center",color:"#777",padding:20}});
