import React,{ReactNode,useEffect,useRef,useState}from"react";
import{KeyboardAvoidingView,Modal,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import type{Session}from"@supabase/supabase-js";
import{supabase}from"./supabase";

type ChatType="STORE_DRIVER"|"CUSTOMER_DRIVER";type Msg={id:string;sender_id:string;content:string;created_at:string};
export default function OrderChatHost({children}:{children:ReactNode}){
 const[session,setSession]=useState<Session|null>(null);const[open,setOpen]=useState(false);const[orderId,setOrderId]=useState<string|null>(null);const[orderNumber,setOrderNumber]=useState<number|null>(null);const[type,setType]=useState<ChatType>("STORE_DRIVER");const[conversationId,setConversationId]=useState<string|null>(null);const[messages,setMessages]=useState<Msg[]>([]);const[text,setText]=useState("");const[notice,setNotice]=useState("");const[sending,setSending]=useState(false);const scroll=useRef<ScrollView>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
 async function findOrder(){if(!session)return null;const{data,error}=await supabase.functions.invoke("driver-active-delivery",{body:{}});if(error||!data?.delivery){setOrderId(null);setOrderNumber(null);return null;}setOrderId(data.delivery.orderId);setOrderNumber(Number(data.delivery.orderNumber));return{id:data.delivery.orderId,order_number:data.delivery.orderNumber};}
 async function openChat(nextType:ChatType=type){setNotice("");const order=orderId?{id:orderId,order_number:orderNumber}:await findOrder();if(!order){setNotice("Você não tem entrega ativa para conversar agora.");setOpen(true);return;}setType(nextType);const{data,error}=await supabase.functions.invoke("order-chat",{body:{orderId:order.id,type:nextType}});if(error||data?.error){setConversationId(null);setMessages([]);setNotice(data?.error==="CUSTOMER_NOT_AVAILABLE"?"Este pedido não possui cliente no aplicativo.":"Não foi possível abrir esta conversa.");setOpen(true);return;}setConversationId(data.conversation.id);setOpen(true);await loadMessages(data.conversation.id);}
 async function loadMessages(id=conversationId){if(!id)return;const{data}=await supabase.from("messages").select("id,sender_id,content,created_at").eq("conversation_id",id).order("created_at",{ascending:true}).limit(200);setMessages((data??[]) as Msg[]);setTimeout(()=>scroll.current?.scrollToEnd({animated:false}),30);}
 useEffect(()=>{if(!conversationId)return;const channel=supabase.channel(`driver-chat-${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>{const row=payload.new as Msg;setMessages(current=>current.some(m=>m.id===row.id)?current:[...current,row]);setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),40);}).subscribe();return()=>{supabase.removeChannel(channel);};},[conversationId]);
 async function send(){const content=text.trim();if(!content||!conversationId)return;setSending(true);setNotice("");const{data,error}=await supabase.functions.invoke("send-message",{body:{conversationId,content}});if(error||data?.error){setNotice(data?.error==="CONTACT_SHARING_BLOCKED"?"Por segurança, telefone, e-mail, links e redes sociais não podem ser enviados.":"Não foi possível enviar a mensagem.");setSending(false);return;}setText("");setSending(false);}
 return <View style={{flex:1}}>{children}{session&&<Pressable style={styles.fab} onPress={()=>openChat()}><Text style={styles.fabIcon}>✉</Text><Text style={styles.fabText}>Chat</Text></Pressable>}<Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={styles.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><View style={styles.header}><View><Text style={styles.brand}><Text style={styles.yellow}>CLICK</Text>-FOOD</Text><Text style={styles.sub}>CHAT DA ENTREGA {orderNumber?`#${orderNumber}`:""}</Text></View><Pressable onPress={()=>setOpen(false)}><Text style={styles.close}>Fechar</Text></Pressable></View><View style={styles.tabs}><Pressable style={[styles.tab,type==="STORE_DRIVER"&&styles.tabActive]} onPress={()=>openChat("STORE_DRIVER")}><Text style={type==="STORE_DRIVER"?styles.tabActiveText:styles.tabText}>Loja</Text></Pressable><Pressable style={[styles.tab,type==="CUSTOMER_DRIVER"&&styles.tabActive]} onPress={()=>openChat("CUSTOMER_DRIVER")}><Text style={type==="CUSTOMER_DRIVER"?styles.tabActiveText:styles.tabText}>Cliente</Text></Pressable></View>{!!notice&&<Text style={styles.notice}>{notice}</Text>}<ScrollView ref={scroll} style={styles.messages} contentContainerStyle={{padding:14,gap:8}}>{messages.map(m=>{const mine=m.sender_id===session?.user.id;return <View key={m.id} style={[styles.bubble,mine?styles.mine:styles.theirs]}><Text style={mine?styles.mineText:styles.theirText}>{m.content}</Text><Text style={[styles.time,mine&&{color:"#bbb"}]}>{new Date(m.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</Text></View>})}{conversationId&&!messages.length&&<Text style={styles.empty}>Envie uma mensagem. Por segurança, mantenha todo o contato dentro do CLICK-FOOD.</Text>}</ScrollView><View style={styles.composer}><TextInput style={styles.input} placeholder="Digite sua mensagem" value={text} onChangeText={setText} multiline maxLength={2000}/><Pressable style={[styles.send,(!text.trim()||sending)&&styles.disabled]} disabled={!text.trim()||sending} onPress={send}><Text style={styles.sendText}>{sending?"...":"ENVIAR"}</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView></Modal></View>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f7f7"},header:{padding:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:"#e6e6e6"},brand:{fontSize:22,fontWeight:"900"},yellow:{color:"#f4c400"},sub:{fontSize:10,fontWeight:"900",color:"#777",marginTop:4},close:{fontWeight:"900",color:"#8b7000",padding:8},tabs:{padding:10,flexDirection:"row",gap:8},tab:{flex:1,padding:12,alignItems:"center",backgroundColor:"#eee",borderRadius:12},tabActive:{backgroundColor:"#111"},tabText:{fontWeight:"900"},tabActiveText:{fontWeight:"900",color:"#f4c400"},notice:{marginHorizontal:12,backgroundColor:"#fff2bd",color:"#5d4b00",padding:10,borderRadius:10,fontWeight:"700"},messages:{flex:1},bubble:{maxWidth:"82%",paddingHorizontal:12,paddingVertical:9,borderRadius:14},mine:{alignSelf:"flex-end",backgroundColor:"#111"},theirs:{alignSelf:"flex-start",backgroundColor:"#fff",borderWidth:1,borderColor:"#e4e4e4"},mineText:{color:"#fff"},theirText:{color:"#222"},time:{fontSize:9,color:"#888",marginTop:4,alignSelf:"flex-end"},empty:{textAlign:"center",color:"#777",marginTop:40,lineHeight:19},composer:{padding:10,flexDirection:"row",alignItems:"flex-end",gap:8,borderTopWidth:1,borderColor:"#ddd",backgroundColor:"#fff"},input:{flex:1,maxHeight:110,borderWidth:1,borderColor:"#ddd",borderRadius:14,padding:11,backgroundColor:"#fafafa"},send:{backgroundColor:"#f4c400",paddingHorizontal:15,paddingVertical:13,borderRadius:12},sendText:{fontWeight:"900",fontSize:11},disabled:{opacity:.45},fab:{position:"absolute",left:14,bottom:126,backgroundColor:"#111",borderRadius:24,paddingHorizontal:15,paddingVertical:11,flexDirection:"row",alignItems:"center",gap:7,elevation:5,shadowColor:"#000",shadowOpacity:.18,shadowRadius:6},fabIcon:{color:"#f4c400",fontSize:16,fontWeight:"900"},fabText:{color:"#fff",fontSize:11,fontWeight:"900"}});
