"use client";

import { FormEvent,useEffect,useState } from "react";
import { supabase } from "../../lib/supabase";

type LegalDoc={id:string;document_type:string;audience:string;version:string;title:string;content:string;active:boolean;published_at:string|null;created_at:string;updated_at:string};
const typeLabel:Record<string,string>={TERMS:"Termos de Uso",PRIVACY:"Política de Privacidade",DRIVER_TERMS:"Termos do Entregador",STORE_TERMS:"Termos da Loja"};
const audienceLabel:Record<string,string>={ALL:"Todos",CUSTOMER:"Cliente",DRIVER:"Entregador",STORE:"Loja"};
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";

export default function LegalAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[canWrite,setCanWrite]=useState(false);const[message,setMessage]=useState("");const[docs,setDocs]=useState<LegalDoc[]>([]);const[saving,setSaving]=useState(false);
 const[form,setForm]=useState({documentType:"TERMS",audience:"CUSTOMER",version:"1.0",title:"Termos de Uso",content:""});
 async function load(){const{data,error}=await supabase.functions.invoke("admin-legal-documents",{body:{action:"LIST"}});if(!error&&!data?.error)setDocs((data?.documents??[]) as LegalDoc[]);}
 async function boot(){setLoading(true);const{data}=await supabase.auth.getSession();const role=String(data.session?.user.app_metadata?.clickfood_role??"");const ok=Boolean(data.session)&&["SUPER_ADMIN","ADMIN","SUPPORT"].includes(role);setAuthorized(ok);setCanWrite(["SUPER_ADMIN","ADMIN"].includes(role));if(ok)await load();setLoading(false);}
 useEffect(()=>{boot();},[]);
 async function create(e:FormEvent){e.preventDefault();if(!canWrite)return;if(form.content.trim().length<20){setMessage("Insira o texto aprovado antes de salvar a versão.");return;}setSaving(true);setMessage("");const{data,error}=await supabase.functions.invoke("admin-legal-documents",{body:{action:"CREATE",...form}});if(error||data?.error){setMessage(data?.error==="LEGAL_VERSION_EXISTS"?"Esta versão já existe para esse documento e público.":"Não foi possível criar o documento.");}else{setMessage("Rascunho criado. Revise antes de publicar.");setForm({...form,content:""});await load();}setSaving(false);}
 async function publish(id:string){if(!canWrite)return;if(!confirm("Publicar esta versão? A versão publicada ficará imutável e passará a exigir novo aceite do público correspondente."))return;setMessage("");const{data,error}=await supabase.functions.invoke("admin-legal-documents",{body:{action:"PUBLISH",id}});setMessage(error||data?.error?"Não foi possível publicar esta versão.":"Versão publicada. Os apps passarão a exigir o aceite desta versão.");await load();}
 async function archive(id:string){if(!canWrite)return;if(!confirm("Arquivar esta versão ativa? Enquanto não houver outra ativa, esse documento deixa de ser exigido."))return;const{data,error}=await supabase.functions.invoke("admin-legal-documents",{body:{action:"ARCHIVE",id}});setMessage(error||data?.error?"Não foi possível arquivar.":"Versão arquivada.");await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando documentos legais...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Somente a equipe autorizada da Matriz pode consultar esta área.</p></div></main>;
 return <main className="adminPage"><section className="adminHeader"><div><small>GOVERNANÇA</small><h1>Termos & Privacidade</h1><p>Versione os documentos do CLICK-FOOD e registre novo aceite sempre que uma versão for publicada.</p></div></section>{message&&<div className="adminNotice">{message}</div>}
  <section className="adminGrid2"><article className="adminPanel"><div className="panelTitle"><div><small>NOVA VERSÃO</small><h2>Criar rascunho</h2></div></div>{canWrite?<form className="adminForm" onSubmit={create}><label>Documento<select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value,title:typeLabel[e.target.value]??form.title})}><option value="TERMS">Termos de Uso</option><option value="PRIVACY">Política de Privacidade</option><option value="DRIVER_TERMS">Termos do Entregador</option><option value="STORE_TERMS">Termos da Loja</option></select></label><label>Público<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="CUSTOMER">Cliente</option><option value="DRIVER">Entregador</option><option value="STORE">Loja</option><option value="ALL">Todos</option></select></label><label>Versão<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})} placeholder="Ex.: 1.0"/></label><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Texto aprovado<textarea rows={18} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Cole aqui o texto revisado/aprovado. A Matriz só deve publicar a versão final."/></label><div className="muted">Salvar cria somente um rascunho. O app não exige aceite até você clicar em PUBLICAR.</div><button className="primaryAction" disabled={saving}>{saving?"SALVANDO...":"SALVAR RASCUNHO"}</button></form>:<p className="muted">Perfil de suporte: leitura permitida, publicação bloqueada.</p>}</article>
  <article className="adminPanel"><div className="panelTitle"><div><small>REGRAS</small><h2>Controle de versão</h2></div></div><div className="adminList"><div><div><b>Publicado = imutável</b><small>Uma versão aceita por usuários nunca é editada por cima.</small></div><span>✓</span></div><div><div><b>Nova versão = novo aceite</b><small>Ao publicar uma nova versão para o mesmo público, a anterior é desativada.</small></div><span>↻</span></div><div><div><b>Sem texto inventado</b><small>O sistema não publica conteúdo automaticamente; a Matriz insere o texto aprovado.</small></div><span>▣</span></div></div></article></section>
  <section className="adminPanel"><div className="panelTitle"><div><small>VERSÕES</small><h2>Documentos cadastrados</h2></div><span>{docs.length}</span></div><div className="adminList">{docs.map(doc=><div key={doc.id} style={{alignItems:"flex-start"}}><div style={{flex:1}}><b>{doc.title} • v{doc.version}</b><small>{typeLabel[doc.document_type]??doc.document_type} • {audienceLabel[doc.audience]??doc.audience} • {doc.active?`PUBLICADO ${dt(doc.published_at)}`:"RASCUNHO/ARQUIVADO"}</small><details style={{marginTop:8}}><summary>Visualizar texto</summary><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:12,lineHeight:1.5}}>{doc.content}</pre></details></div>{canWrite&&<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{!doc.active&&<button className="primaryAction" onClick={()=>publish(doc.id)}>PUBLICAR</button>}{doc.active&&<button className="dangerAction" onClick={()=>archive(doc.id)}>ARQUIVAR</button>}</div>}</div>)}{!docs.length&&<p className="muted">Nenhuma versão cadastrada. Os apps não exigem aceite enquanto não houver documento ativo.</p>}</div></section>
 </main>;
}
