"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Broadcast={id:string;audience:string;store_id:string|null;user_id:string|null;title:string;body:string;recipient_count:number;status:string;created_at:string;stores?:{name:string}|{name:string}[]|null};
type Store={id:string;name:string};
const dt=(v:string)=>new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});const rel=(v:any)=>Array.isArray(v)?v[0]:v;
const audienceLabel:Record<string,string>={CUSTOMERS:"Clientes com pedidos",DRIVERS:"Entregadores ativos",STORE_USERS:"Todos os usuários de lojas",STORE:"Uma loja específica",USER:"Usuário específico"};

export default function NotificationsAdmin(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[stores,setStores]=useState<Store[]>([]);const[history,setHistory]=useState<Broadcast[]>([]);const[sending,setSending]=useState(false);const[form,setForm]=useState({audience:"CUSTOMERS",storeId:"",userId:"",title:"",body:""});
 async function load(){const[sR,hR]=await Promise.all([supabase.from("stores").select("id,name").order("name"),supabase.from("notification_broadcasts").select("id,audience,store_id,user_id,title,body,recipient_count,status,created_at,stores(name)").order("created_at",{ascending:false}).limit(100)]);if(sR.data)setStores(sR.data as Store[]);if(hR.data)setHistory(hR.data as any);}
 async function boot(){setLoading(true);const{data}=await supabase.auth.getSession();const role=String(data.session?.user.app_metadata?.clickfood_role??"");const ok=Boolean(data.session)&&["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(ok)await load();setLoading(false);}
 useEffect(()=>{boot();},[]);
 async function send(e:FormEvent){e.preventDefault();if(!form.title.trim()||!form.body.trim()){setMessage("Informe título e mensagem.");return;}if(form.audience==="STORE"&&!form.storeId){setMessage("Selecione a loja destinatária.");return;}if(form.audience==="USER"&&!form.userId.trim()){setMessage("Informe o ID do usuário.");return;}setSending(true);setMessage("");const{data,error}=await supabase.functions.invoke("admin-notifications",{body:{action:"SEND",audience:form.audience,storeId:form.audience==="STORE"?form.storeId:undefined,userId:form.audience==="USER"?form.userId.trim():undefined,title:form.title.trim(),body:form.body.trim()}});if(error||data?.error)setMessage("Não foi possível enviar a notificação.");else{setMessage(`Notificação enviada para ${Number(data.recipientCount)} destinatário(s).`);setForm({...form,title:"",body:""});await load();}setSending(false);}
 if(loading)return <main className="authPage"><div className="authCard">Carregando notificações...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Somente administradores da Matriz podem disparar notificações.</p></div></main>;
 return <main className="adminPage"><section className="adminHeader"><div><small>COMUNICAÇÃO</small><h1>Central de notificações</h1><p>Dispare avisos operacionais e comunicados internos para públicos do CLICK-FOOD.</p></div></section>{message&&<div className="adminNotice">{message}</div>}
  <section className="adminGrid2"><article className="adminPanel"><div className="panelTitle"><div><small>NOVA NOTIFICAÇÃO</small><h2>Enviar comunicado</h2></div></div><form onSubmit={send} className="adminForm"><label>Público<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value,storeId:"",userId:""})}><option value="CUSTOMERS">Clientes com pedidos</option><option value="DRIVERS">Entregadores ativos</option><option value="STORE_USERS">Todos os usuários de lojas</option><option value="STORE">Uma loja específica</option><option value="USER">Usuário específico</option></select></label>{form.audience==="STORE"&&<label>Loja<select value={form.storeId} onChange={e=>setForm({...form,storeId:e.target.value})}><option value="">Selecione</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{form.audience==="USER"&&<label>ID do usuário<input value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})} placeholder="UUID do usuário"/></label>}<label>Título<input maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Atualização importante"/></label><label>Mensagem<textarea maxLength={500} rows={6} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Escreva a mensagem que aparecerá no centro de notificações."/></label><div className="muted">Entrega atual: notificação interna no CLICK-FOOD. O histórico fica auditado na Matriz.</div><button className="primaryAction" disabled={sending}>{sending?"ENVIANDO...":"ENVIAR NOTIFICAÇÃO"}</button></form></article>
  <article className="adminPanel"><div className="panelTitle"><div><small>CONTROLE</small><h2>Como será distribuída</h2></div></div><div className="adminList"><div><div><b>Clientes</b><small>Clientes que já possuem pedidos registrados.</small></div><span>👤</span></div><div><div><b>Entregadores</b><small>Somente entregadores com cadastro ativo.</small></div><span>🛵</span></div><div><div><b>Usuários das lojas</b><small>Proprietários e equipes vinculadas às lojas.</small></div><span>🏪</span></div></div><p className="muted">Push remoto será conectado aos mesmos registros quando os tokens dos dispositivos forem ativados nos apps móveis; esta tela já deixa o conteúdo e os destinatários prontos.</p></article></section>
  <section className="adminPanel"><div className="panelTitle"><div><small>HISTÓRICO</small><h2>Últimos disparos</h2></div><span>{history.length}</span></div><div className="adminList">{history.map(h=><div key={h.id}><div><b>{h.title}</b><small>{audienceLabel[h.audience]??h.audience}{rel(h.stores)?.name?` • ${rel(h.stores).name}`:""} • {h.recipient_count} destinatário(s) • {dt(h.created_at)}</small><p style={{margin:"6px 0 0",fontSize:12}}>{h.body}</p></div><span>{h.status==="SENT"?"✓":"!"}</span></div>)}{!history.length&&<p className="muted">Nenhuma notificação disparada pela Matriz ainda.</p>}</div></section>
 </main>;
}
