import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")?.trim() ?? "";
const PUBLIC_KEY = Deno.env.get("SUPABASE_ANON_KEY")?.trim() ?? "";

function page(functionUrl: string) {
  const recoveryUrl = JSON.stringify(functionUrl);
  const supabaseUrl = JSON.stringify(SUPABASE_URL);
  const publicKey = JSON.stringify(PUBLIC_KEY);
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Cache-Control" content="no-store"><title>Recuperar senha | CLICK-FOOD</title>
<style>*{box-sizing:border-box}body{margin:0;background:#0a0a0a;color:#111;font-family:Arial,sans-serif;min-height:100vh;display:grid;place-items:center;padding:20px}.card{width:100%;max-width:470px;background:#fff;border-radius:22px;padding:32px;box-shadow:0 24px 80px rgba(0,0,0,.4)}.brand{font-size:29px;font-weight:900}.brand span{color:#f5b800}.badge{display:inline-block;margin-top:14px;padding:7px 10px;border-radius:999px;background:#fff4bf;color:#6d5200;font-size:11px;font-weight:800}h1{font-size:28px;margin:20px 0 8px}.lead{color:#555;line-height:1.55;margin:0 0 22px}form{display:grid;gap:16px}label{display:grid;gap:8px;font-size:14px;font-weight:700}input{width:100%;border:1px solid #d7d7d7;border-radius:12px;padding:14px 15px;font-size:16px}button,.button{border:0;border-radius:12px;padding:15px 18px;background:#f5b800;color:#111;font-weight:900;cursor:pointer;text-align:center;text-decoration:none;font-size:14px}.secondary{background:#151515;color:#fff}.msg{border-radius:12px;padding:13px;background:#fff4e5;color:#7a4300;line-height:1.4}.ok{background:#e9f8ed;color:#176b2c}.hidden{display:none}.small{font-size:12px;color:#777;line-height:1.5;margin-top:18px}.links{display:grid;gap:10px;margin-top:18px}</style></head>
<body><main class="card"><div class="brand"><span>CLICK</span>-FOOD</div><div class="badge">RECUPERAÇÃO SEGURA</div>
<section id="requestView"><h1>Recuperar senha</h1><p class="lead">Informe o e-mail da sua conta para receber um link seguro e criar uma nova senha.</p><form id="requestForm"><label>E-mail<input id="email" type="email" autocomplete="email" required placeholder="seuemail@exemplo.com"></label><div id="requestMsg" class="msg hidden"></div><button id="requestButton" type="submit">ENVIAR LINK DE RECUPERAÇÃO</button></form><p class="small">Use sempre o e-mail mais recente. Links de recuperação são de uso único.</p></section>
<section id="resetView" class="hidden"><h1>Criar nova senha</h1><p class="lead">Digite e confirme sua nova senha CLICK-FOOD.</p><form id="resetForm"><label>Nova senha<input id="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirmar nova senha<input id="confirmPassword" type="password" minlength="8" autocomplete="new-password" required></label><div id="resetMsg" class="msg hidden"></div><button id="resetButton" type="submit">ALTERAR SENHA</button></form></section>
<section id="errorView" class="hidden"><h1>Link inválido ou expirado</h1><div class="msg">Este link não pode mais ser usado. Solicite um novo e-mail de recuperação.</div><div class="links"><a class="button" href="${functionUrl}">SOLICITAR NOVO LINK</a></div></section>
<section id="successView" class="hidden"><h1>Senha alterada</h1><div class="msg ok">Sua senha foi alterada com sucesso. Volte ao aplicativo ou painel CLICK-FOOD e entre com a nova senha.</div><div class="links"><a class="button secondary" href="${functionUrl}">VOLTAR À RECUPERAÇÃO</a></div></section>
</main><script>
const SUPABASE_URL=${supabaseUrl};const API_KEY=${publicKey};const RECOVERY_URL=${recoveryUrl};
const hash=new URLSearchParams(location.hash.replace(/^#/,''));const query=new URLSearchParams(location.search);const accessToken=hash.get('access_token');const tokenType=hash.get('type');const authError=hash.get('error')||query.get('error');const authErrorDescription=hash.get('error_description')||query.get('error_description');
const requestView=document.getElementById('requestView'),resetView=document.getElementById('resetView'),errorView=document.getElementById('errorView'),successView=document.getElementById('successView');
function show(el){[requestView,resetView,errorView,successView].forEach(v=>v.classList.add('hidden'));el.classList.remove('hidden')}function msg(el,text,ok=false){el.textContent=text;el.classList.remove('hidden');el.classList.toggle('ok',ok)}
if(authError||authErrorDescription)show(errorView);else if(accessToken&&(!tokenType||tokenType==='recovery'))show(resetView);else show(requestView);
document.getElementById('requestForm').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('email').value.trim(),button=document.getElementById('requestButton'),output=document.getElementById('requestMsg');button.disabled=true;button.textContent='ENVIANDO...';output.classList.add('hidden');try{const res=await fetch(SUPABASE_URL+'/auth/v1/recover?redirect_to='+encodeURIComponent(RECOVERY_URL),{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json'},body:JSON.stringify({email})});if(res.ok){msg(output,'Link enviado. Abra o e-mail mais recente e toque em Redefinir senha.',true);button.classList.add('hidden')}else if(res.status===429)msg(output,'Muitas solicitações em sequência. Aguarde alguns segundos e tente novamente.');else msg(output,'Não foi possível enviar o link. Confira o e-mail e tente novamente.')}catch{msg(output,'Falha de conexão. Verifique sua internet e tente novamente.')}finally{button.disabled=false;button.textContent='ENVIAR LINK DE RECUPERAÇÃO'}});
document.getElementById('resetForm').addEventListener('submit',async e=>{e.preventDefault();const password=document.getElementById('password').value,confirm=document.getElementById('confirmPassword').value,button=document.getElementById('resetButton'),output=document.getElementById('resetMsg');output.classList.add('hidden');if(password.length<8){msg(output,'A nova senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){msg(output,'As duas senhas não são iguais.');return}if(!accessToken){show(errorView);return}button.disabled=true;button.textContent='SALVANDO...';try{const res=await fetch(SUPABASE_URL+'/auth/v1/user',{method:'PUT',headers:{apikey:API_KEY,Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify({password})});if(res.ok){history.replaceState(null,'',RECOVERY_URL);show(successView)}else msg(output,'Não foi possível alterar a senha. Solicite um novo link e tente novamente.')}catch{msg(output,'Falha de conexão. Verifique sua internet e tente novamente.')}finally{button.disabled=false;button.textContent='ALTERAR SENHA'}});
</script></body></html>`;
}

Deno.serve((req: Request) => {
  if (req.method !== "GET") return new Response("Method not allowed", { status: 405 });
  if (!SUPABASE_URL || !PUBLIC_KEY) return new Response("Configuração de autenticação indisponível", { status: 503 });
  const url = new URL(req.url);url.search="";url.hash="";
  return new Response(page(url.toString()), { status: 200, headers: { "content-type":"text/html; charset=utf-8", "cache-control":"no-store, max-age=0", "x-content-type-options":"nosniff", "referrer-policy":"no-referrer", "content-security-policy":"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src https://*.supabase.co; base-uri 'none'; frame-ancestors 'none'" } });
});
