import { withSupabase } from "npm:@supabase/server@1.4.1";
type Body={action:"LIST"|"SAVE"|"DELETE"|"SET_DEFAULT";paymentToken?:string;cardMask?:string;brand?:string;holderName?:string;holderDocument?:string;email?:string;phone?:string;makeDefault?:boolean;cardId?:string};
export default{fetch:withSupabase({auth:"user"},async(req,ctx)=>{
 if(req.method!=="POST")return Response.json({error:"METHOD_NOT_ALLOWED"},{status:405});let body:Body;try{body=await req.json()}catch{return Response.json({error:"INVALID_JSON"},{status:400})}const userId=ctx.userClaims!.id;
 if(body.action==="LIST"){const{data,error}=await ctx.supabaseAdmin.from("customer_saved_cards").select("id,provider,brand,card_mask,holder_name,is_default,created_at").eq("user_id",userId).eq("active",true).order("is_default",{ascending:false}).order("created_at",{ascending:false});if(error)return Response.json({error:"SAVED_CARD_LIST_FAILED"},{status:500});return Response.json({cards:data??[]});}
 if(body.action==="SAVE"){const paymentToken=String(body.paymentToken??""),cardMask=String(body.cardMask??"").trim(),brand=String(body.brand??"").toLowerCase(),holderName=String(body.holderName??"").trim().slice(0,120),holderDocument=String(body.holderDocument??"").replace(/\D/g,""),email=String(body.email??"").trim().slice(0,200),phone=String(body.phone??"").replace(/\D/g,"");if(paymentToken.length<10||paymentToken.length>1000||cardMask.length<4||cardMask.length>40||!["visa","mastercard","amex","elo"].includes(brand)||holderDocument.length!==11||!email.includes("@")||phone.length<10||phone.length>13)return Response.json({error:"INVALID_SAVED_CARD"},{status:400});const{data,error}=await ctx.supabaseAdmin.rpc("save_customer_saved_card_v2_atomic",{p_user_id:userId,p_payment_token:paymentToken,p_card_mask:cardMask,p_brand:brand,p_holder_name:holderName||null,p_holder_document:holderDocument,p_customer_email:email,p_customer_phone:phone,p_make_default:Boolean(body.makeDefault)});if(error)return Response.json({error:"SAVED_CARD_SAVE_FAILED"},{status:500});const card=Array.isArray(data)?data[0]:data;if(!card)return Response.json({error:"SAVED_CARD_SAVE_FAILED"},{status:500});return Response.json({card},{status:201});}
 if(body.action==="DELETE"){const cardId=String(body.cardId??"");if(!cardId)return Response.json({error:"CARD_ID_REQUIRED"},{status:400});const{error}=await ctx.supabaseAdmin.rpc("delete_customer_saved_card_atomic",{p_user_id:userId,p_card_id:cardId});if(error)return Response.json({error:error.message?.includes("CARD_NOT_FOUND")?"CARD_NOT_FOUND":"SAVED_CARD_DELETE_FAILED"},{status:error.message?.includes("CARD_NOT_FOUND")?404:500});return Response.json({ok:true});}
 if(body.action==="SET_DEFAULT"){const cardId=String(body.cardId??"");if(!cardId)return Response.json({error:"CARD_ID_REQUIRED"},{status:400});const{error}=await ctx.supabaseAdmin.rpc("set_default_customer_saved_card_atomic",{p_user_id:userId,p_card_id:cardId});if(error)return Response.json({error:error.message?.includes("CARD_NOT_FOUND")?"CARD_NOT_FOUND":"SAVED_CARD_DEFAULT_FAILED"},{status:error.message?.includes("CARD_NOT_FOUND")?404:500});return Response.json({ok:true});}
 return Response.json({error:"UNKNOWN_ACTION"},{status:400});
})};