"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Order={id:string;order_number:number;total:number;status:string;source:string;delivery_type:string;created_at:string};type Product={id:string;name:string;price:number};type Finance={id:string;transaction_type:string;direction:string;amount:number;status:string;created_at:string};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
function download(name:string,rows:string[][]){const csv=rows.map(row=>row.map(cell=>`"${String(cell??"").replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export default function Relatorios(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[orders,setOrders]=useState<Order[]>([]);const[products,setProducts]=useState<Product[]>([]);const[finance,setFinance]=useState<Finance[]>([]);const[notice,setNotice]=useState("");
 async function boot(){const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre no Painel do Lojista primeiro.");setLoading(false);return;}const{data:m}=await supabase.from("store_memberships").select("store_id,stores!inner(name)").eq("user_id",s.session.user.id).eq("active",true).limit(1);if(!m?.length){setNotice("Conta sem loja vinculada.");setLoading(false);return;}const row:any=m[0],rel=Array.isArray(row.stores)?row.stores[0]:row.stores;setStoreId(row.store_id);setStoreName(rel?.name??"Minha loja");const[o,p,f]=await Promise.all([supabase.from("orders").select("id,order_number,total,status,source,delivery_type,created_at").eq("store_id",row.store_id).order("created_at",{ascending:false}).limit(1000),supabase.from("products").select("id,name,price").eq("store_id",row.store_id).order("name"),supabase.from("financial_transactions").select("id,transaction_type,direction,amount,status,created_at").eq("store_id",row.store_id).order("created_at",{ascending:false}).limit(1000)]);setOrders((o.data??[]).map((x:any)=>({...x,total:Number(x.total)})));setProducts((p.data??[]).map((x:any)=>({...x,price:Number(x.price)})));setFinance((f.data??[]).map((x:any)=>({...x,amount:Number(x.amount)})));setLoading(false);}
 useEffect(()=>{boot();},[]);
 const metrics=useMemo(()=>{const completed=orders.filter(o=>o.status==="DELIVERED"||o.source==="POS");const sales=completed.reduce((s,o)=>s+o.total,0);return{sales,count:orders.length,completed:completed.length,average:completed.length?sales/completed.length:0,pos:orders.filter(o=>o.source==="POS").length,delivery:orders.filter(o=>o.source!=="POS").length,cancelled:orders.filter(o=>["CANCELLED","REJECTED"].includes(o.status)).length}},[orders]);
 if(loading)return <main className="configPage"><div className="configShell">Carregando relatórios...</div></main>;
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>{storeName}</small><h1>Relatórios</h1></div><a className="backLink" href="/">← Voltar ao painel</a></header>{notice&&<div className="setupMessage">{notice}</div>}<div className="kpis"><article><span>Faturamento registrado</span><b>{brl(metrics.sales)}</b></article><article><span>Pedidos</span><b>{metrics.count}</b></article><article><span>Ticket médio</span><b>{brl(metrics.average)}</b></article><article><span>Cancelados</span><b>{metrics.cancelled}</b></article></div><div className="managementGrid"><article className="mgCard"><h2>Pedidos</h2><p>{metrics.completed} concluídos • {metrics.delivery} delivery • {metrics.pos} PDV</p><button className="setupPrimary" onClick={()=>download(`pedidos-${storeId}.csv`,[["Pedido","Total","Status","Origem","Tipo","Data"],...orders.map(o=>[String(o.order_number),String(o.total),o.status,o.source,o.delivery_type,o.created_at])])}>EXPORTAR PEDIDOS CSV</button></article><article className="mgCard"><h2>Financeiro</h2><p>{finance.length} lançamentos no ledger.</p><button className="setupPrimary" onClick={()=>download(`financeiro-${storeId}.csv`,[["Tipo","Direção","Valor","Status","Data"],...finance.map(f=>[f.transaction_type,f.direction,String(f.amount),f.status,f.created_at])])}>EXPORTAR FINANCEIRO CSV</button></article><article className="mgCard"><h2>Produtos</h2><p>{products.length} produtos cadastrados.</p><button className="setupPrimary" onClick={()=>download(`produtos-${storeId}.csv`,[["Produto","Preço"],...products.map(p=>[p.name,String(p.price)])])}>EXPORTAR PRODUTOS CSV</button></article></div><section className="mgCard"><h2>Pedidos recentes</h2><div className="dataList">{orders.slice(0,50).map(o=><div className="dataRow" key={o.id}><div><b>#{o.order_number}</b><small>{o.source} • {o.delivery_type} • {new Date(o.created_at).toLocaleString("pt-BR")}</small></div><div><b>{brl(o.total)}</b><small>{o.status}</small></div></div>)}{!orders.length&&<div className="emptyRow">Nenhum pedido para relatório.</div>}</div></section></div></main>;
}
