"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Provider={id:string;provider:string;display_name:string;environment:"SANDBOX"|"PRODUCTION";enabled:boolean;credentials_configured:boolean;supported_methods:string[];notes:string|null;updated_at:string};
type RefundView={id:string;payment_id:string;order_id:string;order_number:number;store_name:string;amount:number;reason:string;status:string;provider_refund_id:string|null;created_at:string;completed_at:string|null;payment_status:string;method:string};
const methods=["PIX","CREDIT_CARD","DEBIT_CARD"] as const;
const labels:Record<string,string>={PIX:"PIX",CREDIT_CARD:"Cartão de crédito",DEBIT_CARD:"Cartão de débito"};
const refundLabels:Record<string,string>={PENDING:"Solicitado",PROCESSING:"Em processamento",COMPLETED:"Devolvido",FAILED:"Falhou",CANCELLED:"Cancelado"};
const brl=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
const dateTime=(value:string)=>new Date(value).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});

function efiErrorMessage(code:string,status?:number){
 if(code.startsWith("MISSING_SECRET_"))return `Falta um Secret no Supabase: ${code.replace("MISSING_SECRET_","")}.`;
 if(code==="INVALID_SECRET_EFI_PIX_CERT_B64"||code==="EFI_MTLS_CERT_INVALID")return "O certificado Efí em B64 está inválido.";
 if(code==="INVALID_SECRET_EFI_PIX_KEY_B64"||code==="EFI_MTLS_KEY_INVALID")return "A chave privada Efí em B64 está inválida.";
 if(code==="EFI_MTLS_PAIR_INVALID"||code==="EFI_MTLS_CONNECTION_FAILED")return "O certificado e a chave privada não formaram uma conexão mTLS válida com a Efí.";
 if(code.startsWith("EFI_OAUTH_"))return `A Efí recusou a autenticação OAuth (${code.replace("EFI_OAUTH_","")}). Confira Client ID e Client Secret do ambiente.`;
 if(code==="EFI_WEBHOOK_SETUP_FAILED")return `A autenticação passou, mas a Efí recusou o cadastro do webhook${status?` (HTTP ${status})`:""}.`;
 if(code==="EFI_WEBHOOK_NETWORK_FAILED")return "A autenticação passou, mas houve falha de rede ao registrar o webhook na Efí.";
 return `A Efí não pôde ser validada. Diagnóstico: ${code||"EFI_SETUP_FAILED"}.`;
}
function cardErrorMessage(code:string,status?:number){
 if(code==="EFI_ACCOUNT_ID_REQUIRED")return "Falta somente o Identificador de Conta da Efí (EFI_ACCOUNT_ID). O PIX continua ativo e não foi alterado.";
 if(code==="EFI_CHARGES_OAUTH_401")return "A API de Cobranças recusou estas credenciais. Confirme que a aplicação CLICK-FOOD também está habilitada para API de Emissão de cobranças em Homologação.";
 if(code==="EFI_CHARGES_API_SCOPE_REQUIRED")return "As credenciais autenticaram, mas a API de Emissão de cobranças não está liberada para esta aplicação.";
 if(code==="EFI_CHARGES_API_VALIDATION_FAILED")return `Não foi possível validar a API de Emissão${status?` (HTTP ${status})`:""}.`;
 return `Cartão Efí ainda não pôde ser ativado. Diagnóstico: ${code||"EFI_CARD_SETUP_FAILED"}.`;
}

export default function PaymentsPage(){
 const[allowed,setAllowed]=useState<boolean|null>(null);const[providers,setProviders]=useState<Provider[]>([]);const[refunds,setRefunds]=useState<RefundView[]>([]);const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);const[validatingEfi,setValidatingEfi]=useState(false);const[validatingCard,setValidatingCard]=useState(false);const[refundBusy,setRefundBusy]=useState<string|null>(null);const[externalBusy,setExternalBusy]=useState(false);const[externalResult,setExternalResult]=useState<any|null>(null);
 const[form,setForm]=useState({provider:"",displayName:"",environment:"SANDBOX" as "SANDBOX"|"PRODUCTION",supportedMethods:["PIX"] as string[],notes:"",credentialsConfigured:false,enabled:false});
 async function loadRefunds(){
  const{data:refundRows,error}=await supabase.from("refunds").select("id,payment_id,amount,reason,status,provider_refund_id,created_at,completed_at").order("created_at",{ascending:false}).limit(100);
  if(error||!refundRows?.length){setRefunds([]);return;}
  const paymentIds=refundRows.map((row:any)=>String(row.payment_id));
  const{data:payments}=await supabase.from("payments").select("id,order_id,status,provider,method").in("id",paymentIds);
  const efiPayments=(payments??[]).filter((p:any)=>p.provider==="EFI"&&["PIX","CREDIT_CARD"].includes(String(p.method)));
  const paymentMap=new Map(efiPayments.map((p:any)=>[String(p.id),p]));
  const orderIds=[...new Set(efiPayments.map((p:any)=>String(p.order_id)))];
  const{data:orders}=orderIds.length?await supabase.from("orders").select("id,order_number,store_id").in("id",orderIds):{data:[] as any[]};
  const orderMap=new Map((orders??[]).map((o:any)=>[String(o.id),o]));
  const storeIds=[...new Set((orders??[]).map((o:any)=>String(o.store_id)))];
  const{data:stores}=storeIds.length?await supabase.from("stores").select("id,name").in("id",storeIds):{data:[] as any[]};
  const storeMap=new Map((stores??[]).map((s:any)=>[String(s.id),String(s.name)]));
  const rows:RefundView[]=[];
  for(const raw of refundRows as any[]){const payment:any=paymentMap.get(String(raw.payment_id));if(!payment)continue;const order:any=orderMap.get(String(payment.order_id));if(!order)continue;rows.push({id:String(raw.id),payment_id:String(raw.payment_id),order_id:String(order.id),order_number:Number(order.order_number),store_name:storeMap.get(String(order.store_id))??"Loja",amount:Number(raw.amount),reason:String(raw.reason??""),status:String(raw.status),provider_refund_id:raw.provider_refund_id?String(raw.provider_refund_id):null,created_at:String(raw.created_at),completed_at:raw.completed_at?String(raw.completed_at):null,payment_status:String(payment.status),method:String(payment.method)});}
  setRefunds(rows);
 }
 async function load(){const{data:{session}}=await supabase.auth.getSession();const role=String(session?.user.app_metadata?.clickfood_role??"");const ok=!!session&&["SUPER_ADMIN","ADMIN"].includes(role);setAllowed(ok);if(!ok)return;const{data,error}=await supabase.functions.invoke("admin-payment-config",{body:{action:"LIST"}});if(error||data?.error){setMessage("Não foi possível carregar a configuração de pagamentos.");return;}setProviders(data.providers??[]);await loadRefunds();}
 useEffect(()=>{load();},[]);
 function toggleMethod(method:string){setForm({...form,supportedMethods:form.supportedMethods.includes(method)?form.supportedMethods.filter(x=>x!==method):[...form.supportedMethods,method]});}
 async function save(e:FormEvent){e.preventDefault();if(form.provider==="EFI"){setMessage("A Efí não pode ser ativada manualmente. Use os fluxos seguros de validação PIX/cartão desta página.");return;}setSaving(true);setMessage("");const{data,error}=await supabase.functions.invoke("admin-payment-config",{body:{action:"UPSERT",provider:form.provider,displayName:form.displayName,environment:form.environment,supportedMethods:form.supportedMethods,notes:form.notes,credentialsConfigured:form.credentialsConfigured,enabled:form.enabled}});if(error||data?.error){setMessage("Não foi possível salvar o provedor.");setSaving(false);return;}setMessage(data.warning==="CREDENTIALS_REQUIRED_TO_ENABLE"?"Configuração salva, mas o provedor ficou desativado porque as credenciais reais ainda não foram instaladas no backend.":"Configuração do provedor salva.");setForm({provider:"",displayName:"",environment:"SANDBOX",supportedMethods:["PIX"],notes:"",credentialsConfigured:false,enabled:false});await load();setSaving(false);}
 function edit(p:Provider){if(p.provider==="EFI"){setMessage("A Efí é gerenciada pelos fluxos seguros PIX/cartão desta página.");return;}setForm({provider:p.provider,displayName:p.display_name,environment:p.environment,supportedMethods:p.supported_methods??[],notes:p.notes??"",credentialsConfigured:p.credentials_configured,enabled:p.enabled});window.scrollTo({top:0,behavior:"smooth"});}
 async function setupEfi(){setValidatingEfi(true);setMessage("");const{data,error}=await supabase.functions.invoke("efi-pix-setup",{body:{}});if(error||data?.error||data?.ok===false){setMessage(efiErrorMessage(String(data?.error??"EFI_SETUP_FAILED"),Number(data?.providerStatus)||undefined));setValidatingEfi(false);return;}setMessage(`Efí PIX validada e webhook registrado com sucesso em ${data.environment==="PRODUCTION"?"PRODUÇÃO":"HOMOLOGAÇÃO"}.`);await load();setValidatingEfi(false);}
 async function validateExternalEfi(){setExternalBusy(true);setExternalResult(null);setMessage("");const{data,error}=await supabase.functions.invoke("efi-external-validation",{body:{}});if(error||data?.ok===false){setMessage(`Validação externa Efí falhou${data?.stage?` na etapa ${data.stage}`:""}${data?.providerStatus?` (HTTP ${data.providerStatus})`:""}. Diagnóstico: ${data?.error??"EFI_EXTERNAL_VALIDATION_FAILED"}.`);setExternalBusy(false);return;}setExternalResult(data);setMessage(`Validação externa Efí concluída com sucesso em ${data.environment==="PRODUCTION"?"PRODUÇÃO":"HOMOLOGAÇÃO"}. OAuth, webhook, cobrança, consulta e QR Code responderam corretamente.`);setExternalBusy(false);}
 async function setupCard(){setValidatingCard(true);setMessage("");const{data,error}=await supabase.functions.invoke("efi-card-setup",{body:{}});if(error||data?.error||data?.ok===false){setMessage(cardErrorMessage(String(data?.error??"EFI_CARD_SETUP_FAILED"),Number(data?.providerStatus)||undefined));setValidatingCard(false);return;}setMessage(`Cartão Efí validado em ${data.environment==="PRODUCTION"?"PRODUÇÃO":"HOMOLOGAÇÃO"}. O App Cliente poderá tokenizar cartões sem enviar número/CVV ao CLICK-FOOD.`);await load();setValidatingCard(false);}
 async function reconcileRefund(refund:RefundView){setRefundBusy(refund.id);setMessage("");const fn=refund.method==="CREDIT_CARD"?"efi-card-status":"efi-pix-refund";const body=refund.method==="CREDIT_CARD"?{orderId:refund.order_id}:{orderId:refund.order_id,reason:`Reconciliação pela Matriz do estorno ${refund.id}`};const{data,error}=await supabase.functions.invoke(fn,{body});if(error||data?.error)setMessage("Não foi possível reconciliar este estorno agora.");else if(refund.method==="CREDIT_CARD")setMessage(data?.refunded?"Estorno do cartão confirmado pela Efí.":"Cartão consultado. O estorno ainda está em processamento.");else setMessage(String(data?.refundStatus)==="COMPLETED"?"Estorno PIX confirmado como devolvido pela Efí.":String(data?.refundStatus)==="FAILED"?"A devolução PIX falhou e pode ser tentada novamente.":"Estorno PIX consultado. A devolução continua em processamento.");await loadRefunds();setRefundBusy(null);}
 const efi=providers.find(p=>p.provider==="EFI");const cardActive=!!efi?.supported_methods?.includes("CREDIT_CARD");
 if(allowed===null)return <main className="adminPage"><div className="adminPanel">Carregando...</div></main>;
 if(!allowed)return <main className="adminPage"><div className="adminPanel"><h1>Acesso restrito</h1><p>Entre na Matriz com perfil Super Admin ou Admin.</p></div></main>;
 return <main className="adminPage">
  <header className="adminHeader"><div><small>FINANCEIRO</small><h1>Pagamentos online</h1><p>Efí com validação real no backend. PIX e cartão são liberados separadamente.</p></div><a className="adminLink" href="/">← Matriz</a></header>
  {message&&<div className="adminNotice">{message}</div>}
  <section className="adminPanel" style={{marginBottom:18}}><h2>PIX • Efí Bank</h2><p className="muted">O PIX permanece com OAuth + mTLS e webhook já configurados. As credenciais ficam somente nos Secrets do Supabase.</p><div className="adminList"><div><div><b>{efi?.enabled?"PIX EFÍ ATIVO":"PIX EFÍ AGUARDANDO CONFIGURAÇÃO"}</b><small>{efi?.environment??"SANDBOX"} • {efi?.credentials_configured?"credenciais validadas":"credenciais ainda não validadas"}</small></div></div></div><div style={{marginTop:14}}><b>Secrets PIX</b><p className="muted">EFI_PIX_CLIENT_ID • EFI_PIX_CLIENT_SECRET • EFI_PIX_CERT_B64 • EFI_PIX_KEY_B64 • EFI_PIX_KEY • EFI_PIX_SANDBOX • EFI_WEBHOOK_HMAC</p></div><button className="primaryAction" onClick={setupEfi} disabled={validatingEfi}>{validatingEfi?"VALIDANDO NA EFÍ...":efi?.enabled?"REVALIDAR PIX E WEBHOOK":"VALIDAR E ATIVAR PIX"}</button><button style={{marginLeft:10}} onClick={validateExternalEfi} disabled={externalBusy}>{externalBusy?"TESTANDO NA EFÍ...":"VALIDAÇÃO EXTERNA EFÍ"}</button>{externalResult&&<div className="adminList" style={{marginTop:14}}><div><div><b>Teste externo aprovado</b><small>OAuth: OK • Webhook: {externalResult.webhookRegistered?"OK":"FALHOU"} • Cobrança: {externalResult.chargeCreated?"OK":"FALHOU"} • Consulta: {externalResult.chargeConsulted?"OK":"FALHOU"} • QR Code: {externalResult.qrCodeGenerated?"OK":"FALHOU"}</small><small>Status da cobrança: {externalResult.chargeStatus||"-"} • txid de teste: {externalResult.txid||"-"} • expira em {externalResult.expiresInSeconds||120}s</small></div></div></div>}</section>
  <section className="adminPanel" style={{marginBottom:18}}><h2>Cartão de crédito • Efí Bank</h2><p className="muted">Checkout transparente seguro: número do cartão e CVV ficam dentro da biblioteca oficial da Efí no WebView; o CLICK-FOOD recebe somente o payment_token e a máscara.</p><div className="adminList"><div><div><b>{cardActive?"CARTÃO EFÍ ATIVO":"CARTÃO EFÍ AGUARDANDO VALIDAÇÃO"}</b><small>{efi?.environment??"SANDBOX"} • API de Emissão de cobranças + tokenização</small></div></div></div><div style={{marginTop:14}}><b>Configuração adicional</b><p className="muted">EFI_ACCOUNT_ID (Identificador de Conta da Efí). As mesmas credenciais da aplicação CLICK-FOOD são reutilizadas quando a API de Emissão estiver habilitada; credenciais específicas de Cobranças também são aceitas opcionalmente no backend.</p></div><button className="primaryAction" onClick={setupCard} disabled={validatingCard}>{validatingCard?"VALIDANDO CARTÃO...":cardActive?"REVALIDAR CARTÃO EFÍ":"VALIDAR E ATIVAR CARTÃO"}</button><p className="muted">O cartão só aparece no App Cliente após esta validação passar. O PIX não é desativado se a validação de cartão falhar.</p></section>
  <section className="adminPanel" style={{marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h2>Estornos Efí</h2><p className="muted">PIX e cartão, com reconciliação sem duplicar devoluções.</p></div><button onClick={loadRefunds}>Atualizar</button></div><div className="adminList">{refunds.map(r=><div key={r.id}><div><b>Pedido #{r.order_number} • {r.store_name}</b><small>{labels[r.method]??r.method} • {brl(r.amount)} • {refundLabels[r.status]??r.status} • {dateTime(r.created_at)}</small><small>{r.reason||"Sem motivo informado"}{r.completed_at?` • concluído ${dateTime(r.completed_at)}`:""}</small></div>{["PENDING","PROCESSING","FAILED"].includes(r.status)&&<button onClick={()=>reconcileRefund(r)} disabled={refundBusy===r.id}>{refundBusy===r.id?"Consultando...":"Atualizar estorno"}</button>}</div>)}{!refunds.length&&<p className="muted">Nenhum estorno Efí registrado até agora.</p>}</div></section>
  <div className="adminGrid2"><form className="adminPanel adminForm" onSubmit={save}><h2>Outros provedores</h2><label>Código do provedor<input placeholder="Ex.: MERCADO_PAGO, ASAAS" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"_")})} required/></label><label>Nome exibido<input placeholder="Nome do gateway" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} required/></label><label>Ambiente<select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value as "SANDBOX"|"PRODUCTION"})}><option value="SANDBOX">Sandbox / testes</option><option value="PRODUCTION">Produção</option></select></label><div><b>Métodos aceitos</b>{methods.map(m=><label key={m} style={{display:"flex",gridTemplateColumns:"auto 1fr",alignItems:"center"}}><input style={{width:"auto"}} type="checkbox" checked={form.supportedMethods.includes(m)} onChange={()=>toggleMethod(m)}/>{labels[m]}</label>)}</div><label><span>Credenciais instaladas no backend</span><select value={form.credentialsConfigured?"YES":"NO"} onChange={e=>setForm({...form,credentialsConfigured:e.target.value==="YES"})}><option value="NO">Não</option><option value="YES">Sim</option></select></label><label><span>Status desejado</span><select value={form.enabled?"ON":"OFF"} onChange={e=>setForm({...form,enabled:e.target.value==="ON"})}><option value="OFF">Desativado</option><option value="ON">Ativado</option></select></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Anotações operacionais, sem chaves ou senhas."/></label><button className="primaryAction" disabled={saving}>{saving?"SALVANDO...":"SALVAR CONFIGURAÇÃO"}</button></form><section className="adminPanel"><h2>Provedores cadastrados</h2><div className="adminList">{providers.map(p=><div key={p.id}><div><b>{p.display_name}</b><small>{p.provider} • {p.environment} • {(p.supported_methods??[]).map(x=>labels[x]??x).join(" / ")||"sem método"}</small><small>{p.credentials_configured?"Credenciais validadas":"Credenciais pendentes"} • {p.enabled?"ATIVO":"DESATIVADO"}</small></div>{p.provider!=="EFI"&&<button onClick={()=>edit(p)}>Editar</button>}</div>)}{!providers.length&&<p className="muted">Nenhum gateway configurado. Dinheiro permanece disponível.</p>}</div></section></div>
 </main>;
}
