"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Store={id:string;name:string;status:string};
type Product={id:string;store_id:string;name:string;description:string|null;image_url:string|null;price:number;promotional_price:number|null;active:boolean;available_delivery:boolean;available_pos:boolean;control_inventory:boolean};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);

export default function CatalogosPage(){
 const[loading,setLoading]=useState(true);const[stores,setStores]=useState<Store[]>([]);const[products,setProducts]=useState<Product[]>([]);const[storeId,setStoreId]=useState("");const[query,setQuery]=useState("");const[notice,setNotice]=useState("");
 const storeMap=useMemo(()=>new Map(stores.map(s=>[s.id,s])),[stores]);
 const filtered=useMemo(()=>products.filter(p=>(!storeId||p.store_id===storeId)&&(`${p.name} ${p.description??""} ${storeMap.get(p.store_id)?.name??""}`).toLowerCase().includes(query.toLowerCase())),[products,storeId,query,storeMap]);
 const withoutImage=products.filter(p=>!p.image_url).length;const active=products.filter(p=>p.active).length;const delivery=products.filter(p=>p.active&&p.available_delivery).length;
 async function load(){setLoading(true);setNotice("");const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre no Painel Matriz para consultar os catálogos.");setLoading(false);return;}const[storesR,productsR]=await Promise.all([supabase.from("stores").select("id,name,status").order("name"),supabase.from("products").select("id,store_id,name,description,image_url,price,promotional_price,active,available_delivery,available_pos,control_inventory").order("created_at",{ascending:false}).limit(2000)]);if(storesR.error||productsR.error){setNotice("Não foi possível carregar os catálogos. Confirme que sua conta possui acesso administrativo.");setLoading(false);return;}setStores((storesR.data??[]) as Store[]);setProducts((productsR.data??[]).map((p:any)=>({...p,price:Number(p.price),promotional_price:p.promotional_price==null?null:Number(p.promotional_price)})) as Product[]);setLoading(false);}
 useEffect(()=>{void load();},[]);
 if(loading)return <main className="adminPage"><div className="adminShell">Carregando catálogos...</div></main>;
 return <main className="adminPage"><div className="adminShell"><header className="adminHeader"><div><div className="brand"><span>CLICK</span>-FOOD</div><small>MATRIZ • QUALIDADE DO CARDÁPIO</small><h1>Catálogos dos restaurantes</h1><p>Auditoria visual dos produtos publicados no ecossistema.</p></div><button className="primary" onClick={()=>void load()}>Atualizar</button></header>{notice&&<div className="notice">{notice}</div>}
 <div className="metricGrid"><article className="metric"><p>Restaurantes</p><strong>{stores.length}</strong></article><article className="metric"><p>Produtos</p><strong>{products.length}</strong></article><article className="metric"><p>Ativos no Delivery</p><strong>{delivery}</strong></article><article className="metric"><p>Produtos sem foto</p><strong>{withoutImage}</strong></article></div>
 <section className="panel adminStandalonePanel"><div className="panelTitle"><div><h2>Auditoria do catálogo</h2><small>{active} produtos ativos • fotos ajudam conversão e confiança do cliente.</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><select value={storeId} onChange={e=>setStoreId(e.target.value)} style={{padding:"10px 12px",border:"1px solid #ddd",borderRadius:10}}><option value="">Todos os restaurantes</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name} • {s.status}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto ou loja" style={{padding:"10px 12px",border:"1px solid #ddd",borderRadius:10,minWidth:240}}/></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}>{filtered.map(p=><article key={p.id} style={{border:"1px solid #e5e7eb",borderRadius:16,overflow:"hidden",background:"#fff"}}><div style={{height:150,background:"#f3f4f6",position:"relative"}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{height:"100%",display:"grid",placeItems:"center",textAlign:"center",color:"#7b8190"}}><div><div style={{fontSize:34}}>📷</div><b>SEM FOTO</b></div></div>}<span style={{position:"absolute",top:9,right:9,padding:"5px 8px",borderRadius:999,fontSize:9,fontWeight:900,background:p.active?"#e7f7ec":"#eef0f3",color:p.active?"#17733c":"#646a74"}}>{p.active?"ATIVO":"PAUSADO"}</span></div><div style={{padding:13}}><small style={{color:"#8b7100",fontWeight:800}}>{storeMap.get(p.store_id)?.name??"Restaurante"}</small><h3 style={{margin:"5px 0"}}>{p.name}</h3><p style={{margin:"0 0 9px",fontSize:11,color:"#777",minHeight:30}}>{p.description||"Sem descrição"}</p><div>{p.promotional_price!=null&&<small style={{textDecoration:"line-through",marginRight:6}}>{brl(p.price)}</small>}<b>{brl(p.promotional_price??p.price)}</b></div><div style={{fontSize:10,color:"#777",marginTop:9}}>{p.available_delivery?"Delivery":""}{p.available_delivery&&p.available_pos?" + ":""}{p.available_pos?"PDV":""}{p.control_inventory?" • estoque controlado":""}</div></div></article>)}{!filtered.length&&<div className="emptyState">Nenhum produto encontrado com os filtros atuais.</div>}</div></section></div></main>;
}
