"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type StoreAccess={id:string;name:string;role:string};
type Category={id:string;name:string;active:boolean};
type Product={id:string;name:string;description:string|null;image_url:string|null;price:number;promotional_price:number|null;active:boolean;category_id:string|null;available_pos:boolean;control_inventory:boolean};
type Inventory={product_id:string;quantity:number;minimum_quantity:number};
type CashSession={id:string;opening_balance:number;opened_at:string;status:string};
type CartItem=Product&{quantity:number};
type PaymentMethod="CASH"|"PIX"|"CREDIT_CARD"|"DEBIT_CARD";
type PosPayment={method:PaymentMethod;amount:string};

const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string)=>new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});
const methodLabel:Record<PaymentMethod,string>={CASH:"Dinheiro",PIX:"PIX",CREDIT_CARD:"Crédito",DEBIT_CARD:"Débito"};

export default function PdvPage(){
 const[loading,setLoading]=useState(true);const[store,setStore]=useState<StoreAccess|null>(null);const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[inventory,setInventory]=useState<Inventory[]>([]);const[cashSession,setCashSession]=useState<CashSession|null>(null);const[openingBalance,setOpeningBalance]=useState("0");const[cart,setCart]=useState<CartItem[]>([]);const[query,setQuery]=useState("");const[categoryId,setCategoryId]=useState("");const[payments,setPayments]=useState<PosPayment[]>([{method:"CASH",amount:""}]);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[lastSale,setLastSale]=useState("");
 const inventoryMap=useMemo(()=>new Map(inventory.map(i=>[i.product_id,i])),[inventory]);
 const filtered=useMemo(()=>products.filter(p=>p.active&&p.available_pos&&(!categoryId||p.category_id===categoryId)&&`${p.name} ${p.description??""}`.toLowerCase().includes(query.toLowerCase())),[products,categoryId,query]);
 const total=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.promotional_price??item.price)*item.quantity,0),[cart]);
 const paymentTotal=useMemo(()=>payments.length===1&&!payments[0].amount.trim()?total:payments.reduce((sum,p)=>sum+(Number(p.amount.replace(",","."))||0),0),[payments,total]);
 const paymentDiff=Math.round((total-paymentTotal)*100)/100;

 async function load(){
  setLoading(true);const{data:s}=await supabase.auth.getSession();if(!s.session){setStore(null);setNotice("Entre no Painel Lojista primeiro.");setLoading(false);return;}
  const{data:m}=await supabase.from("store_memberships").select("store_id,role,stores!inner(name)").eq("user_id",s.session.user.id).eq("active",true).limit(1);if(!m?.length){setStore(null);setNotice("Sua conta ainda não está vinculada a uma loja.");setLoading(false);return;}
  const row:any=m[0],rel=Array.isArray(row.stores)?row.stores[0]:row.stores;const access={id:String(row.store_id),name:String(rel?.name??"Minha loja"),role:String(row.role)};setStore(access);
  const[pR,cR,iR,cashR]=await Promise.all([
   supabase.from("products").select("id,name,description,image_url,price,promotional_price,active,category_id,available_pos,control_inventory").eq("store_id",access.id).order("name"),
   supabase.from("categories").select("id,name,active").eq("store_id",access.id).eq("active",true).order("sort_order").order("name"),
   supabase.from("inventory_items").select("product_id,quantity,minimum_quantity").eq("store_id",access.id),
   supabase.functions.invoke("cash-session-action",{body:{action:"STATUS",storeId:access.id}})
  ]);
  if(pR.error||cR.error||iR.error){setNotice("Não foi possível carregar o PDV agora.");setLoading(false);return;}
  setProducts((pR.data??[]).map((p:any)=>({...p,price:Number(p.price),promotional_price:p.promotional_price==null?null:Number(p.promotional_price)})) as Product[]);setCategories((cR.data??[]) as Category[]);setInventory((iR.data??[]).map((i:any)=>({...i,quantity:Number(i.quantity),minimum_quantity:Number(i.minimum_quantity)})) as Inventory[]);setCashSession(cashR.data?.session?{...cashR.data.session,opening_balance:Number(cashR.data.session.opening_balance)}:null);setLoading(false);
 }
 useEffect(()=>{void load();},[]);

 function add(product:Product){const inv=inventoryMap.get(product.id);if(product.control_inventory&&Number(inv?.quantity??0)<=0){setNotice("Este produto está sem estoque.");return;}setCart(current=>{const found=current.find(i=>i.id===product.id);if(found){const nextQty=found.quantity+1;if(product.control_inventory&&nextQty>Number(inv?.quantity??0)){setNotice("Quantidade maior que o estoque disponível.");return current;}return current.map(i=>i.id===product.id?{...i,quantity:nextQty}:i);}return[...current,{...product,quantity:1}];});}
 function changeQty(id:string,delta:number){const product=products.find(p=>p.id===id);if(!product)return;const inv=inventoryMap.get(id);setCart(current=>current.map(item=>{if(item.id!==id)return item;const next=item.quantity+delta;if(product.control_inventory&&next>Number(inv?.quantity??0)){setNotice("Quantidade maior que o estoque disponível.");return item;}return{...item,quantity:next};}).filter(item=>item.quantity>0));}
 async function openCash(){if(!store)return;const value=Number(openingBalance.replace(",","."));if(!Number.isFinite(value)||value<0){setNotice("Informe um saldo inicial válido.");return;}setBusy(true);const{data,error}=await supabase.functions.invoke("cash-session-action",{body:{action:"OPEN",storeId:store.id,openingBalance:value}});setBusy(false);if(error||data?.error){setNotice(data?.error==="CASH_ALREADY_OPEN"?"O caixa já está aberto.":"Não foi possível abrir o caixa.");await load();return;}setCashSession({...data.session,opening_balance:Number(data.session.opening_balance)});setNotice("Caixa aberto. O PDV está pronto para vender.");}
 function addPayment(){setPayments(current=>{if(current.length>=4||total<=0)return current;if(current.length===1&&!current[0].amount.trim()){const first=Math.floor(total*50)/100;return[{...current[0],amount:first.toFixed(2)},{method:"PIX",amount:(total-first).toFixed(2)}];}const used=current.reduce((sum,p)=>sum+(Number(p.amount.replace(",","."))||0),0);return[...current,{method:"PIX",amount:Math.max(0,total-used).toFixed(2)}];});}
 function updatePayment(index:number,patch:Partial<PosPayment>){setPayments(current=>current.map((p,i)=>i===index?{...p,...patch}:p));}
 function removePayment(index:number){setPayments(current=>current.length<=1?current:current.filter((_,i)=>i!==index));}
 async function finalize(){if(!store||!cashSession||!cart.length||busy)return;const finalPayments=payments.map(p=>({method:p.method,amount:payments.length===1&&!p.amount.trim()?total:Number(p.amount.replace(",","."))}));if(finalPayments.some(p=>!Number.isFinite(p.amount)||p.amount<=0)){setNotice("Revise os valores do pagamento.");return;}if(Math.abs(finalPayments.reduce((s,p)=>s+p.amount,0)-total)>0.009){setNotice(`A soma dos pagamentos deve ser ${brl(total)}.`);return;}setBusy(true);setNotice("");const{data,error}=await supabase.functions.invoke("create-pos-sale",{body:{storeId:store.id,cashSessionId:cashSession.id,items:cart.map(i=>({productId:i.id,quantity:i.quantity})),payments:finalPayments,discount:0}});setBusy(false);if(error||data?.error){const messages:Record<string,string>={INSUFFICIENT_STOCK:"Estoque insuficiente para concluir a venda.",PRODUCT_UNAVAILABLE:"Um produto ficou indisponível.",PAYMENT_TOTAL_MISMATCH:"A soma dos pagamentos não confere."};setNotice(messages[data?.error]??"Não foi possível concluir a venda.");await load();return;}setLastSale(String(data.orderId??""));setCart([]);setPayments([{method:"CASH",amount:""}]);setNotice("Venda concluída com sucesso. Estoque, caixa e financeiro foram atualizados.");await load();}

 if(loading)return <main className="pdvPage"><div className="pdvShell">Carregando PDV...</div></main>;
 if(!store)return <main className="pdvPage"><div className="pdvShell"><h1>PDV</h1><p>{notice}</p><a href="/">Voltar ao painel</a></div></main>;
 return <main className="pdvPage"><div className="pdvShell">
  <header className="pdvHero"><div><span>PDV CLICK-FOOD</span><h1>{store.name}</h1><p>Venda no balcão com catálogo visual, estoque e caixa integrados.</p></div><div className="pdvHeroActions"><a href="/">← Painel</a><a href="/produtos">Produtos</a><a href="/estoque">Estoque</a><button onClick={()=>void load()}>Atualizar</button></div></header>
  {notice&&<div className="pdvNotice">{notice}</div>}
  {!cashSession?<section className="pdvOpenCash"><div><span>CAIXA FECHADO</span><h2>Abra o caixa para começar o turno</h2><p>O saldo inicial fica registrado para a conferência no fechamento.</p></div><div><input value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)} inputMode="decimal" placeholder="Saldo inicial"/><button disabled={busy} onClick={openCash}>{busy?"ABRINDO...":"ABRIR CAIXA"}</button></div></section>:<section className="pdvCashStatus"><div><span>CAIXA ABERTO</span><b>Saldo inicial {brl(cashSession.opening_balance)}</b><small>Aberto em {dt(cashSession.opened_at)}</small></div><a href="/?tab=Financeiro">Conferir financeiro</a></section>}
  <section className="pdvLayout"><div className="pdvCatalog"><div className="pdvFilters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto..."/><button className={!categoryId?"active":""} onClick={()=>setCategoryId("")}>Todos</button>{categories.map(c=><button className={categoryId===c.id?"active":""} key={c.id} onClick={()=>setCategoryId(c.id)}>{c.name}</button>)}</div><div className="pdvGrid">{filtered.map(p=>{const inv=inventoryMap.get(p.id),out=p.control_inventory&&Number(inv?.quantity??0)<=0,low=p.control_inventory&&Number(inv?.quantity??0)<=Number(inv?.minimum_quantity??0);return <button className={`pdvProduct ${out?"soldOut":""}`} key={p.id} disabled={out} onClick={()=>add(p)}><div className="pdvProductImage">{p.image_url?<img src={p.image_url} alt={p.name}/>:<div>🍽️</div>}{out&&<span>SEM ESTOQUE</span>}</div><div className="pdvProductBody"><b>{p.name}</b><small>{p.description||"Produto do catálogo"}</small><strong>{brl(p.promotional_price??p.price)}</strong>{p.control_inventory&&<em className={low?"low":""}>Estoque: {Number(inv?.quantity??0)}</em>}</div></button>})}{!filtered.length&&<div className="pdvEmpty">Nenhum produto disponível no PDV com esses filtros.</div>}</div></div>
   <aside className="pdvCart"><div className="pdvCartHeader"><div><span>VENDA ATUAL</span><h2>Balcão</h2></div><button onClick={()=>setCart([])}>Limpar</button></div><div className="pdvCartItems">{cart.map(item=><div className="pdvCartItem" key={item.id}><div>{item.image_url?<img src={item.image_url} alt=""/>:<span>🍽️</span>}<div><b>{item.name}</b><small>{brl(item.promotional_price??item.price)} cada</small><div className="pdvQty"><button onClick={()=>changeQty(item.id,-1)}>−</button><strong>{item.quantity}</strong><button onClick={()=>changeQty(item.id,1)}>+</button></div></div></div><strong>{brl(Number(item.promotional_price??item.price)*item.quantity)}</strong></div>)}{!cart.length&&<div className="pdvEmpty">Toque nos produtos para montar a venda.</div>}</div>
    <div className="pdvPayments"><div className="pdvPaymentHead"><b>Pagamento</b><button disabled={!cart.length||payments.length>=4} onClick={addPayment}>+ Dividir</button></div>{payments.map((p,index)=><div className="pdvPaymentRow" key={index}><select value={p.method} onChange={e=>updatePayment(index,{method:e.target.value as PaymentMethod})}>{(Object.keys(methodLabel) as PaymentMethod[]).map(method=><option value={method} key={method}>{methodLabel[method]}</option>)}</select><input value={p.amount} onChange={e=>updatePayment(index,{amount:e.target.value})} inputMode="decimal" placeholder={payments.length===1?total.toFixed(2):"0,00"}/>{payments.length>1&&<button onClick={()=>removePayment(index)}>×</button>}</div>)}<small className={Math.abs(paymentDiff)<.01?"ok":"warn"}>{payments.length===1&&!payments[0].amount.trim()?`Total: ${brl(total)}`:Math.abs(paymentDiff)<.01?`Total conferido: ${brl(paymentTotal)}`:paymentDiff>0?`Falta ${brl(paymentDiff)}`:`Excede ${brl(Math.abs(paymentDiff))}`}</small></div>
    <div className="pdvTotal"><span>Total</span><strong>{brl(total)}</strong></div><button className="pdvCheckout" disabled={!cashSession||!cart.length||busy||Math.abs(paymentDiff)>=.01} onClick={finalize}>{!cashSession?"ABRA O CAIXA":busy?"PROCESSANDO...":"FINALIZAR VENDA"}</button>{lastSale&&<a className="pdvReceipt" href={`/recibo?orderId=${encodeURIComponent(lastSale)}`}>IMPRIMIR ÚLTIMO RECIBO</a>}
   </aside></section>
 </div></main>;
}
