"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Metrics={gmv_today:number;platform_revenue_today:number;orders_today:number;active_stores:number;online_drivers:number;customers:number;average_ticket_today:number;past_due_invoices:number;pending_drivers:number;failed_payments:number;critical_tickets:number};
type StoreRow={id:string;name:string;slug:string;status:string;city_id:string|null;created_at:string;cities?:{name:string;state:string}|{name:string;state:string}[]|null};
type DriverRow={id:string;user_id:string;status:string;online:boolean;rating:number;acceptance_rate:number;city_id:string|null;cities?:{name:string;state:string}|{name:string;state:string}[]|null;profileName?:string};
type City={id:string;name:string;state:string};type Plan={id:string;name:string;description:string|null;setup_fee:number;monthly_fee:number;commission_percentage:number;included_orders:number|null;extra_order_fee:number;active:boolean};
type Order={id:string;order_number:number;total:number;status:string;payment_status:string;source:string;delivery_type:string;created_at:string;stores?:{name:string}|{name:string}[]|null};
type Invoice={id:string;amount:number;due_date:string;status:string;reference_month:string;stores?:{name:string}|{name:string}[]|null};type Finance={id:string;transaction_type:string;direction:string;amount:number;status:string;created_at:string;stores?:{name:string}|{name:string}[]|null};
type BonusRule={id:string;name:string;metric:string;target:number;period:string;points_awarded:number;active:boolean};type BonusReward={id:string;name:string;points_cost:number;reward_type:string;reward_value:number|null;requires_approval:boolean;active:boolean};type Audit={id:string;action:string;entity_type:string;entity_id:string|null;created_at:string;after_data:any};
type Tab="Dashboard"|"Pedidos"|"Cidades"|"Lojas"|"Entregadores"|"Planos"|"Financeiro"|"Bônus"|"Auditoria";
const tabs:Tab[]=["Dashboard","Pedidos","Cidades","Lojas","Entregadores","Planos","Financeiro","Bônus","Auditoria"];
const emptyMetrics:Metrics={gmv_today:0,platform_revenue_today:0,orders_today:0,active_stores:0,online_drivers:0,customers:0,average_ticket_today:0,past_due_invoices:0,pending_drivers:0,failed_payments:0,critical_tickets:0};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);const number=(v:number)=>new Intl.NumberFormat("pt-BR").format(v||0);const dt=(v:string)=>new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"});const relation=(v:any)=>Array.isArray(v)?v[0]:v;const normalizeSlug=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function Home(){
 const[loading,setLoading]=useState(true);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[authMode,setAuthMode]=useState<"login"|"signup">("login");const[message,setMessage]=useState("");const[authorized,setAuthorized]=useState(false);const[signedIn,setSignedIn]=useState(false);const[userEmail,setUserEmail]=useState("");const[bootstrapCode,setBootstrapCode]=useState("");const[tab,setTab]=useState<Tab>("Dashboard");const[metrics,setMetrics]=useState<Metrics>(emptyMetrics);
 const[stores,setStores]=useState<StoreRow[]>([]);const[drivers,setDrivers]=useState<DriverRow[]>([]);const[cities,setCities]=useState<City[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[finance,setFinance]=useState<Finance[]>([]);const[bonusRules,setBonusRules]=useState<BonusRule[]>([]);const[bonusRewards,setBonusRewards]=useState<BonusReward[]>([]);const[audit,setAudit]=useState<Audit[]>([]);
 const[activationCode,setActivationCode]=useState("");const[activationStore,setActivationStore]=useState("");const[cityForm,setCityForm]=useState({name:"",state:"GO"});const[storeForm,setStoreForm]=useState({storeName:"",legalName:"",slug:"",document:"",email:"",phone:"",cityId:"",description:""});const[planForm,setPlanForm]=useState({name:"",description:"",setupFee:"0",monthlyFee:"0",commission:"0",includedOrders:"",extraFee:"0"});const[planChoice,setPlanChoice]=useState<Record<string,string>>({});
 const[bonusRuleForm,setBonusRuleForm]=useState({name:"",metric:"COMPLETED_ORDERS",target:"100",period:"MONTHLY",points:"100"});const[bonusRewardForm,setBonusRewardForm]=useState({name:"",description:"",pointsCost:"500",rewardType:"CREDIT",rewardValue:"50"});const[citySettings,setCitySettings]=useState<Record<string,{base:string;perKm:string;minimum:string;timeout:string;initialRadius:string;maxRadius:string;batch:string}>>({});
 const cards=useMemo(()=>[["GMV hoje",brl(metrics.gmv_today)],["Receita CLICK-FOOD",brl(metrics.platform_revenue_today)],["Pedidos hoje",number(metrics.orders_today)],["Lojas ativas",number(metrics.active_stores)],["Entregadores online",number(metrics.online_drivers)],["Clientes",number(metrics.customers)],["Ticket médio",brl(metrics.average_ticket_today)],["Inadimplentes",number(metrics.past_due_invoices)]],[metrics]);
 const financeSummary=useMemo(()=>finance.reduce((a,t)=>{const v=Number(t.amount);if(t.direction==="CREDIT")a.credit+=v;else a.debit+=v;return a},{credit:0,debit:0}),[finance]);

 async function loadAll(){
  const[mr,sr,dr,cr,or,pr,ir,fr,br,brr,ar]=await Promise.all([
   supabase.rpc("admin_dashboard_metrics"),supabase.from("stores").select("id,name,slug,status,city_id,created_at,cities(name,state)").order("created_at",{ascending:false}).limit(300),supabase.from("drivers").select("id,user_id,status,online,rating,acceptance_rate,city_id,cities(name,state)").order("created_at",{ascending:false}).limit(300),supabase.from("cities").select("id,name,state").eq("active",true).order("state").order("name"),supabase.from("orders").select("id,order_number,total,status,payment_status,source,delivery_type,created_at,stores(name)").order("created_at",{ascending:false}).limit(100),supabase.from("plans").select("*").order("created_at",{ascending:false}),supabase.from("invoices").select("id,amount,due_date,status,reference_month,stores(name)").order("due_date",{ascending:false}).limit(100),supabase.from("financial_transactions").select("id,transaction_type,direction,amount,status,created_at,stores(name)").order("created_at",{ascending:false}).limit(100),supabase.from("bonus_rules").select("id,name,metric,target,period,points_awarded,active").order("created_at",{ascending:false}),supabase.from("bonus_rewards").select("id,name,points_cost,reward_type,reward_value,requires_approval,active").order("created_at",{ascending:false}),supabase.from("audit_logs").select("id,action,entity_type,entity_id,created_at,after_data").order("created_at",{ascending:false}).limit(100)
  ]);
  if(mr.data)setMetrics({...emptyMetrics,...mr.data as Metrics});if(sr.data)setStores(sr.data as any);if(cr.data)setCities(cr.data as City[]);if(or.data)setOrders(or.data.map((x:any)=>({...x,total:Number(x.total)})));if(pr.data)setPlans(pr.data.map((x:any)=>({...x,setup_fee:Number(x.setup_fee),monthly_fee:Number(x.monthly_fee),commission_percentage:Number(x.commission_percentage),extra_order_fee:Number(x.extra_order_fee)})));if(ir.data)setInvoices(ir.data.map((x:any)=>({...x,amount:Number(x.amount)})));if(fr.data)setFinance(fr.data.map((x:any)=>({...x,amount:Number(x.amount)})));if(br.data)setBonusRules(br.data.map((x:any)=>({...x,target:Number(x.target)})));if(brr.data)setBonusRewards(brr.data.map((x:any)=>({...x,reward_value:x.reward_value==null?null:Number(x.reward_value)})));if(ar.data)setAudit(ar.data as any);
  if(dr.data){const raw=dr.data as any[];const ids=raw.map(x=>x.user_id);const profiles=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[] as any[]};const names=new Map((profiles.data??[]).map((p:any)=>[p.id,p.full_name]));setDrivers(raw.map(d=>({...d,rating:Number(d.rating),acceptance_rate:Number(d.acceptance_rate),profileName:names.get(d.user_id)||"Entregador"})));}
  const [pricingR,dispatchR]=await Promise.all([supabase.from("city_delivery_pricing").select("*"),supabase.from("delivery_dispatch_settings").select("*")]);const draft:Record<string,any>={};for(const city of cities.length?cities:(cr.data??[])){const p=(pricingR.data??[]).find((x:any)=>x.city_id===city.id);const d=(dispatchR.data??[]).find((x:any)=>x.city_id===city.id);draft[city.id]={base:String(Number(p?.driver_base_earning??4)),perKm:String(Number(p?.driver_per_km??1)),minimum:String(Number(p?.driver_minimum_earning??6)),timeout:String(Number(d?.offer_timeout_seconds??15)),initialRadius:String(Number(d?.initial_radius_km??5)),maxRadius:String(Number(d?.max_radius_km??20)),batch:String(Number(d?.batch_size??3))};}setCitySettings(draft);
 }
 async function loadSession(){setLoading(true);const{data}=await supabase.auth.getSession();const session=data.session;if(!session){setSignedIn(false);setAuthorized(false);setLoading(false);return;}setSignedIn(true);setUserEmail(session.user.email??"");const role=String(session.user.app_metadata?.clickfood_role??"");const ok=["SUPER_ADMIN","ADMIN","SUPPORT"].includes(role);setAuthorized(ok);if(ok)await loadAll();setLoading(false);}
 useEffect(()=>{loadSession();const{data}=supabase.auth.onAuthStateChange(()=>loadSession());return()=>data.subscription.unsubscribe();},[]);
 async function submitAuth(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");if(authMode==="signup"){const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:"Administrador CLICK-FOOD"}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Conta criada. Confirme o e-mail e depois entre.");else await loadSession();}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage("E-mail ou senha inválidos.");}setLoading(false);}
 async function bootstrapAdmin(){const{data,error}=await supabase.functions.invoke("bootstrap-admin",{body:{code:bootstrapCode}});if(error||data?.error){setMessage("Código inválido, expirado ou já utilizado.");return;}await supabase.auth.refreshSession();await loadSession();}
 async function logout(){await supabase.auth.signOut();setAuthorized(false);setSignedIn(false);}
 async function createCity(e:FormEvent){e.preventDefault();const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"CREATE_CITY",name:cityForm.name,state:cityForm.state}});setMessage(error||data?.error?"Não foi possível cadastrar a cidade.":"Cidade cadastrada.");if(!error&&!data?.error)setCityForm({name:"",state:cityForm.state});await loadAll();}
 async function createStore(e:FormEvent){e.preventDefault();setActivationCode("");const slug=storeForm.slug||normalizeSlug(storeForm.storeName);const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"CREATE_STORE",...storeForm,slug,cityId:storeForm.cityId||undefined}});if(error||data?.error){setMessage(data?.error==="SLUG_ALREADY_EXISTS"?"Já existe loja com esse identificador.":"Não foi possível criar a loja.");return;}setActivationCode(data.onboardingCode);setActivationStore(data.store?.name??storeForm.storeName);setStoreForm({storeName:"",legalName:"",slug:"",document:"",email:"",phone:"",cityId:"",description:""});await loadAll();}
 async function changeStoreStatus(id:string,status:"ACTIVE"|"SUSPENDED"|"BLOCKED"){const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"STORE_STATUS",storeId:id,status}});setMessage(error||data?.error?"Falha ao alterar loja.":`Loja ${status}.`);await loadAll();}
 async function reissueCode(id:string,name:string){const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"REISSUE_STORE_CODE",storeId:id}});if(error||data?.error){setMessage("Falha ao gerar código.");return;}setActivationCode(data.onboardingCode);setActivationStore(name);}
 async function changeDriverStatus(id:string,status:"ACTIVE"|"BLOCKED"|"PENDING"){const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"DRIVER_STATUS",driverId:id,status}});setMessage(error||data?.error?"Falha ao alterar entregador.":"Entregador atualizado.");await loadAll();}
 async function createPlan(e:FormEvent){e.preventDefault();const{data,error}=await supabase.functions.invoke("admin-commerce",{body:{action:"CREATE_PLAN",name:planForm.name,description:planForm.description,setupFee:Number(planForm.setupFee.replace(",",".")),monthlyFee:Number(planForm.monthlyFee.replace(",",".")),commissionPercentage:Number(planForm.commission.replace(",",".")),includedOrders:planForm.includedOrders?Number(planForm.includedOrders):null,extraOrderFee:Number(planForm.extraFee.replace(",","."))}});setMessage(error||data?.error?(data?.error==="PLAN_EXISTS"?"Já existe plano com esse nome.":"Não foi possível criar o plano."):"Plano criado.");if(!error&&!data?.error)setPlanForm({name:"",description:"",setupFee:"0",monthlyFee:"0",commission:"0",includedOrders:"",extraFee:"0"});await loadAll();}
 async function assignPlan(storeId:string){const planId=planChoice[storeId];if(!planId){setMessage("Escolha um plano.");return;}const{data,error}=await supabase.functions.invoke("admin-commerce",{body:{action:"ASSIGN_PLAN",storeId,planId,status:"ACTIVE"}});setMessage(error||data?.error?"Não foi possível aplicar o plano.":"Plano aplicado à loja.");}
 async function togglePlan(p:Plan){await supabase.functions.invoke("admin-commerce",{body:{action:"TOGGLE_PLAN",planId:p.id,active:!p.active}});await loadAll();}
 async function createBonusRule(e:FormEvent){e.preventDefault();const{data,error}=await supabase.functions.invoke("admin-commerce",{body:{action:"CREATE_BONUS_RULE",name:bonusRuleForm.name,metric:bonusRuleForm.metric,target:Number(bonusRuleForm.target),period:bonusRuleForm.period,pointsAwarded:Number(bonusRuleForm.points)}});setMessage(error||data?.error?"Não foi possível criar a meta.":"Meta de bônus criada.");await loadAll();}
 async function createBonusReward(e:FormEvent){e.preventDefault();const{data,error}=await supabase.functions.invoke("admin-commerce",{body:{action:"CREATE_BONUS_REWARD",name:bonusRewardForm.name,description:bonusRewardForm.description,pointsCost:Number(bonusRewardForm.pointsCost),rewardType:bonusRewardForm.rewardType,rewardValue:bonusRewardForm.rewardValue?Number(bonusRewardForm.rewardValue):null,requiresApproval:true}});setMessage(error||data?.error?"Não foi possível criar a recompensa.":"Recompensa criada.");await loadAll();}
 async function saveCitySettings(cityId:string){const x=citySettings[cityId];if(!x)return;const{data,error}=await supabase.functions.invoke("admin-commerce",{body:{action:"UPDATE_CITY_DELIVERY",cityId,driverBaseEarning:Number(x.base),driverPerKm:Number(x.perKm),driverMinimumEarning:Number(x.minimum),offerTimeoutSeconds:Number(x.timeout),initialRadiusKm:Number(x.initialRadius),maxRadiusKm:Number(x.maxRadius),batchSize:Number(x.batch)}});setMessage(error||data?.error?"Não foi possível salvar as regras da cidade.":"Regras da cidade atualizadas.");}
 async function invoiceStatus(id:string,status:"PAID"|"CANCELLED"|"WAIVED"){await supabase.functions.invoke("admin-commerce",{body:{action:"INVOICE_STATUS",invoiceId:id,status}});await loadAll();}

 if(loading)return <main className="authPage"><div className="authCard"><div className="brand dark"><span>CLICK</span>-FOOD</div><p>Carregando ambiente seguro...</p></div></main>;
 if(!signedIn)return <main className="authPage"><form className="authCard" onSubmit={submitAuth}><div className="brand dark"><span>CLICK</span>-FOOD</div><p className="authRole">ADMINISTRAÇÃO CENTRAL</p><h1>{authMode==="login"?"Entrar na Matriz":"Criar acesso inicial"}</h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton">{authMode==="login"?"ENTRAR":"CRIAR CONTA"}</button><button type="button" className="textButton" onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Primeiro acesso? Criar conta":"Já tenho conta"}</button></form></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><div className="brand dark"><span>CLICK</span>-FOOD</div><p className="authRole">ATIVAÇÃO DA MATRIZ</p><h1>Ativar Super Admin</h1><p>{userEmail}</p><label>Código único<input value={bootstrapCode} onChange={e=>setBootstrapCode(e.target.value)} /></label>{message&&<div className="authMessage">{message}</div>}<button className="loginButton" onClick={bootstrapAdmin}>ATIVAR SUPER ADMIN</button><button className="textButton" onClick={logout}>Sair</button></div></main>;

 return <main className="shell"><aside className="sidebar"><div className="brand"><span>CLICK</span>-FOOD</div><p className="role">MATRIZ</p><nav>{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</nav></aside><section className="content"><header className="topbar"><div><p className="eyebrow">Operação CLICK-FOOD</p><h1>{tab}</h1><small>{userEmail}</small></div><div className="topActions"><div className="status">Produção conectada</div><button className="logout" onClick={()=>loadAll()}>Atualizar</button><button className="logout" onClick={logout}>Sair</button></div></header>{message&&<div className="notice">{message}</div>}{activationCode&&<div className="activationBox"><div><b>Código de ativação — {activationStore}</b><p>Expira em 7 dias e funciona uma única vez.</p></div><code>{activationCode}</code><button onClick={()=>navigator.clipboard?.writeText(activationCode)}>Copiar</button></div>}
 {tab==="Dashboard"&&<><div className="metricGrid">{cards.map(([l,v])=><article className="metric" key={l}><p>{l}</p><strong>{v}</strong></article>)}</div><div className="panels"><article className="panel wide"><div className="panelTitle"><h2>Resumo operacional</h2></div><div className="summaryGrid"><div><b>{cities.length}</b><span>cidades</span></div><div><b>{stores.length}</b><span>lojas</span></div><div><b>{drivers.length}</b><span>entregadores</span></div></div></article><article className="panel"><h2>Atenção</h2><ul className="alerts"><li>{metrics.past_due_invoices} inadimplentes</li><li>{metrics.pending_drivers} entregadores pendentes</li><li>{metrics.failed_payments} pagamentos com falha</li><li>{metrics.critical_tickets} chamados críticos</li></ul></article></div></>}
 {tab==="Pedidos"&&<section className="panel"><div className="panelTitle"><h2>Pedidos recentes</h2><span>{orders.length}</span></div><div className="adminDataList">{orders.map(o=>{const s=relation(o.stores);return <div className="adminDataRow" key={o.id}><div><b>#{o.order_number} • {s?.name??"Loja"}</b><small>{o.source} • {o.delivery_type} • {dt(o.created_at)}</small></div><span className={`badge ${o.status.toLowerCase()}`}>{o.status}</span><b>{brl(o.total)}</b></div>})}{!orders.length&&<div className="emptyState">Nenhum pedido ainda.</div>}</div></section>}
 {tab==="Cidades"&&<div className="twoColumns"><form className="panel formPanel" onSubmit={createCity}><h2>Liberar nova cidade</h2><label>Cidade<input value={cityForm.name} onChange={e=>setCityForm({...cityForm,name:e.target.value})} required/></label><label>UF<input value={cityForm.state} maxLength={2} onChange={e=>setCityForm({...cityForm,state:e.target.value.toUpperCase()})} required/></label><button className="primary wideButton">CADASTRAR CIDADE</button></form><section className="panel"><h2>Tarifa e despacho por cidade</h2><div className="adminDataList">{cities.map(c=>{const x=citySettings[c.id];return <div className="citySettings" key={c.id}><div className="cityTitle"><b>{c.name} - {c.state}</b><span className="badge active">ATIVA</span></div>{x&&<div className="cityInputs"><label>Base entregador<input value={x.base} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,base:e.target.value}})}/></label><label>R$/km<input value={x.perKm} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,perKm:e.target.value}})}/></label><label>Mínimo<input value={x.minimum} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,minimum:e.target.value}})}/></label><label>Timeout<input value={x.timeout} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,timeout:e.target.value}})}/></label><label>Raio inicial<input value={x.initialRadius} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,initialRadius:e.target.value}})}/></label><label>Raio máx.<input value={x.maxRadius} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,maxRadius:e.target.value}})}/></label><label>Lote<input value={x.batch} onChange={e=>setCitySettings({...citySettings,[c.id]:{...x,batch:e.target.value}})}/></label><button onClick={()=>saveCitySettings(c.id)}>Salvar</button></div>}</div>})}</div></section></div>}
 {tab==="Lojas"&&<div className="twoColumns"><form className="panel formPanel" onSubmit={createStore}><h2>Nova loja</h2><label>Nome<input value={storeForm.storeName} onChange={e=>setStoreForm({...storeForm,storeName:e.target.value,slug:storeForm.slug||normalizeSlug(e.target.value)})} required/></label><label>Razão social<input value={storeForm.legalName} onChange={e=>setStoreForm({...storeForm,legalName:e.target.value})}/></label><label>Slug<input value={storeForm.slug} onChange={e=>setStoreForm({...storeForm,slug:normalizeSlug(e.target.value)})} required/></label><div className="formRow"><label>Documento<input value={storeForm.document} onChange={e=>setStoreForm({...storeForm,document:e.target.value})}/></label><label>Telefone<input value={storeForm.phone} onChange={e=>setStoreForm({...storeForm,phone:e.target.value})}/></label></div><label>E-mail<input value={storeForm.email} onChange={e=>setStoreForm({...storeForm,email:e.target.value})}/></label><label>Cidade<select value={storeForm.cityId} onChange={e=>setStoreForm({...storeForm,cityId:e.target.value})}><option value="">Selecione</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}-{c.state}</option>)}</select></label><button className="primary wideButton">CRIAR LOJA + CÓDIGO</button></form><section className="panel"><h2>Lojas cadastradas</h2><div className="adminDataList">{stores.map(s=>{const c=relation(s.cities);return <div className="adminDataRow storeAdminRow" key={s.id}><div><b>{s.name}</b><small>{s.slug} • {c?`${c.name}-${c.state}`:"sem cidade"}</small></div><span className={`badge ${s.status.toLowerCase()}`}>{s.status}</span><div className="adminActions"><button onClick={()=>reissueCode(s.id,s.name)}>Novo código</button>{s.status!=="ACTIVE"&&<button onClick={()=>changeStoreStatus(s.id,"ACTIVE")}>Ativar</button>}{s.status==="ACTIVE"&&<button onClick={()=>changeStoreStatus(s.id,"SUSPENDED")}>Suspender</button>}<button className="danger" onClick={()=>changeStoreStatus(s.id,"BLOCKED")}>Bloquear</button></div><div className="planAssign"><select value={planChoice[s.id]??""} onChange={e=>setPlanChoice({...planChoice,[s.id]:e.target.value})}><option value="">Plano...</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={()=>assignPlan(s.id)}>Aplicar</button></div></div>})}</div></section></div>}
 {tab==="Entregadores"&&<section className="panel"><h2>Entregadores</h2><div className="adminDataList">{drivers.map(d=>{const c=relation(d.cities);return <div className="adminDataRow" key={d.id}><div><b>{d.profileName}</b><small>{c?`${c.name}-${c.state}`:"sem cidade"} • ★ {d.rating.toFixed(1)} • aceitação {d.acceptance_rate.toFixed(0)}%</small></div><span className={`badge ${d.status.toLowerCase()}`}>{d.status}{d.online?" • ONLINE":""}</span><div className="adminActions">{d.status!=="ACTIVE"&&<button onClick={()=>changeDriverStatus(d.id,"ACTIVE")}>Aprovar</button>}{d.status==="ACTIVE"&&<button className="danger" onClick={()=>changeDriverStatus(d.id,"BLOCKED")}>Bloquear</button>}{d.status==="BLOCKED"&&<button onClick={()=>changeDriverStatus(d.id,"PENDING")}>Revisar</button>}</div></div>})}{!drivers.length&&<div className="emptyState">Nenhum entregador cadastrado.</div>}</div></section>}
 {tab==="Planos"&&<div className="twoColumns"><form className="panel formPanel" onSubmit={createPlan}><h2>Criar plano</h2><label>Nome<input value={planForm.name} onChange={e=>setPlanForm({...planForm,name:e.target.value})} required/></label><label>Descrição<input value={planForm.description} onChange={e=>setPlanForm({...planForm,description:e.target.value})}/></label><div className="formRow"><label>Implantação<input value={planForm.setupFee} onChange={e=>setPlanForm({...planForm,setupFee:e.target.value})}/></label><label>Mensalidade<input value={planForm.monthlyFee} onChange={e=>setPlanForm({...planForm,monthlyFee:e.target.value})}/></label></div><div className="formRow"><label>Comissão %<input value={planForm.commission} onChange={e=>setPlanForm({...planForm,commission:e.target.value})}/></label><label>Pedidos inclusos<input value={planForm.includedOrders} onChange={e=>setPlanForm({...planForm,includedOrders:e.target.value})}/></label></div><label>Excedente/pedido<input value={planForm.extraFee} onChange={e=>setPlanForm({...planForm,extraFee:e.target.value})}/></label><button className="primary wideButton">CRIAR PLANO</button></form><section className="panel"><h2>Planos</h2><div className="adminDataList">{plans.map(p=><div className="adminDataRow" key={p.id}><div><b>{p.name}</b><small>{brl(p.monthly_fee)}/mês • {p.commission_percentage}% • {p.included_orders??"∞"} pedidos</small></div><span className={`badge ${p.active?"active":"blocked"}`}>{p.active?"ATIVO":"PAUSADO"}</span><button onClick={()=>togglePlan(p)}>{p.active?"Pausar":"Ativar"}</button></div>)}</div></section></div>}
 {tab==="Financeiro"&&<><div className="metricGrid"><article className="metric"><p>Créditos registrados</p><strong>{brl(financeSummary.credit)}</strong></article><article className="metric"><p>Débitos registrados</p><strong>{brl(financeSummary.debit)}</strong></article><article className="metric"><p>Faturas abertas</p><strong>{invoices.filter(i=>["OPEN","PAST_DUE"].includes(i.status)).length}</strong></article><article className="metric"><p>Inadimplentes</p><strong>{invoices.filter(i=>i.status==="PAST_DUE").length}</strong></article></div><div className="twoColumns"><section className="panel"><h2>Faturas</h2><div className="adminDataList">{invoices.map(i=>{const s=relation(i.stores);return <div className="adminDataRow" key={i.id}><div><b>{s?.name??"Loja"} • {brl(i.amount)}</b><small>Venc. {new Date(i.due_date+"T12:00:00").toLocaleDateString("pt-BR")} • {i.status}</small></div><div className="adminActions">{i.status!=="PAID"&&<button onClick={()=>invoiceStatus(i.id,"PAID")}>Marcar paga</button>}<button onClick={()=>invoiceStatus(i.id,"WAIVED")}>Isentar</button></div></div>})}{!invoices.length&&<div className="emptyState">Nenhuma fatura gerada ainda.</div>}</div></section><section className="panel"><h2>Ledger financeiro</h2><div className="adminDataList">{finance.map(t=>{const s=relation(t.stores);return <div className="adminDataRow" key={t.id}><div><b>{t.transaction_type}</b><small>{s?.name??"Plataforma"} • {dt(t.created_at)}</small></div><b>{t.direction==="DEBIT"?"−":"+"} {brl(t.amount)}</b></div>})}{!finance.length&&<div className="emptyState">Sem lançamentos.</div>}</div></section></div></>}
 {tab==="Bônus"&&<div className="adminBonusGrid"><form className="panel formPanel" onSubmit={createBonusRule}><h2>Nova meta</h2><label>Nome<input value={bonusRuleForm.name} onChange={e=>setBonusRuleForm({...bonusRuleForm,name:e.target.value})} required/></label><label>Métrica<select value={bonusRuleForm.metric} onChange={e=>setBonusRuleForm({...bonusRuleForm,metric:e.target.value})}><option value="COMPLETED_ORDERS">Pedidos concluídos</option><option value="GMV">GMV</option><option value="NEW_CUSTOMERS">Novos clientes</option><option value="RATING">Avaliação</option></select></label><label>Meta<input value={bonusRuleForm.target} onChange={e=>setBonusRuleForm({...bonusRuleForm,target:e.target.value})}/></label><label>Período<select value={bonusRuleForm.period} onChange={e=>setBonusRuleForm({...bonusRuleForm,period:e.target.value})}><option value="DAILY">Diária</option><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensal</option><option value="CAMPAIGN">Campanha</option></select></label><label>Pontos<input value={bonusRuleForm.points} onChange={e=>setBonusRuleForm({...bonusRuleForm,points:e.target.value})}/></label><button className="primary">CRIAR META</button></form><form className="panel formPanel" onSubmit={createBonusReward}><h2>Nova recompensa</h2><label>Nome<input value={bonusRewardForm.name} onChange={e=>setBonusRewardForm({...bonusRewardForm,name:e.target.value})} required/></label><label>Descrição<input value={bonusRewardForm.description} onChange={e=>setBonusRewardForm({...bonusRewardForm,description:e.target.value})}/></label><label>Custo pontos<input value={bonusRewardForm.pointsCost} onChange={e=>setBonusRewardForm({...bonusRewardForm,pointsCost:e.target.value})}/></label><label>Tipo<select value={bonusRewardForm.rewardType} onChange={e=>setBonusRewardForm({...bonusRewardForm,rewardType:e.target.value})}><option value="CREDIT">Crédito</option><option value="FREE_MONTH">Mês grátis</option><option value="APP_HIGHLIGHT">Destaque no app</option><option value="CAMPAIGN">Campanha</option><option value="CUSTOM">Personalizada</option></select></label><label>Valor<input value={bonusRewardForm.rewardValue} onChange={e=>setBonusRewardForm({...bonusRewardForm,rewardValue:e.target.value})}/></label><button className="primary">CRIAR RECOMPENSA</button></form><section className="panel"><h2>Regras e recompensas</h2><div className="adminDataList">{bonusRules.map(r=><div className="adminDataRow" key={r.id}><div><b>{r.name}</b><small>{r.metric} • {r.period}</small></div><b>{r.points_awarded} pts</b></div>)}{bonusRewards.map(r=><div className="adminDataRow" key={r.id}><div><b>{r.name}</b><small>{r.reward_type}</small></div><b>{r.points_cost} pts</b></div>)}</div></section></div>}
 {tab==="Auditoria"&&<section className="panel"><h2>Auditoria</h2><div className="adminDataList">{audit.map(a=><div className="adminDataRow" key={a.id}><div><b>{a.action}</b><small>{a.entity_type} • {dt(a.created_at)}</small></div><code>{a.entity_id?.slice(0,8)??"-"}</code></div>)}{!audit.length&&<div className="emptyState">Sem registros.</div>}</div></section>}
 </section></main>;
}
