"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Store={id:string;name:string;slug:string;document:string|null;city_id:string|null;status:string;slogan:string|null;description:string|null;phone:string|null;email:string|null;whatsapp:string|null;instagram:string|null;address_line:string|null;neighborhood:string|null;postal_code:string|null;address_complement:string|null;primary_color:string;secondary_color:string;minimum_order:number;average_preparation_time:number;latitude:number|null;longitude:number|null};
type City={id:string;name:string;state:string;active:boolean};
type Draft={name:string;slug:string;document:string;cityId:string;slogan:string;description:string;phone:string;email:string;whatsapp:string;instagram:string;addressLine:string;neighborhood:string;postalCode:string;addressComplement:string;primaryColor:string;secondaryColor:string;minimumOrder:string;preparationTime:string;latitude:string;longitude:string};
const blank:Draft={name:"",slug:"",document:"",cityId:"",slogan:"",description:"",phone:"",email:"",whatsapp:"",instagram:"",addressLine:"",neighborhood:"",postalCode:"",addressComplement:"",primaryColor:"#F4C400",secondaryColor:"#111111",minimumOrder:"0",preparationTime:"30",latitude:"",longitude:""};
const normalize=(s:Store):Draft=>({name:s.name??"",slug:s.slug??"",document:s.document??"",cityId:s.city_id??"",slogan:s.slogan??"",description:s.description??"",phone:s.phone??"",email:s.email??"",whatsapp:s.whatsapp??"",instagram:s.instagram??"",addressLine:s.address_line??"",neighborhood:s.neighborhood??"",postalCode:s.postal_code??"",addressComplement:s.address_complement??"",primaryColor:s.primary_color??"#F4C400",secondaryColor:s.secondary_color??"#111111",minimumOrder:String(Number(s.minimum_order??0)),preparationTime:String(Number(s.average_preparation_time??30)),latitude:s.latitude==null?"":String(Number(s.latitude)),longitude:s.longitude==null?"":String(Number(s.longitude))});

export default function MatrixStoresPage(){
 const[stores,setStores]=useState<Store[]>([]);const[cities,setCities]=useState<City[]>([]);const[selectedId,setSelectedId]=useState("");const[draft,setDraft]=useState<Draft>(blank);const[status,setStatus]=useState("PENDING");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[allowed,setAllowed]=useState<boolean|null>(null);
 async function load(preferredId?:string){
  setLoading(true);const{data:{session}}=await supabase.auth.getSession();const role=String(session?.user.app_metadata?.clickfood_role??"");const ok=!!session&&["SUPER_ADMIN","ADMIN"].includes(role);setAllowed(ok);if(!ok){setLoading(false);return;}
  const[sR,cR]=await Promise.all([supabase.from("stores").select("id,name,slug,document,city_id,status,slogan,description,phone,email,whatsapp,instagram,address_line,neighborhood,postal_code,address_complement,primary_color,secondary_color,minimum_order,average_preparation_time,latitude,longitude").order("name"),supabase.from("cities").select("id,name,state,active").eq("active",true).order("name")]);
  if(sR.error||cR.error){setMessage("Não foi possível carregar as lojas para edição.");setLoading(false);return;}
  const rows=(sR.data??[]).map((s:any)=>({...s,minimum_order:Number(s.minimum_order),average_preparation_time:Number(s.average_preparation_time),latitude:s.latitude==null?null:Number(s.latitude),longitude:s.longitude==null?null:Number(s.longitude)})) as Store[];setStores(rows);setCities((cR.data??[]) as City[]);
  const id=preferredId&&rows.some(s=>s.id===preferredId)?preferredId:(selectedId&&rows.some(s=>s.id===selectedId)?selectedId:(rows[0]?.id??""));setSelectedId(id);const current=rows.find(s=>s.id===id);if(current){setDraft(normalize(current));setStatus(current.status);}setLoading(false);
 }
 useEffect(()=>{void load();},[]);
 function selectStore(id:string){setSelectedId(id);const current=stores.find(s=>s.id===id);if(current){setDraft(normalize(current));setStatus(current.status);setMessage("");}}
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(v=>({...v,[key]:value}));}
 async function save(e:FormEvent){
  e.preventDefault();if(!selectedId)return;const minimumOrder=Number(draft.minimumOrder.replace(",",".")),prep=Number(draft.preparationTime),latitude=draft.latitude.trim()?Number(draft.latitude.replace(",",".")):undefined,longitude=draft.longitude.trim()?Number(draft.longitude.replace(",",".")):undefined;
  if(draft.name.trim().length<2){setMessage("Informe um nome válido para a loja.");return;}if(!Number.isFinite(minimumOrder)||minimumOrder<0||!Number.isInteger(prep)||prep<1){setMessage("Revise pedido mínimo e tempo de preparo.");return;}if((latitude===undefined)!==(longitude===undefined)){setMessage("Preencha latitude e longitude juntas.");return;}
  setSaving(true);setMessage("");const{data,error}=await supabase.functions.invoke("store-settings",{body:{storeId:selectedId,name:draft.name,slug:draft.slug,document:draft.document,cityId:draft.cityId||null,slogan:draft.slogan,description:draft.description,phone:draft.phone,email:draft.email,whatsapp:draft.whatsapp,instagram:draft.instagram,addressLine:draft.addressLine,neighborhood:draft.neighborhood,postalCode:draft.postalCode,addressComplement:draft.addressComplement,primaryColor:draft.primaryColor,secondaryColor:draft.secondaryColor,minimumOrder,averagePreparationTime:prep,...(latitude!==undefined&&longitude!==undefined?{latitude,longitude}:{})}});
  if(error||data?.error){const code=String(data?.error??"");const messages:Record<string,string>={SLUG_ALREADY_EXISTS:"Esse identificador (slug) já pertence a outra loja.",INVALID_STORE_SLUG:"Use somente letras minúsculas, números e hífens no identificador.",INVALID_EMAIL:"Informe um e-mail válido.",INVALID_STORE_CITY:"Selecione uma cidade ativa.",INVALID_COORDINATES:"Revise latitude e longitude."};setMessage(messages[code]??"Não foi possível salvar a loja.");setSaving(false);return;}
  setMessage("Loja atualizada pela Matriz. As alterações já passam a valer para o Painel Lojista e App Cliente.");await load(selectedId);setSaving(false);
 }
 async function saveStatus(){if(!selectedId||!["ACTIVE","SUSPENDED","BLOCKED"].includes(status))return;setSaving(true);const{data,error}=await supabase.functions.invoke("admin-operations",{body:{action:"STORE_STATUS",storeId:selectedId,status}});setMessage(error||data?.error?"Não foi possível alterar o status da loja.":"Status da loja atualizado pela Matriz.");await load(selectedId);setSaving(false);}
 if(loading)return <main className="adminPage"><div className="adminPanel">Carregando lojas...</div></main>;
 if(!allowed)return <main className="adminPage"><div className="adminPanel"><h1>Acesso restrito</h1><p>Somente Super Admin ou Admin da Matriz pode editar lojas.</p></div></main>;
 return <main className="adminPage"><header className="adminHeader"><div><small>MATRIZ • LOJAS</small><h1>Editar loja</h1><p>A Matriz controla os dados administrativos da loja. O Lojista opera dentro das liberações definidas pela Matriz.</p></div><a className="adminLink" href="/">← Matriz</a></header>
  {message&&<div className="adminNotice">{message}</div>}
  <section className="adminPanel" style={{marginBottom:18}}><label>Loja<select value={selectedId} onChange={e=>selectStore(e.target.value)}>{stores.map(s=><option value={s.id} key={s.id}>{s.name} • {s.status}</option>)}</select></label></section>
  {!selectedId?<section className="adminPanel"><p>Nenhuma loja cadastrada.</p></section>:<form className="adminPanel adminForm" onSubmit={save}>
   <h2>Dados da loja</h2><div className="adminGrid2">
    <label>Nome público<input value={draft.name} maxLength={120} onChange={e=>field("name",e.target.value)} required/></label><label>Identificador (slug)<input value={draft.slug} maxLength={120} onChange={e=>field("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))} required/></label>
    <label>Documento<input value={draft.document} maxLength={40} onChange={e=>field("document",e.target.value)}/></label><label>Cidade<select value={draft.cityId} onChange={e=>field("cityId",e.target.value)}><option value="">Sem cidade vinculada</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></label>
    <label>Telefone<input value={draft.phone} maxLength={30} onChange={e=>field("phone",e.target.value)}/></label><label>E-mail<input type="email" value={draft.email} maxLength={160} onChange={e=>field("email",e.target.value)}/></label>
    <label>WhatsApp<input value={draft.whatsapp} maxLength={30} onChange={e=>field("whatsapp",e.target.value)}/></label><label>Instagram<input value={draft.instagram} maxLength={80} onChange={e=>field("instagram",e.target.value)}/></label>
   </div><label>Slogan<input value={draft.slogan} maxLength={140} onChange={e=>field("slogan",e.target.value)}/></label><label>Descrição<textarea value={draft.description} maxLength={1200} onChange={e=>field("description",e.target.value)}/></label>
   <h2>Endereço e operação</h2><div className="adminGrid2"><label>Endereço<input value={draft.addressLine} maxLength={180} onChange={e=>field("addressLine",e.target.value)}/></label><label>Bairro<input value={draft.neighborhood} maxLength={100} onChange={e=>field("neighborhood",e.target.value)}/></label><label>CEP<input value={draft.postalCode} maxLength={20} onChange={e=>field("postalCode",e.target.value)}/></label><label>Complemento<input value={draft.addressComplement} maxLength={120} onChange={e=>field("addressComplement",e.target.value)}/></label><label>Pedido mínimo<input inputMode="decimal" value={draft.minimumOrder} onChange={e=>field("minimumOrder",e.target.value)}/></label><label>Tempo médio de preparo (min)<input inputMode="numeric" value={draft.preparationTime} onChange={e=>field("preparationTime",e.target.value)}/></label><label>Latitude<input value={draft.latitude} onChange={e=>field("latitude",e.target.value)}/></label><label>Longitude<input value={draft.longitude} onChange={e=>field("longitude",e.target.value)}/></label><label>Cor principal<input value={draft.primaryColor} maxLength={7} onChange={e=>field("primaryColor",e.target.value.toUpperCase())}/></label><label>Cor de contraste<input value={draft.secondaryColor} maxLength={7} onChange={e=>field("secondaryColor",e.target.value.toUpperCase())}/></label></div>
   <button className="primaryAction" disabled={saving}>{saving?"SALVANDO...":"SALVAR ALTERAÇÕES DA LOJA"}</button>
   <div style={{marginTop:20,paddingTop:16,borderTop:"1px solid #e5e5e5"}}><h2>Status controlado pela Matriz</h2><div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><label style={{minWidth:220}}>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">ATIVA</option><option value="SUSPENDED">SUSPENSA</option><option value="BLOCKED">BLOQUEADA</option></select></label><button type="button" onClick={()=>void saveStatus()} disabled={saving}>APLICAR STATUS</button></div></div>
  </form>}
 </main>;
}
