"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Ticket={id:string;category:string;priority:string;status:string;subject:string;created_at:string;updated_at:string};type Msg={id:string;sender_id:string;body:string;created_at:string};
export default function Suporte(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[tickets,setTickets]=useState<Ticket[]>([]);const[selected,setSelected]=useState<Ticket|null>(null);const[messages,setMessages]=useState<Msg[]>([]);const[notice,setNotice]=useState("");const[form,setForm]=useState({category:"OPERACAO",priority:"NORMAL",subject:"",message:""});const[reply,setReply]=useState("");
 async function boot(){const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre no Painel do Lojista primeiro.");setLoading(false);return;}const{data:m}=await supabase.from("store_memberships").select("store_id,stores!inner(name)").eq("user_id",s.session.user.id).eq("active",true).limit(1);if(!m?.length){setNotice("Conta sem loja vinculada.");setLoading(false);return;}const row:any=m[0],rel=Array.isArray(row.stores)?row.stores[0]:row.stores;setStoreId(row.store_id);setStoreName(rel?.name??"Minha loja");await loadTickets(row.store_id);setLoading(false);}
 async function loadTickets(id=storeId){if(!id)return;const{data}=await supabase.from("support_tickets").select("id,category,priority,status,subject,created_at,updated_at").eq("store_id",id).order("updated_at",{ascending:false});setTickets((data??[]) as Ticket[]);}
 async function openTicket(ticket:Ticket){setSelected(ticket);const{data}=await supabase.from("support_messages").select("id,sender_id,body,created_at").eq("ticket_id",ticket.id).order("created_at");setMessages((data??[]) as Msg[]);}
 useEffect(()=>{boot();},[]);
 async function createTicket(e:FormEvent){e.preventDefault();const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"CREATE",storeId,category:form.category,priority:form.priority,subject:form.subject,message:form.message}});if(error||data?.error){setNotice("Não foi possível abrir o chamado.");return;}setForm({...form,subject:"",message:""});setNotice("Chamado aberto com sucesso.");await loadTickets(storeId);}
 async function sendReply(e:FormEvent){e.preventDefault();if(!selected||!reply.trim())return;const{data,error}=await supabase.functions.invoke("support-action",{body:{action:"REPLY",ticketId:selected.id,message:reply}});if(error||data?.error){setNotice("Não foi possível enviar a mensagem.");return;}setReply("");setNotice("Mensagem enviada.");await openTicket(selected);await loadTickets(storeId);}
 if(loading)return <main className="configPage"><div className="configShell">Carregando suporte...</div></main>;
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>{storeName}</small><h1>Central de suporte</h1></div><a className="backLink" href="/">← Voltar ao painel</a></header>{notice&&<div className="setupMessage">{notice}</div>}<div className="managementGrid two"><form className="mgCard" onSubmit={createTicket}><h2>Novo chamado</h2><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="OPERACAO">Operação</option><option value="PEDIDO">Pedido</option><option value="ENTREGADOR">Entregador</option><option value="PAGAMENTO">Pagamento</option><option value="PDV">PDV</option><option value="CONTA">Conta</option><option value="OUTRO">Outro</option></select></label><label>Prioridade<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="LOW">Baixa</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></label><label>Assunto<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></label><label>Mensagem<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} required/></label><button className="setupPrimary">ABRIR CHAMADO</button></form><section className="mgCard"><h2>Meus chamados</h2><div className="dataList">{tickets.map(ticket=><button className="dataRow ticketButton" key={ticket.id} onClick={()=>openTicket(ticket)}><div><b>{ticket.subject}</b><small>{ticket.category} • {new Date(ticket.created_at).toLocaleDateString("pt-BR")}</small></div><span>{ticket.status}</span></button>)}{!tickets.length&&<div className="emptyRow">Nenhum chamado.</div>}</div></section></div>{selected&&<section className="mgCard supportThread"><h2>{selected.subject}</h2><p>{selected.status} • {selected.priority}</p><div className="supportMessages">{messages.map(m=><div className="supportMessage" key={m.id}><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString("pt-BR")}</small></div>)}</div><form onSubmit={sendReply}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Digite sua resposta..."/><button className="setupPrimary">ENVIAR RESPOSTA</button></form></section>}</div></main>;
}
