"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../../lib/supabase";

type Order={id:string;order_number:number;status:string;created_at:string;customer_id:string|null};
type Msg={id:string;sender_id:string;content:string;created_at:string};
type ChatType="CUSTOMER_STORE"|"STORE_DRIVER";
const terminal=["DELIVERED","CANCELLED","REJECTED","REFUNDED"];
const statusLabel:Record<string,string>={WAITING_STORE:"Aguardando aceite",ACCEPTED:"Aceito",PREPARING:"Em preparo",READY:"Pronto",WAITING_DRIVER:"Procurando entregador",DRIVER_ASSIGNED:"Entregador confirmado",PICKUP_CONFIRMED:"Retirado",DRIVER_TO_CUSTOMER:"Em rota",DRIVER_AT_CUSTOMER:"No cliente"};

export default function ChatLojista(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState<string|null>(null);const[userId,setUserId]=useState<string|null>(null);const[orders,setOrders]=useState<Order[]>([]);const[selected,setSelected]=useState<Order|null>(null);const[type,setType]=useState<ChatType>("CUSTOMER_STORE");const[conversationId,setConversationId]=useState<string|null>(null);const[messages,setMessages]=useState<Msg[]>([]);const[text,setText]=useState("");const[notice,setNotice]=useState("");const[sending,setSending]=useState(false);const scroll=useRef<HTMLDivElement>(null);
 async function load(){setLoading(true);setNotice("");const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre no Painel Lojista primeiro.");setLoading(false);return;}setUserId(s.session.user.id);const{data:m}=await supabase.from("store_memberships").select("store_id,role").eq("user_id",s.session.user.id).eq("active",true).in("role",["OWNER","MANAGER","EXPEDITION"]).limit(1).maybeSingle();if(!m){setNotice("Seu usuário não possui permissão para o chat operacional.");setLoading(false);return;}setStoreId(m.store_id);const{data:o,error}=await supabase.from("orders").select("id,order_number,status,created_at,customer_id").eq("store_id",m.store_id).order("created_at",{ascending:false}).limit(100);if(error){setNotice("Não foi possível carregar os pedidos.");setLoading(false);return;}const active=((o??[]) as Order[]).filter(order=>!terminal.includes(order.status));setOrders(active);if(selected){const updated=active.find(x=>x.id===selected.id);setSelected(updated??null);}setLoading(false);}
 useEffect(()=>{load();},[]);
 async function openChat(order:Order,nextType:ChatType=type){setSelected(order);setType(nextType);setNotice("");const{data,error}=await supabase.functions.invoke("order-chat",{body:{orderId:order.id,type:nextType}});if(error||data?.error){setConversationId(null);setMessages([]);setNotice(data?.error==="DRIVER_NOT_ASSIGNED"?"Ainda não há entregador atribuído a este pedido.":data?.error==="CUSTOMER_NOT_AVAILABLE"?"Este pedido não possui cliente no aplicativo.":"Não foi possível abrir esta conversa.");return;}setConversationId(data.conversation.id);await loadMessages(data.conversation.id);}
 async function loadMessages(id=conversationId){if(!id)return;const{data}=await supabase.from("messages").select("id,sender_id,content,created_at").eq("conversation_id",id).order("created_at",{ascending:true}).limit(300);setMessages((data??[]) as Msg[]);setTimeout(()=>scroll.current?.scrollTo({top:scroll.current.scrollHeight}),20);}
 useEffect(()=>{if(!conversationId)return;const channel=supabase.channel(`merchant-chat-${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>{const row=payload.new as Msg;setMessages(current=>current.some(m=>m.id===row.id)?current:[...current,row]);setTimeout(()=>scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:"smooth"}),30);}).subscribe();return()=>{supabase.removeChannel(channel);};},[conversationId]);
 async function send(){const content=text.trim();if(!conversationId||!content)return;setSending(true);setNotice("");const{data,error}=await supabase.functions.invoke("send-message",{body:{conversationId,content}});if(error||data?.error){setNotice(data?.error==="CONTACT_SHARING_BLOCKED"?"Por segurança, telefone, e-mail, links e redes sociais não podem ser enviados.":"Não foi possível enviar a mensagem.");setSending(false);return;}setText("");setSending(false);}
 const pending=useMemo(()=>orders.filter(o=>o.customer_id).length,[orders]);
 if(loading)return <main className="authPage"><div className="authCard">Carregando chat...</div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">PAINEL LOJISTA</p><h1>Chat dos pedidos</h1><p>Cliente ↔ Loja ↔ Entregador, sem troca de contatos externos.</p></div><a className="logout" href="/">← Voltar ao painel</a></header>{notice&&<div className="notice">{notice}</div>}<div className="metricGrid"><article className="metric"><p>Pedidos ativos</p><strong>{orders.length}</strong></article><article className="metric"><p>Com cliente no app</p><strong>{pending}</strong></article></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(260px,340px) 1fr",gap:16,alignItems:"stretch"}}><section className="panel"><div className="panelTitle"><h2>Conversas</h2><button className="primary" onClick={load}>Atualizar</button></div><div className="adminDataList">{orders.map(order=><button key={order.id} onClick={()=>openChat(order)} style={{width:"100%",textAlign:"left",border:selected?.id===order.id?"2px solid #f4c400":"1px solid #e8e8e8",background:"#fff",borderRadius:13,padding:13,cursor:"pointer"}}><b>Pedido #{order.order_number}</b><small style={{display:"block",marginTop:5,color:"#777"}}>{statusLabel[order.status]??order.status} • {new Date(order.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></button>)}{!orders.length&&<div className="emptyState">Nenhum pedido ativo.</div>}</div></section>
 <section className="panel" style={{display:"flex",flexDirection:"column",minHeight:580}}><div className="panelTitle"><div><h2>{selected?`Pedido #${selected.order_number}`:"Selecione um pedido"}</h2><small>Mensagens moderadas pelo CLICK-FOOD</small></div>{selected&&<div className="adminActions"><button className={type==="CUSTOMER_STORE"?"primary":""} onClick={()=>openChat(selected,"CUSTOMER_STORE")}>Cliente</button><button className={type==="STORE_DRIVER"?"primary":""} onClick={()=>openChat(selected,"STORE_DRIVER")}>Entregador</button></div>}</div><div ref={scroll} style={{flex:1,minHeight:390,maxHeight:500,overflowY:"auto",padding:12,background:"#f8f8f8",borderRadius:14}}>{messages.map(m=>{const mine=m.sender_id===userId;return <div key={m.id} style={{maxWidth:"78%",marginLeft:mine?"auto":0,marginBottom:8,background:mine?"#111":"#fff",color:mine?"#fff":"#222",padding:"10px 12px",borderRadius:14,border:mine?"none":"1px solid #e5e5e5"}}><div>{m.content}</div><small style={{display:"block",textAlign:"right",marginTop:5,opacity:.65}}>{new Date(m.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></div>})}{conversationId&&!messages.length&&<div className="emptyState">Nenhuma mensagem ainda.</div>}{!conversationId&&<div className="emptyState">Escolha um pedido e um canal para começar.</div>}</div><div style={{display:"flex",gap:8,marginTop:12}}><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Digite sua mensagem" style={{flex:1,minHeight:56,resize:"vertical",border:"1px solid #ddd",borderRadius:12,padding:11,font:"inherit"}}/><button className="primary" disabled={!conversationId||!text.trim()||sending} onClick={send}>{sending?"Enviando...":"Enviar"}</button></div><small style={{marginTop:8,color:"#777"}}>Telefone, e-mail, links e redes sociais são bloqueados automaticamente por segurança.</small></section></div>
 </main>;
}
