"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Payout={id:string;amount:number;method:string;status:string;destination_value:string|null;review_notes:string|null;requested_at:string;processed_at:string|null};
type Ledger={direction:string;amount:number;status:string};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const mask=(v:string|null)=>{if(!v)return"-";if(v.length<=6)return"••••";return `${v.slice(0,3)}••••${v.slice(-3)}`;};

export default function Repasses(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[role,setRole]=useState("");const[message,setMessage]=useState("");const[payouts,setPayouts]=useState<Payout[]>([]);const[ledger,setLedger]=useState<Ledger[]>([]);const[form,setForm]=useState({amount:"",method:"PIX",destinationValue:""});const[busy,setBusy]=useState(false);
 const canManage=["OWNER","MANAGER"].includes(role);
 const available=useMemo(()=>ledger.filter(x=>x.status!=="VOID").reduce((sum,x)=>sum+(x.direction==="CREDIT"?Number(x.amount):-Number(x.amount)),0),[ledger]);
 async function boot(){setLoading(true);const{data:sd}=await supabase.auth.getSession();if(!sd.session){setMessage("Entre no Painel Lojista.");setLoading(false);return;}const{data}=await supabase.from("store_memberships").select("store_id,role,stores(name)").eq("user_id",sd.session.user.id).eq("active",true).limit(1);if(!data?.length){setMessage("Conta sem loja vinculada.");setLoading(false);return;}const m:any=data[0],s=Array.isArray(m.stores)?m.stores[0]:m.stores;setStoreId(m.store_id);setStoreName(s?.name??"Minha loja");setRole(m.role);await load(m.store_id);setLoading(false);}
 async function load(id=storeId){if(!id)return;const[pR,lR]=await Promise.all([supabase.from("payouts").select("id,amount,method,status,destination_value,review_notes,requested_at,processed_at").eq("recipient_type","STORE").eq("store_id",id).order("requested_at",{ascending:false}).limit(100),supabase.from("financial_transactions").select("direction,amount,status").eq("store_id",id).in("status",["POSTED","PENDING"])]);setPayouts((pR.data??[]).map((x:any)=>({...x,amount:Number(x.amount)})));setLedger((lR.data??[]).map((x:any)=>({...x,amount:Number(x.amount)})));}
 useEffect(()=>{boot();},[]);
 async function request(e:FormEvent){e.preventDefault();if(!canManage)return;const amount=Number(form.amount.replace(",","."));if(!Number.isFinite(amount)||amount<=0){setMessage("Informe um valor válido.");return;}if(amount>available){setMessage("O valor solicitado é maior que o saldo disponível.");return;}if(!form.destinationValue.trim()){setMessage("Informe a chave PIX ou destino do repasse.");return;}setBusy(true);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"REQUEST",storeId,amount,method:form.method,destinationValue:form.destinationValue}});setBusy(false);if(error||data?.error){setMessage(data?.error==="INSUFFICIENT_AVAILABLE_BALANCE"?"Saldo disponível insuficiente.":"Não foi possível solicitar o repasse.");return;}setForm({...form,amount:""});setMessage("Repasse solicitado e valor reservado no saldo.");await load();}
 async function cancel(id:string){setBusy(true);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"CANCEL",payoutId:id}});setBusy(false);setMessage(error||data?.error?"Não foi possível cancelar o repasse.":"Solicitação cancelada e saldo liberado.");await load();}
 if(loading)return <main className="configPage"><div className="configShell">Carregando repasses...</div></main>;
 return <main className="configPage"><div className="configShell"><div className="setupTitle"><div><small>CLICK-FOOD • {storeName}</small><h1>Repasses</h1></div><span>{role}</span></div>{message&&<div className="setupMessage">{message}</div>}
  <section className="setupGrid"><article className="setupCard"><small>SALDO DISPONÍVEL</small><h2 style={{fontSize:32,margin:"8px 0"}}>{brl(available)}</h2><p className="setupHint">Pedidos de repasse ficam reservados no ledger imediatamente para evitar saque duplicado.</p></article><article className="setupCard"><h2>Solicitar repasse</h2>{!canManage&&<div className="notice">Somente Proprietário ou Gerente pode solicitar repasse.</div>}<form onSubmit={request}><label>Valor<input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label>Método<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="PIX">PIX</option><option value="BANK_TRANSFER">Transferência bancária</option><option value="OTHER">Outro</option></select></label><label>Chave PIX / destino<input value={form.destinationValue} onChange={e=>setForm({...form,destinationValue:e.target.value})} placeholder="CPF, CNPJ, e-mail, telefone ou chave aleatória"/></label><button className="setupPrimary" disabled={!canManage||busy}>{busy?"PROCESSANDO...":"SOLICITAR REPASSE"}</button></form></article><article className="setupCard hoursCard"><div className="setupTitle"><div><small>HISTÓRICO</small><h2>Solicitações</h2></div><span>{payouts.length}</span></div><div className="setupList">{payouts.map(p=><div key={p.id}><div><b>{brl(p.amount)} • {p.status}</b><small>{p.method} • destino {mask(p.destination_value)} • solicitado {dt(p.requested_at)}{p.processed_at?` • processado ${dt(p.processed_at)}`:""}{p.review_notes?` • ${p.review_notes}`:""}</small></div>{p.status==="REQUESTED"&&canManage?<button disabled={busy} onClick={()=>cancel(p.id)}>Cancelar</button>:<span>{p.status}</span>}</div>)}{!payouts.length&&<p className="setupHint">Nenhum repasse solicitado.</p>}</div></article></section>
 </div></main>;
}
