"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Payout={id:string;amount:number;gross_amount?:number;anticipation?:boolean;anticipation_fee?:number;anticipation_days?:number;method:string;status:string;destination_value:string|null;review_notes:string|null;requested_at:string;processed_at:string|null;automatic_payout?:boolean};
type Anticipation={availableGross:number;fee:number;net:number;maxDays:number;minRateMonthly:number;maxRateMonthly:number;details:any[]};
type PixType="CPF"|"CNPJ"|"EMAIL"|"PHONE"|"RANDOM";
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const dt=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const mask=(v:string|null)=>{if(!v)return"-";if(v.length<=6)return"••••";return `${v.slice(0,3)}••••${v.slice(-3)}`;};
const requestError=(code?:string)=>({INVALID_PIX_KEY:"A chave PIX informada é inválida. Use CPF, CNPJ, e-mail, telefone ou chave aleatória válida.",INVALID_AMOUNT:"Informe um valor válido com até duas casas decimais.",INVALID_METHOD:"Selecione um método de repasse válido.",INSUFFICIENT_AVAILABLE_BALANCE:"O saldo disponível mudou. Atualize e tente novamente.",STORE_MANAGER_REQUIRED:"Somente Proprietário ou Gerente pode movimentar repasses."}[String(code??"")]??"Não foi possível solicitar o repasse.");

export default function Repasses(){
 const[loading,setLoading]=useState(true);const[storeId,setStoreId]=useState("");const[storeName,setStoreName]=useState("");const[role,setRole]=useState("");const[message,setMessage]=useState("");const[payouts,setPayouts]=useState<Payout[]>([]);const[available,setAvailable]=useState(0);const[form,setForm]=useState({amount:"",method:"PIX",destinationValue:""});const[busy,setBusy]=useState(false);
 const[pixType,setPixType]=useState<PixType>("CNPJ");const[pixKey,setPixKey]=useState("");const[automatic,setAutomatic]=useState(false);const[minimum,setMinimum]=useState("1,00");const[profileBusy,setProfileBusy]=useState(false);const[profileSaved,setProfileSaved]=useState(false);const[anticipation,setAnticipation]=useState<Anticipation>({availableGross:0,fee:0,net:0,maxDays:0,minRateMonthly:0,maxRateMonthly:0,details:[]});const[antAmount,setAntAmount]=useState("");const[antPreview,setAntPreview]=useState<Anticipation|null>(null);
 const canManage=["OWNER","MANAGER"].includes(role);
 async function boot(){setLoading(true);const{data:sd}=await supabase.auth.getSession();if(!sd.session){setMessage("Entre no Painel Lojista.");setLoading(false);return;}const{data}=await supabase.from("store_memberships").select("store_id,role,stores(name)").eq("user_id",sd.session.user.id).eq("active",true).limit(1);if(!data?.length){setMessage("Conta sem loja vinculada.");setLoading(false);return;}const m:any=data[0],s=Array.isArray(m.stores)?m.stores[0]:m.stores;setStoreId(m.store_id);setStoreName(s?.name??"Minha loja");setRole(m.role);if(!["OWNER","MANAGER"].includes(m.role)){setMessage("Somente Proprietário ou Gerente pode acessar os repasses financeiros.");setLoading(false);return;}await Promise.all([load(m.store_id),loadProfile(m.store_id)]);setLoading(false);}
 async function load(id=storeId){if(!id)return;const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"STORE_SUMMARY",storeId:id}});if(error||data?.error){setMessage(data?.error==="STORE_MANAGER_REQUIRED"?"Seu perfil não possui acesso aos repasses.":"Não foi possível consultar saldo e repasses agora.");return;}setAvailable(Number(data.availableBalance??0));setAnticipation({...{availableGross:0,fee:0,net:0,maxDays:0,minRateMonthly:0,maxRateMonthly:0,details:[]},...(data.anticipation??{})});setPayouts((data.payouts??[]).map((x:any)=>({...x,amount:Number(x.amount),gross_amount:Number(x.gross_amount??x.amount),anticipation_fee:Number(x.anticipation_fee??0)})));}
 async function loadProfile(id=storeId){if(!id)return;const{data,error}=await supabase.functions.invoke("payout-profile-action",{body:{action:"READ_STORE",storeId:id}});if(error||data?.error){setProfileSaved(false);return;}const p=data?.profile;if(!p){setProfileSaved(false);return;}setPixType(String(p.pix_key_type??"CNPJ") as PixType);setPixKey(String(p.pix_key??""));setAutomatic(Boolean(p.automatic_payout));setMinimum(Number(p.minimum_payout??1).toFixed(2).replace(".",","));setProfileSaved(true);}
 useEffect(()=>{boot();},[]);
 async function request(e:FormEvent){e.preventDefault();if(!canManage)return;const amount=Number(form.amount.replace(",","."));if(!Number.isFinite(amount)||amount<=0){setMessage("Informe um valor válido.");return;}if(amount>available+0.001){setMessage("O valor solicitado é maior que o saldo disponível.");return;}if(!form.destinationValue.trim()){setMessage(form.method==="PIX"?"Informe a chave PIX que receberá o repasse.":"Informe o destino do repasse.");return;}setBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"REQUEST",storeId,amount,method:form.method,destinationValue:form.destinationValue}});setBusy(false);if(error||data?.error){setMessage(requestError(data?.error));await load();return;}setForm({...form,amount:"",destinationValue:""});setMessage("Repasse solicitado e valor reservado no saldo.");await load();}
 async function previewAnticipation(){const amount=Number(antAmount.replace(",","."));if(!Number.isFinite(amount)||amount<=0){setMessage("Informe o valor que deseja antecipar.");return;}if(amount>anticipation.availableGross+0.001){setMessage("O valor é maior que o saldo disponível para antecipação.");return;}setBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"STORE_ANTICIPATION_PREVIEW",storeId,amount}});setBusy(false);if(error||data?.error){setAntPreview(null);setMessage(requestError(data?.error));return;}setAntPreview(data.preview);setMessage("Confira a taxa e o valor líquido antes de solicitar.");}
 async function requestAnticipation(){const amount=Number(antAmount.replace(",","."));if(!antPreview||Math.abs(Number(antPreview.requestedGross??amount)-amount)>0.01){setMessage("Calcule novamente a antecipação antes de confirmar.");return;}if(!pixKey.trim()){setMessage("Cadastre a chave PIX da loja antes de antecipar.");return;}if(!window.confirm(`Antecipar ${brl(amount)}? Taxa da Matriz: ${brl(Number(antPreview.fee||0))}. Líquido: ${brl(Number(antPreview.net||0))}.`))return;setBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"REQUEST_ANTICIPATION",storeId,amount,destinationValue:pixKey}});setBusy(false);if(error||data?.error){setMessage(requestError(data?.error));await load();return;}setAntAmount("");setAntPreview(null);setMessage(`Antecipação solicitada. Valor líquido reservado para PIX: ${brl(Number(data?.payout?.amount??0))}.`);await load();}
 async function cancel(id:string){setBusy(true);const{data,error}=await supabase.functions.invoke("payout-action",{body:{action:"CANCEL",payoutId:id}});setBusy(false);setMessage(error||data?.error?"Não foi possível cancelar o repasse.":"Solicitação cancelada e saldo liberado.");await load();}
 async function saveAutomatic(e:FormEvent){e.preventDefault();if(!canManage||!storeId)return;const min=Number(minimum.replace(",","."));if(!Number.isFinite(min)||min<0.01){setMessage("Informe um valor mínimo de repasse válido.");return;}if(!pixKey.trim()){setMessage("Cadastre a chave PIX da loja antes de salvar.");return;}setProfileBusy(true);setMessage("");const{data,error}=await supabase.functions.invoke("payout-profile-action",{body:{action:"SAVE_STORE",storeId,pixKeyType:pixType,pixKey,automaticPayout:automatic,minimumPayout:min}});setProfileBusy(false);if(error||data?.error){const code=String(data?.error??"");setMessage(code==="INVALID_PIX_KEY"?"Confira a chave PIX informada.":code==="INVALID_MINIMUM_PAYOUT"?"Confira o valor mínimo do repasse.":"Não foi possível salvar a configuração de repasse automático.");return;}setProfileSaved(true);setMessage(automatic?"Repasse automático ativado. Somente saldo de PIX/cartão pago e pedido entregue será enviado.":"Configuração PIX salva. Repasse automático permanece desligado.");await loadProfile(storeId);}
 if(loading)return <main className="configPage"><div className="configShell">Carregando repasses...</div></main>;
 return <main className="configPage"><div className="configShell"><div className="setupTitle"><div><small>CLICK-FOOD • {storeName}</small><h1>Repasses</h1></div><span>{role}</span></div>{message&&<div className="setupMessage">{message}</div>}
  <section className="setupGrid"><article className="setupCard"><small>SALDO DISPONÍVEL</small><h2 style={{fontSize:32,margin:"8px 0"}}>{brl(available)}</h2><p className="setupHint">Saldo calculado no backend financeiro do CLICK-FOOD. Solicitações ficam reservadas imediatamente para impedir saque duplicado.</p><button onClick={()=>load()} disabled={busy}>Atualizar saldo</button></article>
  <article className="setupCard"><h2>PIX automático da loja</h2><p className="setupHint">Quando ativado, o CLICK-FOOD pode enviar automaticamente o saldo liquidado de pedidos pagos online por PIX/cartão, depois que o pedido for entregue. Pedidos em dinheiro não entram no automático.</p><form onSubmit={saveAutomatic}><label>Tipo da chave PIX<select value={pixType} onChange={e=>setPixType(e.target.value as PixType)}><option value="CNPJ">CNPJ</option><option value="CPF">CPF</option><option value="EMAIL">E-mail</option><option value="PHONE">Telefone</option><option value="RANDOM">Aleatória</option></select></label><label>Chave PIX<input value={pixKey} onChange={e=>setPixKey(e.target.value)} placeholder="Chave que receberá os repasses"/></label><label>Valor mínimo para enviar<input value={minimum} onChange={e=>setMinimum(e.target.value)} placeholder="1,00"/></label><label style={{display:"flex",gap:10,alignItems:"center"}}><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)} style={{width:18,height:18}}/><span>Ativar repasse automático</span></label><p className="setupHint">{profileSaved?"Configuração PIX cadastrada.":"Ainda não há configuração PIX salva para esta loja."}</p><button className="setupPrimary" disabled={!canManage||profileBusy}>{profileBusy?"SALVANDO...":"SALVAR CONFIGURAÇÃO PIX"}</button></form></article>
  <article className="setupCard"><h2>Antecipação de recebíveis</h2><p className="setupHint">A Matriz define o prazo normal e a taxa mensal. Aqui você antecipa somente recebíveis ainda não vencidos. A taxa é mostrada antes da confirmação e vai integralmente para a Matriz.</p><small>SALDO ANTECIPÁVEL</small><h2 style={{fontSize:28,margin:"8px 0"}}>{brl(Number(anticipation.availableGross||0))}</h2>{anticipation.availableGross>0?<><label>Valor bruto a antecipar<input value={antAmount} onChange={e=>{setAntAmount(e.target.value);setAntPreview(null)}} placeholder="0,00"/></label><button type="button" disabled={busy} onClick={previewAnticipation}>CALCULAR TAXA</button>{antPreview&&<div className="notice" style={{marginTop:10}}><b>Taxa Matriz: {brl(Number(antPreview.fee||0))}</b><br/>Líquido a receber: <b>{brl(Number(antPreview.net||0))}</b><br/>Prazo antecipado: até {Number(antPreview.maxDays||0)} dia(s) • taxa {Number(antPreview.minRateMonthly||0).toFixed(2)}% a.m.{Number(antPreview.maxRateMonthly||0)!==Number(antPreview.minRateMonthly||0)?` a ${Number(antPreview.maxRateMonthly||0).toFixed(2)}% a.m.`:""}<br/><button type="button" className="setupPrimary" style={{marginTop:10}} disabled={busy} onClick={requestAnticipation}>SOLICITAR ANTECIPAÇÃO PIX</button></div>}</>:<p className="setupHint">Nenhum recebível futuro elegível. Quando uma Regra de Divisão ativa gerar valores com D+n, eles aparecerão aqui.</p>}</article>
  <article className="setupCard"><h2>Solicitar repasse manual</h2>{!canManage&&<div className="notice">Somente Proprietário ou Gerente pode solicitar repasse.</div>}<form onSubmit={request}><label>Valor<input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label>Método<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="PIX">PIX</option><option value="BANK_TRANSFER">Transferência bancária</option><option value="OTHER">Outro</option></select></label><label>{form.method==="PIX"?"Chave PIX":"Destino do repasse"}<input value={form.destinationValue} onChange={e=>setForm({...form,destinationValue:e.target.value})} placeholder={form.method==="PIX"?"CPF, CNPJ, e-mail, telefone ou chave aleatória":"Dados do destino"}/></label>{form.method==="PIX"&&<p className="setupHint">A chave é validada e normalizada pelo servidor antes da solicitação ser criada.</p>}<button className="setupPrimary" disabled={!canManage||busy}>{busy?"PROCESSANDO...":"SOLICITAR REPASSE"}</button></form></article>
  <article className="setupCard hoursCard"><div className="setupTitle"><div><small>HISTÓRICO</small><h2>Solicitações</h2></div><span>{payouts.length}</span></div><div className="setupList">{payouts.map(p=><div key={p.id}><div><b>{brl(p.amount)} • {p.status}{p.anticipation?" • ANTECIPAÇÃO":""}{p.automatic_payout?" • AUTOMÁTICO":""}</b><small>{p.anticipation?`Bruto ${brl(Number(p.gross_amount??p.amount))} • taxa Matriz ${brl(Number(p.anticipation_fee??0))} • ${Number(p.anticipation_days??0)} dia(s) • `:""}{p.method} • destino {mask(p.destination_value)} • solicitado {dt(p.requested_at)}{p.processed_at?` • processado ${dt(p.processed_at)}`:""}{p.review_notes?` • ${p.review_notes}`:""}</small></div>{p.status==="REQUESTED"&&canManage?<button disabled={busy} onClick={()=>cancel(p.id)}>Cancelar</button>:<span>{p.status}</span>}</div>)}{!payouts.length&&<p className="setupHint">Nenhum repasse solicitado.</p>}</div></article></section>
 </div></main>;
}
