import React,{useEffect,useState}from"react";
import{Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{supabase}from"./supabase";

type Receipt={order:{orderNumber:number;deliveryType:string;status:string;paymentStatus:string;subtotal:number;deliveryFee:number;discount:number;total:number;notes:string|null;createdAt:string};store:{name:string;phone:string|null}|null;address:any;items:Array<{id:string;name:string;quantity:number;unitPrice:number;totalPrice:number;notes:string|null;options:Array<{name:string;price:number;quantity:number}>}>;payments:Array<{method:string;provider:string|null;status:string;amount:number;paidAt:string|null;createdAt:string}>;refunds:Array<{amount:number;reason:string|null;status:string;createdAt:string;completedAt:string|null}>;delivery:{status:string;fee:number;pickupAt:string|null;deliveredAt:string|null;driver:{name:string;rating:number}|null}|null;history:Array<{status:string;reason:string|null;createdAt:string}>};
type Props={orderId:string|null;onClose:()=>void};
const brl=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
const dt=(value:string|null|undefined)=>value?new Date(value).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"-";
const statusLabel:Record<string,string>={PENDING_PAYMENT:"Aguardando pagamento",WAITING_STORE:"Aguardando loja",ACCEPTED:"Aceito",PREPARING:"Em preparação",READY:"Pronto",WAITING_DRIVER:"Procurando entregador",DRIVER_ASSIGNED:"Entregador confirmado",PICKED_UP:"Retirado",ON_THE_WAY:"A caminho",DELIVERED:"Entregue",CANCELLED:"Cancelado",REJECTED:"Recusado",PAYMENT_FAILED:"Pagamento falhou",REFUNDED:"Estornado"};
const paymentLabel:Record<string,string>={PIX:"PIX",CASH:"Dinheiro",CREDIT_CARD:"Cartão de crédito",DEBIT_CARD:"Cartão de débito",WALLET:"Carteira",OTHER:"Outro"};

export default function CustomerOrderReceipt({orderId,onClose}:Props){
 const[loading,setLoading]=useState(false);const[data,setData]=useState<Receipt|null>(null);const[message,setMessage]=useState("");
 useEffect(()=>{if(!orderId){setData(null);setMessage("");return;}void load(orderId);},[orderId]);
 async function load(id:string){setLoading(true);setMessage("");const result=await supabase.functions.invoke("customer-order-receipt",{body:{orderId:id}});if(result.error||result.data?.error){setMessage("Não foi possível abrir o comprovante deste pedido.");setData(null);setLoading(false);return;}setData(result.data as Receipt);setLoading(false);}
 return <Modal visible={!!orderId} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.brand}><Text style={styles.yellow}>CLICK</Text>-FOOD</Text><Text style={styles.kicker}>COMPROVANTE DO PEDIDO</Text></View><Pressable style={styles.close} onPress={onClose}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={styles.scroll}>
  {loading&&<Text style={styles.center}>Carregando comprovante...</Text>}{!!message&&<Text style={styles.notice}>{message}</Text>}
  {data&&<>
   <View style={styles.hero}><Text style={styles.orderTitle}>Pedido #{data.order.orderNumber}</Text><Text style={styles.meta}>{data.store?.name??"CLICK-FOOD"} • {dt(data.order.createdAt)}</Text><Text style={styles.status}>{statusLabel[data.order.status]??data.order.status}</Text></View>
   <Text style={styles.section}>Itens</Text>{data.items.map(item=><View style={styles.card} key={item.id}><View style={styles.row}><Text style={styles.itemName}>{item.quantity}× {item.name}</Text><Text style={styles.price}>{brl(item.totalPrice)}</Text></View>{item.options.map((option,index)=><Text style={styles.detail} key={`${item.id}-${index}`}>{option.quantity}× {option.name}{option.price?` (+${brl(option.price)})`:""}</Text>)}{!!item.notes&&<Text style={styles.detail}>Obs.: {item.notes}</Text>}</View>)}
   <Text style={styles.section}>Valores</Text><View style={styles.card}><View style={styles.row}><Text>Subtotal</Text><Text>{brl(data.order.subtotal)}</Text></View><View style={styles.row}><Text>Entrega</Text><Text>{brl(data.order.deliveryFee)}</Text></View>{data.order.discount>0&&<View style={styles.row}><Text>Desconto</Text><Text>- {brl(data.order.discount)}</Text></View>}<View style={[styles.row,styles.totalRow]}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>{brl(data.order.total)}</Text></View></View>
   <Text style={styles.section}>Pagamento</Text><View style={styles.card}>{data.payments.length?data.payments.map((payment,index)=><View style={styles.payment} key={index}><Text style={styles.itemName}>{paymentLabel[payment.method]??payment.method} • {payment.status}</Text><Text style={styles.detail}>{brl(payment.amount)}{payment.provider?` • ${payment.provider}`:""}{payment.paidAt?` • confirmado ${dt(payment.paidAt)}`:""}</Text></View>):<Text style={styles.detail}>Nenhum pagamento registrado.</Text>}{data.refunds.map((refund,index)=><View style={styles.refund} key={index}><Text style={styles.itemName}>Estorno • {refund.status}</Text><Text style={styles.detail}>{brl(refund.amount)}{refund.reason?` • ${refund.reason}`:""}{refund.completedAt?` • concluído ${dt(refund.completedAt)}`:""}</Text></View>)}</View>
   {data.order.deliveryType==="DELIVERY"&&<><Text style={styles.section}>Entrega</Text><View style={styles.card}>{data.address&&<Text style={styles.detail}>{data.address.street}, {data.address.number}{data.address.complement?` • ${data.address.complement}`:""}{data.address.district?` • ${data.address.district}`:""}</Text>}{data.delivery?.driver&&<Text style={styles.detail}>Entregador: {data.delivery.driver.name} • ★ {Number(data.delivery.driver.rating).toFixed(1)}</Text>}<Text style={styles.detail}>Status: {data.delivery?.status??"Aguardando"}</Text></View></>}
   <Text style={styles.section}>Histórico</Text><View style={styles.card}>{data.history.map((event,index)=><View style={styles.timeline} key={index}><View style={styles.dot}/><View style={{flex:1}}><Text style={styles.itemName}>{statusLabel[event.status]??event.status}</Text><Text style={styles.detail}>{dt(event.createdAt)}{event.reason?` • ${event.reason}`:""}</Text></View></View>)}</View>
   {!!data.order.notes&&<><Text style={styles.section}>Observação do pedido</Text><View style={styles.card}><Text style={styles.detail}>{data.order.notes}</Text></View></>}
   <Text style={styles.footer}>Comprovante informativo do pedido no CLICK-FOOD. Os valores e estados acima vêm diretamente do backend.</Text>
  </>}
 </ScrollView></SafeAreaView></Modal>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f7f7"},header:{backgroundColor:"#111",padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},brand:{fontSize:22,fontWeight:"900",color:"#fff"},yellow:{color:"#f4c400"},kicker:{fontSize:9,color:"#aaa",fontWeight:"900",letterSpacing:1,marginTop:4},close:{width:42,height:42,borderRadius:21,backgroundColor:"#292929",alignItems:"center",justifyContent:"center"},closeText:{color:"#fff",fontSize:28},scroll:{padding:18,paddingBottom:40},center:{textAlign:"center",padding:30,color:"#777"},notice:{backgroundColor:"#fff4c6",color:"#675100",padding:12,borderRadius:12},hero:{backgroundColor:"#fff",borderRadius:18,padding:17,borderWidth:1,borderColor:"#e5e5e5"},orderTitle:{fontSize:24,fontWeight:"900"},meta:{fontSize:11,color:"#777",marginTop:5},status:{marginTop:10,fontWeight:"900",color:"#8a6d00"},section:{fontSize:18,fontWeight:"900",marginTop:20,marginBottom:9},card:{backgroundColor:"#fff",borderRadius:15,padding:14,borderWidth:1,borderColor:"#e6e6e6",marginBottom:8},row:{flexDirection:"row",justifyContent:"space-between",gap:12,marginBottom:7},itemName:{fontWeight:"900",flex:1},price:{fontWeight:"900",color:"#8d7000"},detail:{fontSize:11,color:"#666",lineHeight:17,marginTop:3},totalRow:{borderTopWidth:1,borderTopColor:"#eee",paddingTop:10,marginTop:5},totalLabel:{fontSize:17,fontWeight:"900"},total:{fontSize:19,fontWeight:"900"},payment:{paddingVertical:6,borderBottomWidth:1,borderBottomColor:"#eee"},refund:{padding:9,borderRadius:10,backgroundColor:"#fff7d7",marginTop:8},timeline:{flexDirection:"row",gap:10,marginBottom:12},dot:{width:10,height:10,borderRadius:5,backgroundColor:"#f4c400",marginTop:4},footer:{fontSize:10,color:"#888",textAlign:"center",lineHeight:15,marginTop:20}});