import React, { useMemo, useState } from "react";
import { Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

export type CustomerProduct={id:string;name:string;description:string|null;price:number;promotional_price:number|null;image_url?:string|null};
export type CustomerVariant={id:string;product_id:string;name:string;price:number;active:boolean};
export type CustomerOptionGroup={id:string;name:string;required:boolean;minimum_choices:number;maximum_choices:number;active:boolean};
export type CustomerOption={id:string;option_group_id:string;name:string;additional_price:number;active:boolean};
export type CustomerPromotion={id:string;name:string;promotion_type:string;discount_value:number;product_id:string|null};
export type SelectedCustomerOption={optionId:string;name:string;price:number;quantity:number};
export type CustomizedItem={productId:string;productName:string;variantId?:string;variantName?:string;unitPrice:number;quantity:number;notes?:string;options:SelectedCustomerOption[]};

type Props={product:CustomerProduct;variants:CustomerVariant[];groups:CustomerOptionGroup[];options:CustomerOption[];promotions:CustomerPromotion[];onCancel:()=>void;onAdd:(item:CustomizedItem)=>void};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);

function promotedPrice(base:number,productId:string,promotions:CustomerPromotion[]){let value=base;for(const promo of promotions.filter(p=>p.product_id===productId)){const d=Number(promo.discount_value);if(promo.promotion_type==="PRODUCT_PRICE")value=Math.min(value,d);else if(promo.promotion_type==="PERCENTAGE"&&d>=0&&d<=100)value=Math.min(value,value*(1-d/100));else if(promo.promotion_type==="FIXED")value=Math.min(value,Math.max(0,value-d));}return Math.max(0,value);}

export default function ProductCustomizer({product,variants,groups,options,promotions,onCancel,onAdd}:Props){
 const[selectedVariantId,setSelectedVariantId]=useState(variants.length===1?variants[0].id:"");const[selected,setSelected]=useState<Record<string,number>>({});const[quantity,setQuantity]=useState(1);const[notes,setNotes]=useState("");const[message,setMessage]=useState("");
 const variant=variants.find(v=>v.id===selectedVariantId);const basePrice=variant?variant.price:Number(product.promotional_price??product.price);const unitPrice=promotedPrice(basePrice,product.id,promotions);const optionsTotal=useMemo(()=>options.reduce((sum,o)=>sum+Number(o.additional_price)*(selected[o.id]??0),0),[options,selected]);const total=(unitPrice+optionsTotal)*quantity;
 function groupCount(groupId:string){return options.filter(o=>o.option_group_id===groupId).reduce((sum,o)=>sum+(selected[o.id]??0),0);}
 function changeOption(option:CustomerOption,delta:number){const group=groups.find(g=>g.id===option.option_group_id);if(!group)return;const current=selected[option.id]??0;const next=Math.max(0,current+delta);const currentGroup=groupCount(group.id);if(delta>0&&currentGroup>=group.maximum_choices){setMessage(`Você pode escolher no máximo ${group.maximum_choices} em ${group.name}.`);return;}setSelected({...selected,[option.id]:next});setMessage("");}
 function add(){if(variants.length&&!variant){setMessage("Escolha uma variação/tamanho para continuar.");return;}for(const group of groups){const count=groupCount(group.id);if(count<group.minimum_choices||(group.required&&count<Math.max(1,group.minimum_choices))){setMessage(`Complete a escolha: ${group.name}.`);return;}if(count>group.maximum_choices){setMessage(`Revise o grupo ${group.name}.`);return;}}const chosen=options.filter(o=>(selected[o.id]??0)>0).map(o=>({optionId:o.id,name:o.name,price:Number(o.additional_price),quantity:selected[o.id]}));onAdd({productId:product.id,productName:product.name,variantId:variant?.id,variantName:variant?.name,unitPrice,quantity,notes:notes.trim()||undefined,options:chosen});}
 return <View style={styles.card}>{product.image_url?<Image source={{uri:product.image_url}} style={styles.heroImage}/>:null}<View style={styles.top}><View style={{flex:1}}><Text style={styles.kicker}>PERSONALIZE SEU ITEM</Text><Text style={styles.title}>{product.name}</Text><Text style={styles.desc}>{product.description||"Escolha as opções antes de adicionar."}</Text></View><Pressable onPress={onCancel} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View>
  {variants.length>0&&<View style={styles.block}><Text style={styles.blockTitle}>Escolha o tamanho/variação *</Text>{variants.map(v=><Pressable key={v.id} style={[styles.choice,selectedVariantId===v.id&&styles.choiceActive]} onPress={()=>{setSelectedVariantId(v.id);setMessage("");}}><View><Text style={styles.choiceName}>{v.name}</Text><Text style={styles.choiceMeta}>{brl(promotedPrice(v.price,product.id,promotions))}</Text></View><Text style={styles.radio}>{selectedVariantId===v.id?"●":"○"}</Text></Pressable>)}</View>}
  {groups.map(group=>{const groupOptions=options.filter(o=>o.option_group_id===group.id);return <View style={styles.block} key={group.id}><View style={styles.groupHeader}><View><Text style={styles.blockTitle}>{group.name}{group.required?" *":""}</Text><Text style={styles.groupMeta}>Escolha {group.minimum_choices} a {group.maximum_choices}</Text></View><Text style={styles.counter}>{groupCount(group.id)}/{group.maximum_choices}</Text></View>{groupOptions.map(option=><View style={styles.optionRow} key={option.id}><View style={{flex:1}}><Text style={styles.choiceName}>{option.name}</Text><Text style={styles.choiceMeta}>{Number(option.additional_price)>0?`+ ${brl(Number(option.additional_price))}`:"Sem acréscimo"}</Text></View><View style={styles.stepper}><Pressable onPress={()=>changeOption(option,-1)}><Text style={styles.step}>−</Text></Pressable><Text style={styles.stepValue}>{selected[option.id]??0}</Text><Pressable onPress={()=>changeOption(option,1)}><Text style={styles.step}>+</Text></Pressable></View></View>)}</View>})}
  <View style={styles.block}><Text style={styles.blockTitle}>Observação</Text><TextInput style={styles.input} placeholder="Ex.: sem cebola, molho separado..." value={notes} onChangeText={setNotes} multiline maxLength={500}/></View>
  <View style={styles.footer}><View style={styles.stepper}><Pressable onPress={()=>setQuantity(Math.max(1,quantity-1))}><Text style={styles.step}>−</Text></Pressable><Text style={styles.stepValue}>{quantity}</Text><Pressable onPress={()=>setQuantity(Math.min(99,quantity+1))}><Text style={styles.step}>+</Text></Pressable></View><View style={{flex:1}}><Text style={styles.totalLabel}>Total do item</Text><Text style={styles.total}>{brl(total)}</Text></View></View>{!!message&&<Text style={styles.message}>{message}</Text>}<Pressable style={styles.add} onPress={add}><Text style={styles.addText}>ADICIONAR AO CARRINHO • {brl(total)}</Text></Pressable><Pressable onPress={onCancel}><Text style={styles.cancel}>Cancelar</Text></Pressable>
 </View>;
}

const styles=StyleSheet.create({card:{backgroundColor:"#fff",borderWidth:2,borderColor:"#f4c400",borderRadius:20,padding:16,marginVertical:12,overflow:"hidden"},heroImage:{width:"100%",height:190,borderRadius:15,marginBottom:14,backgroundColor:"#eee"},top:{flexDirection:"row",gap:10},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.1,color:"#8b7000"},title:{fontSize:22,fontWeight:"900",marginTop:4},desc:{fontSize:11,color:"#777",marginTop:4,lineHeight:16},close:{width:34,height:34,borderRadius:17,backgroundColor:"#f2f2f2",alignItems:"center",justifyContent:"center"},closeText:{fontSize:24,fontWeight:"700"},block:{marginTop:16},blockTitle:{fontWeight:"900",fontSize:14},groupHeader:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:6},groupMeta:{fontSize:10,color:"#777",marginTop:2},counter:{fontSize:10,fontWeight:"900",color:"#8b7000"},choice:{borderWidth:1,borderColor:"#e4e4e4",borderRadius:12,padding:12,marginTop:7,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},choiceActive:{borderColor:"#d6b000",backgroundColor:"#fff9d7"},choiceName:{fontWeight:"800",fontSize:13},choiceMeta:{fontSize:10,color:"#777",marginTop:3},radio:{fontSize:22,color:"#9c7c00"},optionRow:{borderBottomWidth:1,borderBottomColor:"#eee",paddingVertical:10,flexDirection:"row",alignItems:"center",gap:10},stepper:{flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:"#ddd",borderRadius:10,overflow:"hidden"},step:{fontSize:18,fontWeight:"900",paddingHorizontal:12,paddingVertical:7},stepValue:{minWidth:26,textAlign:"center",fontWeight:"900"},input:{borderWidth:1,borderColor:"#ddd",borderRadius:12,padding:12,minHeight:70,marginTop:7,textAlignVertical:"top"},footer:{flexDirection:"row",alignItems:"center",gap:12,marginTop:16},totalLabel:{fontSize:10,color:"#777"},total:{fontSize:22,fontWeight:"900"},message:{backgroundColor:"#fff0d9",color:"#7a4f00",padding:10,borderRadius:10,marginTop:10,fontSize:11},add:{backgroundColor:"#f4c400",padding:15,borderRadius:13,alignItems:"center",marginTop:12},addText:{fontWeight:"900",fontSize:12},cancel:{textAlign:"center",fontWeight:"800",color:"#777",paddingTop:12}});