"use client";
import { useEffect,useState } from "react";
import { supabase } from "../../lib/supabase";
type Delivery={pickup:boolean;ownDelivery:boolean;clickfoodDelivery:boolean};type Payments={cash:boolean;pix:boolean;creditCardOnline:boolean;cardOnDelivery:boolean;debitCardOnDelivery:boolean};const emptyD:Delivery={pickup:false,ownDelivery:false,clickfoodDelivery:false};const emptyP:Payments={cash:false,pix:false,creditCardOnline:false,cardOnDelivery:false,debitCardOnDelivery:false};
export default function Permissoes(){const[stores,setStores]=useState<any[]>([]);const[storeId,setStoreId]=useState("");const[delivery,setDelivery]=useState<Delivery>(emptyD);const[payments,setPayments]=useState<Payments>(emptyP);const[msg,setMsg]=useState("");const[loading,setLoading]=useState(false);
 async function boot(){const{data:r,error}=await supabase.functions.invoke("admin-report-read",{body:{limit:250}});if(error||r?.error)return setMsg("Não foi possível carregar as lojas.");setStores(r.stores??[]);const id=r.stores?.[0]?.id??"";setStoreId(id);if(id)await read(id);}useEffect(()=>{void boot()},[]);
 async function read(id:string){setLoading(true);const{data:r,error}=await supabase.functions.invoke("admin-store-permissions",{body:{action:"READ",storeId:id}});setLoading(false);if(error||r?.error){setMsg("Falha ao ler as permissões.");return;}const d=r.permissions?.delivery,p=r.permissions?.payments;setDelivery({pickup:Boolean(d?.pickup_allowed),ownDelivery:Boolean(d?.own_delivery_allowed),clickfoodDelivery:Boolean(d?.clickfood_delivery_allowed)});setPayments({cash:Boolean(p?.cash_allowed),pix:Boolean(p?.pix_allowed),creditCardOnline:Boolean(p?.credit_card_online_allowed),cardOnDelivery:Boolean(p?.card_on_delivery_allowed),debitCardOnDelivery:Boolean(p?.debit_card_on_delivery_allowed)});}
 async function save(){setLoading(true);const{data:r,error}=await supabase.functions.invoke("admin-store-permissions",{body:{action:"UPDATE",storeId,delivery,payments}});setLoading(false);setMsg(error||r?.error?"Não foi possível salvar as liberações.":"Liberações da loja atualizadas pela Matriz.");}
 const dItems:Array<[keyof Delivery,string]>=[["clickfoodDelivery","Entrega com entregadores CLICK-FOOD"],["ownDelivery","Entrega própria da loja"],["pickup","Retirada na loja"]];const pItems:Array<[keyof Payments,string]>=[["pix","PIX"],["creditCardOnline","Cartão online"],["cash","Dinheiro"],["cardOnDelivery","Crédito na entrega"],["debitCardOnDelivery","Débito na entrega"]];
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>MATRIZ</small><h1>Liberações das lojas</h1><p>A Matriz define quais modalidades e pagamentos cada loja poderá configurar.</p></div><a className="backLink" href="/">← Painel Matriz</a></header><section className="mgCard"><label>Loja<select value={storeId} onChange={e=>{setStoreId(e.target.value);void read(e.target.value)}}>{stores.map(s=><option value={s.id} key={s.id}>{s.name} • {s.status}</option>)}</select></label></section>{msg&&<div className="setupMessage">{msg}</div>}<div className="managementGrid"><section className="mgCard"><h2>Formas de entrega</h2><p>Entregadores CLICK-FOOD são sempre cadastrados e configurados pela Matriz.</p>{dItems.map(([k,l])=><label key={k} style={row}><input type="checkbox" checked={delivery[k]} onChange={e=>setDelivery({...delivery,[k]:e.target.checked})}/><b>{l}</b></label>)}</section><section className="mgCard"><h2>Formas de pagamento</h2><p>O Lojista só poderá ativar opções liberadas aqui.</p>{pItems.map(([k,l])=><label key={k} style={row}><input type="checkbox" checked={payments[k]} onChange={e=>setPayments({...payments,[k]:e.target.checked})}/><b>{l}</b></label>)}</section></div><button className="setupPrimary" onClick={()=>void save()} disabled={loading||!storeId}>{loading?"SALVANDO...":"SALVAR LIBERAÇÕES DA MATRIZ"}</button></div></main>}
const row:React.CSSProperties={display:"flex",alignItems:"center",gap:9,padding:"11px 0",borderBottom:"1px solid #eee"};
