"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "../../lib/supabase";
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const localDate=(d:Date)=>d.toISOString().slice(0,10);
function startDays(days:number){const d=new Date();d.setDate(d.getDate()-days+1);return localDate(d)}
export default function RelatoriosMatriz(){const[from,setFrom]=useState(startDays(7));const[to,setTo]=useState(localDate(new Date()));const[loading,setLoading]=useState(false);const[data,setData]=useState<any>({metrics:{},orders:[],drivers:[],finance:[]});const[msg,setMsg]=useState("");
 async function load(){setLoading(true);setMsg("");const end=new Date(`${to}T00:00:00`);end.setDate(end.getDate()+1);const{data:r,error}=await supabase.functions.invoke("admin-report-read",{body:{from:`${from}T00:00:00`,to:end.toISOString(),limit:150}});setLoading(false);if(error||r?.error){setMsg("Não foi possível carregar o relatório.");return;}setData(r??{});}useEffect(()=>{void load()},[]);
 const driverTotals=useMemo(()=>((data.drivers??[]) as any[]).reduce((a,d)=>({deliveries:a.deliveries+Number(d.period?.deliveries||0),earnings:a.earnings+Number(d.period?.earnings||0)}),{deliveries:0,earnings:0}),[data]);
 return <main className="configPage"><div className="configShell"><header className="configHeader"><div><div className="logo"><span>CLICK</span>-FOOD</div><small>MATRIZ</small><h1>Relatórios da plataforma</h1><p>Dados carregados somente para o período selecionado.</p></div><a className="backLink" href="/">← Painel Matriz</a></header><section className="mgCard"><div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="setupPrimary" onClick={()=>void load()} disabled={loading}>{loading?"CARREGANDO...":"FILTRAR"}</button><button className="setupSecondary" onClick={()=>{setFrom(startDays(7));setTo(localDate(new Date()));}}>7 DIAS</button><button className="setupSecondary" onClick={()=>{setFrom(startDays(30));setTo(localDate(new Date()));}}>30 DIAS</button></div></section>{msg&&<div className="setupMessage">{msg}</div>}<div className="kpis"><article><span>GMV no período</span><b>{brl(Number(data.metrics?.gmv||0))}</b></article><article><span>Pedidos</span><b>{Number(data.metrics?.orders||0)}</b></article><article><span>Entregas concluídas</span><b>{driverTotals.deliveries}</b></article><article><span>Ganhos dos entregadores</span><b>{brl(driverTotals.earnings)}</b></article></div><section className="mgCard"><h2>Entregadores no período</h2><p>Máximo de 150 registros por consulta. Use o filtro para mudar o período.</p><div className="dataList">{(data.drivers??[]).filter((d:any)=>Number(d.period?.deliveries||0)>0).map((d:any)=><div className="dataRow" key={d.id}><div><b>{d.name}</b><small>{d.city||"Sem cidade"} • {d.status} • {d.online?"online":"offline"} • ★ {Number(d.rating||0).toFixed(1)}</small></div><div><b>{d.period?.deliveries||0} entregas</b><small>{brl(Number(d.period?.earnings||0))}</small></div></div>)}</div></section><section className="mgCard"><h2>Pedidos do período</h2><div className="dataList">{(data.orders??[]).slice(0,60).map((o:any)=><div className="dataRow" key={o.id}><div><b>#{o.order_number}</b><small>{new Date(o.created_at).toLocaleString("pt-BR")} • {o.source} • {o.delivery_type}</small></div><div><b>{brl(Number(o.total))}</b><small>{o.status}</small></div></div>)}</div></section></div></main>}
