"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type Store={id:string;name:string};
type Campaign={id:string;store_id:string|null;name:string;description:string|null;campaign_type:string;starts_at:string|null;ends_at:string|null;active:boolean;created_at:string};
type Coupon={id:string;store_id:string|null;code:string;discount_type:string;discount_value:number;minimum_order:number;max_uses:number|null;max_uses_per_customer:number|null;starts_at:string|null;ends_at:string|null;active:boolean;created_at:string};
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const when=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"sem limite";

export default function Marketing(){
 const[loading,setLoading]=useState(true);const[authorized,setAuthorized]=useState(false);const[message,setMessage]=useState("");const[stores,setStores]=useState<Store[]>([]);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[coupons,setCoupons]=useState<Coupon[]>([]);
 const[campaign,setCampaign]=useState({name:"",description:"",storeId:"",startsAt:"",endsAt:""});
 const[coupon,setCoupon]=useState({code:"",storeId:"",discountType:"PERCENTAGE",discountValue:"10",minimumOrder:"0",maxUses:"",maxPerCustomer:"1",startsAt:"",endsAt:"",firstOrderOnly:false});
 const storeMap=useMemo(()=>new Map(stores.map(s=>[s.id,s.name])),[stores]);
 async function load(){setLoading(true);const{data:sd}=await supabase.auth.getSession();const session=sd.session;if(!session){setAuthorized(false);setLoading(false);return;}const role=String(session.user.app_metadata?.clickfood_role??"");const ok=["SUPER_ADMIN","ADMIN"].includes(role);setAuthorized(ok);if(!ok){setLoading(false);return;}const[sR,cR,cpR]=await Promise.all([supabase.from("stores").select("id,name").order("name"),supabase.from("campaigns").select("id,store_id,name,description,campaign_type,starts_at,ends_at,active,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("coupons").select("id,store_id,code,discount_type,discount_value,minimum_order,max_uses,max_uses_per_customer,starts_at,ends_at,active,created_at").order("created_at",{ascending:false}).limit(100)]);setStores((sR.data??[]) as Store[]);setCampaigns((cR.data??[]) as Campaign[]);setCoupons((cpR.data??[]).map((x:any)=>({...x,discount_value:Number(x.discount_value),minimum_order:Number(x.minimum_order)})));setLoading(false);}
 useEffect(()=>{load();},[]);
 function iso(v:string){return v?new Date(v).toISOString():null;}
 async function createCampaign(e:FormEvent){e.preventDefault();setMessage("");if(!campaign.name.trim()){setMessage("Informe o nome da campanha.");return;}const{data,error}=await supabase.functions.invoke("admin-marketing",{body:{action:"CREATE_CAMPAIGN",name:campaign.name,description:campaign.description,storeId:campaign.storeId||null,startsAt:iso(campaign.startsAt),endsAt:iso(campaign.endsAt),campaignType:"PROMOTION"}});if(error||data?.error){setMessage(data?.error==="INVALID_PERIOD"?"Revise o período da campanha.":"Não foi possível criar a campanha.");return;}setCampaign({name:"",description:"",storeId:"",startsAt:"",endsAt:""});setMessage("Campanha criada.");await load();}
 async function createCoupon(e:FormEvent){e.preventDefault();setMessage("");const value=Number(coupon.discountValue.replace(",",".")),minimum=Number(coupon.minimumOrder.replace(",","."));const{data,error}=await supabase.functions.invoke("admin-marketing",{body:{action:"CREATE_COUPON",code:coupon.code,storeId:coupon.storeId||null,discountType:coupon.discountType,discountValue:value,minimumOrder:minimum,maxUses:coupon.maxUses?Number(coupon.maxUses):null,maxUsesPerCustomer:coupon.maxPerCustomer?Number(coupon.maxPerCustomer):null,startsAt:iso(coupon.startsAt),endsAt:iso(coupon.endsAt),firstOrderOnly:coupon.firstOrderOnly}});if(error||data?.error){setMessage(data?.error==="COUPON_EXISTS"?"Já existe um cupom com esse código.":data?.error==="INVALID_PERCENTAGE"?"O percentual deve ser de 0 a 100%.":"Não foi possível criar o cupom.");return;}setCoupon({...coupon,code:""});setMessage("Cupom criado.");await load();}
 async function toggleCampaign(c:Campaign){const{data,error}=await supabase.functions.invoke("admin-marketing",{body:{action:"TOGGLE_CAMPAIGN",campaignId:c.id,active:!c.active}});setMessage(error||data?.error?"Falha ao alterar campanha.":"Campanha atualizada.");await load();}
 async function toggleCoupon(c:Coupon){const{data,error}=await supabase.functions.invoke("admin-marketing",{body:{action:"TOGGLE_COUPON",couponId:c.id,active:!c.active}});setMessage(error||data?.error?"Falha ao alterar cupom.":"Cupom atualizado.");await load();}
 if(loading)return <main className="authPage"><div className="authCard">Carregando marketing...</div></main>;
 if(!authorized)return <main className="authPage"><div className="authCard"><h1>Acesso restrito</h1><p>Entre na Matriz com perfil Super Admin ou Admin.</p><a href="/">Voltar</a></div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">MATRIZ CLICK-FOOD</p><h1>Marketing global</h1><small>Campanhas e cupons controlados pela Matriz</small></div><button className="logout" onClick={load}>Atualizar</button></header>{message&&<div className="notice">{message}</div>}
  <div className="twoColumns"><form className="panel formPanel" onSubmit={createCampaign}><h2>Nova campanha</h2><label>Nome<input value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})} required/></label><label>Descrição<textarea value={campaign.description} onChange={e=>setCampaign({...campaign,description:e.target.value})}/></label><label>Alcance<select value={campaign.storeId} onChange={e=>setCampaign({...campaign,storeId:e.target.value})}><option value="">Toda a plataforma</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="formRow"><label>Início<input type="datetime-local" value={campaign.startsAt} onChange={e=>setCampaign({...campaign,startsAt:e.target.value})}/></label><label>Fim<input type="datetime-local" value={campaign.endsAt} onChange={e=>setCampaign({...campaign,endsAt:e.target.value})}/></label></div><button className="primary wideButton">CRIAR CAMPANHA</button></form>
  <form className="panel formPanel" onSubmit={createCoupon}><h2>Novo cupom global</h2><label>Código<input value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value.toUpperCase()})} required/></label><label>Alcance<select value={coupon.storeId} onChange={e=>setCoupon({...coupon,storeId:e.target.value})}><option value="">Todas as lojas</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="formRow"><label>Tipo<select value={coupon.discountType} onChange={e=>setCoupon({...coupon,discountType:e.target.value})}><option value="PERCENTAGE">Percentual</option><option value="FIXED">Valor fixo</option><option value="FREE_DELIVERY">Entrega grátis</option></select></label><label>Valor<input value={coupon.discountValue} onChange={e=>setCoupon({...coupon,discountValue:e.target.value})}/></label></div><div className="formRow"><label>Pedido mínimo<input value={coupon.minimumOrder} onChange={e=>setCoupon({...coupon,minimumOrder:e.target.value})}/></label><label>Usos totais<input value={coupon.maxUses} onChange={e=>setCoupon({...coupon,maxUses:e.target.value})} placeholder="Ilimitado"/></label></div><div className="formRow"><label>Usos por cliente<input value={coupon.maxPerCustomer} onChange={e=>setCoupon({...coupon,maxPerCustomer:e.target.value})}/></label><label className="checkLine"><input type="checkbox" checked={coupon.firstOrderOnly} onChange={e=>setCoupon({...coupon,firstOrderOnly:e.target.checked})}/> Somente 1º pedido</label></div><div className="formRow"><label>Início<input type="datetime-local" value={coupon.startsAt} onChange={e=>setCoupon({...coupon,startsAt:e.target.value})}/></label><label>Fim<input type="datetime-local" value={coupon.endsAt} onChange={e=>setCoupon({...coupon,endsAt:e.target.value})}/></label></div><button className="primary wideButton">CRIAR CUPOM</button></form></div>
  <div className="twoColumns" style={{marginTop:16}}><section className="panel"><div className="panelTitle"><h2>Campanhas</h2><span>{campaigns.length}</span></div><div className="adminDataList">{campaigns.map(c=><div className="adminDataRow" key={c.id}><div><b>{c.name}</b><small>{c.store_id?storeMap.get(c.store_id)??"Loja específica":"GLOBAL"} • {when(c.starts_at)} → {when(c.ends_at)}</small></div><span className={`badge ${c.active?"active":"blocked"}`}>{c.active?"ATIVA":"PAUSADA"}</span><button onClick={()=>toggleCampaign(c)}>{c.active?"Pausar":"Ativar"}</button></div>)}{!campaigns.length&&<div className="emptyState">Nenhuma campanha criada.</div>}</div></section>
  <section className="panel"><div className="panelTitle"><h2>Cupons</h2><span>{coupons.length}</span></div><div className="adminDataList">{coupons.map(c=><div className="adminDataRow" key={c.id}><div><b>{c.code}</b><small>{c.store_id?storeMap.get(c.store_id)??"Loja específica":"GLOBAL"} • {c.discount_type} {c.discount_type==="FIXED"?brl(c.discount_value):c.discount_type==="PERCENTAGE"?`${c.discount_value}%`:""} • mínimo {brl(c.minimum_order)}</small></div><span className={`badge ${c.active?"active":"blocked"}`}>{c.active?"ATIVO":"PAUSADO"}</span><button onClick={()=>toggleCoupon(c)}>{c.active?"Pausar":"Ativar"}</button></div>)}{!coupons.length&&<div className="emptyState">Nenhum cupom criado.</div>}</div></section></div>
 </main>;
}
