"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Store={id:string;name:string;logo_url:string|null;cover_url:string|null};type Product={id:string;name:string;image_url:string|null;active:boolean};
const accept="image/jpeg,image/png,image/webp";
function extension(file:File){const byType:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};return byType[file.type]??"jpg";}

export default function Midia(){
 const[loading,setLoading]=useState(true);const[store,setStore]=useState<Store|null>(null);const[products,setProducts]=useState<Product[]>([]);const[notice,setNotice]=useState("");const[uploading,setUploading]=useState("");
 async function load(){setLoading(true);setNotice("");const{data:s}=await supabase.auth.getSession();if(!s.session){setNotice("Entre no Painel Lojista primeiro.");setLoading(false);return;}const{data:m,error:me}=await supabase.from("store_memberships").select("store_id,role").eq("user_id",s.session.user.id).eq("active",true).in("role",["OWNER","MANAGER"]).limit(1).maybeSingle();if(me||!m){setNotice("Somente proprietário ou gerente pode alterar as imagens.");setLoading(false);return;}const[st,pr]=await Promise.all([supabase.from("stores").select("id,name,logo_url,cover_url").eq("id",m.store_id).single(),supabase.from("products").select("id,name,image_url,active").eq("store_id",m.store_id).order("name")]);if(st.error||pr.error){setNotice("Não foi possível carregar a mídia.");setLoading(false);return;}setStore(st.data as Store);setProducts((pr.data??[]) as Product[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 function validate(file?:File){if(!file)return"Nenhum arquivo selecionado.";if(!["image/jpeg","image/png","image/webp"].includes(file.type))return"Use JPG, PNG ou WEBP.";if(file.size>8*1024*1024)return"A imagem deve ter no máximo 8 MB.";return"";}
 async function uploadBrand(kind:"logo"|"cover",event:ChangeEvent<HTMLInputElement>){if(!store)return;const file=event.target.files?.[0];const problem=validate(file);event.target.value="";if(problem){setNotice(problem);return;}setUploading(kind);setNotice("");const path=`${store.id}/branding/${kind}-${Date.now()}.${extension(file!)}`;const{error}=await supabase.storage.from("store-media").upload(path,await file!.arrayBuffer(),{contentType:file!.type,cacheControl:"3600",upsert:false});if(error){setNotice("Não foi possível enviar a imagem.");setUploading("");return;}const result=await supabase.functions.invoke("store-settings",{body:{storeId:store.id,[kind==="logo"?"logoPath":"coverPath"]:path}});if(result.error||result.data?.error){setNotice("Imagem enviada, mas não foi possível vinculá-la à loja.");setUploading("");return;}setNotice(kind==="logo"?"Logo atualizado.":"Capa atualizada.");await load();setUploading("");}
 async function uploadProduct(product:Product,event:ChangeEvent<HTMLInputElement>){if(!store)return;const file=event.target.files?.[0];const problem=validate(file);event.target.value="";if(problem){setNotice(problem);return;}setUploading(product.id);setNotice("");const path=`${store.id}/products/${product.id}-${Date.now()}.${extension(file!)}`;const{error}=await supabase.storage.from("store-media").upload(path,await file!.arrayBuffer(),{contentType:file!.type,cacheControl:"3600",upsert:false});if(error){setNotice("Não foi possível enviar a foto do produto.");setUploading("");return;}const{data}=supabase.storage.from("store-media").getPublicUrl(path);const{error:updateError}=await supabase.from("products").update({image_url:data.publicUrl,updated_at:new Date().toISOString()}).eq("id",product.id).eq("store_id",store.id);if(updateError){setNotice("Foto enviada, mas não foi possível vinculá-la ao produto.");setUploading("");return;}setNotice(`Foto de ${product.name} atualizada.`);await load();setUploading("");}
 if(loading)return <main className="authPage"><div className="authCard">Carregando mídia...</div></main>;
 return <main className="content"><header className="topbar"><div><p className="eyebrow">PAINEL LOJISTA</p><h1>Mídia da loja</h1><p>Logo, capa e fotos do cardápio.</p></div><a className="logout" href="/">← Voltar ao painel</a></header>{notice&&<div className="notice">{notice}</div>}{!store?<div className="emptyState">Nenhuma loja gerenciável encontrada.</div>:<>
 <section className="panel" style={{marginBottom:18}}><div className="panelTitle"><h2>Identidade visual</h2><span>{store.name}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16}}><article style={{border:"1px solid #e8e8e8",borderRadius:16,padding:16}}><b>Logo</b><div style={{height:150,margin:"12px 0",background:"#f4f4f4",borderRadius:14,display:"grid",placeItems:"center",overflow:"hidden"}}>{store.logo_url?<img src={store.logo_url} alt="Logo" style={{width:"100%",height:"100%",objectFit:"contain"}}/>:<span>Sem logo</span>}</div><label className="primary" style={{display:"inline-block",cursor:"pointer"}}>{uploading==="logo"?"ENVIANDO...":"ALTERAR LOGO"}<input hidden type="file" accept={accept} disabled={!!uploading} onChange={e=>uploadBrand("logo",e)}/></label></article><article style={{border:"1px solid #e8e8e8",borderRadius:16,padding:16}}><b>Capa</b><div style={{height:150,margin:"12px 0",background:"#f4f4f4",borderRadius:14,display:"grid",placeItems:"center",overflow:"hidden"}}>{store.cover_url?<img src={store.cover_url} alt="Capa" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span>Sem capa</span>}</div><label className="primary" style={{display:"inline-block",cursor:"pointer"}}>{uploading==="cover"?"ENVIANDO...":"ALTERAR CAPA"}<input hidden type="file" accept={accept} disabled={!!uploading} onChange={e=>uploadBrand("cover",e)}/></label></article></div><small style={{display:"block",marginTop:12,color:"#777"}}>JPG, PNG ou WEBP • até 8 MB. Logo e capa ficam no bucket público de mídia; documentos de entregador usam armazenamento privado separado.</small></section>
 <section className="panel"><div className="panelTitle"><h2>Fotos dos produtos</h2><span>{products.length} item(ns)</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{products.map(product=><article key={product.id} style={{border:"1px solid #e8e8e8",borderRadius:14,padding:12}}><div style={{height:130,background:"#f4f4f4",borderRadius:12,display:"grid",placeItems:"center",overflow:"hidden"}}>{product.image_url?<img src={product.image_url} alt={product.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span>Sem foto</span>}</div><h3 style={{margin:"10px 0 4px"}}>{product.name}</h3><small>{product.active?"Ativo":"Pausado"}</small><div style={{marginTop:10}}><label className="primary" style={{display:"inline-block",cursor:"pointer"}}>{uploading===product.id?"ENVIANDO...":"ESCOLHER FOTO"}<input hidden type="file" accept={accept} disabled={!!uploading} onChange={e=>uploadProduct(product,e)}/></label></div></article>)}{!products.length&&<div className="emptyState">Cadastre produtos antes de enviar as fotos.</div>}</div></section></>}
 </main>;
}
